<a href="https://colab.research.google.com/github/vaidegiarch/Cross-Market-Analysis-Crypto-Oil-Stocks-with-SQL-and-Streamlit/blob/main/project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
!pip install requests

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.1.4)

In [12]:
import requests
import time

In [13]:

base_url="https://api.coingecko.com/api/v3/coins/markets"
all_records=[]

for page in range(1,6):#shows data 1 to 5 page

  url=(f"{base_url}?vs_currency=inr&per_page=250&order=market_cap_desc&page={page}&sparkline=False")
  response=requests.get(url)#gets data from url

  if response.status_code==200:
    data=response.json()
    all_records.extend(data)
    print (f"page{page} fetched successfully")

  else:
    print (f"failed to fetch page{page}")

  time.sleep(30)

print ("total records collected:",len (all_records))

page1 fetched successfully
page2 fetched successfully
page3 fetched successfully
page4 fetched successfully
page5 fetched successfully
total records collected: 1250

In [14]:
len(all_records)

1250

In [15]:
data=all_records

records=[]

for i in data:
  records.append(dict(id=i["id"],
                     symbol=i["symbol"],
                     name=i["name"],
                     current_price=i["current_price"],
                     market_cap=i["market_cap"],
                     market_cap_rank=i["market_cap_rank"],
                     total_volume=i["total_volume"],
                     circulating_supply=i["circulating_supply"],
                     total_supply=i["total_supply"],
                     ath=i["ath"],
                     atl=i["atl"],
                     last_updated=i["last_updated"]))

In [16]:
import pandas as pd
Cryptocurrencies_df=pd.DataFrame(records)
Cryptocurrencies_df

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,5.978426e+06,119492824100063,1,3.561193e+12,1.999344e+07,1.999344e+07,1.118701e+07,3.993420e+03,2026-02-23T09:09:33.292Z
1,ethereum,eth,Ethereum,1.712600e+05,20665183551559,2,1.515937e+12,1.206924e+08,1.206924e+08,4.319460e+05,2.813000e+01,2026-02-23T09:09:33.498Z
2,tether,usdt,Tether,9.084000e+01,16680747314099,3,5.699465e+12,1.836242e+11,1.890912e+11,1.055200e+02,3.686000e+01,2026-02-23T09:09:36.358Z
3,ripple,xrp,XRP,1.243600e+02,7580152143181,4,2.349981e+11,6.101858e+10,9.998571e+10,3.139900e+02,1.593430e-01,2026-02-23T09:09:34.973Z
4,binancecoin,bnb,BNB,5.462700e+04,7444065516099,5,9.409038e+10,1.363590e+08,1.363590e+08,1.214220e+05,2.580000e+00,2026-02-23T09:09:33.327Z
...,...,...,...,...,...,...,...,...,...,...,...,...
1245,bitrise-token,brise,Bitgert,1.960000e-06,774602879,1246,1.202681e+08,3.956882e+14,4.270635e+14,1.417800e-04,4.533800e-08,2026-02-23T09:11:43.639Z
1246,landwolf-0x67,wolf,LandWolf,8.572700e-04,772329935,1247,6.698073e+07,9.021595e+11,9.021595e+11,2.406188e-02,2.280700e-04,2026-02-23T09:11:36.520Z
1247,localcoinswap,lcs,LocalCoinSwap,2.011000e+01,769218143,1248,1.510000e+05,3.825207e+07,7.273242e+07,5.723000e+01,1.458910e-01,2026-02-23T09:11:36.675Z
1248,bitcoin-usd-btcfi,btcusd,Bitcoin USD (BTCFi),9.040000e+01,769080571,1249,1.377424e+06,8.507197e+06,8.507197e+06,1.015000e+02,7.936000e+01,2026-02-23T09:11:32.397Z
1249,pivx,pivx,PIVX,7.620000e+00,768707497,1253,9.649097e+07,1.008221e+08,1.008221e+08,8.648500e+02,3.561335e-02,2026-02-23T09:11:38.554Z

In [17]:
Cryptocurrencies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1250 entries, 0 to 1249
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  1250 non-null   object
 1   symbol              1250 non-null   object
 2   name                1250 non-null   object
 3   current_price       1250 non-null   float64
 4   market_cap          1250 non-null   int64
 5   market_cap_rank     1250 non-null   int64
 6   total_volume        1234 non-null   float64
 7   circulating_supply  1250 non-null   float64
 8   total_supply        1248 non-null   float64
 9   ath                 1250 non-null   float64
 10  atl                 1250 non-null   float64
 11  last_updated        1250 non-null   object
dtypes: float64(6), int64(2), object(4)
memory usage: 117.3+ KB

In [18]:
Cryptocurrencies_df["last_updated"]=pd.to_datetime(Cryptocurrencies_df["last_updated"]).dt.date
Cryptocurrencies_df["last_updated"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1250 entries, 0 to 1249
Series name: last_updated
Non-Null Count  Dtype
--------------  -----
1250 non-null   object
dtypes: object(1)
memory usage: 9.9+ KB

In [19]:
Cryptocurrencies_df.rename(columns={"last_updated": "date"}, inplace=True)

In [20]:
Cryptocurrencies_df # 1.data frame of all cryptocoins

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,date
0,bitcoin,btc,Bitcoin,5.978426e+06,119492824100063,1,3.561193e+12,1.999344e+07,1.999344e+07,1.118701e+07,3.993420e+03,2026-02-23
1,ethereum,eth,Ethereum,1.712600e+05,20665183551559,2,1.515937e+12,1.206924e+08,1.206924e+08,4.319460e+05,2.813000e+01,2026-02-23
2,tether,usdt,Tether,9.084000e+01,16680747314099,3,5.699465e+12,1.836242e+11,1.890912e+11,1.055200e+02,3.686000e+01,2026-02-23
3,ripple,xrp,XRP,1.243600e+02,7580152143181,4,2.349981e+11,6.101858e+10,9.998571e+10,3.139900e+02,1.593430e-01,2026-02-23
4,binancecoin,bnb,BNB,5.462700e+04,7444065516099,5,9.409038e+10,1.363590e+08,1.363590e+08,1.214220e+05,2.580000e+00,2026-02-23
...,...,...,...,...,...,...,...,...,...,...,...,...
1245,bitrise-token,brise,Bitgert,1.960000e-06,774602879,1246,1.202681e+08,3.956882e+14,4.270635e+14,1.417800e-04,4.533800e-08,2026-02-23
1246,landwolf-0x67,wolf,LandWolf,8.572700e-04,772329935,1247,6.698073e+07,9.021595e+11,9.021595e+11,2.406188e-02,2.280700e-04,2026-02-23
1247,localcoinswap,lcs,LocalCoinSwap,2.011000e+01,769218143,1248,1.510000e+05,3.825207e+07,7.273242e+07,5.723000e+01,1.458910e-01,2026-02-23
1248,bitcoin-usd-btcfi,btcusd,Bitcoin USD (BTCFi),9.040000e+01,769080571,1249,1.377424e+06,8.507197e+06,8.507197e+06,1.015000e+02,7.936000e+01,2026-02-23
1249,pivx,pivx,PIVX,7.620000e+00,768707497,1253,9.649097e+07,1.008221e+08,1.008221e+08,8.648500e+02,3.561335e-02,2026-02-23

historical price for three coins

In [21]:
import requests
from datetime import datetime
import time

coin_ids = ["bitcoin", "ethereum", "tether"]
all_price_records = []  # ✅ must be empty

for coin_id in coin_ids:
    url = f"https://api.coingecko.com/api/v3/coins/{coin_id}/market_chart?vs_currency=inr&days=365"

    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()
        # Loop through daily prices
        for price_entry in data['prices']:
            timestamp, price = price_entry
            date = datetime.utcfromtimestamp(timestamp / 1000).date()

            # Add to our list
            all_price_records.append({
                "coin_id": coin_id,
                "date": date,
                "price_inr": price
            })
        print(f"{coin_id} prices fetched")
    else:
        print(f"Failed to fetch {coin_id}")

    time.sleep(30)  # polite delay to avoid API rate limits

/tmp/ipython-input-90423288.py:18: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
  date = datetime.utcfromtimestamp(timestamp / 1000).date()

bitcoin prices fetched
ethereum prices fetched
tether prices fetched

In [22]:
Crypto_prices_df=pd.DataFrame(all_price_records)

In [23]:
Crypto_prices_df["coin_id"].value_counts()

coin_id
bitcoin     366
ethereum    366
tether      366
Name: count, dtype: int64

In [24]:
Crypto_prices_df  # 2. data frame of top 3 coins -historical prices for 1 year (each coin)

      coin_id        date     price_inr
0     bitcoin  2025-02-24  8.341958e+06
1     bitcoin  2025-02-25  7.922798e+06
2     bitcoin  2025-02-26  7.729282e+06
3     bitcoin  2025-02-27  7.314307e+06
4     bitcoin  2025-02-28  7.397417e+06
...       ...         ...           ...
1093   tether  2026-02-20  9.101081e+01
1094   tether  2026-02-21  9.069154e+01
1095   tether  2026-02-22  9.070614e+01
1096   tether  2026-02-23  9.069543e+01
1097   tether  2026-02-23  9.083841e+01

[1098 rows x 3 columns]

oil prices

In [25]:
import pandas as pd
oil_df = pd.read_csv("https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv")

oil_df

oil_df["Date"]=pd.to_datetime(oil_df["Date"])


Oil_prices_df=oil_df[
    (oil_df["Date"]>="2020-01-01")&
    (oil_df["Date"]<="2026-01-31")]

In [26]:
Oil_prices_df

            Date  Price
8569  2020-01-02  61.17
8570  2020-01-03  63.00
8571  2020-01-06  63.27
8572  2020-01-07  62.70
8573  2020-01-08  59.65
...          ...    ...
10084 2026-01-26  60.46
10085 2026-01-27  62.04
10086 2026-01-28  62.75
10087 2026-01-29  64.77
10088 2026-01-30  64.50

[1520 rows x 2 columns]

In [27]:
Oil_prices_df.reset_index(drop=True, inplace=True)
Oil_prices_df # 3.data frame of oil prices from Jan 2020 – Jan 2026.

           Date  Price
0    2020-01-02  61.17
1    2020-01-03  63.00
2    2020-01-06  63.27
3    2020-01-07  62.70
4    2020-01-08  59.65
...         ...    ...
1515 2026-01-26  60.46
1516 2026-01-27  62.04
1517 2026-01-28  62.75
1518 2026-01-29  64.77
1519 2026-01-30  64.50

[1520 rows x 2 columns]

Stock Prices (Yahoo Finance API)

In [28]:
import yfinance as yf
import pandas as pd

tickers = ["^GSPC", "^IXIC", "^NSEI"]
start_date = "2020-01-01"
end_date = "2026-01-12"

stocks_df = yf.download(tickers, start=start_date, end=end_date, group_by="ticker")
stocks_df.head()

/tmp/ipython-input-2364413695.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  stocks_df = yf.download(tickers, start=start_date, end=end_date, group_by="ticker")
[*********************100%***********************]  3 of 3 completed

Ticker             ^NSEI                                                      \
Price               Open          High           Low         Close    Volume
Date
2020-01-01  12202.150391  12222.200195  12165.299805  12182.500000  304100.0
2020-01-02  12198.549805  12289.900391  12195.250000  12282.200195  407700.0
2020-01-03  12261.099609  12265.599609  12191.349609  12226.650391  428800.0
2020-01-06  12170.599609  12179.099609  11974.200195  11993.049805  396500.0
2020-01-07  12079.099609  12152.150391  12005.349609  12052.950195  447800.0

Ticker            ^GSPC                                                       \
Price              Open         High          Low        Close        Volume
Date
2020-01-01          NaN          NaN          NaN          NaN           NaN
2020-01-02  3244.669922  3258.139893  3235.530029  3257.850098  3.459930e+09
2020-01-03  3226.360107  3246.149902  3222.340088  3234.850098  3.484700e+09
2020-01-06  3217.550049  3246.840088  3214.639893  3246.280029  3.702460e+09
2020-01-07  3241.860107  3244.909912  3232.429932  3237.179932  3.435910e+09

Ticker            ^IXIC
Price              Open         High          Low        Close        Volume
Date
2020-01-01          NaN          NaN          NaN          NaN           NaN
2020-01-02  9039.459961  9093.429688  9010.889648  9092.190430  2.862700e+09
2020-01-03  8976.429688  9065.759766  8976.429688  9020.769531  2.586520e+09
2020-01-06  8943.500000  9072.410156  8943.500000  9071.469727  2.810450e+09
2020-01-07  9076.639648  9091.929688  9042.549805  9068.580078  2.381740e+09

In [29]:
stock_prices_df=stocks_df[["^GSPC", "^IXIC", "^NSEI"]].reset_index().dropna()#dropped null values using list
stock_prices_df # 4 data frame --of yahoo finace stock prices

Ticker       Date        ^GSPC                                         \
Price                     Open         High          Low        Close
1      2020-01-02  3244.669922  3258.139893  3235.530029  3257.850098
2      2020-01-03  3226.360107  3246.149902  3222.340088  3234.850098
3      2020-01-06  3217.550049  3246.840088  3214.639893  3246.280029
4      2020-01-07  3241.860107  3244.909912  3232.429932  3237.179932
5      2020-01-08  3238.590088  3267.070068  3236.669922  3253.050049
...           ...          ...          ...          ...          ...
1558   2026-01-05  6892.189941  6920.379883  6891.560059  6902.049805
1559   2026-01-06  6908.029785  6948.689941  6904.020020  6944.819824
1560   2026-01-07  6945.069824  6965.689941  6919.189941  6920.930176
1561   2026-01-08  6914.109863  6931.279785  6899.330078  6921.459961
1562   2026-01-09  6927.830078  6978.359863  6917.640137  6966.279785

Ticker                       ^IXIC                                            \
Price         Volume          Open          High           Low         Close
1       3.459930e+09   9039.459961   9093.429688   9010.889648   9092.190430
2       3.484700e+09   8976.429688   9065.759766   8976.429688   9020.769531
3       3.702460e+09   8943.500000   9072.410156   8943.500000   9071.469727
4       3.435910e+09   9076.639648   9091.929688   9042.549805   9068.580078
5       3.726840e+09   9068.030273   9168.889648   9059.379883   9129.240234
...              ...           ...           ...           ...           ...
1558    5.771930e+09  23449.669922  23476.509766  23332.230469  23395.820312
1559    5.509680e+09  23446.960938  23559.150391  23389.570312  23547.169922
1560    5.214480e+09  23544.890625  23723.369141  23504.210938  23584.279297
1561    5.333200e+09  23548.880859  23558.169922  23353.460938  23480.019531
1562    5.163900e+09  23496.210938  23721.150391  23426.480469  23671.349609

Ticker                       ^NSEI                                            \
Price         Volume          Open          High           Low         Close
1       2.862700e+09  12198.549805  12289.900391  12195.250000  12282.200195
2       2.586520e+09  12261.099609  12265.599609  12191.349609  12226.650391
3       2.810450e+09  12170.599609  12179.099609  11974.200195  11993.049805
4       2.381740e+09  12079.099609  12152.150391  12005.349609  12052.950195
5       2.472620e+09  11939.099609  12044.950195  11929.599609  12025.349609
...              ...           ...           ...           ...           ...
1558    8.737320e+09  26333.699219  26373.199219  26210.050781  26250.300781
1559    9.012640e+09  26189.699219  26273.949219  26124.750000  26178.699219
1560    8.396920e+09  26143.099609  26187.150391  26067.900391  26140.750000
1561    7.723140e+09  26106.500000  26133.199219  25858.449219  25876.849609
1562    8.124420e+09  25840.400391  25940.599609  25623.000000  25683.300781

Ticker
Price     Volume
1       407700.0
2       428800.0
3       396500.0
4       447800.0
5       446000.0
...          ...
1558    338800.0
1559    383000.0
1560    338200.0
1561    328500.0
1562    348800.0

[1444 rows x 16 columns]

sql queries

In [30]:
pip install pymysql

Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.3/45.3 kB 2.0 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2

In [31]:
import sqlite3
conn = sqlite3.connect("Cryptocurrencies.db")
cursor = conn.cursor()
print("SQLite connected")

SQLite connected

In [32]:
# Pushing dataframe into sql

Cryptocurrencies_df.to_sql("Cryptocurrencies", conn, if_exists="replace", index=False)

1250

In [33]:
print(Cryptocurrencies_df.columns)

Index(['id', 'symbol', 'name', 'current_price', 'market_cap',
       'market_cap_rank', 'total_volume', 'circulating_supply', 'total_supply',
       'ath', 'atl', 'date'],
      dtype='object')

In [34]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS Cryptocurrencies (
    id VARCHAR(50) PRIMARY KEY,
    symbol VARCHAR(10),
    name VARCHAR(100),
    current_price DECIMAL(18, 6),
    market_cap BIGINT,
    market_cap_rank INT,
    total_volume BIGINT,
    circulating_supply DECIMAL(20, 6),
    total_supply DECIMAL(20, 6),
    ath DECIMAL(18, 6),
    atl DECIMAL(18, 6),
    date DATE)""")

In [35]:
sql = """
INSERT or REPLACE INTO Cryptocurrencies (id, symbol, name, current_price,market_cap,
       market_cap_rank, total_volume, circulating_supply, total_supply,
       ath, atl, date)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )
"""

In [36]:
data = Cryptocurrencies_df[["id","symbol","name","current_price", 'market_cap',
       'market_cap_rank', 'total_volume', 'circulating_supply', 'total_supply',
       'ath', 'atl', 'date']].values.tolist()

In [37]:
cursor.executemany(sql, data)
conn.commit()

In [38]:
cursor.execute("SELECT * FROM Cryptocurrencies LIMIT 10")
rows = cursor.fetchall()

for row in rows:
    print(row)

('bitcoin', 'btc', 'Bitcoin', 5978426.0, 119492824100063, 1, 3561192576684.0, 19993440.0, 19993440.0, 11187013.0, 3993.42, '2026-02-23')
('ethereum', 'eth', 'Ethereum', 171260.0, 20665183551559, 2, 1515936824091.0, 120692355.0689789, 120692355.0689789, 431946.0, 28.13, '2026-02-23')
('tether', 'usdt', 'Tether', 90.84, 16680747314099, 3, 5699465365552.0, 183624238441.843, 189091175734.4462, 105.52, 36.86, '2026-02-23')
('ripple', 'xrp', 'XRP', 124.36, 7580152143181, 4, 234998067450.0, 61018583977.0, 99985712847.0, 313.99, 0.159343, '2026-02-23')
('binancecoin', 'bnb', 'BNB', 54627.0, 7444065516099, 5, 94090382146.0, 136359026.0799999, 136359026.0799999, 121422.0, 2.58, '2026-02-23')
('usd-coin', 'usdc', 'USDC', 90.85, 6761710399228, 6, 756821233186.0, 74428856046.35391, 74432898545.46739, 1327.87, 65.31, '2026-02-23')
('solana', 'sol', 'Solana', 7166.93, 4071704815825, 7, 347327805864.0, 568474330.1417973, 620928834.6978452, 25396.0, 38.03, '2026-02-23')
('tron', 'trx', 'TRON', 26.09, 2471562724097, 8, 49153106449.0, 94730601626.2116, 94735278179.03369, 36.53, 0.117589, '2026-02-23')
('dogecoin', 'doge', 'Dogecoin', 8.62, 1454148630680, 9, 80058265291.0, 168830643126.5791, 168853803126.5791, 53.62, 0.00552883, '2026-02-23')
('figure-heloc', 'figr_heloc', 'Figure Heloc', 94.91, 1444891708320, 10, 108352471.0, 15224003657.427, 15224003657.427, 120.96, 13.78, '2026-02-22')

In [39]:
cursor.execute("""SELECT * from Cryptocurrencies
order by market_cap_rank asc
limit 3""")

rows = cursor.fetchall()

for row in rows:
    print(row)    # Find the top 3 cryptocurrencies by market cap.

('bitcoin', 'btc', 'Bitcoin', 5978426.0, 119492824100063, 1, 3561192576684.0, 19993440.0, 19993440.0, 11187013.0, 3993.42, '2026-02-23')
('bitcoin', 'btc', 'Bitcoin', 5978426.0, 119492824100063, 1, 3561192576684.0, 19993440.0, 19993440.0, 11187013.0, 3993.42, '2026-02-23')
('ethereum', 'eth', 'Ethereum', 171260.0, 20665183551559, 2, 1515936824091.0, 120692355.0689789, 120692355.0689789, 431946.0, 28.13, '2026-02-23')

In [40]:
cursor.execute("""SELECT id,symbol,name,circulating_supply, total_supply
from Cryptocurrencies
where circulating_supply > 0.9 * total_supply""")

rows = cursor.fetchall()

for row in rows:
    print(row)  #List all coins where circulating supply exceeds 90% of total supply.

('bitcoin', 'btc', 'Bitcoin', 19993440.0, 19993440.0)
('ethereum', 'eth', 'Ethereum', 120692355.0689789, 120692355.0689789)
('tether', 'usdt', 'Tether', 183624238441.843, 189091175734.4462)
('binancecoin', 'bnb', 'BNB', 136359026.0799999, 136359026.0799999)
('usd-coin', 'usdc', 'USDC', 74428856046.35391, 74432898545.46739)
('solana', 'sol', 'Solana', 568474330.1417973, 620928834.6978452)
('tron', 'trx', 'TRON', 94730601626.2116, 94735278179.03369)
('dogecoin', 'doge', 'Dogecoin', 168830643126.5791, 168853803126.5791)
('figure-heloc', 'figr_heloc', 'Figure Heloc', 15224003657.427, 15224003657.427)
('bitcoin-cash', 'bch', 'Bitcoin Cash', 19998946.77165078, 19999156.14665078)
('usds', 'usds', 'USDS', 9889121116.640924, 9889121116.640924)
('leo-token', 'leo', 'LEO Token', 921306944.9, 985239504.0)
('ethena-usde', 'usde', 'Ethena USDe', 6148720059.803138, 6148720059.803138)
('canton-network', 'cc', 'Canton', 37816248801.26848, 37816248801.26848)
('monero', 'xmr', 'Monero', 18446744.07370955, 18446744.07370955)
('usd1-wlfi', 'usd1', 'USD1', 5023324161.228893, 5023324161.228893)
('dai', 'dai', 'Dai', 4190418004.950516, 4190418004.950516)
('paypal-usd', 'pyusd', 'PayPal USD', 4067584402.503733, 4080759746.960552)
('zcash', 'zec', 'Zcash', 16567439.2280448, 16567690.7905448)
('litecoin', 'ltc', 'Litecoin', 76879739.48347135, 76879739.48347135)
('avalanche-2', 'avax', 'Avalanche', 431771961.1772119, 463441061.1772119)
('shiba-inu', 'shib', 'Shiba Inu', 589243858512311.2, 589500400279439.5)
('pax-gold', 'paxg', 'PAX Gold', 459009.975, 459009.975)
('polkadot', 'dot', 'Polkadot', 1668168515.775637, 1668168515.775637)
('blackrock-usd-institutional-digital-liquidity-fund', 'buidl', 'BlackRock USD Institutional Digital Liquidity Fund', 1940292266.820448, 1940292266.820448)
('falcon-finance', 'usdf', 'Falcon USD', 1755667122.206704, 1755667122.206704)
('aave', 'aave', 'Aave', 15190669.890452404, 16000000.0)
('pepe', 'pepe', 'Pepe', 420690000000000.0, 420690000000000.0)
('global-dollar', 'usdg', 'Global Dollar', 1627147250.164927, 1627147250.164927)
('okb', 'okb', 'OKB', 21000000.0, 21000000.0)
('hashnote-usyc', 'usyc', 'Circle USYC', 1553562286.22948, 1553562286.22948)
('ripple-usd', 'rlusd', 'Ripple USD', 1558570717.127498, 1558570717.127498)
('htx-dao', 'htx', 'HTX DAO', 916533066327098.8, 916533066327098.8)
('sky', 'sky', 'Sky', 23041035146.237114, 23462665147.36596)
('bfusd', 'bfusd', 'BFUSD', 1320000000.0, 1320000000.0)
('ethereum-classic', 'etc', 'Ethereum Classic', 155641151.8572869, 155641151.8572869)
('near', 'near', 'NEAR Protocol', 1288494337.0, 1288494755.0)
('superstate-short-duration-us-government-securities-fund-ustb', 'ustb', 'Superstate Short Duration U.S. Government Securities Fund (USTB)', 110875243.984532, 110875243.984532)
('gatechain-token', 'gt', 'Gate', 115180573.04885802, 115180573.04885802)
('internet-computer', 'icp', 'Internet Computer', 549205859.4117957, 549205859.4117957)
('polygon-ecosystem-token', 'pol', 'POL (ex-MATIC)', 10596603396.79995, 10596603396.79995)
('kucoin-shares', 'kcs', 'KuCoin', 132155021.7355671, 142155021.7355671)
('cosmos', 'atom', 'Cosmos Hub', 494694550.775976, 494694550.775976)
('quant-network', 'qnt', 'Quant', 14544176.164081175, 14612493.0)
('usdtb', 'usdtb', 'USDtb', 835207478.1461825, 835207478.1461825)
('nexo', 'nexo', 'NEXO', 1000000000.0, 1000000000.0)
('kaspa', 'kas', 'Kaspa', 26777148610.50726, 27226788738.92672)
('eutbl', 'eutbl', 'Spiko EU T-Bills Money Market Fund', 639398403.0543, 639398403.0543)
('algorand', 'algo', 'Algorand', 8880114343.678478, 8880428604.830294)
('usdd', 'usdd', 'USDD', 734748464.9, 743918558.57)
('janus-henderson-anemoy-aaa-clo-fund', 'jaaa', 'Janus Henderson Anemoy AAA CLO Fund', 703562532.975816, 703562532.975816)
('render-token', 'render', 'Render', 518714713.0140741, 533474886.2940741)
('ousg', 'ousg', 'OUSG', 6195574.974199085, 6195574.974199085)
('pippin', 'pippin', 'pippin', 999937490.763531, 999937490.763531)
('vechain', 'vet', 'VeChain', 85985041177.0, 85985041177.0)
('janus-henderson-anemoy-treasury-fund', 'jtrsy', 'Janus Henderson Anemoy Treasury Fund', 518328892.305495, 518328892.305495)
('usual-usd', 'usd0', 'Usual USD', 564960051.8026483, 564960051.8026483)
('gho', 'gho', 'GHO', 527437881.841152, 527437881.841152)
('bonk', 'bonk', 'Bonk', 87995151264912.56, 87995151264913.58)
('a7a5', 'a7a5', 'A7A5', 39191262224.85074, 39191262224.85074)
('true-usd', 'tusd', 'TrueUSD', 494515083.0, 494515083.0)
('usdai', 'usdai', 'USDai', 475913443.2613222, 475913443.2613222)
('euro-coin', 'eurc', 'EURC', 389457916.1959331, 389457916.1959331)
('decred', 'dcr', 'Decred', 17289117.20668488, 17289383.6304469)
('blockstack', 'stx', 'Stacks', 1779075203.6934, 1779075203.6934)
('dash', 'dash', 'Dash', 12601041.40999666, 12602931.54990315)
('tezos', 'xtz', 'Tezos', 1076316365.264427, 1096365624.410848)
('first-digital-usd', 'fdusd', 'First Digital USD', 394590429.2242489, 394590429.2242489)
('kinesis-gold', 'kau', 'Kinesis Gold', 2386227.8342, 2386227.8342)
('just', 'jst', 'JUST', 8815108920.581306, 8815108920.581306)
('chiliz', 'chz', 'Chiliz', 10292158746.0, 10292158746.0)
('usx', 'usx', 'USX', 340894983.707251, 340894983.707251)
('hastra-prime', 'prime', 'PRIME', 332312653.260563, 332312653.260563)
('injective-protocol', 'inj', 'Injective', 100000000.0, 100000000.0)
('apenft', 'nft', 'AINFT', 990105667256391.5, 990105667256391.5)
('bittorrent', 'btt', 'BitTorrent', 987037885840674.8, 990000000000000.0)
('sun-token', 'sun', 'Sun Token', 19213033038.81119, 19900730000.0)
('kaia', 'kaia', 'Kaia', 5856641747.106198, 5856641936.044253)
('bitcoin-cash-sv', 'bsv', 'Bitcoin SV', 19992190.625, 19992353.125)
('crvusd', 'crvusd', 'crvUSD', 290746273.4342943, 290746273.4342943)
('the-graph', 'grt', 'The Graph', 10726797069.81144, 10800262816.04821)
('jasmycoin', 'jasmy', 'JasmyCoin', 49444999677.59027, 50000000000.0)
('floki', 'floki', 'FLOKI', 9654894633121.0, 10000000000000.0)
('frax', 'frax', 'Legacy Frax Dollar', 276015184.0102677, 276015184.0102677)
('spx6900', 'spx', 'SPX6900', 930993080.908372, 930993080.908372)
('conflux-token', 'cfx', 'Conflux', 5159697336.126149, 5732659499.895275)
('telcoin', 'tel', 'Telcoin', 95077236366.71, 100000000000.0)
('newton-project', 'ab', 'AB', 98823661261.46, 98823661261.46)
('syrup', 'syrup', 'Maple Finance', 1157190702.5885315, 1216127147.998563)
('nusd-2', 'nusd', 'Neutrl USD', 229976977.9726906, 229976977.9726906)
('spiko-us-t-bills-money-market-fund', 'ustbl', 'Spiko US T-Bills Money Market Fund', 203992718.29824, 203992718.29824)
('ylds', 'ylds', 'YLDS', 219246327.11, 219246327.11)
('usda-2', 'usda', 'USDa', 220698063.9335999, 220698063.9335999)
('agora-dollar', 'ausd', 'AUSD', 216456853.0, 216456853.0)
('siren-2', 'siren', 'Siren', 728857925.4937865, 728857925.4937865)
('blockchain-capital', 'bcap', 'Blockchain Capital', 9112111.0, 9112111.0)
('dogwifcoin', 'wif', 'dogwifhat', 998926392.0, 998926392.0)
('ape-and-pepe', 'apepe', 'Ape and Pepe', 210000000000000.0, 210000000000000.0)
('zebec-network', 'zbcn', 'Zebec Network', 97951717939.67068, 99997633929.55516)
('tradable-na-rent-financing-platform-sstn', 'pc0000031', 'Tradable NA Rent Financing Platform SSTN', 189500000.0, 189500000.0)
('theta-token', 'theta', 'Theta Network', 1000000000.0, 1000000000.0)
('swissborg', 'borg', 'SwissBorg', 981852443.4419999, 981852443.4419999)
('fidelity-digital-interest-token', 'fdit', 'Fidelity Digital Interest Token', 179358279.23, 179358279.23)
('basic-attention-token', 'bat', 'Basic Attention', 1495724656.9526057, 1500000000.0)
('infinifi-usd', 'iusd', 'InfiniFi USD', 170677011.4056163, 170677011.4056163)
('gala', 'gala', 'GALA', 47342171723.79021, 47342171777.79018)
('compound-governance-token', 'comp', 'Compound', 9668189.278360886, 10000000.0)
('convex-finance', 'cvx', 'Convex Finance', 91758226.73956148, 99953913.00617307)
('bnb48-club-token', 'koge', 'KOGE', 3379998.56, 3379998.56)
('reallink', 'real', 'RealLink', 3125863975.0, 3125863975.0)
('golem', 'glm', 'Golem', 1000000000.0, 1000000000.0)
('satoshi-stablecoin', 'satusd', 'Satoshi Stablecoin', 159395807.6966203, 159395807.6966203)
('fartcoin', 'fartcoin', 'Fartcoin', 999979240.832154, 999979240.832154)
('stasis-eurs', 'eurs', 'STASIS EURO', 124125940.0, 124125940.0)
('ribbita-by-virtuals', 'tibbir', 'Ribbita by Virtuals', 999904783.797368, 999904783.797368)
('mimblewimblecoin', 'mwc', 'MimbleWimbleCoin', 11001384.21778801, 11001394.21778801)
('ecash', 'xec', 'eCash', 19992282797580.0, 19992404672580.0)
('astherus-usdf', 'usdf', 'Aster USDF', 152465165.4236837, 152465165.4236837)
('sonic-3', 's', 'Sonic', 3784775845.0, 3885497663.0)
('theo-short-duration-us-treasury-fund', 'thbill', 'Theo Short Duration US Treasury Fund', 149434980.654288, 149434980.654288)
('havven', 'snx', 'Synthetix', 343466216.99839866, 343889850.0967736)
('comedian', 'ban', 'Comedian', 999961859.27, 999961859.27)
('rollbit-coin', 'rlb', 'Rollbit Coin', 1747323198.74477, 1747352927.040053)
('build-on', 'b', 'BUILDon', 1000000000.0, 1000000000.0)
('apollo-diversified-credit-securitize-fund', 'acred', 'Apollo Diversified Credit Securitize Fund', 119353.619317, 119353.619317)
('zano', 'zano', 'Zano', 15169780.32, 15170082.64)
('gmt-token', 'gomining', 'GoMining Token', 405555826.3608998, 405555826.3608998)
('safepal', 'sfp', 'SafePal', 500000000.0, 500000000.0)
('coco-2', 'coco', 'coco', 1000000000.0, 1000000000.0)
('elrond-erd-2', 'egld', 'MultiversX', 29383839.0, 29383839.0)
('1inch', '1inch', '1INCH', 1408847430.661079, 1499999999.997)
('arweave', 'ar', 'Arweave', 65454185.5381511, 65454185.5381511)
('ozone-chain', 'ozo', 'Ozone Chain', 947649982.0, 1000000000.0)
('cap-usd', 'cusd', 'Cap USD', 120533031.1810633, 120533031.1810633)
('pleasing-usd', 'pusd', 'Pleasing USD', 120000000.0, 120000000.0)
('cash-4', 'cash', 'CASH', 113340252.686047, 113340252.686047)
('frax-usd', 'frxusd', 'Frax USD', 113300074.3343118, 113300120.2202303)
('stp-network', 'awe', 'AWE Network', 1942420283.0270672, 1942420283.0270672)
('re-protocol-reusd', 'reusd', 'Re Protocol reUSD', 104708861.6946972, 104708861.6946972)
('avant-usd', 'avusd', 'Avant USD', 110364596.8339995, 110364596.8339995)
('livepeer', 'lpt', 'Livepeer', 49688954.55058027, 49688954.55058027)
('standx-dusd', 'dusd', 'StandX DUSD', 108086424.275034, 108086424.275034)
('midas-mf-one', 'mf-one', 'Midas mF-ONE', 101028766.2860154, 101028766.2860154)
('securitize-tokenized-aaa-clo-fund', 'stac', 'Securitize Tokenized AAA CLO Fund', 105099.694673, 105099.694673)
('onyc', 'onyc', 'Onchain Yield Coin', 98171516.81515163, 98171516.81515163)
('melania-meme', 'melania', 'Melania Meme', 952496375.911841, 999996316.201778)
('apecoin', 'ape', 'ApeCoin', 985156250.0, 1000000000.0)
('grx-chain', 'grx', 'GRX Chain', 9515537.0, 9999924.0)
('mnee-usd-stablecoin', 'mnee', 'MNEE USD Stablecoin', 101398682.9733, 101398682.9733)
('ring-usd', 'usdr', 'Ring USD', 100400000.0, 100400000.0)
('pleasing-gold', 'pgold', 'Pleasing Gold', 19505.0, 19505.0)
('theta-fuel', 'tfuel', 'Theta Fuel', 7238197564.0, 7238317915.0)
('quantum-resistant-ledger', 'qrl', 'Quantum Resistant Ledger', 78392960.0, 78392960.0)
('gas', 'gas', 'Gas', 65093580.54427269, 65093580.54427269)
('yearn-finance', 'yfi', 'yearn.finance', 35671.80338551937, 36666.0)
('verge', 'xvg', 'Verge', 16521951235.74134, 16555000000.0)
('xdai', 'xdai', 'XDAI', 93624731.0387929, 93624731.0387929)
('qtum', 'qtum', 'Qtum', 105970059.75, 107822406.0)
('anzen-usdz', 'usdz', 'Anzen USDz', 93597524.923903, 93597524.923903)
('ravencoin', 'rvn', 'Ravencoin', 16097092677.14732, 16098302577.14732)
('dog-go-to-the-moon-rune', 'dog', 'Dog (Bitcoin)', 100000000000.0, 100000000000.0)
('nxm', 'nxm', 'Nexus Mutual', 1856083.594650984, 1856083.594650984)
('cheems-token', 'cheems', 'Cheems Token', 203672952113698.72, 203672952113698.72)
('ai-rig-complex', 'arc', 'AI Rig Complex', 999983971.989603, 999983971.989603)
('usda-3', 'usda', 'USDA', 90878832.95454128, 90878832.95454128)
('resolv-usr', 'usr', 'Resolv USR', 89920719.57273877, 89920719.57273877)
('akash-network', 'akt', 'Akash Network', 287969092.225094, 288588311.595395)
('toshi', 'toshi', 'Toshi', 420690000000.0, 420690000000.0)
('meta-2-2', 'meta', 'MetaDAO', 22684699.264119, 22684699.264119)
('kusama', 'ksm', 'Kusama', 17809411.33624786, 17809411.33624786)
('swop-2', 'swop', 'Swop', 9999998190.509241, 9999998190.509241)
('zilliqa', 'zil', 'Zilliqa', 19927008111.78959, 20370064389.54358)
('luxxcoin', 'lux', 'Luxxcoin', 100000000000.0, 100000000000.0)
('matrixdock-gold', 'xaum', 'Matrixdock Gold', 15816.8019, 15816.8019)
('mag7-ssi', 'mag7.ssi', 'MAG7.ssi', 169838930.7177998, 169838930.7177998)
('chutes', 'sn64', 'Chutes', 4433044.24784072, 4433044.24784072)
('digibyte', 'dgb', 'DigiByte', 18153091273.06013, 18161785765.17971)
('vaneck-treasury-fund', 'vbill', 'VanEck Treasury Fund', 78040344.82, 78040344.82)
('aioz-network', 'aioz', 'AIOZ Network', 1227090921.343223, 1237542500.063904)
('societe-generale-forge-eurcv', 'eurcv', 'EUR CoinVertible', 65755949.0, 65755949.0)
('rekt-4', 'rekt', 'Rekt', 420690000000000.0, 420690000000000.0)
('gama-token', 'gama', 'Gama Token', 100027888.0, 100027888.0)
('mina-protocol', 'mina', 'Mina Protocol', 1275517894.840039, 1275517894.840039)
('cygnus-finance-global-usd', 'cgusd', 'Cygnus Finance Global USD', 74972221.01628, 74972221.01628)
('temple', 'temple', 'TempleDAO', 23722422.590706147, 23769704.54225455)
('nervos-network', 'ckb', 'Nervos Network', 48271085069.22463, 49038846636.87179)
('threshold-network-token', 't', 'Threshold Network', 11155000000.0, 11155000000.0)
('agentfun-ai', 'agentfun', 'AgentFun.AI', 100000000.0, 100000000.0)
('uchain-2', 'ucn', 'UCHAIN', 100000.0, 100000.0)
('coinex-token', 'cet', 'CoinEx', 2551684326.53, 2551684326.53)
('nano', 'xno', 'Nano', 133248297.0, 133248297.0)
('puff-the-dragon', 'puff', 'Puff The Dragon', 888888888.0, 888888888.0)
('turbo', 'turbo', 'Turbo', 69000000000.0, 69000000000.0)
('based-brett', 'brett', 'Brett', 9909610058.14089, 9909610058.195889)
('ai-companions', 'aic', 'AI Companions', 1000000000.0, 1000000000.0)
('tdccp', 'tdccp', 'TDCCP', 639999980.9, 639999980.9)
('railgun', 'rail', 'Railgun', 57500000.0, 57500000.0)
('usdu', 'usdu', 'USDu', 66219697.78560518, 66219697.78560518)
('openeden-open-dollar', 'usdo', 'OpenEden OpenDollar', 65753969.06985586, 65753969.06985586)
('holotoken', 'hot', 'Holo', 177619433541.1413, 177619433541.1413)
('bc-token', 'bc', 'BCGame Coin', 9989401146.207348, 9989401146.207348)
('jupusd', 'jupusd', 'JupUSD', 64548442.244425, 64548442.244425)
('gmx', 'gmx', 'GMX', 10394592.22201674, 10394592.22201674)
('proton', 'xpr', 'XPR Network', 28524121530.50599, 31509447680.0396)
('mog-coin', 'mog', 'Mog Coin', 390561998053223.3, 390561998053223.3)
('jelly-my-jelly', 'jellyjelly', 'Jelly-My-Jelly', 999999099.34, 999999099.34)
('fidelity-digital-dollar', 'fidd', 'Fidelity Digital Dollar', 62101061.0, 62101061.0)
('straitsx-xusd', 'xusd', 'StraitsX XUSD', 61396294.451, 61396294.451)
('siacoin', 'sc', 'Siacoin', 56025636522.07519, 62217525676.30304)
('astar', 'astr', 'Astar', 8547791071.0, 8639855937.0)
('bianrensheng', '币安人生', '币安人生 (BinanceLife)', 1000000000.0, 1000000000.0)
('midas-mhyper', 'mhyper', 'Midas mHYPER', 56274777.4930246, 56274777.4930246)
('megausd', 'usdm', 'MegaUSD', 60417530.075457, 60417530.075457)
('bankercoin-2', 'bnkr', 'BankrCoin', 99999999999.99998, 99999999999.99998)
('deso', 'deso', 'Decentralized Social', 10532253.8854, 10808492.6854)
('non-playable-coin', 'npc', 'Non-Playable Coin', 8050126520.0, 8050126520.0)
('verus-coin', 'vrsc', 'Verus', 79971414.50342315, 79972484.33138148)
('frax-share', 'frax', 'Frax (prev. FXS)', 94793630.18322459, 99681495.5911336)
('biconomy', 'bico', 'Biconomy', 999998453.8902866, 1000000000.0)
('axelar', 'axl', 'Axelar', 1125020099.206385, 1232436987.353478)
('vethor-token', 'vtho', 'VeThor', 98226643803.0, 98244964408.0)
('flow', 'flow', 'Flow', 1643378795.344888, 1643378795.344888)
('xyo-network', 'xyo', 'XYO Network', 13931216938.01129, 13931216938.01129)
('anchored-coins-eur', 'aeur', 'Anchored Coins AEUR', 47929604.59999999, 47929604.59999999)
('eurite', 'euri', 'Eurite', 46968932.99990108, 46968932.99990108)
('kava', 'kava', 'Kava', 1082847302.0, 1082847302.0)
('compounding-open-dollar', 'cusdo', 'Compounding OpenDollar', 51339157.21661483, 51339157.21661483)
('blur', 'blur', 'Blur', 2740033005.422374, 3000000000.0)
('sushi', 'sushi', 'Sushi', 273012266.12632084, 287676365.3148028)
('constellation-labs', 'dag', 'Constellation', 3818894903.014177, 3818894903.014177)
('alphabet-class-a-ondo-tokenized-stock', 'googlon', 'Alphabet Class A (Ondo Tokenized Stock)', 165810.923739494, 165810.923739494)
('moo-deng', 'moodeng', 'Moo Deng', 989938657.244417, 989938657.244417)
('cat-in-a-dogs-world', 'mew', 'cat in a dogs world', 88888888888.88, 88888888888.88)
('ordinals', 'ordi', 'ORDI', 21000000.0, 21000000.0)
('polymesh', 'polyx', 'Polymesh', 1249279709.62035, 1249279709.62035)
('ondo-u-s-dollar-token', 'usdon', 'Ondo U.S. Dollar Token', 50712863.01621444, 50712863.01621444)
('pythia', 'pythia', 'PYTHIA', 998160858.664884, 998160858.664884)
('usdkg', 'usdkg', 'USDKG', 50000000.0, 50000000.0)
('alloy-tether', 'ausdt', 'Alloy Tether', 50000005.0, 50000005.0)
('usdx', 'usdx', 'USDX', 111568045.0, 111568045.0)
('the-white-whale', 'whitewhale', 'The White Whale', 1000000000.0, 1000000000.0)
('pirate-chain', 'arrr', 'Pirate Chain', 196213797.97055, 200000000.0)
('midas-mtbill', 'mtbill', 'Midas mTBILL', 45842568.77724632, 45842568.77724632)
('banana-for-scale-2', 'bananas31', 'Banana For Scale', 10000000000.0, 10000000000.0)
('niza-global-2', 'niza', 'Niza Global', 1150000000.0, 1150000000.0)
('paxos-standard', 'usdp', 'Pax Dollar', 47569452.76182543, 47569452.76182543)
('usd', 'usd+', 'Overnight.fi USD+', 48085096.3705041, 48085096.3705041)
('rocket-pool', 'rpl', 'Rocket Pool', 22200229.5293232, 22200229.5293232)
('sygnum-fiusd-liquidity-fund', 'fiusd', 'Sygnum FIUSD Liquidity Fund', 3997.66, 3997.66)
('waves', 'waves', 'Waves', 100000000.0, 100000000.0)
('popcat', 'popcat', 'Popcat', 979978669.96, 979978669.96)
('resolv-rlp', 'rlp', 'Resolv Liquidity Provider Token', 35582865.05030021, 35582865.05030021)
('singularry', 'singularry', 'Singularry', 999897536.93, 999897536.93)
('peanut-the-squirrel', 'pnut', 'Peanut the Squirrel', 999842575.356522, 999842575.356522)
('hex-trust-usdx', 'usdx', 'Hex Trust USD', 44442373.09, 44442373.09)
('gemini-dollar', 'gusd', 'Gemini Dollar', 44078677.17, 44078677.17)
('bora', 'bora', 'BORA', 1152750000.0, 1205750000.0)
('circle-internet-group-ondo-tokenized-stock', 'crclon', 'Circle Internet Group (Ondo Tokenized Stock)', 706389.014518864, 706389.014518864)
('victoria-vr', 'vr', 'Victoria VR', 16800000000.0, 16800000000.0)
('dai-on-pulsechain', 'dai', 'DAI on PulseChain', 44365217521.40316, 44365217521.40316)
('ardor', 'ardr', 'Ardor', 998466231.0, 998466231.0)
('ssv-network', 'ssv', 'SSV Network', 14699173.1, 14699173.1)
('ankr', 'ankr', 'Ankr Network', 10000000000.0, 10000000000.0)
('casper-network', 'cspr', 'Casper Network', 13878413910.0, 14367938775.0)
('lcx', 'lcx', 'LCX', 940989527.0, 942100166.6783277)
('burnedfi', 'burn', 'BurnedFi', 12364658.089806054, 12364658.089806054)
('mask-network', 'mask', 'Mask Network', 100000000.0, 100000000.0)
('loopring', 'lrc', 'Loopring', 1245991468.94246, 1373873397.442457)
('austin-capitals', 'aux', 'Austin Capitals', 9786000.0, 9786000.0)
('would', 'would', 'would', 999452591.96863, 999452591.96863)
('dusk-network', 'dusk', 'DUSK', 500000000.0, 500000000.0)
('snek', 'snek', 'Snek', 74738859163.0, 75250524708.0)
('iotex', 'iotx', 'IoTeX', 9441368979.0, 9441368983.0)
('binance-usd', 'busd', 'BUSD', 40026297.12594552, 40026297.12594552)
('skale', 'skl', 'SKALE', 6061936004.0, 6076000000.0)
('atomone', 'atone', 'AtomOne', 123887465.883922, 135695377.543922)
('purr-2', 'purr', 'Purr', 595620458.00339, 595620489.25124)

In [41]:
cursor.execute("""SELECT name,symbol,current_price,ath
from Cryptocurrencies
where current_price >=0.9* ath """)

rows = cursor.fetchall()

for row in rows:
    print(row) #Get coins that are within 10% of their all-time-high (ATH).

('USDS', 'usds', 90.83, 92.23)
('Ethena USDe', 'usde', 90.81, 92.91)
('USD1', 'usd1', 90.78, 92.17)
('Rain', 'rain', 0.901026, 0.989197)
('Dai', 'dai', 90.85, 92.29)
('PayPal USD', 'pyusd', 90.83, 92.2)
('Tether Gold', 'xaut', 465381.0, 514631.0)
('PAX Gold', 'paxg', 468546.0, 516779.0)
('BlackRock USD Institutional Digital Liquidity Fund', 'buidl', 90.85, 92.2)
('Falcon USD', 'usdf', 90.61, 92.45)
('Circle USYC', 'usyc', 101.11, 102.4)
('Ripple USD', 'rlusd', 90.84, 92.15)
('BFUSD', 'bfusd', 90.78, 92.02)
('Superstate Short Duration U.S. Government Securities Fund (USTB)', 'ustb', 999.28, 1011.63)
('USDtb', 'usdtb', 91.15, 95.66)
('Spiko EU T-Bills Money Market Fund', 'eutbl', 112.39, 115.38)
('USDD', 'usdd', 90.84, 92.2)
('Janus Henderson Anemoy AAA CLO Fund', 'jaaa', 93.3, 94.38)
('OUSG', 'ousg', 10390.8, 10520.12)
('pippin', 'pippin', 64.3, 68.76)
('Ondo US Dollar Yield', 'usdy', 98.85, 105.8)
('Janus Henderson Anemoy Treasury Fund', 'jtrsy', 99.49, 100.75)
('GHO', 'gho', 90.83, 92.12)
('Kite', 'kite', 24.25, 26.21)
('EURC', 'eurc', 107.29, 111.47)
('First Digital USD', 'fdusd', 90.79, 100.07)
('Kinesis Gold', 'kau', 14922.98, 16494.48)
('USX', 'usx', 90.83, 95.56)
('PRIME', 'prime', 92.68, 94.01)
('ADI', 'adi', 290.37, 300.71)
('crvUSD', 'crvusd', 90.94, 96.91)
('Legacy Frax Dollar', 'frax', 89.94, 91.66)
('Neutrl USD', 'nusd', 90.84, 94.55)
('Spiko US T-Bills Money Market Fund', 'ustbl', 97.66, 98.88)
('YLDS', 'ylds', 90.86, 92.2)
('USDa', 'usda', 89.79, 90.58)
('AUSD', 'ausd', 90.83, 92.19)
('Fidelity Digital Interest Token', 'fdit', 90.86, 92.2)
('Aster USDF', 'usdf', 90.68, 94.12)
('Theo Short Duration US Treasury Fund', 'thbill', 92.1, 98.66)
('GUSD', 'gusd', 90.79, 92.35)
('Apollo Diversified Credit Securitize Fund', 'acred', 99677.0, 101170.0)
('Pleasing USD', 'pusd', 91.03, 95.47)
('CASH', 'cash', 90.84, 93.86)
('Frax USD', 'frxusd', 90.81, 92.17)
('Re Protocol reUSD', 'reusd', 96.48, 98.49)
('Avant USD', 'avusd', 90.84, 93.96)
('StandX DUSD', 'dusd', 90.75, 92.19)
('Midas mF-ONE', 'mf-one', 96.15, 97.07)
('Securitize Tokenized AAA CLO Fund', 'stac', 91559.0, 92829.0)
('Onchain Yield Coin', 'onyc', 97.96, 98.7)
('GRX Chain', 'grx', 967.81, 971.89)
('MNEE USD Stablecoin', 'mnee', 90.66, 93.6)
('Tradable Singapore Fintech SSL', 'pc0000023', 90.86, 92.2)
('Ring USD', 'usdr', 90.85, 97.09)
('Pleasing Gold', 'pgold', 467165.0, 506532.0)
('Anzen USDz', 'usdz', 90.51, 94.1)
('Power Protocol', 'power', 40.26, 43.37)
('Resolv USR', 'usr', 90.85, 92.16)
('JUSD', 'jusd', 90.83, 92.09)
('Matrixdock Gold', 'xaum', 462804.0, 512412.0)
('VanEck Treasury Fund', 'vbill', 90.86, 92.2)
('EUR CoinVertible', 'eurcv', 107.2, 111.87)
('Gama Token', 'gama', 69.45, 76.6)
('Felix feUSD', 'feusd', 90.68, 94.32)
('Cygnus Finance Global USD', 'cgusd', 90.64, 93.4)
('USDu', 'usdu', 90.88, 92.57)
('JupUSD', 'jupusd', 90.83, 93.09)
('Fidelity Digital Dollar', 'fidd', 90.86, 91.43)
('Midas mHYPER', 'mhyper', 98.09, 99.04)
('MegaUSD', 'usdm', 90.83, 92.27)
('Eurite', 'euri', 107.26, 110.43)
('Compounding OpenDollar', 'cusdo', 95.01, 96.87)
('Alphabet Class A (Ondo Tokenized Stock)', 'googlon', 28660.0, 31792.0)
('Ondo U.S. Dollar Token', 'usdon', 90.85, 92.2)
('The Game Company', 'gmrt', 13.12, 13.12)
('USDKG', 'usdkg', 90.86, 93.85)
('Alloy Tether', 'ausdt', 90.75, 93.99)
('Midas mTBILL', 'mtbill', 95.63, 96.83)
('Pax Dollar', 'usdp', 90.83, 99.13)
('Sygnum FIUSD Liquidity Fund', 'fiusd', 1070378.0, 1083341.0)
('Espresso', 'esp', 8.01, 8.56)
('Resolv Liquidity Provider Token', 'rlp', 116.2, 118.41)
('Singularry', 'singularry', 4.05, 4.15)
('Austin Capitals', 'aux', 384.56, 391.45)
('Frankencoin', 'zchf', 118.11, 120.88)
('PumpMeme', 'pm', 96.01, 103.41)
('AIntivirus', 'ainti', 2.86, 2.89)
('Micron Technology (Ondo Tokenized Stock)', 'muon', 38632.0, 41937.0)
('USTBL', 'ustbl', 95.02, 96.24)
('Noon USN', 'usn', 90.67, 99.6)
('Liquity USD', 'lusd', 91.61, 92.61)
('BOLD', 'bold', 91.26, 92.36)
('Yield Optimizer USD', 'yousd', 97.06, 98.15)
('infiniFi Locked iUSD (1week)', 'liusd', 105.49, 111.36)
('SPDR S&P 500 ETF (Ondo Tokenized ETF)', 'spyon', 62557.0, 64397.0)
('MAI', 'mimatic', 90.82, 98.03)
('MimboGameGroup', 'mgg', 0.272721, 0.293933)
('Monerium EUR emoney', 'eure', 107.08, 110.77)
('Predictions', 'prdt', 101.44, 111.64)
('Midas mMEV', 'mmev', 100.81, 102.05)
('USD CoinVertible', 'usdcv', 90.84, 100.53)
('Noble Dollar (USDN)', 'usdn', 90.86, 92.83)
('Monerium EUR emoney [OLD]', 'eure', 107.42, 110.85)
('Electronic USD', 'eusd', 90.94, 94.57)
('Gyroscope GYD', 'gyd', 90.99, 93.94)
('Invesco QQQ ETF (Ondo Tokenized ETF)', 'qqqon', 55144.0, 58660.0)
('iShares Core S&P 500 ETF (Ondo Tokenized ETF)', 'ivvon', 62927.0, 64683.0)
('USDH', 'usdh', 90.92, 98.73)
('Unity', 'uty', 91.92, 93.02)
('MetaMask USD', 'musd', 90.88, 96.53)
('NVIDIA xStock', 'nvdax', 17186.19, 18702.52)
('Decentralized Validator Token', 'dvsteth', 122559.0, 122866.0)
('USAT', 'usat', 90.83, 92.22)
('Crown BRLV', 'brlv', 17.55, 17.55)
('iShares 20+ Year Treasury Bond ETF (Ondo Tokenized ETF)', 'tlton', 8310.76, 8411.82)
('Mezo USD', 'musd', 89.95, 93.66)
('Main Street Yield', 'msy', 93.28, 93.85)
('Ryze', 'ryze', 13.72, 14.52)
('SP500 xStock', 'spyx', 62442.0, 64229.0)
('Hylo USD', 'hyusd', 91.08, 92.27)
('Plume USD', 'pusd', 90.96, 92.57)
('Alphabet xStock', 'googlx', 28624.0, 31754.0)
('iShares Core MSCI EAFE ETF (Ondo Tokenized ETF)', 'iefaon', 9028.52, 9725.14)
('Midas mAPOLLO', 'mapollo', 97.39, 98.58)
('Orizon', 'ori', 4981.86, 5294.54)
('Felysyum', 'fely', 32.11, 34.04)
('f(x) Protocol fxUSD', 'fxusd', 90.71, 93.77)
('Yochi', 'yochi', 0.00289335, 0.0029107)
('iShares Core US Aggregate Bond ETF (Ondo Tokenized ETF)', 'aggon', 9353.67, 9461.67)
('NVIDIA (Ondo Tokenized Stock)', 'nvdaon', 17190.04, 18732.02)
('DIAMOND TOKEN 💎', 'dit', 13.2, 13.25)
('Mento Dollar', 'usdm', 90.81, 97.99)
('Midas msyrupUSDp', 'msyrupusdp', 94.14, 95.13)
('Spiko Digital Assets Cash & Carry Fund', 'spkcc', 91.79, 93.18)
('eSui Dollar', 'suiusde', 90.71, 91.09)
('VCRED', 'vcred', 90.73, 91.82)
('Hydrated Dollar', 'hollar', 90.83, 93.64)
('JPY Coin', 'jpyc', 0.585961, 0.599801)
('BRLA Digital BRLA', 'brla', 17.5, 17.77)
('Play', 'play', 106.28, 108.22)
('Comtech Gold', 'cgo', 14976.14, 16448.86)
('iShares TIPS Bond ETF (Ondo Tokenized ETF)', 'tipon', 10204.93, 10406.47)
('Midas mRe7YIELD', 'mre7yield', 99.16, 100.21)
('iShares MSCI EAFE ETF (Ondo Tokenized ETF)', 'efaon', 9633.73, 9743.41)
('Nest Alpha Vault (LP)', 'inalpha', 88.03, 94.2)
('DADI Insight Token', 'dit', 1736.5, 1916.25)
('iShares Core S&P Total US Stock Market ETF (Ondo Tokenized ETF)', 'itoton', 13750.69, 14175.06)
('Mu Digital AZND', 'aznd', 90.65, 91.07)
('Worldwide USD', 'wusd', 90.81, 92.11)
('Hermetica USDh', 'usdh', 90.81, 94.37)
('eUSD', 'eusd', 90.86, 93.78)
('Defi.money', 'money', 90.61, 92.47)
('Precious Metals USD', 'pmusd', 91.24, 94.77)
('Overnight.fi USD+ (Blast)', 'usd+', 88.79, 94.96)
('Freedom Dollar', 'fusd', 90.84, 92.15)
('Stable Coin', 'sbc', 90.86, 92.22)
('Gold xStock', 'gldx', 42906.0, 47013.0)
('iShares Russell 1000 Growth ETF (Ondo Tokenized ETF)', 'iwfon', 41039.0, 44771.0)
('USDS', 'usds', 90.83, 92.23)
('Ethena USDe', 'usde', 90.81, 92.91)
('USD1', 'usd1', 90.78, 92.17)
('Rain', 'rain', 0.901026, 0.989197)
('Dai', 'dai', 90.85, 92.29)
('PayPal USD', 'pyusd', 90.83, 92.2)
('Tether Gold', 'xaut', 465381.0, 514631.0)
('PAX Gold', 'paxg', 468546.0, 516779.0)
('BlackRock USD Institutional Digital Liquidity Fund', 'buidl', 90.85, 92.2)
('Falcon USD', 'usdf', 90.61, 92.45)
('Circle USYC', 'usyc', 101.11, 102.4)
('Ripple USD', 'rlusd', 90.84, 92.15)
('BFUSD', 'bfusd', 90.78, 92.02)
('Superstate Short Duration U.S. Government Securities Fund (USTB)', 'ustb', 999.28, 1011.63)
('USDtb', 'usdtb', 91.15, 95.66)
('Spiko EU T-Bills Money Market Fund', 'eutbl', 112.39, 115.38)
('USDD', 'usdd', 90.84, 92.2)
('Janus Henderson Anemoy AAA CLO Fund', 'jaaa', 93.3, 94.38)
('OUSG', 'ousg', 10390.8, 10520.12)
('pippin', 'pippin', 64.3, 68.76)
('Ondo US Dollar Yield', 'usdy', 98.85, 105.8)
('Janus Henderson Anemoy Treasury Fund', 'jtrsy', 99.49, 100.75)
('GHO', 'gho', 90.83, 92.12)
('Kite', 'kite', 24.25, 26.21)
('EURC', 'eurc', 107.29, 111.47)
('First Digital USD', 'fdusd', 90.79, 100.07)
('Kinesis Gold', 'kau', 14922.98, 16494.48)
('USX', 'usx', 90.83, 95.56)
('PRIME', 'prime', 92.68, 94.01)
('ADI', 'adi', 290.37, 300.71)
('crvUSD', 'crvusd', 90.94, 96.91)
('Legacy Frax Dollar', 'frax', 89.94, 91.66)
('Neutrl USD', 'nusd', 90.84, 94.55)
('Spiko US T-Bills Money Market Fund', 'ustbl', 97.66, 98.88)
('YLDS', 'ylds', 90.86, 92.2)
('USDa', 'usda', 89.79, 90.58)
('AUSD', 'ausd', 90.83, 92.19)
('Fidelity Digital Interest Token', 'fdit', 90.86, 92.2)
('Aster USDF', 'usdf', 90.68, 94.12)
('Theo Short Duration US Treasury Fund', 'thbill', 92.1, 98.66)
('GUSD', 'gusd', 90.79, 92.35)
('Apollo Diversified Credit Securitize Fund', 'acred', 99677.0, 101170.0)
('Pleasing USD', 'pusd', 91.03, 95.47)
('CASH', 'cash', 90.84, 93.86)
('Frax USD', 'frxusd', 90.81, 92.17)
('Re Protocol reUSD', 'reusd', 96.48, 98.49)
('Avant USD', 'avusd', 90.84, 93.96)
('StandX DUSD', 'dusd', 90.75, 92.19)
('Midas mF-ONE', 'mf-one', 96.15, 97.07)
('Securitize Tokenized AAA CLO Fund', 'stac', 91559.0, 92829.0)
('Onchain Yield Coin', 'onyc', 97.96, 98.7)
('GRX Chain', 'grx', 967.81, 971.89)
('MNEE USD Stablecoin', 'mnee', 90.66, 93.6)
('Tradable Singapore Fintech SSL', 'pc0000023', 90.86, 92.2)
('Ring USD', 'usdr', 90.85, 97.09)
('Pleasing Gold', 'pgold', 467165.0, 506532.0)
('Anzen USDz', 'usdz', 90.51, 94.1)
('Power Protocol', 'power', 40.26, 43.37)
('Resolv USR', 'usr', 90.85, 92.16)
('JUSD', 'jusd', 90.83, 92.09)
('Matrixdock Gold', 'xaum', 462804.0, 512412.0)
('VanEck Treasury Fund', 'vbill', 90.86, 92.2)
('EUR CoinVertible', 'eurcv', 107.2, 111.87)
('Gama Token', 'gama', 69.45, 76.6)
('Felix feUSD', 'feusd', 90.68, 94.32)
('Cygnus Finance Global USD', 'cgusd', 90.64, 93.4)
('USDu', 'usdu', 90.88, 92.57)
('JupUSD', 'jupusd', 90.83, 93.09)
('Fidelity Digital Dollar', 'fidd', 90.86, 91.43)
('Midas mHYPER', 'mhyper', 98.09, 99.04)
('MegaUSD', 'usdm', 90.83, 92.27)
('Eurite', 'euri', 107.26, 110.43)
('Compounding OpenDollar', 'cusdo', 95.01, 96.87)
('Alphabet Class A (Ondo Tokenized Stock)', 'googlon', 28660.0, 31792.0)
('Ondo U.S. Dollar Token', 'usdon', 90.85, 92.2)
('The Game Company', 'gmrt', 13.12, 13.12)
('USDKG', 'usdkg', 90.86, 93.85)
('Alloy Tether', 'ausdt', 90.75, 93.99)
('Midas mTBILL', 'mtbill', 95.63, 96.83)
('Pax Dollar', 'usdp', 90.83, 99.13)
('Sygnum FIUSD Liquidity Fund', 'fiusd', 1070378.0, 1083341.0)
('Espresso', 'esp', 8.01, 8.56)
('Resolv Liquidity Provider Token', 'rlp', 116.2, 118.41)
('Singularry', 'singularry', 4.05, 4.15)
('Austin Capitals', 'aux', 384.56, 391.45)
('Frankencoin', 'zchf', 118.11, 120.88)
('PumpMeme', 'pm', 96.01, 103.41)
('AIntivirus', 'ainti', 2.86, 2.89)
('Micron Technology (Ondo Tokenized Stock)', 'muon', 38632.0, 41937.0)
('USTBL', 'ustbl', 95.02, 96.24)
('Noon USN', 'usn', 90.67, 99.6)
('Liquity USD', 'lusd', 91.61, 92.61)
('BOLD', 'bold', 91.26, 92.36)
('Yield Optimizer USD', 'yousd', 97.06, 98.15)
('infiniFi Locked iUSD (1week)', 'liusd', 105.49, 111.36)
('SPDR S&P 500 ETF (Ondo Tokenized ETF)', 'spyon', 62557.0, 64397.0)
('MAI', 'mimatic', 90.82, 98.03)
('MimboGameGroup', 'mgg', 0.272721, 0.293933)
('Monerium EUR emoney', 'eure', 107.08, 110.77)
('Predictions', 'prdt', 101.44, 111.64)
('Midas mMEV', 'mmev', 100.81, 102.05)
('USD CoinVertible', 'usdcv', 90.84, 100.53)
('Noble Dollar (USDN)', 'usdn', 90.86, 92.83)
('Monerium EUR emoney [OLD]', 'eure', 107.42, 110.85)
('Electronic USD', 'eusd', 90.94, 94.57)
('Gyroscope GYD', 'gyd', 90.99, 93.94)
('Invesco QQQ ETF (Ondo Tokenized ETF)', 'qqqon', 55144.0, 58660.0)
('iShares Core S&P 500 ETF (Ondo Tokenized ETF)', 'ivvon', 62927.0, 64683.0)
('USDH', 'usdh', 90.92, 98.73)
('Unity', 'uty', 91.92, 93.02)
('MetaMask USD', 'musd', 90.88, 96.53)
('NVIDIA xStock', 'nvdax', 17186.19, 18702.52)
('Decentralized Validator Token', 'dvsteth', 122559.0, 122866.0)
('USAT', 'usat', 90.83, 92.22)
('Crown BRLV', 'brlv', 17.55, 17.55)
('iShares 20+ Year Treasury Bond ETF (Ondo Tokenized ETF)', 'tlton', 8310.76, 8411.82)
('Mezo USD', 'musd', 89.95, 93.66)
('Main Street Yield', 'msy', 93.28, 93.85)
('Ryze', 'ryze', 13.72, 14.52)
('SP500 xStock', 'spyx', 62442.0, 64229.0)
('Hylo USD', 'hyusd', 91.08, 92.27)
('Plume USD', 'pusd', 90.96, 92.57)
('Alphabet xStock', 'googlx', 28624.0, 31754.0)
('iShares Core MSCI EAFE ETF (Ondo Tokenized ETF)', 'iefaon', 9028.52, 9725.14)
('Midas mAPOLLO', 'mapollo', 97.39, 98.58)
('Orizon', 'ori', 4981.86, 5294.54)
('Felysyum', 'fely', 32.11, 34.04)
('f(x) Protocol fxUSD', 'fxusd', 90.71, 93.77)
('Yochi', 'yochi', 0.00289335, 0.0029107)
('iShares Core US Aggregate Bond ETF (Ondo Tokenized ETF)', 'aggon', 9353.67, 9461.67)
('NVIDIA (Ondo Tokenized Stock)', 'nvdaon', 17190.04, 18732.02)
('DIAMOND TOKEN 💎', 'dit', 13.2, 13.25)
('Mento Dollar', 'usdm', 90.81, 97.99)
('Midas msyrupUSDp', 'msyrupusdp', 94.14, 95.13)
('Spiko Digital Assets Cash & Carry Fund', 'spkcc', 91.79, 93.18)
('eSui Dollar', 'suiusde', 90.71, 91.09)
('VCRED', 'vcred', 90.73, 91.82)
('Hydrated Dollar', 'hollar', 90.83, 93.64)
('JPY Coin', 'jpyc', 0.585961, 0.599801)
('BRLA Digital BRLA', 'brla', 17.5, 17.77)
('Play', 'play', 106.28, 108.22)
('Comtech Gold', 'cgo', 14976.14, 16448.86)
('iShares TIPS Bond ETF (Ondo Tokenized ETF)', 'tipon', 10204.93, 10406.47)
('Midas mRe7YIELD', 'mre7yield', 99.16, 100.21)
('iShares MSCI EAFE ETF (Ondo Tokenized ETF)', 'efaon', 9633.73, 9743.41)
('Nest Alpha Vault (LP)', 'inalpha', 88.03, 94.2)
('DADI Insight Token', 'dit', 1736.5, 1916.25)
('iShares Core S&P Total US Stock Market ETF (Ondo Tokenized ETF)', 'itoton', 13750.69, 14175.06)
('Mu Digital AZND', 'aznd', 90.65, 91.07)
('Worldwide USD', 'wusd', 90.81, 92.11)
('Hermetica USDh', 'usdh', 90.81, 94.37)
('eUSD', 'eusd', 90.86, 93.78)
('Defi.money', 'money', 90.61, 92.47)
('Precious Metals USD', 'pmusd', 91.24, 94.77)
('Overnight.fi USD+ (Blast)', 'usd+', 88.79, 94.96)
('Freedom Dollar', 'fusd', 90.84, 92.15)
('Stable Coin', 'sbc', 90.86, 92.22)
('Gold xStock', 'gldx', 42906.0, 47013.0)
('iShares Russell 1000 Growth ETF (Ondo Tokenized ETF)', 'iwfon', 41039.0, 44771.0)

In [42]:
cursor.execute("""SELECT name, avg(market_cap_rank)
from Cryptocurrencies
where total_volume > 1000000000 """)

rows = cursor.fetchall()

for row in rows:
    print(row) #Find the average market cap rank of coins with volume above $1B.

('Bitcoin', 254.15165876777252)

In [43]:
cursor.execute("""SELECT name,symbol,date
from Cryptocurrencies
order by date desc
limit 1 """)

rows = cursor.fetchall()

for row in rows:
    print(row) #Get the most recently updated coin.

('Bitcoin', 'btc', '2026-02-23')

In [45]:
print(Crypto_prices_df.columns) # 2 data frame top 3

Index(['coin_id', 'date', 'price_inr'], dtype='object')

In [44]:
import sqlite3

conn = sqlite3.connect("Crypto_prices.db")
cursor = conn.cursor()

In [46]:
# Pushing dataframe into sql

Crypto_prices_df.to_sql("Crypto_prices", conn, if_exists="replace", index=False)

1098

In [47]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS Crypto_prices  (
    coin_id VARCHAR(50) ,
    date DATE,
    price_inr DECIMAL(18, 6),
    FOREIGN KEY (coin_id) REFERENCES Cryptocurrencies(id))
    """)

In [48]:
Crypto_prices_df["date"] =  pd.to_datetime(Crypto_prices_df["date"]).dt.strftime("%Y-%m-%d") #converts data order

In [49]:
sql = ("""
INSERT or REPLACE INTO  Crypto_prices (coin_id, date, price_inr)
VALUES (?, ?, ? )
""")
data = Crypto_prices_df[['coin_id', 'date', 'price_inr']].values.tolist()


cursor.executemany(sql, data)
conn.commit()

In [50]:
cursor.execute("SELECT * FROM Crypto_prices LIMIT 10")
rows = cursor.fetchall()

for row in rows:
    print(row)

('bitcoin', '2025-02-24', 8341958.303704703)
('bitcoin', '2025-02-25', 7922797.740624487)
('bitcoin', '2025-02-26', 7729282.415455005)
('bitcoin', '2025-02-27', 7314307.147526646)
('bitcoin', '2025-02-28', 7397416.663356487)
('bitcoin', '2025-03-01', 7386259.847331922)
('bitcoin', '2025-03-02', 7523008.862171689)
('bitcoin', '2025-03-03', 8244472.61232367)
('bitcoin', '2025-03-04', 7521257.854514662)
('bitcoin', '2025-03-05', 7615008.334491884)

In [51]:
cursor.execute("""SELECT coin_id,date, MAX(price_inr)
               FROM Crypto_prices
               WHERE coin_id="bitcoin"
                """)
rows = cursor.fetchall()

for row in rows:
    print(row) #Find the highest daily price of Bitcoin in the last 365 days.

('bitcoin', '2025-10-07', 11070472.246732509)

In [52]:
cursor.execute("""SELECT coin_id,date, AVG(price_inr)
               FROM Crypto_prices
               WHERE coin_id="ethereum"
               AND date >= date('now','-365 day')
               ORDER BY date
                """)
rows = cursor.fetchall()

for row in rows:
    print(row) #Calculate the average daily price of Ethereum in the past 1 year.

('ethereum', '2025-02-24', 263789.89604061405)

In [53]:
cursor.execute("""
SELECT coin_id, date, price_inr
FROM Crypto_prices
WHERE coin_id = "bitcoin"
AND date BETWEEN '2025-02-01' AND '2025-02-28'
ORDER BY date
""")

rows = cursor.fetchall()

for row in rows:
    print(row) #Show the daily price trend of Bitcoin in January 2025./ since data for jan not available took for feb

('bitcoin', '2025-02-24', 8341958.303704703)
('bitcoin', '2025-02-24', 8341958.303704703)
('bitcoin', '2025-02-25', 7922797.740624487)
('bitcoin', '2025-02-25', 7922797.740624487)
('bitcoin', '2025-02-26', 7729282.415455005)
('bitcoin', '2025-02-26', 7729282.415455005)
('bitcoin', '2025-02-27', 7314307.147526646)
('bitcoin', '2025-02-27', 7314307.147526646)
('bitcoin', '2025-02-28', 7397416.663356487)
('bitcoin', '2025-02-28', 7397416.663356487)

In [54]:
cursor.execute("""
SELECT coin_id, date,
AVG (price_inr)
FROM Crypto_prices
GROUP BY coin_id
ORDER BY avg(price_inr) DESC
LIMIT 1
""")

rows = cursor.fetchall()

for row in rows:
    print(row)#Find the coin with the highest average price over 1 year.

('bitcoin', '2025-02-24', 8685946.934184808)

In [55]:
cursor.execute("""
SELECT AVG(price_inr)
FROM Crypto_prices
WHERE coin_id='bitcoin'
AND date LIKE '2025-02-%'
""")#Any date that starts with %

feb2025_price = cursor.fetchone()[0]
print("feb 2025 Avg Price:", feb2025_price)#avg price of feb 2025

feb 2025 Avg Price: 7741152.454133466

In [56]:
cursor.execute("""
SELECT AVG(price_inr)
FROM Crypto_prices
WHERE coin_id='bitcoin'
AND date LIKE '2026-02-%'
""")

feb2026_price = cursor.fetchone()[0]
print("feb 2026 Avg Price:", feb2026_price)#avg price of feb 2026

feb 2026 Avg Price: 6331916.263712154

In [57]:
percent_change = ((feb2025_price - feb2026_price) / feb2025_price) * 100
print("Percentage Change:", round(percent_change,2), "%")#Get the % change in Bitcoin’s price between feb 2025 and feb 2026.

Percentage Change: 18.2 %

In [58]:
print((Oil_prices_df.columns))

Index(['Date', 'Price'], dtype='object')

In [59]:
import sqlite3
conn = sqlite3.connect("Oil_prices.db")
cursor = conn.cursor()
print("SQLite connected")

SQLite connected

In [60]:
# Pushing dataframe into sql

Oil_prices_df.to_sql("Oil_prices", conn, if_exists="replace", index=False)

1520

In [61]:
Oil_prices_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1520 entries, 0 to 1519
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1520 non-null   datetime64[ns]
 1   Price   1520 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 23.9 KB

In [62]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS Oil_prices (
    Date DATE PRIMARY KEY,
   Price DECIMAL(18,6)
)
""")

In [64]:
Oil_prices_df = Oil_prices_df.copy()
Oil_prices_df["Date"] = pd.to_datetime(Oil_prices_df["Date"]).dt.strftime("%Y-%m-%d")

In [65]:
sql = """
INSERT OR REPLACE INTO Oil_prices (Date, Price)
VALUES (?, ?)
"""



data = Oil_prices_df[['Date','Price']].values.tolist()

cursor.executemany(sql, data)
conn.commit()

In [66]:
cursor.execute("""
ALTER TABLE Oil_prices
RENAME COLUMN Date TO date
""")
cursor.execute("""
ALTER TABLE Oil_prices
RENAME COLUMN Price TO price_inr
""")

In [67]:
cursor.execute("""
SELECT date,price_inr
FROM Oil_prices
WHERE Date >= date('now','-5 years')
ORDER BY price_inr DESC
LIMIT 1
""")

rows = cursor.fetchall()

for row in rows:
    print(row)#Find the highest oil price in the last 5 years.

('2022-03-08 00:00:00', 123.64)

In [68]:
cursor.execute("""
SELECT substr(date,1,4) AS year,
       AVG(price_inr)
FROM Oil_prices
GROUP BY substr(date,1,4)
ORDER BY year
LIMIT 5
""")

rows = cursor.fetchall()

for row in rows:
    print(row) #Get the average oil price per year.

('2020', 39.16043650793649)
('2021', 68.13509960159365)
('2022', 94.9028685258964)
('2023', 77.5765322580645)
('2024', 76.6322400000001)

In [69]:
cursor.execute("""
SELECT date, price_inr
FROM Oil_prices
WHERE date BETWEEN '2020-03-01' AND '2020-04-30'
ORDER BY date
""")

rows = cursor.fetchall()

for row in rows:
    print(row) #Show oil prices during COVID crash (March–April 2020).

('2020-03-02', 46.78)
('2020-03-02 00:00:00', 46.78)
('2020-03-03', 47.27)
('2020-03-03 00:00:00', 47.27)
('2020-03-04', 46.78)
('2020-03-04 00:00:00', 46.78)
('2020-03-05', 45.9)
('2020-03-05 00:00:00', 45.9)
('2020-03-06', 41.14)
('2020-03-06 00:00:00', 41.14)
('2020-03-09', 31.05)
('2020-03-09 00:00:00', 31.05)
('2020-03-10', 34.47)
('2020-03-10 00:00:00', 34.47)
('2020-03-11', 33.13)
('2020-03-11 00:00:00', 33.13)
('2020-03-12', 31.56)
('2020-03-12 00:00:00', 31.56)
('2020-03-13', 31.72)
('2020-03-13 00:00:00', 31.72)
('2020-03-16', 28.96)
('2020-03-16 00:00:00', 28.96)
('2020-03-17', 26.96)
('2020-03-17 00:00:00', 26.96)
('2020-03-18', 20.48)
('2020-03-18 00:00:00', 20.48)
('2020-03-19', 25.09)
('2020-03-19 00:00:00', 25.09)
('2020-03-20', 19.48)
('2020-03-20 00:00:00', 19.48)
('2020-03-23', 23.33)
('2020-03-23 00:00:00', 23.33)
('2020-03-24', 21.03)
('2020-03-24 00:00:00', 21.03)
('2020-03-25', 20.75)
('2020-03-25 00:00:00', 20.75)
('2020-03-26', 16.6)
('2020-03-26 00:00:00', 16.6)
('2020-03-27', 15.48)
('2020-03-27 00:00:00', 15.48)
('2020-03-30', 14.1)
('2020-03-30 00:00:00', 14.1)
('2020-03-31', 20.51)
('2020-03-31 00:00:00', 20.51)
('2020-04-01', 20.28)
('2020-04-01 00:00:00', 20.28)
('2020-04-02', 25.18)
('2020-04-02 00:00:00', 25.18)
('2020-04-03', 28.36)
('2020-04-03 00:00:00', 28.36)
('2020-04-06', 26.21)
('2020-04-06 00:00:00', 26.21)
('2020-04-07', 23.54)
('2020-04-07 00:00:00', 23.54)
('2020-04-08', 24.97)
('2020-04-08 00:00:00', 24.97)
('2020-04-09', 22.9)
('2020-04-09 00:00:00', 22.9)
('2020-04-13', 22.36)
('2020-04-13 00:00:00', 22.36)
('2020-04-14', 20.15)
('2020-04-14 00:00:00', 20.15)
('2020-04-15', 19.96)
('2020-04-15 00:00:00', 19.96)
('2020-04-16', 19.82)
('2020-04-16 00:00:00', 19.82)
('2020-04-17', 18.31)
('2020-04-17 00:00:00', 18.31)
('2020-04-20', -36.98)
('2020-04-20 00:00:00', -36.98)
('2020-04-21', 8.91)
('2020-04-21 00:00:00', 8.91)
('2020-04-22', 13.64)
('2020-04-22 00:00:00', 13.64)
('2020-04-23', 15.06)
('2020-04-23 00:00:00', 15.06)
('2020-04-24', 15.99)
('2020-04-24 00:00:00', 15.99)
('2020-04-27', 12.17)
('2020-04-27 00:00:00', 12.17)
('2020-04-28', 12.4)
('2020-04-28 00:00:00', 12.4)
('2020-04-29', 15.04)
('2020-04-29 00:00:00', 15.04)
('2020-04-30', 19.23)

In [70]:
cursor.execute("""
SELECT MIN(price_inr)
FROM Oil_prices
WHERE date >= date('now','-10 years')
""")

rows = cursor.fetchall()
for row in rows:
    print(row) #Find the lowest price of oil in the last 10 years.

(-36.98,)

In [71]:
cursor.execute("""
SELECT
    strftime('%Y', date) AS year,
    MAX(price_inr) - MIN(price_inr) AS volatility
FROM Oil_prices
GROUP BY year
ORDER BY year;
""")

rows = cursor.fetchall()#highest oil price in that year-lowest oil price in that year = volatility val
for row in rows:
    print(row) #Calculate the volatility of oil prices (max-min difference per year).

('2020', 100.25)
('2021', 38.17)
('2022', 52.59)
('2023', 27.060000000000002)
('2024', 20.959999999999994)
('2025', 25.290000000000006)
('2026', 8.759999999999998)

In [72]:
print((stock_prices_df.columns))

MultiIndex([( 'Date',       ''),
            ('^GSPC',   'Open'),
            ('^GSPC',   'High'),
            ('^GSPC',    'Low'),
            ('^GSPC',  'Close'),
            ('^GSPC', 'Volume'),
            ('^IXIC',   'Open'),
            ('^IXIC',   'High'),
            ('^IXIC',    'Low'),
            ('^IXIC',  'Close'),
            ('^IXIC', 'Volume'),
            ('^NSEI',   'Open'),
            ('^NSEI',   'High'),
            ('^NSEI',    'Low'),
            ('^NSEI',  'Close'),
            ('^NSEI', 'Volume')],
           names=['Ticker', 'Price'])

In [73]:
gspc = stock_prices_df[
    [('Date',''),
     ('^GSPC','Open'),
     ('^GSPC','High'),
     ('^GSPC','Low'),
     ('^GSPC','Close'),
     ('^GSPC','Volume')]
].copy()

gspc.columns = ['date','open','high','low','close','volume']
gspc['ticker'] = '^GSPC'


ixic = stock_prices_df[
    [('Date',''),
     ('^IXIC','Open'),
     ('^IXIC','High'),
     ('^IXIC','Low'),
     ('^IXIC','Close'),
     ('^IXIC','Volume')]
].copy()

ixic.columns = ['date','open','high','low','close','volume']
ixic['ticker'] = '^IXIC'


nsei = stock_prices_df[
    [('Date',''),
     ('^NSEI','Open'),
     ('^NSEI','High'),
     ('^NSEI','Low'),
     ('^NSEI','Close'),
     ('^NSEI','Volume')]
].copy()

nsei.columns = ['date','open','high','low','close','volume']
nsei['ticker'] = '^NSEI'

In [74]:
stock_final_df = pd.concat([gspc, ixic, nsei])

In [75]:
stock_final_df.head()

,date,open,high,low,close,volume,ticker
1,2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09,^GSPC
2,2020-01-03,3226.360107,3246.149902,3222.340088,3234.850098,3.484700e+09,^GSPC
3,2020-01-06,3217.550049,3246.840088,3214.639893,3246.280029,3.702460e+09,^GSPC
4,2020-01-07,3241.860107,3244.909912,3232.429932,3237.179932,3.435910e+09,^GSPC
5,2020-01-08,3238.590088,3267.070068,3236.669922,3253.050049,3.726840e+09,^GSPC

In [76]:
import sqlite3

# Connect to database (creates if not exists)
conn = sqlite3.connect('stocks.db')
cursor = conn.cursor()

# Insert dataframe into table
stock_final_df.to_sql('stocks', conn, if_exists='replace', index=False)

# Create table if not exists
cursor.execute('''
CREATE TABLE IF NOT EXISTS stocks (
    date DATE,
    open DECIMAL(18, 6),
    high DECIMAL(18, 6),
    low DECIMAL(18, 6),
    close DECIMAL(18, 6),
    volume BIGINT,
    ticker VARCHAR(20)
)
''')
stock_final_df["date"] =  pd.to_datetime(stock_final_df["date"]).dt.date

# Check inserted data
cursor.execute("SELECT * FROM stocks LIMIT 5")
print(cursor.fetchall())

# Close connection
conn.close()

[('2020-01-02 00:00:00', 3244.669921875, 3258.139892578125, 3235.530029296875, 3257.85009765625, 3459930000.0, '^GSPC'), ('2020-01-03 00:00:00', 3226.360107421875, 3246.14990234375, 3222.340087890625, 3234.85009765625, 3484700000.0, '^GSPC'), ('2020-01-06 00:00:00', 3217.550048828125, 3246.840087890625, 3214.639892578125, 3246.280029296875, 3702460000.0, '^GSPC'), ('2020-01-07 00:00:00', 3241.860107421875, 3244.909912109375, 3232.429931640625, 3237.179931640625, 3435910000.0, '^GSPC'), ('2020-01-08 00:00:00', 3238.590087890625, 3267.070068359375, 3236.669921875, 3253.050048828125, 3726840000.0, '^GSPC')]

In [77]:
import sqlite3

# Re-establish connection to the database
conn = sqlite3.connect('stocks.db')
cursor = conn.cursor()

cursor.execute("""
SELECT date, open, high, low, close, volume
FROM stocks
WHERE ticker = '^NSEI'
ORDER BY date
""")#Get all stock prices for a given ticker

rows = cursor.fetchall()

for row in rows:
    print(row)

# Close the connection after use
conn.close()

('2020-01-02 00:00:00', 12198.5498046875, 12289.900390625, 12195.25, 12282.2001953125, 407700.0)
('2020-01-03 00:00:00', 12261.099609375, 12265.599609375, 12191.349609375, 12226.650390625, 428800.0)
('2020-01-06 00:00:00', 12170.599609375, 12179.099609375, 11974.2001953125, 11993.0498046875, 396500.0)
('2020-01-07 00:00:00', 12079.099609375, 12152.150390625, 12005.349609375, 12052.9501953125, 447800.0)
('2020-01-08 00:00:00', 11939.099609375, 12044.9501953125, 11929.599609375, 12025.349609375, 446000.0)
('2020-01-09 00:00:00', 12153.150390625, 12224.0498046875, 12132.5498046875, 12215.900390625, 477500.0)
('2020-01-10 00:00:00', 12271.0, 12311.2001953125, 12213.2001953125, 12256.7998046875, 660600.0)
('2020-01-13 00:00:00', 12296.7001953125, 12337.75, 12285.7998046875, 12329.5498046875, 501000.0)
('2020-01-14 00:00:00', 12333.099609375, 12374.25, 12308.7001953125, 12362.2998046875, 616300.0)
('2020-01-15 00:00:00', 12349.400390625, 12355.150390625, 12278.75, 12343.2998046875, 684400.0)
('2020-01-16 00:00:00', 12347.099609375, 12389.0498046875, 12315.7998046875, 12355.5, 395700.0)
('2020-01-17 00:00:00', 12328.400390625, 12385.4501953125, 12321.400390625, 12352.349609375, 502100.0)
('2020-01-21 00:00:00', 12195.2998046875, 12230.0498046875, 12162.2998046875, 12169.849609375, 400.0)
('2020-01-22 00:00:00', 12218.349609375, 12225.0498046875, 12087.900390625, 12106.900390625, 500.0)
('2020-01-23 00:00:00', 12123.75, 12189.0, 12094.099609375, 12180.349609375, 867700.0)
('2020-01-24 00:00:00', 12174.5498046875, 12272.150390625, 12149.650390625, 12248.25, 593200.0)
('2020-01-27 00:00:00', 12197.099609375, 12216.599609375, 12107.0, 12119.0, 441200.0)
('2020-01-28 00:00:00', 12148.099609375, 12163.5498046875, 12024.5, 12055.7998046875, 478500.0)
('2020-01-29 00:00:00', 12114.900390625, 12169.599609375, 12103.7998046875, 12129.5, 514400.0)
('2020-01-30 00:00:00', 12147.75, 12150.2998046875, 12010.599609375, 12035.7998046875, 538100.0)
('2020-01-31 00:00:00', 12100.400390625, 12103.5498046875, 11945.849609375, 11962.099609375, 771300.0)
('2020-02-03 00:00:00', 11627.4501953125, 11749.849609375, 11614.5, 11707.900390625, 669800.0)
('2020-02-04 00:00:00', 11786.25, 11986.150390625, 11783.400390625, 11979.650390625, 560400.0)
('2020-02-05 00:00:00', 12005.849609375, 12098.150390625, 11953.349609375, 12089.150390625, 758000.0)
('2020-02-06 00:00:00', 12120.0, 12160.599609375, 12084.650390625, 12137.9501953125, 565100.0)
('2020-02-07 00:00:00', 12151.150390625, 12154.7001953125, 12073.9501953125, 12098.349609375, 473500.0)
('2020-02-10 00:00:00', 12102.349609375, 12103.5498046875, 11990.75, 12031.5, 524700.0)
('2020-02-11 00:00:00', 12108.400390625, 12172.2998046875, 12099.0, 12107.900390625, 480000.0)
('2020-02-12 00:00:00', 12151.0, 12231.75, 12144.2998046875, 12201.2001953125, 411700.0)
('2020-02-13 00:00:00', 12219.5498046875, 12225.650390625, 12139.7998046875, 12174.650390625, 501200.0)
('2020-02-14 00:00:00', 12190.150390625, 12246.7001953125, 12091.2001953125, 12113.4501953125, 622800.0)
('2020-02-18 00:00:00', 12028.25, 12030.75, 11908.0498046875, 11992.5, 676900.0)
('2020-02-19 00:00:00', 12090.599609375, 12134.7001953125, 12042.099609375, 12125.900390625, 513600.0)
('2020-02-20 00:00:00', 12119.0, 12152.0, 12071.4501953125, 12080.849609375, 502600.0)
('2020-02-24 00:00:00', 12012.5498046875, 12012.5498046875, 11813.400390625, 11829.400390625, 490800.0)
('2020-02-25 00:00:00', 11877.5, 11883.0498046875, 11779.900390625, 11797.900390625, 461000.0)
('2020-02-26 00:00:00', 11738.5498046875, 11783.25, 11639.599609375, 11678.5, 567600.0)
('2020-02-27 00:00:00', 11661.25, 11663.849609375, 11536.7001953125, 11633.2998046875, 608600.0)
('2020-02-28 00:00:00', 11382.0, 11384.7998046875, 11175.0498046875, 11201.75, 809900.0)
('2020-03-02 00:00:00', 11387.349609375, 11433.0, 11036.25, 11132.75, 680800.0)
('2020-03-03 00:00:00', 11217.5498046875, 11342.25, 11152.5498046875, 11303.2998046875, 696500.0)
('2020-03-04 00:00:00', 11351.349609375, 11356.599609375, 11082.150390625, 11251.0, 797700.0)
('2020-03-05 00:00:00', 11306.0498046875, 11389.5, 11244.599609375, 11269.0, 1352500.0)
('2020-03-06 00:00:00', 10942.650390625, 11035.099609375, 10827.400390625, 10989.4501953125, 1811000.0)
('2020-03-09 00:00:00', 10742.0498046875, 10751.5498046875, 10294.4501953125, 10451.4501953125, 1565500.0)
('2020-03-11 00:00:00', 10334.2998046875, 10545.099609375, 10334.0, 10458.400390625, 1218500.0)
('2020-03-12 00:00:00', 10039.9501953125, 10040.75, 9508.0, 9590.150390625, 1343500.0)
('2020-03-13 00:00:00', 9107.599609375, 10159.400390625, 8555.150390625, 9955.2001953125, 1388000.0)
('2020-03-16 00:00:00', 9587.7998046875, 9602.2001953125, 9165.099609375, 9197.400390625, 897700.0)
('2020-03-17 00:00:00', 9285.400390625, 9403.7998046875, 8915.599609375, 8967.0498046875, 935600.0)
('2020-03-18 00:00:00', 9088.4501953125, 9127.5498046875, 8407.0498046875, 8468.7998046875, 1516600.0)
('2020-03-19 00:00:00', 8063.2998046875, 8575.4501953125, 7832.5498046875, 8263.4501953125, 925700.0)
('2020-03-20 00:00:00', 8284.4501953125, 8883.0, 8178.2001953125, 8745.4501953125, 1071500.0)
('2020-03-23 00:00:00', 7945.7001953125, 8159.25, 7583.60009765625, 7610.25, 653500.0)
('2020-03-24 00:00:00', 7848.2998046875, 8036.9501953125, 7511.10009765625, 7801.0498046875, 738400.0)
('2020-03-25 00:00:00', 7735.14990234375, 8376.75, 7714.75, 8317.849609375, 736900.0)
('2020-03-26 00:00:00', 8451.0, 8749.0498046875, 8304.900390625, 8641.4501953125, 865600.0)
('2020-03-27 00:00:00', 8949.099609375, 9038.900390625, 8522.900390625, 8660.25, 801500.0)
('2020-03-30 00:00:00', 8385.9501953125, 8576.0, 8244.0, 8281.099609375, 593300.0)
('2020-03-31 00:00:00', 8529.349609375, 8678.2998046875, 8358.0, 8597.75, 712700.0)
('2020-04-01 00:00:00', 8584.099609375, 8588.099609375, 8198.349609375, 8253.7998046875, 506300.0)
('2020-04-03 00:00:00', 8356.5498046875, 8356.5498046875, 8055.7998046875, 8083.7998046875, 697000.0)
('2020-04-07 00:00:00', 8446.2998046875, 8819.400390625, 8360.9501953125, 8792.2001953125, 814200.0)
('2020-04-08 00:00:00', 8688.900390625, 9131.7001953125, 8653.900390625, 8748.75, 896500.0)
('2020-04-09 00:00:00', 8973.0498046875, 9128.349609375, 8904.5498046875, 9111.900390625, 742100.0)
('2020-04-13 00:00:00', 9103.9501953125, 9112.0498046875, 8912.400390625, 8993.849609375, 644000.0)
('2020-04-15 00:00:00', 9196.400390625, 9261.2001953125, 8874.099609375, 8925.2998046875, 879100.0)
('2020-04-16 00:00:00', 8851.25, 9053.75, 8821.900390625, 8992.7998046875, 719400.0)
('2020-04-17 00:00:00', 9323.4501953125, 9324.0, 9091.349609375, 9266.75, 684200.0)
('2020-04-20 00:00:00', 9390.2001953125, 9390.849609375, 9230.7998046875, 9261.849609375, 726400.0)
('2020-04-21 00:00:00', 9016.9501953125, 9044.400390625, 8909.400390625, 8981.4501953125, 655100.0)
('2020-04-22 00:00:00', 9026.75, 9209.75, 8946.25, 9187.2998046875, 734400.0)
('2020-04-23 00:00:00', 9232.349609375, 9343.599609375, 9170.150390625, 9313.900390625, 666700.0)
('2020-04-24 00:00:00', 9163.900390625, 9296.900390625, 9141.2998046875, 9154.400390625, 659400.0)
('2020-04-27 00:00:00', 9259.7001953125, 9377.099609375, 9250.349609375, 9282.2998046875, 512800.0)
('2020-04-28 00:00:00', 9389.7998046875, 9404.400390625, 9260.0, 9380.900390625, 614500.0)
('2020-04-29 00:00:00', 9408.599609375, 9599.849609375, 9392.349609375, 9553.349609375, 653000.0)
('2020-04-30 00:00:00', 9753.5, 9889.0498046875, 9731.5, 9859.900390625, 931200.0)
('2020-05-04 00:00:00', 9533.5, 9533.5, 9266.9501953125, 9293.5, 687500.0)
('2020-05-05 00:00:00', 9429.400390625, 9450.900390625, 9190.75, 9205.599609375, 725200.0)
('2020-05-06 00:00:00', 9226.7998046875, 9346.900390625, 9116.5, 9270.900390625, 722200.0)
('2020-05-07 00:00:00', 9234.0498046875, 9277.849609375, 9175.900390625, 9199.0498046875, 708700.0)
('2020-05-08 00:00:00', 9376.9501953125, 9382.650390625, 9238.2001953125, 9251.5, 609100.0)
('2020-05-11 00:00:00', 9348.150390625, 9439.900390625, 9219.9501953125, 9239.2001953125, 704600.0)
('2020-05-12 00:00:00', 9168.849609375, 9240.849609375, 9043.9501953125, 9196.5498046875, 805500.0)
('2020-05-13 00:00:00', 9584.2001953125, 9584.5, 9351.099609375, 9383.5498046875, 846400.0)
('2020-05-14 00:00:00', 9213.9501953125, 9281.099609375, 9119.75, 9142.75, 602600.0)
('2020-05-15 00:00:00', 9182.400390625, 9182.400390625, 9050.0, 9136.849609375, 575900.0)
('2020-05-18 00:00:00', 9158.2998046875, 9158.2998046875, 8806.75, 8823.25, 773000.0)
('2020-05-19 00:00:00', 8961.7001953125, 9030.349609375, 8855.2998046875, 8879.099609375, 762200.0)
('2020-05-20 00:00:00', 8889.150390625, 9093.7998046875, 8875.349609375, 9066.5498046875, 622300.0)
('2020-05-21 00:00:00', 9079.4501953125, 9178.5498046875, 9056.099609375, 9106.25, 631500.0)
('2020-05-22 00:00:00', 9067.900390625, 9149.599609375, 8968.5498046875, 9039.25, 675800.0)
('2020-05-26 00:00:00', 9099.75, 9161.650390625, 8996.650390625, 9029.0498046875, 655000.0)
('2020-05-27 00:00:00', 9082.2001953125, 9334.0, 9004.25, 9314.9501953125, 763500.0)
('2020-05-28 00:00:00', 9364.9501953125, 9511.25, 9336.5, 9490.099609375, 837900.0)
('2020-05-29 00:00:00', 9422.2001953125, 9598.849609375, 9376.900390625, 9580.2998046875, 967000.0)
('2020-06-01 00:00:00', 9726.849609375, 9931.599609375, 9706.9501953125, 9826.150390625, 794200.0)
('2020-06-02 00:00:00', 9880.849609375, 9995.599609375, 9824.0498046875, 9979.099609375, 770200.0)
('2020-06-03 00:00:00', 10108.2998046875, 10176.2001953125, 10035.5498046875, 10061.5498046875, 794700.0)
('2020-06-04 00:00:00', 10054.25, 10123.849609375, 9944.25, 10029.099609375, 775100.0)
('2020-06-05 00:00:00', 10093.7998046875, 10177.7998046875, 10040.75, 10142.150390625, 987100.0)
('2020-06-08 00:00:00', 10326.75, 10328.5, 10120.25, 10167.4501953125, 936500.0)
('2020-06-09 00:00:00', 10181.150390625, 10291.150390625, 10021.4501953125, 10046.650390625, 754200.0)
('2020-06-10 00:00:00', 10072.599609375, 10148.75, 10036.849609375, 10116.150390625, 632400.0)
('2020-06-11 00:00:00', 10094.099609375, 10112.0498046875, 9885.0498046875, 9902.0, 715500.0)
('2020-06-12 00:00:00', 9544.9501953125, 9996.0498046875, 9544.349609375, 9972.900390625, 796300.0)
('2020-06-15 00:00:00', 9919.349609375, 9943.349609375, 9726.349609375, 9813.7001953125, 716100.0)
('2020-06-16 00:00:00', 10014.7998046875, 10046.150390625, 9728.5, 9914.0, 899900.0)
('2020-06-17 00:00:00', 9876.7001953125, 10003.599609375, 9833.7998046875, 9881.150390625, 685400.0)
('2020-06-18 00:00:00', 9863.25, 10111.2001953125, 9845.0498046875, 10091.650390625, 622900.0)
('2020-06-19 00:00:00', 10119.0, 10272.400390625, 10072.650390625, 10244.400390625, 892100.0)
('2020-06-22 00:00:00', 10318.75, 10393.650390625, 10277.599609375, 10311.2001953125, 685400.0)
('2020-06-23 00:00:00', 10347.9501953125, 10484.7001953125, 10301.75, 10471.0, 669200.0)
('2020-06-24 00:00:00', 10529.25, 10553.150390625, 10281.9501953125, 10305.2998046875, 854800.0)
('2020-06-25 00:00:00', 10235.5498046875, 10361.7998046875, 10194.5, 10288.900390625, 994200.0)
('2020-06-26 00:00:00', 10378.900390625, 10409.849609375, 10311.25, 10383.0, 671900.0)
('2020-06-29 00:00:00', 10311.9501953125, 10337.9501953125, 10223.599609375, 10312.400390625, 574500.0)
('2020-06-30 00:00:00', 10382.599609375, 10401.0498046875, 10267.349609375, 10302.099609375, 556200.0)
('2020-07-01 00:00:00', 10323.7998046875, 10447.0498046875, 10299.599609375, 10430.0498046875, 573600.0)
('2020-07-02 00:00:00', 10493.0498046875, 10598.2001953125, 10485.5498046875, 10551.7001953125, 597400.0)
('2020-07-06 00:00:00', 10723.849609375, 10811.400390625, 10695.099609375, 10763.650390625, 571200.0)
('2020-07-07 00:00:00', 10802.849609375, 10813.7998046875, 10689.7001953125, 10799.650390625, 636800.0)
('2020-07-08 00:00:00', 10818.650390625, 10847.849609375, 10676.5498046875, 10705.75, 767900.0)
('2020-07-09 00:00:00', 10755.5498046875, 10836.849609375, 10733.0, 10813.4501953125, 618700.0)
('2020-07-10 00:00:00', 10764.099609375, 10819.400390625, 10713.0, 10768.0498046875, 590700.0)
('2020-07-13 00:00:00', 10851.849609375, 10894.0498046875, 10756.0498046875, 10802.7001953125, 554100.0)
('2020-07-14 00:00:00', 10750.849609375, 10755.650390625, 10562.900390625, 10607.349609375, 532400.0)
('2020-07-15 00:00:00', 10701.0, 10827.4501953125, 10577.75, 10618.2001953125, 715900.0)
('2020-07-16 00:00:00', 10706.2001953125, 10755.2998046875, 10595.2001953125, 10739.9501953125, 694400.0)
('2020-07-17 00:00:00', 10752.0, 10933.4501953125, 10749.650390625, 10901.7001953125, 676900.0)
('2020-07-20 00:00:00', 10999.4501953125, 11037.900390625, 10953.0, 11022.2001953125, 554300.0)
('2020-07-21 00:00:00', 11126.099609375, 11179.5498046875, 11113.25, 11162.25, 772000.0)
('2020-07-22 00:00:00', 11231.2001953125, 11238.099609375, 11056.5498046875, 11132.599609375, 765100.0)
('2020-07-23 00:00:00', 11135.0, 11239.7998046875, 11103.150390625, 11215.4501953125, 621600.0)
('2020-07-24 00:00:00', 11149.9501953125, 11225.400390625, 11090.2998046875, 11194.150390625, 678900.0)
('2020-07-27 00:00:00', 11225.0, 11225.0, 11087.849609375, 11131.7998046875, 588100.0)
('2020-07-28 00:00:00', 11154.099609375, 11317.75, 11151.400390625, 11300.5498046875, 683900.0)
('2020-07-29 00:00:00', 11276.900390625, 11341.400390625, 11149.75, 11202.849609375, 600700.0)
('2020-07-30 00:00:00', 11254.2998046875, 11299.9501953125, 11084.9501953125, 11102.150390625, 677800.0)
('2020-07-31 00:00:00', 11139.5, 11150.400390625, 11026.650390625, 11073.4501953125, 642600.0)
('2020-08-03 00:00:00', 11057.5498046875, 11058.0498046875, 10882.25, 10891.599609375, 680900.0)
('2020-08-04 00:00:00', 10946.650390625, 11112.25, 10908.099609375, 11095.25, 625700.0)
('2020-08-05 00:00:00', 11155.75, 11225.650390625, 11064.0498046875, 11101.650390625, 667600.0)
('2020-08-06 00:00:00', 11185.7001953125, 11256.7998046875, 11127.2998046875, 11200.150390625, 600400.0)
('2020-08-07 00:00:00', 11186.650390625, 11231.900390625, 11142.0498046875, 11214.0498046875, 452600.0)
('2020-08-10 00:00:00', 11270.25, 11337.2998046875, 11238.0, 11270.150390625, 492000.0)
('2020-08-11 00:00:00', 11322.25, 11373.599609375, 11299.150390625, 11322.5, 586100.0)
('2020-08-12 00:00:00', 11289.0, 11322.0, 11242.650390625, 11308.400390625, 609900.0)
('2020-08-13 00:00:00', 11334.849609375, 11359.2998046875, 11269.9501953125, 11300.4501953125, 562400.0)
('2020-08-14 00:00:00', 11353.2998046875, 11366.25, 11111.4501953125, 11178.400390625, 645100.0)
('2020-08-17 00:00:00', 11248.900390625, 11267.099609375, 11144.5, 11247.099609375, 634000.0)
('2020-08-18 00:00:00', 11259.7998046875, 11401.7001953125, 11253.150390625, 11385.349609375, 579200.0)
('2020-08-19 00:00:00', 11452.150390625, 11460.349609375, 11394.099609375, 11408.400390625, 626200.0)
('2020-08-20 00:00:00', 11317.4501953125, 11361.4501953125, 11289.7998046875, 11312.2001953125, 791600.0)
('2020-08-21 00:00:00', 11409.650390625, 11418.5, 11362.2001953125, 11371.599609375, 668700.0)
('2020-08-24 00:00:00', 11412.0, 11497.25, 11410.650390625, 11466.4501953125, 532900.0)
('2020-08-25 00:00:00', 11513.099609375, 11525.900390625, 11423.349609375, 11472.25, 638200.0)
('2020-08-26 00:00:00', 11512.849609375, 11561.75, 11461.849609375, 11549.599609375, 743400.0)
('2020-08-27 00:00:00', 11609.2998046875, 11617.349609375, 11540.599609375, 11559.25, 719800.0)
('2020-08-28 00:00:00', 11602.9501953125, 11686.0498046875, 11589.400390625, 11647.599609375, 807000.0)
('2020-08-31 00:00:00', 11777.5498046875, 11794.25, 11325.849609375, 11387.5, 1371800.0)
('2020-09-01 00:00:00', 11464.2998046875, 11553.5498046875, 11366.900390625, 11470.25, 783800.0)
('2020-09-02 00:00:00', 11478.5498046875, 11554.75, 11430.400390625, 11535.0, 593500.0)
('2020-09-03 00:00:00', 11566.2001953125, 11584.9501953125, 11507.650390625, 11527.4501953125, 607100.0)
('2020-09-04 00:00:00', 11354.400390625, 11452.0498046875, 11303.650390625, 11333.849609375, 681300.0)
('2020-09-08 00:00:00', 11378.5498046875, 11437.25, 11290.4501953125, 11317.349609375, 572200.0)
('2020-09-09 00:00:00', 11218.599609375, 11298.150390625, 11185.150390625, 11278.0, 728900.0)
('2020-09-10 00:00:00', 11363.2998046875, 11464.0498046875, 11327.400390625, 11449.25, 679400.0)
('2020-09-11 00:00:00', 11447.7998046875, 11493.5, 11419.900390625, 11464.4501953125, 554800.0)
('2020-09-14 00:00:00', 11540.150390625, 11568.900390625, 11383.5498046875, 11440.0498046875, 642300.0)
('2020-09-15 00:00:00', 11487.2001953125, 11535.9501953125, 11442.25, 11521.7998046875, 506700.0)
('2020-09-16 00:00:00', 11538.4501953125, 11618.099609375, 11516.75, 11604.5498046875, 527800.0)
('2020-09-17 00:00:00', 11539.400390625, 11587.2001953125, 11498.5, 11516.099609375, 0.0)
('2020-09-18 00:00:00', 11584.099609375, 11584.099609375, 11446.099609375, 11504.9501953125, 764200.0)
('2020-09-21 00:00:00', 11503.7998046875, 11535.25, 11218.5, 11250.5498046875, 602900.0)
('2020-09-22 00:00:00', 11301.75, 11302.2001953125, 11084.650390625, 11153.650390625, 672200.0)
('2020-09-23 00:00:00', 11258.75, 11259.5498046875, 11024.400390625, 11131.849609375, 714900.0)
('2020-09-24 00:00:00', 11011.0, 11015.2998046875, 10790.2001953125, 10805.5498046875, 706100.0)
('2020-09-25 00:00:00', 10910.400390625, 11072.599609375, 10854.849609375, 11050.25, 559600.0)
('2020-09-28 00:00:00', 11140.849609375, 11239.349609375, 11099.849609375, 11227.5498046875, 472800.0)
('2020-09-29 00:00:00', 11288.599609375, 11305.400390625, 11181.0, 11222.400390625, 498300.0)
('2020-09-30 00:00:00', 11244.4501953125, 11295.400390625, 11184.5498046875, 11247.5498046875, 499300.0)
('2020-10-01 00:00:00', 11364.4501953125, 11428.599609375, 11347.0498046875, 11416.9501953125, 447700.0)
('2020-10-05 00:00:00', 11487.7998046875, 11578.0498046875, 11452.2998046875, 11503.349609375, 530600.0)
('2020-10-06 00:00:00', 11603.4501953125, 11680.2998046875, 11564.2998046875, 11662.400390625, 561400.0)
('2020-10-07 00:00:00', 11679.25, 11763.0498046875, 11629.349609375, 11738.849609375, 513400.0)
('2020-10-08 00:00:00', 11835.400390625, 11905.7001953125, 11791.150390625, 11834.599609375, 608800.0)
('2020-10-09 00:00:00', 11852.0498046875, 11938.599609375, 11805.2001953125, 11914.2001953125, 611100.0)
('2020-10-12 00:00:00', 11973.5498046875, 12022.0498046875, 11867.2001953125, 11930.9501953125, 522600.0)
('2020-10-13 00:00:00', 11934.650390625, 11988.2001953125, 11888.900390625, 11934.5, 458300.0)
('2020-10-14 00:00:00', 11917.400390625, 11997.2001953125, 11822.150390625, 11971.0498046875, 569200.0)
('2020-10-15 00:00:00', 12023.4501953125, 12025.4501953125, 11661.2998046875, 11680.349609375, 608900.0)
('2020-10-16 00:00:00', 11727.400390625, 11789.75, 11667.849609375, 11762.4501953125, 555800.0)
('2020-10-19 00:00:00', 11879.2001953125, 11898.25, 11820.400390625, 11873.0498046875, 541400.0)
('2020-10-20 00:00:00', 11861.0, 11949.25, 11837.25, 11896.7998046875, 453600.0)
('2020-10-21 00:00:00', 11958.5498046875, 12018.650390625, 11775.75, 11937.650390625, 623700.0)
('2020-10-22 00:00:00', 11890.0, 11939.5498046875, 11823.4501953125, 11896.4501953125, 544900.0)
('2020-10-23 00:00:00', 11957.900390625, 11974.5498046875, 11908.75, 11930.349609375, 502300.0)
('2020-10-26 00:00:00', 11937.400390625, 11942.849609375, 11711.7001953125, 11767.75, 519800.0)
('2020-10-27 00:00:00', 11807.099609375, 11899.0498046875, 11723.0, 11889.400390625, 616300.0)
('2020-10-28 00:00:00', 11922.599609375, 11929.400390625, 11684.849609375, 11729.599609375, 704000.0)
('2020-10-29 00:00:00', 11633.2998046875, 11744.150390625, 11606.4501953125, 11670.7998046875, 555000.0)
('2020-10-30 00:00:00', 11678.4501953125, 11748.9501953125, 11535.4501953125, 11642.400390625, 553700.0)
('2020-11-02 00:00:00', 11697.349609375, 11725.650390625, 11557.400390625, 11669.150390625, 568400.0)
('2020-11-03 00:00:00', 11734.4501953125, 11836.2001953125, 11723.2998046875, 11813.5, 674300.0)
('2020-11-04 00:00:00', 11783.349609375, 11929.650390625, 11756.400390625, 11908.5, 667300.0)

In [78]:
import sqlite3

# Re-establish connection to the database
conn = sqlite3.connect('stocks.db')
cursor = conn.cursor()

cursor.execute("""
SELECT date, ticker,close
FROM stocks
WHERE ticker = '^IXIC'
ORDER BY close DESC
LIMIT 1
""")


rows = cursor.fetchall()

for row in rows:
    print(row)#Find the highest closing price for NASDAQ (^IXIC)

('2025-10-29 00:00:00', '^IXIC', 23958.470703125)

In [79]:






cursor.execute("""
SELECT date, high,low,
(high - low) AS price_difference
FROM stocks
WHERE ticker = '^GSPC'
ORDER BY price_difference DESC
LIMIT 5
""")


rows = cursor.fetchall()

for row in rows:
    print(row)#List top 5 days with highest price difference (high - low) for S&P 500 (^GSPC)

('2025-04-09 00:00:00', 5481.33984375, 4948.43017578125, 532.90966796875)
('2025-04-07 00:00:00', 5246.56982421875, 4835.0400390625, 411.52978515625)
('2025-04-08 00:00:00', 5267.47021484375, 4910.419921875, 357.05029296875)
('2025-11-20 00:00:00', 6770.35009765625, 6534.0498046875, 236.30029296875)
('2025-04-04 00:00:00', 5292.14013671875, 5069.89990234375, 222.240234375)

In [80]:




cursor.execute("""
SELECT
    ticker,
    strftime('%Y-%m', date) AS month,
    AVG(close)
FROM stocks
GROUP BY ticker, month
ORDER BY ticker, month
LIMIT 20
""")


rows = cursor.fetchall()

for row in rows:
    print(row)#Get monthly average closing price for each ticker

('^GSPC', '2020-01', 3278.202857607887)
('^GSPC', '2020-02', 3273.956637912326)
('^GSPC', '2020-03', 2641.449044363839)
('^GSPC', '2020-04', 2775.8244357638887)
('^GSPC', '2020-05', 2924.287353515625)
('^GSPC', '2020-06', 3104.6609330610795)
('^GSPC', '2020-07', 3207.6190962357955)
('^GSPC', '2020-08', 3391.7100190662204)
('^GSPC', '2020-09', 3365.516671316964)
('^GSPC', '2020-10', 3422.0466657366073)
('^GSPC', '2020-11', 3540.628323025174)
('^GSPC', '2020-12', 3695.3100142045455)
('^GSPC', '2021-01', 3790.6444498697915)
('^GSPC', '2021-02', 3883.4321160567433)
('^GSPC', '2021-03', 3906.25048828125)
('^GSPC', '2021-04', 4140.348427220395)
('^GSPC', '2021-05', 4170.762669613487)
('^GSPC', '2021-06', 4238.48954634233)
('^GSPC', '2021-07', 4363.963940429688)
('^GSPC', '2021-08', 4456.259556361607)

In [81]:
cursor.execute("""
SELECT
    AVG(volume)
FROM stocks
WHERE ticker = '^NSEI'
AND date BETWEEN '2024-01-01' AND '2024-12-31'
""")

rows = cursor.fetchall()

for row in rows:
    print(row)#Get average trading volume of NSEI in 2024

(316511.39240506326,)

merge 4 datas

In [82]:
for db in ["Crypto_prices.db","Cryptocurrencies.db","Oil_prices.db","stocks.db"]:
    conn = sqlite3.connect(db)
    cursor = conn.cursor()

    cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
    print(db, "->", cursor.fetchall())

    conn.close()

Crypto_prices.db -> [('Crypto_prices',)]
Cryptocurrencies.db -> [('Cryptocurrencies',)]
Oil_prices.db -> [('Oil_prices',)]
stocks.db -> [('stocks',)]

In [83]:
merged_df = pd.concat(
    [Cryptocurrencies_df,Crypto_prices_df,Oil_prices_df,stock_prices_df],
    axis=1
)


Cryptocurrencies_df,Crypto_prices_df,Oil_prices_df,stock_prices_df

(                     id  symbol                 name  current_price  \
 0               bitcoin     btc              Bitcoin   5.978426e+06
 1              ethereum     eth             Ethereum   1.712600e+05
 2                tether    usdt               Tether   9.084000e+01
 3                ripple     xrp                  XRP   1.243600e+02
 4           binancecoin     bnb                  BNB   5.462700e+04
 ...                 ...     ...                  ...            ...
 1245      bitrise-token   brise              Bitgert   1.960000e-06
 1246      landwolf-0x67    wolf             LandWolf   8.572700e-04
 1247      localcoinswap     lcs        LocalCoinSwap   2.011000e+01
 1248  bitcoin-usd-btcfi  btcusd  Bitcoin USD (BTCFi)   9.040000e+01
 1249               pivx    pivx                 PIVX   7.620000e+00

            market_cap  market_cap_rank  total_volume  circulating_supply  \
 0     119492824100063                1  3.561193e+12        1.999344e+07
 1      20665183551559                2  1.515937e+12        1.206924e+08
 2      16680747314099                3  5.699465e+12        1.836242e+11
 3       7580152143181                4  2.349981e+11        6.101858e+10
 4       7444065516099                5  9.409038e+10        1.363590e+08
 ...               ...              ...           ...                 ...
 1245        774602879             1246  1.202681e+08        3.956882e+14
 1246        772329935             1247  6.698073e+07        9.021595e+11
 1247        769218143             1248  1.510000e+05        3.825207e+07
 1248        769080571             1249  1.377424e+06        8.507197e+06
 1249        768707497             1253  9.649097e+07        1.008221e+08

       total_supply           ath           atl        date
 0     1.999344e+07  1.118701e+07  3.993420e+03  2026-02-23
 1     1.206924e+08  4.319460e+05  2.813000e+01  2026-02-23
 2     1.890912e+11  1.055200e+02  3.686000e+01  2026-02-23
 3     9.998571e+10  3.139900e+02  1.593430e-01  2026-02-23
 4     1.363590e+08  1.214220e+05  2.580000e+00  2026-02-23
 ...            ...           ...           ...         ...
 1245  4.270635e+14  1.417800e-04  4.533800e-08  2026-02-23
 1246  9.021595e+11  2.406188e-02  2.280700e-04  2026-02-23
 1247  7.273242e+07  5.723000e+01  1.458910e-01  2026-02-23
 1248  8.507197e+06  1.015000e+02  7.936000e+01  2026-02-23
 1249  1.008221e+08  8.648500e+02  3.561335e-02  2026-02-23

 [1250 rows x 12 columns],
       coin_id        date     price_inr
 0     bitcoin  2025-02-24  8.341958e+06
 1     bitcoin  2025-02-25  7.922798e+06
 2     bitcoin  2025-02-26  7.729282e+06
 3     bitcoin  2025-02-27  7.314307e+06
 4     bitcoin  2025-02-28  7.397417e+06
 ...       ...         ...           ...
 1093   tether  2026-02-20  9.101081e+01
 1094   tether  2026-02-21  9.069154e+01
 1095   tether  2026-02-22  9.070614e+01
 1096   tether  2026-02-23  9.069543e+01
 1097   tether  2026-02-23  9.083841e+01

 [1098 rows x 3 columns],
             Date  Price
 0     2020-01-02  61.17
 1     2020-01-03  63.00
 2     2020-01-06  63.27
 3     2020-01-07  62.70
 4     2020-01-08  59.65
 ...          ...    ...
 1515  2026-01-26  60.46
 1516  2026-01-27  62.04
 1517  2026-01-28  62.75
 1518  2026-01-29  64.77
 1519  2026-01-30  64.50

 [1520 rows x 2 columns],
 Ticker       Date        ^GSPC                                         \
 Price                     Open         High          Low        Close
 1      2020-01-02  3244.669922  3258.139893  3235.530029  3257.850098
 2      2020-01-03  3226.360107  3246.149902  3222.340088  3234.850098
 3      2020-01-06  3217.550049  3246.840088  3214.639893  3246.280029
 4      2020-01-07  3241.860107  3244.909912  3232.429932  3237.179932
 5      2020-01-08  3238.590088  3267.070068  3236.669922  3253.050049
 ...           ...          ...          ...          ...          ...
 1558   2026-01-05  6892.189941  6920.379883  6891.560059  6902.049805
 1559   2026-01-06  6908.029785  6948.689941  6904.020020  6944.819824
 1560   2026-01-07  6945.069824  6965.689941  6919.189941  6920.930176
 1561   2026-01-08  6914.109863  6931.279785  6899.330078  6921.459961
 1562   2026-01-09  6927.830078  6978.359863  6917.640137  6966.279785

 Ticker                       ^IXIC                                            \
 Price         Volume          Open          High           Low         Close
 1       3.459930e+09   9039.459961   9093.429688   9010.889648   9092.190430
 2       3.484700e+09   8976.429688   9065.759766   8976.429688   9020.769531
 3       3.702460e+09   8943.500000   9072.410156   8943.500000   9071.469727
 4       3.435910e+09   9076.639648   9091.929688   9042.549805   9068.580078
 5       3.726840e+09   9068.030273   9168.889648   9059.379883   9129.240234
 ...              ...           ...           ...           ...           ...
 1558    5.771930e+09  23449.669922  23476.509766  23332.230469  23395.820312
 1559    5.509680e+09  23446.960938  23559.150391  23389.570312  23547.169922
 1560    5.214480e+09  23544.890625  23723.369141  23504.210938  23584.279297
 1561    5.333200e+09  23548.880859  23558.169922  23353.460938  23480.019531
 1562    5.163900e+09  23496.210938  23721.150391  23426.480469  23671.349609

 Ticker                       ^NSEI                                            \
 Price         Volume          Open          High           Low         Close
 1       2.862700e+09  12198.549805  12289.900391  12195.250000  12282.200195
 2       2.586520e+09  12261.099609  12265.599609  12191.349609  12226.650391
 3       2.810450e+09  12170.599609  12179.099609  11974.200195  11993.049805
 4       2.381740e+09  12079.099609  12152.150391  12005.349609  12052.950195
 5       2.472620e+09  11939.099609  12044.950195  11929.599609  12025.349609
 ...              ...           ...           ...           ...           ...
 1558    8.737320e+09  26333.699219  26373.199219  26210.050781  26250.300781
 1559    9.012640e+09  26189.699219  26273.949219  26124.750000  26178.699219
 1560    8.396920e+09  26143.099609  26187.150391  26067.900391  26140.750000
 1561    7.723140e+09  26106.500000  26133.199219  25858.449219  25876.849609
 1562    8.124420e+09  25840.400391  25940.599609  25623.000000  25683.300781

 Ticker
 Price     Volume
 1       407700.0
 2       428800.0
 3       396500.0
 4       447800.0
 5       446000.0
 ...          ...
 1558    338800.0
 1559    383000.0
 1560    338200.0
 1561    328500.0
 1562    348800.0

 [1444 rows x 16 columns])

In [84]:
merged_df.head()

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,...,"(^IXIC, Open)","(^IXIC, High)","(^IXIC, Low)","(^IXIC, Close)","(^IXIC, Volume)","(^NSEI, Open)","(^NSEI, High)","(^NSEI, Low)","(^NSEI, Close)","(^NSEI, Volume)"
0,bitcoin,btc,Bitcoin,5978426.00,1.194928e+14,1.0,3.561193e+12,1.999344e+07,1.999344e+07,11187013.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ethereum,eth,Ethereum,171260.00,2.066518e+13,2.0,1.515937e+12,1.206924e+08,1.206924e+08,431946.00,...,9039.459961,9093.429688,9010.889648,9092.190430,2.862700e+09,12198.549805,12289.900391,12195.250000,12282.200195,407700.0
2,tether,usdt,Tether,90.84,1.668075e+13,3.0,5.699465e+12,1.836242e+11,1.890912e+11,105.52,...,8976.429688,9065.759766,8976.429688,9020.769531,2.586520e+09,12261.099609,12265.599609,12191.349609,12226.650391,428800.0
3,ripple,xrp,XRP,124.36,7.580152e+12,4.0,2.349981e+11,6.101858e+10,9.998571e+10,313.99,...,8943.500000,9072.410156,8943.500000,9071.469727,2.810450e+09,12170.599609,12179.099609,11974.200195,11993.049805,396500.0
4,binancecoin,bnb,BNB,54627.00,7.444066e+12,5.0,9.409038e+10,1.363590e+08,1.363590e+08,121422.00,...,9076.639648,9091.929688,9042.549805,9068.580078,2.381740e+09,12079.099609,12152.150391,12005.349609,12052.950195,447800.0

In [85]:
print(merged_df.columns)

Index([                'id',             'symbol',               'name',
            'current_price',         'market_cap',    'market_cap_rank',
             'total_volume', 'circulating_supply',       'total_supply',
                      'ath',                'atl',               'date',
                  'coin_id',               'date',          'price_inr',
                     'Date',              'Price',         ('Date', ''),
          ('^GSPC', 'Open'),    ('^GSPC', 'High'),     ('^GSPC', 'Low'),
         ('^GSPC', 'Close'),  ('^GSPC', 'Volume'),    ('^IXIC', 'Open'),
          ('^IXIC', 'High'),     ('^IXIC', 'Low'),   ('^IXIC', 'Close'),
        ('^IXIC', 'Volume'),    ('^NSEI', 'Open'),    ('^NSEI', 'High'),
           ('^NSEI', 'Low'),   ('^NSEI', 'Close'),  ('^NSEI', 'Volume')],
      dtype='object')

In [86]:
gspc.rename(columns={('Date',''): 'date'}, inplace=True)
ixic.rename(columns={('Date',''): 'date'}, inplace=True)
nsei.rename(columns={('Date',''): 'date'}, inplace=True)

In [87]:
merged_df.columns = [
             'id',             'symbol',               'name',
            'current_price',         'market_cap',    'market_cap_rank',
             'total_volume', 'circulating_supply',       'total_supply',
                      'ath',                'atl',               'date',
                  'coin_id',               'date',          'price_inr',
                     'date',              'Price',         ('Date', ''),
          ('^GSPC', 'Open'),    ('^GSPC', 'High'),     ('^GSPC', 'Low'),
         ('^GSPC', 'Close'),  ('^GSPC', 'Volume'),    ('^IXIC', 'Open'),
          ('^IXIC', 'High'),     ('^IXIC', 'Low'),   ('^IXIC', 'Close'),
        ('^IXIC', 'Volume'),    ('^NSEI', 'Open'),    ('^NSEI', 'High'),
           ('^NSEI', 'Low'),   ('^NSEI', 'Close'),  ('^NSEI', 'Volume')]

In [88]:
merged_df.columns = [
    '_'.join(col).replace('^','') if isinstance(col, tuple) else col.replace('^','')
    for col in merged_df.columns
]

In [89]:
merged_df = merged_df.loc[:, ~merged_df.columns.duplicated()] #removes duplicate date column

In [90]:
import sqlite3

# Re-establish connection to the database
conn = sqlite3.connect('merged_data.db')
cursor = conn.cursor()

In [91]:
merged_df.to_sql("merged_data",conn,if_exists="replace", index=False)

 # Pushing dataframe into sql

1561

In [92]:
cursor.execute("""
SELECT
    'Bitcoin' AS asset,
    AVG(price_inr) AS avg_price_2025
FROM merged_data
WHERE coin_id = 'bitcoin'
  AND date BETWEEN '2026-01-01' AND '2026-12-31'

UNION ALL

SELECT
    'Oil' AS asset,
    AVG(price) AS avg_price_2025
FROM  merged_data
WHERE date BETWEEN '2026-01-01' AND '2026-12-31'
""")

results = cursor.fetchall()
for r in results:
    print(r)#Compare Bitcoin vs Oil average price in 2026.

('Bitcoin', 8685946.934184814)
('Oil', 71.23506399999997)

In [93]:
print(merged_df.columns)

Index(['id', 'symbol', 'name', 'current_price', 'market_cap',
       'market_cap_rank', 'total_volume', 'circulating_supply', 'total_supply',
       'ath', 'atl', 'date', 'coin_id', 'price_inr', 'Price', 'Date_',
       'GSPC_Open', 'GSPC_High', 'GSPC_Low', 'GSPC_Close', 'GSPC_Volume',
       'IXIC_Open', 'IXIC_High', 'IXIC_Low', 'IXIC_Close', 'IXIC_Volume',
       'NSEI_Open', 'NSEI_High', 'NSEI_Low', 'NSEI_Close', 'NSEI_Volume'],
      dtype='object')

In [94]:
import pandas as pd#Get Bitcoin data,#Get S&P 500 close prices

cursor.execute("""
SELECT Date, price_inr, GSPC_Close AS sp500_close
FROM merged_data
WHERE coin_id = 'bitcoin'
""")

correlation = merged_df["price_inr"].corr(
    merged_df["GSPC_Close"]
)

print("Correlation between Bitcoin and S&P 500:", correlation)#Check if Bitcoin moves with S&P 500 (correlation idea).

Correlation between Bitcoin and S&P 500: -0.7442512652682988

In [95]:
cursor.execute("""
SELECT
date, Price,price_inr,
IXIC_Close AS nasdaq_close
FROM merged_data
WHERE coin_id = 'ethereum'
AND date BETWEEN '2026-01-01' AND '2026-12-31'

""")


daily_prices = cursor.fetchall()

for row in daily_prices:
    print(row)

 # Compare Ethereum and NASDAQ daily prices for 2025.

('2026-02-23', 71.06, 244834.16977505904, 13756.330078125)
('2026-02-23', 71.64, 216983.40981432973, 13614.509765625)
('2026-02-23', 73.64, 217304.159336794, 13814.490234375)
('2026-02-23', 73.15, 202765.03870967304, 13881.7197265625)
('2026-02-23', 73.11, 201317.5125202556, 13924.91015625)
('2026-02-23', 73.31, 195516.66716854277, 13911.75)
('2026-02-23', 74.21, 193559.06747479382, 14020.330078125)
('2026-02-23', 72.98, 220175.98842114926, 14069.419921875)
('2026-02-23', 73.14, 187601.93013882774, 14174.1396484375)
('2026-02-23', 73.52, 189391.99179852934, 14072.8603515625)
('2026-02-23', 75.33, 194675.72885365813, 14039.6796875)
('2026-02-23', 75.37, 191886.11355343607, 14161.349609375)
('2026-02-23', 73.62, 186564.74028701626, 14030.3798828125)
('2026-02-23', 72.22, 191643.05645176853, 14141.48046875)
('2026-02-23', 72.98, 175758.37045736366, 14253.26953125)
('2026-02-23', 74.56, 164149.389538545, 14271.73046875)
('2026-02-23', 74.21, 167538.8977230319, 14369.7099609375)
('2026-02-23', 75.24, 166533.75651871518, 14360.3896484375)
('2026-02-23', 73.06, 161919.08161409126, 14500.509765625)
('2026-02-23', 71.67, 166129.37514050907, 14528.330078125)
('2026-02-23', 71.76, 168649.33224748378, 14503.9501953125)
('2026-02-23', 66.45, 164134.74219204995, 14522.3798828125)
('2026-02-23', 67.32, 167679.9006033522, 14639.330078125)
('2026-02-23', 70.26, 167319.001543521, None)
('2026-02-23', 72.15, 177917.82793888426, 14663.6396484375)
('2026-02-23', 72.24, 171006.12473780697, 14665.0595703125)
('2026-02-23', 72.15, 168930.37673281875, 14559.7802734375)
('2026-02-23', 71.68, 170229.9761188356, 14701.919921875)
('2026-02-23', 72.37, 172085.9718554942, 14733.240234375)
('2026-02-23', 73.62, 177753.92370784696, 14677.650390625)
('2026-02-23', 73.93, 177052.68464483944, 14644.9501953125)
('2026-02-23', 71.31, 172151.5682806194, 14543.1298828125)
('2026-02-23', 70.64, 171697.82772804037, 14427.240234375)
('2026-02-23', 68.19, 162266.37796915465, 14274.98046875)
('2026-02-23', 69.1, 156474.22180351955, 14498.8798828125)
('2026-02-23', 68.26, 154426.70647452315, None)
('2026-02-23', 66.56, 155840.4924805317, 14684.599609375)
('2026-02-23', 68.33, 163227.64895741257, 14836.990234375)
('2026-02-23', 69.3, 153890.04212059852, 14840.7099609375)
('2026-02-23', 69.12, 155066.27550185894, 14660.580078125)
('2026-02-23', 68.36, 155313.1292931023, 14762.580078125)
('2026-02-23', 67.44, 154802.90633012433, 14778.259765625)
('2026-02-23', 66.5, 134677.50142669896, 14672.6796875)
('2026-02-23', 65.36, 133837.57278106204, 14681.0703125)
('2026-02-23', 63.69, 127176.85742857557, 14761.2900390625)
('2026-02-23', 62.25, 143324.73934384843, 14780.5302734375)
('2026-02-23', 65.65, 131454.92128790365, 14895.1201171875)
('2026-02-23', 67.5, 134990.81789744264, 14835.759765625)
('2026-02-23', 68.54, 141499.98989505236, 14860.1796875)
('2026-02-23', 67.42, 137163.51905527923, 14788.08984375)
('2026-02-23', 68.84, 139502.26918137303, 14765.1396484375)
('2026-02-23', 69.28, 136118.34029958773, 14816.259765625)
('2026-02-23', 68.43, 135084.25007491114, 14822.900390625)
('2026-02-23', 68.63, 135202.85645156694, 14793.759765625)
('2026-02-23', 70.07, 135687.4227659859, 14656.1796875)
('2026-02-23', 69.34, 137898.7403436233, 14525.91015625)
('2026-02-23', 68.49, 135372.22120159038, None)
('2026-02-23', 69.36, 134334.00818529903, 14714.66015625)
('2026-02-23', 68.26, 149984.44480204728, 14942.650390625)
('2026-02-23', 69.82, 153384.6912264906, 15019.7998046875)
('2026-02-23', 70.54, 150793.82263866183, 15041.8603515625)
('2026-02-23', 70.53, 152736.0854367373, 14945.8095703125)
('2026-02-23', 72.59, 155508.64352977095, 15129.5)
('2026-02-23', 72.69, 153154.64715995087, 15265.8896484375)
('2026-02-23', 72.09, 153246.47199208362, 15259.240234375)
('2026-02-23', 70.41, 153045.86830616, 15309.3798828125)
('2026-02-23', 70.51, 151706.98921091956, 15331.1796875)
('2026-02-23', 72.37, 155745.16924065605, 15363.51953125)
('2026-02-23', 73.43, 155840.93772632716, None)
('2026-02-23', 74.18, 155254.81405305702, 15374.330078125)
('2026-02-13', 75.54, 152837.10606631296, 15286.6396484375)
('2026-02-23', 75.44, 153282.69389658255, 15248.25)
('2026-02-23', 75.06, 153903.86052217713, None)
('2026-02-23', 75.22, 153546.46543390723, 15105.580078125)
('2026-02-23', 76.01, 189067.0538600533, 15037.759765625)
('2026-02-23', 77.68, 199979.47617304884, 15161.5302734375)
('2026-02-23', 79.17, 220672.16056835878, 15181.919921875)
('2026-02-23', 77.66, 214170.10011952536, 15043.9697265625)
('2026-02-23', 78.46, 211740.19586880849, 14713.900390625)
('2026-02-23', 79.55, 227649.06017478785, 14746.400390625)
('2026-02-23', 80.64, 222550.86125964453, 14896.849609375)
('2026-02-23', 80.75, 217226.91460543944, 15052.240234375)
('2026-02-23', 80.67, 217756.90685748137, 15047.7001953125)
('2026-02-23', 81.43, 211823.19396124792, 14969.9697265625)
('2026-02-20', 82.39, 210787.9756927576, 14546.6796875)
('2026-02-23', 82.62, 215738.55684027018, 14512.4404296875)
('2026-02-23', 83.19, 215915.19935485243, 14448.580078125)
('2026-02-23', 84.4, 219047.5756337483, 14566.7001953125)
('2026-02-23', 82.64, 228450.3696380665, 14255.48046875)
('2026-02-23', 84.53, 214375.8056090152, 14433.830078125)
('2026-02-23', 84.64, 215195.01779836757, 14501.91015625)
('2026-02-23', 85.64, 216970.8522801864, 14654.01953125)
('2026-02-23', 82.66, 218190.67523487698, 14579.5400390625)
('2026-02-23', 82.78, 227238.5848495167, 14486.2001953125)
('2026-02-23', 83.5, 228525.93909568293, 14465.919921875)
('2026-02-23', 84.08, 224768.84403505738, 14571.6396484375)
('2026-02-23', 83.91, 216016.02336935312, 14823.4296875)
('2026-02-23', 80.82, 216690.8648491384, None)
('2026-02-23', 78.88, 217089.5740742275, 15021.8095703125)
('2026-02-23', 81.25, 222777.49872829148, 15129.08984375)
('2026-02-23', 81.96, 222455.17860950096, 15121.6796875)
('2026-02-23', 84.12, 224236.44416331983, 15215.7001953125)
('2026-02-23', 81.23, 207961.65418872624, 15090.2001953125)
('2026-02-23', 81.47, 212876.9182145838, 15226.7099609375)
('2026-02-23', 80.87, 216727.81140618862, 15235.7099609375)
('2026-02-23', 80.85, 215217.42336418747, 15235.83984375)
('2026-02-23', 80.76, 230255.54711844953, 15448.1201171875)
('2026-02-23', 78.32, 240556.86572695823, 15498.3896484375)
('2026-02-23', 78.92, 237276.58179525606, 15595.919921875)
('2026-02-23', 76.11, 227345.61024210224, 15649.599609375)
('2026-02-23', 76.74, 221936.8494721614, 15811.580078125)
('2026-02-23', 78.32, 218235.52611319744, 15940.3095703125)
('2026-02-23', 78.32, 219421.86983518038, None)
('2026-02-23', 69.88, 220541.89744913176, 15982.3603515625)
('2026-02-23', 66.14, 217182.0562912451, 15886.5400390625)
('2026-02-23', 65.44, 218382.42014738446, 15622.7099609375)
('2026-02-23', 66.6, 218767.0130883784, 15704.2802734375)
('2026-02-23', 66.39, 208337.07852694736, 15860.9599609375)
('2026-02-23', 69.62, 196636.0383307714, 15853.849609375)
('2026-02-23', 71.94, 192852.03096719063, 15973.8603515625)
('2026-02-23', 72.43, 209315.24780590468, 15921.5703125)
('2026-02-23', 70.87, 210338.28060317386, 15993.7099609375)
('2026-02-23', 71.71, 207894.42363255343, None)
('2026-02-23', 71.19, 206903.99097231845, 15854.759765625)
('2026-02-23', 70.57, 207191.0496905718, 15775.1396484375)
('2026-02-23', 70.89, 208396.95938860573, 15845.23046875)
('2026-02-23', 72.34, 213866.80820581852, None)
('2026-02-23', 70.93, 213247.902753943, 15491.66015625)
('2026-02-23', 68.69, 206191.53795072352, 15782.830078125)
('2026-02-11', 71.1, 220583.0677146267, 15537.6904296875)
('2026-02-23', 72.82, 221209.20718607036, 15254.0498046875)
('2026-02-23', 73.89, 214841.71925105614, 15381.3203125)
('2026-02-23', 75.49, 215995.5389160479, 15085.4697265625)
('2026-02-23', 76.01, 219842.28509645213, 15225.150390625)
('2026-02-23', 76.58, 218478.50703220506, 15686.919921875)
('2026-02-23', 76.83, 224192.01293457407, 15786.990234375)
('2026-02-23', 75.33, 237634.3285912139, 15517.3701171875)
('2026-02-23', 75.99, 252785.18261104374, 15630.599609375)
('2026-02-23', 77.0, 253963.71411998925, 15413.2802734375)
('2026-02-23', 77.83, 252599.85968309751, 15237.6396484375)
('2026-02-23', 79.47, 255256.0749124428, 15565.580078125)
('2026-02-23', 79.0, 258953.02296009834, 15180.4296875)
('2026-02-23', 78.11, 269423.17285168904, 15169.6796875)
('2026-02-23', 81.17, 289273.06195820443, 14980.9404296875)
('2026-02-23', 82.51, 299604.7001320289, 15341.08984375)
('2026-02-23', 81.97, 305580.9799247014, 15521.8896484375)
('2026-02-23', 83.82, 309629.88231970003, 15653.3701171875)
('2026-02-23', 85.42, 323799.5635112756, None)
('2026-02-23', 86.84, 324888.02667051577, 15871.259765625)
('2026-02-23', 86.29, 323522.2855073287, 15781.7197265625)
('2026-02-23', 85.16, 313632.80993368995, 15766.2197265625)
('2026-02-23', 84.48, 320521.28663827025, 15741.5595703125)
('2026-02-23', 86.61, 322067.53188592376, 15644.9697265625)
('2026-02-23', 88.33, 323729.6744159729, 15832.7998046875)
('2026-02-23', 87.61, 334271.3356334813, 15622.7197265625)
('2026-02-23', 87.67, 328567.3072022601, 15100.169921875)
('2026-02-23', 89.16, 329848.44489638496, 15080.8603515625)
('2026-02-23', 88.22, 333798.49786685634, 14935.900390625)
('2026-02-23', 88.16, 323419.73918441863, 14942.830078125)
('2026-02-23', 90.17, 303617.9116663577, 15153.4501953125)
('2026-02-23', 92.27, 296151.6805356246, 15188.3896484375)
('2026-02-23', 91.25, 305147.6597239278, 14806.8095703125)
('2026-02-23', 89.32, 326586.85608261486, 14893.75)
('2026-02-23', 89.57, 316895.55183794844, None)
('2026-02-23', 89.83, 323322.0010279766, 14506.900390625)
('2026-02-23', 93.1, 341975.0422938313, 14340.259765625)
('2026-02-23', 95.52, 352049.4403810017, 14154.01953125)
('2026-02-23', 92.07, 374193.3376648639, 13768.919921875)
('2026-02-23', 93.83, 372140.5970629246, 13855.1298828125)
('2026-02-23', 91.78, 370718.8174494866, 13539.2900390625)
('2026-02-23', 91.26, 403547.06190802733, None)
('2026-02-23', 92.11, 416582.6051270567, 13352.7802734375)
('2026-02-23', 92.14, 399375.2127189976, 13770.5703125)
('2026-02-23', 92.77, 387732.95356370165, 14239.8798828125)
('2026-02-23', 91.68, 387408.6664674909, 14346.0)
('2026-02-23', 96.13, 392681.4189909559, 14417.5498046875)
('2026-02-23', 103.66, 376878.0982824829, 13878.8203125)
('2026-02-23', 110.74, 354772.70430919825, 14098.009765625)
('2026-02-23', 107.69, 376832.66666282027, 14015.669921875)
('2026-02-23', 115.77, 368766.6639472321, 14194.4501953125)
('2026-02-23', 119.26, 421737.4738716338, 14490.3701171875)
('2026-02-23', 123.64, 416904.49092835333, 14185.6396484375)
('2026-02-23', 108.81, 417273.9071184703, 13791.150390625)
('2026-02-23', 105.93, 383869.2304155191, 13790.919921875)
('2026-02-23', 109.31, 403346.84673449927, 14139.759765625)
('2026-02-23', 103.22, 394479.82107990474, 14124.08984375)
('2026-02-23', 96.42, 394824.62858350464, 13716.7197265625)
('2026-02-23', 94.85, 384794.36172029114, 13548.0703125)
('2026-02-23', 102.97, 385618.86285304534, None)
('2026-02-23', 104.69, 386992.0744205619, 13381.51953125)
('2026-02-23', 112.14, 378688.487081064, 13037.490234375)
('2026-02-23', 111.03, 380669.0608269572, 13473.58984375)
('2026-02-23', 114.89, 391914.25736500154, 13694.6201171875)
('2026-02-23', 114.2, 379062.50711160863, 13751.400390625)
('2026-02-23', 116.2, 379789.69451721257, None)
('2026-02-23', 107.55, 376830.61714539555, 13752.01953125)
('2026-02-23', 104.25, 379557.7315665512, 13537.9404296875)
('2026-02-23', 107.81, 379169.3803941581, 13313.4404296875)
('2026-02-23', 100.53, 380163.9598970403, 12830.9599609375)
('2026-02-23', 99.32, 382811.6356012148, 12795.5498046875)
('2026-02-23', 103.29, 393614.0739117057, 13255.5498046875)
('2026-02-23', 101.98, 415686.0060768963, 13129.9599609375)
('2026-02-23', 96.39, 412052.856085073, 12843.8095703125)
('2026-02-23', 96.05, 406940.596240047, 12581.2197265625)
('2026-02-23', 98.35, 398693.42995223537, 12948.6201171875)
('2026-02-23', 94.22, 395856.797622927, 13436.5498046875)
('2026-02-23', 100.52, 403666.7568900215, 13614.7802734375)
('2026-02-23', 104.26, 404926.98327490315, None)
('2026-02-23', 106.84, 393846.3358485685, 13838.4599609375)
('2026-02-23', 108.24, 394843.6203459821, 14108.8203125)
('2026-02-23', 102.54, 392295.47524281475, 13922.599609375)
('2026-02-23', 102.56, 370875.27142150694, 14191.83984375)
('2026-02-23', 103.89, 369992.0919011612, 14169.2998046875)
('2026-02-23', 102.86, 368312.96560615575, 14354.900390625)
('2026-02-23', 99.6, 342937.4440185811, 14619.6396484375)
('2026-02-23', 102.62, 357978.55612770614, 14442.26953125)
('2026-02-23', 101.96, 356321.1005771281, 14220.51953125)
('2026-02-23', 105.47, 367286.12298418215, 14261.5)
('2026-02-23', 104.59, 373944.85329388455, 14532.5498046875)
('2026-02-23', 105.18, 368177.3713848715, 14204.169921875)
('2026-02-23', 102.53, 385235.77973544877, 13888.8203125)
('2026-02-23', 107.84, 397823.05193989933, 13897.2998046875)
('2026-02-23', 108.17, 400707.46142882656, 13711.0)
('2026-02-23', 109.72, 398218.8935895547, 13411.9599609375)
('2026-02-23', 103.08, 400668.6421398132, 13371.5703125)
('2026-02-23', 99.74, 416041.06085392536, 13643.58984375)
('2026-02-22', 105.5, 395289.8026309068, None)
('2026-02-23', 106.15, 401911.0484708849, 13332.3603515625)
('2026-02-23', 110.52, 388222.87205311254, 13619.66015625)
('2026-02-23', 114.07, 340432.9353676543, 13453.0703125)
('2026-02-23', 112.31, 332747.98798714374, 13174.650390625)
('2026-02-23', 109.67, 369207.3362657844, 12839.2900390625)
('2026-02-23', 112.21, 376492.3574048653, 13004.849609375)
('2026-02-23', 112.63, 366574.05838423775, 12490.740234375)
('2026-02-23', 110.32, 349761.3884710538, 12488.9296875)
('2026-02-23', 112.55, 342302.33220614656, 12871.5302734375)
('2026-02-23', 112.88, 337247.7588866496, 12334.6396484375)
('2026-02-23', 116.19, 342375.6803081046, 12536.01953125)
('2026-02-23', 114.96, 350696.6804336402, None)
('2026-02-23', 114.38, 349657.073530753, 12964.8603515625)
('2026-02-23', 115.26, 341303.9842640361, 12317.6904296875)
('2026-02-23', 116.88, 333571.21535914514, 12144.66015625)
('2026-02-23', 118.97, 338462.9290819708, 11623.25)
('2026-02-23', 118.41, 345416.6546043208, 11737.669921875)
('2026-02-23', 119.55, 347083.5922685809, 11364.240234375)
('2026-02-23', 121.94, 365539.5621120337, 11370.9599609375)
('2026-02-23', 121.52, 363758.94232227415, 11805.0)
('2026-02-23', 120.73, 351342.5325721324, 11662.7900390625)
('2026-02-23', 120.92, 344315.5289450759, 11984.51953125)
('2026-02-23', 118.92, 337015.4990615576, 11418.150390625)
('2026-02-19', 115.32, 341801.10296794504, 11388.5)
('2026-02-23', 117.56, 343730.3913686987, 11354.6201171875)
('2026-02-23', 109.56, 347169.85800323385, 11535.26953125)
('2026-02-23', 110.49, 319468.25832003524, 11264.4501953125)
('2026-02-23', 106.22, 292527.2014230804, 11434.740234375)
('2026-02-23', 105.75, 303546.1807953054, 11740.650390625)
('2026-02-23', 109.07, 293412.52766766545, 12131.1298828125)
('2026-02-23', 111.44, 304507.99491275364, None)
('2026-02-23', 113.66, 301591.6290594234, 12081.3896484375)
('2026-02-23', 111.65, 317071.7291616941, 11994.4599609375)
('2026-02-23', 107.76, 316207.1597353334, 12316.900390625)
('2026-02-23', 110.3, 302271.19106009, 12012.73046875)
('2026-02-23', 101.55, 302072.2252489844, 12061.3701171875)
('2026-02-23', 100.31, 287385.51825001417, 12175.23046875)
('2026-02-23', 104.62, 275511.26516527805, 12086.26953125)
('2026-02-23', 106.78, 281155.6844835739, 11754.23046875)
('2026-02-23', 106.09, 275080.20597856207, 11340.01953125)
('2026-02-23', 97.69, 267796.5731112152, 10809.23046875)
('2026-02-23', 98.44, 276052.04898099863, 10828.349609375)
('2026-02-23', 97.79, 267032.830083096, 11099.150390625)
('2026-02-23', 99.59, 251183.08126814634, 10646.099609375)
('2026-02-23', 104.48, 247777.39778764817, 10798.349609375)
('2026-02-23', 106.12, 248183.09115512334, None)
('2026-02-23', 104.45, 250950.12836319354, 11069.2998046875)
('2026-02-23', 98.44, 263283.40358322934, 11053.080078125)
('2026-02-23', 97.71, 263444.9399900479, 11232.1904296875)
('2026-02-23', 99.83, 269938.1970950932, 11607.6201171875)
('2026-02-23', 97.74, 269490.2527975858, 11524.5498046875)
('2026-02-23', 100.03, 271004.1486761167, 11181.5400390625)
('2026-02-20', 99.11, 267260.2384447111, 11177.8896484375)
('2026-02-23', 101.31, 267424.4592587914, 11028.740234375)
('2026-02-23', 96.59, 250829.94408877468, 11127.849609375)
('2026-02-23', 97.14, 269370.30418167287, None)
('2026-02-23', 93.25, 288132.42535713845, 11322.240234375)
('2026-02-23', 91.29, 281520.95159888716, 11361.849609375)
('2026-02-23', 91.77, 271893.52182715805, 11621.349609375)
('2026-02-23', 93.52, 273416.13820120675, 11635.3095703125)
('2026-02-23', 93.18, 274616.2375638853, 11372.599609375)
('2026-02-23', 94.68, 281685.69218486216, 11264.73046875)
('2026-02-23', 97.02, 298746.9630305986, 11247.580078125)
('2026-02-23', 94.86, 298675.7147486205, 11251.1904296875)
('2026-02-23', 92.24, 292065.55714175856, 11452.419921875)
('2026-02-23', 89.23, 279306.9974351619, 11360.0498046875)
('2026-02-23', 90.85, 282191.1596649078, 11713.150390625)
('2026-02-23', 93.2, 277686.2575249929, 11897.650390625)
('2026-02-23', 93.55, 269107.8224748998, 12059.6103515625)
('2026-02-23', 93.42, 269596.8374095658, 11834.1103515625)
('2026-02-23', 96.46, 255672.94816147196, 11782.669921875)
('2026-02-23', 95.52, 255132.82641488407, 11562.5703125)
('2026-02-23', 93.33, 266653.5750632806, 12032.419921875)
('2026-02-23', 93.63, 266686.3060581252, 12162.58984375)
('2026-02-23', 97.4, 268857.45721078233, 12390.6904296875)
('2026-02-23', 92.08, 269330.66898642445, 12368.98046875)
('2026-02-23', 90.09, 265308.33057719615, 12348.759765625)
('2026-02-23', 87.09, 264638.4624631536, 12668.16015625)
('2026-02-23', 87.29, 261698.83888170918, 12720.580078125)
('2026-02-23', 87.35, 262776.73658441985, 12657.5498046875)
('2026-02-23', 82.5, 264850.5744899021, 12644.4599609375)
('2026-02-23', 84.04, 264760.5504658988, None)
('2026-02-23', 87.27, 263786.42273046816, 12854.7998046875)
('2026-02-23', 88.18, 266620.8671552428, 12779.91015625)
('2026-02-23', 87.84, 266951.6312463789, 13047.1904296875)
('2026-02-23', 88.88, 269940.3569195695, None)
('2026-02-23', 85.72, 281016.1719855551, 13102.5498046875)
('2026-02-23', 85.57, 281388.8695194364, 12938.1201171875)
('2026-02-23', 86.15, 282560.6030133936, 12965.33984375)
('2026-02-23', 84.69, 291299.3568651643, 12705.2197265625)
('2026-02-23', 83.38, 297045.36579862604, 12381.5703125)
('2026-02-23', 84.02, 284403.12191626645, 12381.2998046875)
('2026-02-23', 79.07, 279086.945835317, 12431.5302734375)
('2026-02-23', 77.17, 278309.6101406161, 12639.26953125)
('2026-02-23', 78.91, 278294.1933407241, 12141.7099609375)
('2026-02-23', 82.61, 281519.50124331604, 12017.669921875)
('2026-02-23', 81.78, 278535.9889192714, 11883.1396484375)
('2026-02-23', 79.91, 299728.9177688779, None)
('2026-02-23', 84.05, 302917.5844429012, 11785.1298828125)
('2026-02-23', 86.87, 299838.3615803796, 11630.8603515625)
('2026-02-23', 88.22, 299041.3190188698, None)
('2026-02-23', 88.9, 300496.6677650833, 11544.91015625)
('2026-02-23', 93.07, 297943.7602436932, 11791.900390625)
('2026-02-23', 91.6, 289592.03165583033, 11862.1298828125)
('2026-02-23', 89.75, 267489.81096221146, 12112.3095703125)
('2026-02-23', 87.83, 272419.05713641306, 12266.41015625)
('2026-02-23', 89.59, 269940.0485702116, 11633.5703125)
('2026-02-23', 86.1, 270322.79786255566, 11719.6796875)
('2026-02-23', 86.0, 270125.836049164, 11552.3603515625)
('2026-02-23', 83.29, 257898.21011062048, 11448.400390625)
('2026-02-23', 86.0, 268521.1124032741, 11535.01953125)
('2026-02-23', 86.02, 276537.237355733, 11425.0498046875)
('2026-02-23', 85.47, 276752.68161058764, 11220.1904296875)
('2026-02-23', 86.12, 258717.1664228855, 11066.8095703125)
('2026-02-23', 86.93, 247763.65614624374, 10867.9296875)
('2026-02-23', 89.39, 224065.64499097393, 10802.919921875)
('2026-02-23', 89.06, 208098.68569226892, 10829.5)
('2026-02-23', 87.85, 212055.7416695305, 11051.6396484375)

In [96]:
cursor.execute("""
SELECT
    date,
    Price,
    LAG(Price) OVER (ORDER BY date) AS prev_price,
    (Price - LAG(Price) OVER (ORDER BY date)) * 100.0
        / LAG(Price) OVER (ORDER BY date) AS pct_change
FROM merged_data
""")

rows = cursor.fetchall()#Find days when oil price spiked and compare with Bitcoin price change.

for r in rows:
    print(r)

(None, 71.73, None, None)
(None, 72.44, 71.73, 0.9898229471629635)
(None, 73.79, 72.44, 1.8636112644947662)
(None, 74.64, 73.79, 1.1519176040113759)
(None, 74.31, 74.64, -0.44212218649517454)
(None, 74.99, 74.31, 0.9150854528327178)
(None, 73.99, 74.99, -1.3335111348179758)
(None, 77.27, 73.99, 4.433031490741994)
(None, 79.57, 77.27, 2.97657564384625)
(None, 78.2, 79.57, -1.721754430061569)
(None, 80.73, 78.2, 3.23529411764706)
(None, 79.35, 80.73, -1.7094017094017213)
(None, 78.56, 79.35, -0.9955891619407587)
(None, 76.79, 78.56, -2.2530549898166954)
(None, 76.12, 76.79, -0.8725094413335092)
(None, 75.03, 76.12, -1.431949553336841)
(None, 74.97, 75.03, -0.07996801279488508)
(None, 73.51, 74.97, -1.9474456449246282)
(None, 74.15, 73.51, 0.8706298462794185)
(None, 72.94, 74.15, -1.6318273769386484)
(None, 73.1, 72.94, 0.2193583767480074)
(None, 72.84, 73.1, -0.3556771545827509)
(None, 73.52, 72.84, 0.9335529928610552)
(None, 73.04, 73.52, -0.6528835690968305)
(None, 71.39, 73.04, -2.259036144578321)
(None, 70.97, 71.39, -0.5883176915534413)
(None, 71.32, 70.97, 0.4931661265323296)
(None, 72.73, 71.32, 1.9770050476724774)
(None, 73.67, 72.73, 1.2924515330675068)
(None, 71.72, 73.67, -2.6469390525315633)
(None, 71.66, 71.72, -0.083658672615731)
(None, 71.05, 71.66, -0.8512419759977665)
(None, 72.21, 71.05, 1.6326530612244852)
(None, 72.58, 72.21, 0.5123944052070414)
(None, 72.88, 72.58, 0.41333700744006224)
(None, 70.72, 72.88, -2.9637760702524654)
(None, 71.06, 70.72, 0.4807692307692356)
(None, 69.15, 71.06, -2.687869406135655)
(None, 68.87, 69.15, -0.404916847433118)
(None, 70.62, 68.87, 2.541019311746769)
(None, 69.97, 70.62, -0.9204191447182182)
(None, 68.63, 69.97, -1.9151064742032349)
(None, 68.47, 68.63, -0.2331341978726455)
(None, 66.58, 68.47, -2.7603329925514832)
(None, 66.62, 66.58, 0.06007810153200098)
(None, 67.29, 66.62, 1.005703992794959)
(None, 66.31, 67.29, -1.456382820627142)
(None, 66.52, 66.31, 0.31669431458300973)
(None, 67.65, 66.52, 1.6987372218881687)
(None, 66.82, 67.65, -1.2269031781227087)
(None, 67.43, 66.82, 0.9129003292427622)
(None, 67.84, 67.43, 0.6080379652973402)
(None, 67.49, 67.84, -0.5159198113207673)
(None, 67.4, 67.49, -0.13335308934655388)
(None, 68.55, 67.4, 1.706231454005922)
(None, 68.52, 68.55, -0.043763676148798156)
(None, 69.46, 68.52, 1.3718622300058345)
(None, 69.48, 69.46, 0.02879355024475991)
(None, 70.05, 69.48, 0.8203799654576758)
(None, 70.3, 70.05, 0.35688793718772305)
(None, 69.74, 70.3, -0.7965860597439578)
(None, 71.87, 69.74, 3.0542013191855606)
(None, 71.61, 71.87, -0.3617642966467303)
(None, 72.12, 71.61, 0.7121910347716871)
(None, 67.43, 72.12, -6.503050471436491)
(None, 62.42, 67.43, -7.429927332048057)
(None, 61.05, 62.42, -2.194809355975656)
(None, 60.04, 61.05, -1.6543816543816512)
(None, 62.63, 60.04, 4.313790806129253)
(None, 60.57, 62.63, -3.2891585502155554)
(None, 61.91, 60.57, 2.212316328215282)
(None, 61.99, 61.91, 0.1292198352447188)
(None, 61.74, 61.99, -0.4032908533634457)
(None, 62.88, 61.74, 1.846452866861031)
(None, 65.07, 62.88, 3.482824427480901)
(None, 63.48, 65.07, -2.443522360534803)
(None, 64.6, 63.48, 1.7643352236924976)
(None, 62.64, 64.6, -3.03405572755417)
(None, 63.55, 62.64, 1.452745849297568)
(None, 63.85, 63.55, 0.4720692368214072)
(None, 63.3, 63.85, -0.8613938919342274)
(None, 61.84, 63.3, -2.3064770932069414)
(None, 59.55, 61.84, -3.703104786545935)
(None, 60.59, 59.55, 1.7464315701091626)
(None, 59.67, 60.59, -1.5184023766298096)
(None, 58.5, 59.67, -1.960784313725493)
(None, 60.42, 58.5, 3.282051282051285)
(None, 59.42, 60.42, -1.6550810989738496)
(None, 61.25, 59.42, 3.079771120834733)
(None, 62.37, 61.25, 1.8285714285714243)
(None, 63.32, 62.37, 1.523168189834861)
(None, 65.04, 63.32, 2.7163613392293207)
(None, 64.48, 65.04, -0.8610086100861043)
(None, 63.03, 64.48, -2.2487593052109225)
(None, 63.84, 63.03, 1.2851023322227546)
(None, 63.98, 63.84, 0.21929824561402483)
(None, 63.97, 63.98, -0.015629884338852783)
(None, 62.93, 63.97, -1.625762075973111)
(None, 62.55, 62.93, -0.6038455426664588)
(None, 62.89, 62.55, 0.5435651478817001)
(None, 61.61, 62.89, -2.0352997296867565)
(None, 62.54, 61.61, 1.5094952118162632)
(None, 61.66, 62.54, -1.4070994563479415)
(None, 61.46, 61.66, -0.3243593902043395)
(None, 63.27, 61.46, 2.945004881223564)
(None, 64.1, 63.27, 1.3118381539434032)
(None, 63.57, 64.1, -0.8268330733229237)
(None, 64.06, 63.57, 0.770803838288504)
(None, 65.3, 64.06, 1.9356852950358958)
(None, 65.99, 65.3, 1.0566615620214361)
(None, 65.66, 65.99, -0.500075769055915)
(None, 68.91, 65.66, 4.949741090466038)
(None, 68.73, 68.91, -0.26121027427077725)
(None, 73.84, 68.73, 7.4348901498617765)
(None, 72.53, 73.84, -1.7741061755146292)
(None, 75.62, 72.53, 4.260306080242663)
(None, 75.89, 75.62, 0.3570483998942026)
(None, 75.72, 75.89, -0.2240084332586661)
(None, 69.36, 75.72, -8.399366085578446)
(None, 65.45, 69.36, -5.637254901960779)
(None, 65.98, 65.45, 0.8097784568372821)
(None, 66.44, 65.98, 0.6971809639284536)
(None, 66.66, 66.44, 0.33112582781456784)
(None, 66.3, 66.66, -0.5400540054005393)
(None, 66.64, 66.3, 0.512820512820518)
(None, 68.66, 66.64, 3.0312124849939917)
(None, 68.13, 68.66, -0.7719196038450352)
(None, 69.16, 68.13, 1.5118156465580526)
(None, 69.55, 69.16, 0.563909774436091)
(None, 69.61, 69.55, 0.08626887131560355)
(None, 67.78, 69.61, -2.628932624622897)
(None, 69.63, 67.78, 2.7294187075833496)
(None, 68.19, 69.63, -2.068074105988795)
(None, 67.76, 68.19, -0.6305909957471661)
(None, 67.13, 67.76, -0.9297520661157167)
(None, 68.76, 67.13, 2.4281245344853417)
(None, 68.53, 68.76, -0.3344968004653926)
(None, 68.39, 68.53, -0.2042900919305422)
(None, 67.56, 68.39, -1.2136277233513646)
(None, 66.05, 67.56, -2.235050325636479)
(None, 67.16, 66.05, 1.6805450416351242)
(None, 66.38, 67.16, -1.1614055985705796)
(None, 67.81, 66.38, 2.154263332329025)
(None, 70.27, 67.81, 3.6277835127562215)
(None, 71.09, 70.27, 1.1669275651060302)
(None, 70.36, 71.09, -1.0268673512449065)
(None, 68.39, 70.36, -2.79988629903354)
(None, 67.33, 68.39, -1.5499342009065686)
(None, 66.2, 67.33, -1.6783009059854381)
(None, 65.38, 66.2, -1.2386706948640593)
(None, 64.9, 65.38, -0.7341694707861576)
(None, 64.94, 64.9, 0.061633281972252756)
(None, 65.03, 64.94, 0.13858946720049803)
(None, 64.22, 65.03, -1.2455789635552856)
(None, 63.68, 64.22, -0.8408595453129853)
(None, 64.99, 63.68, 2.057160804020093)
(None, 63.78, 64.99, -1.8618248961378578)
(None, 64.51, 63.78, 1.1445594230166258)
(None, 63.38, 64.51, -1.7516664083087932)
(None, 64.19, 63.38, 1.2780056800252368)
(None, 64.56, 64.19, 0.5764137716155235)
(None, 64.08, 64.56, -0.7434944237918277)
(None, 65.18, 64.08, 1.7166042446941456)
(None, 63.6, 65.18, -2.4240564590365223)
(None, 64.49, 63.6, 1.3993710691823795)
(None, 64.96, 64.49, 0.7287951620406248)
(None, 64.36, 64.96, -0.9236453201970357)
(None, 65.95, 64.36, 2.470478558110633)
(None, 64.36, 65.95, -2.410917361637609)
(None, 63.81, 64.36, -0.8545680546923511)
(None, 62.22, 63.81, -2.491772449459338)
(None, 62.6, 62.22, 0.6107360977177797)
(None, 62.97, 62.6, 0.5910543130990374)
(None, 64.01, 62.97, 1.6515801175162876)
(None, 62.71, 64.01, -2.0309326667708234)
(None, 63.02, 62.71, 0.49433902088981385)
(None, 63.66, 63.02, 1.0155506188511478)
(None, 64.89, 63.66, 1.932139491046189)
(None, 64.41, 64.89, -0.7397133610725904)
(None, 63.91, 64.41, -0.776276975624903)
(None, 63.02, 63.91, -1.3925833202941535)
(None, 62.99, 63.02, -0.04760393525864985)
(None, 63.76, 62.99, 1.2224162565486523)
(None, 65.4, 63.76, 2.57214554579675)
(None, 65.51, 65.4, 0.16819571865443336)
(None, 66.5, 65.51, 1.5112196611204316)
(None, 64.27, 66.5, -3.3533834586466225)
(None, 63.17, 64.27, -1.7115294849852098)
(None, 62.59, 63.17, -0.9181573531739723)
(None, 61.28, 62.59, -2.0929861000159806)
(None, 61.65, 61.28, 0.6037859007832856)
(None, 62.49, 61.65, 1.3625304136253098)
(None, 62.52, 62.49, 0.048007681228998456)
(None, 63.37, 62.52, 1.3595649392194407)
(None, 62.36, 63.37, -1.5938141076219001)
(None, 59.75, 62.36, -4.185375240538806)
(None, 59.52, 59.75, -0.38493723849371864)
(None, 59.08, 59.52, -0.7392473118279651)
(None, 58.29, 59.08, -1.3371699390656722)
(None, 58.3, 58.29, 0.017155601303822286)
(None, 58.34, 58.3, 0.06861063464838123)
(None, 58.66, 58.34, 0.5485087418580616)
(None, 59.3, 58.66, 1.091033071939994)
(None, 62.44, 59.3, 5.295109612141654)
(None, 62.27, 62.44, -0.2722613709160708)
(None, 62.13, 62.27, -0.22482736470210465)
(None, 60.97, 62.13, -1.867052953484635)
(None, 61.26, 60.97, 0.4756437592258474)
(None, 61.36, 61.26, 0.16323865491348583)
(None, 61.75, 61.36, 0.635593220338984)
(None, 61.79, 61.75, 0.06477732793522128)
(None, 61.38, 61.79, -0.6635377892862868)
(None, 60.4, 61.38, -1.5966112740306353)
(None, 60.24, 60.4, -0.26490066225165)
(None, 60.54, 60.24, 0.4980079681274853)
(None, 60.94, 60.54, 0.6607201850016494)
(None, 59.3, 60.94, -2.6911716442402374)
(None, 59.54, 59.3, 0.40472175379426983)
(None, 60.87, 59.54, 2.2337924084648946)
(None, 60.66, 60.87, -0.34499753573188907)
(None, 61.51, 60.66, 1.4012528849324126)
(None, 60.27, 61.51, -2.015932368720525)
(None, 60.07, 60.27, -0.33184005309441317)
(None, 58.86, 60.07, -2.0143166305976377)
(None, 59.11, 58.86, 0.42473666326877335)
(None, 58.25, 59.11, -1.454914566063271)
(None, 58.81, 58.25, 0.9613733905579438)
(None, 58.58, 58.81, -0.39108995068866514)
(None, 59.47, 58.58, 1.5192898600204858)
(None, 58.81, 59.47, -1.109803262148977)
(None, 59.09, 58.81, 0.4761095051861947)
(None, 59.82, 59.09, 1.235403621594173)
(None, 60.23, 59.82, 0.6853895018388442)
(None, 59.04, 60.23, -1.975759588245057)
(None, 58.4, 59.04, -1.084010840108402)
(None, 58.67, 58.4, 0.462328767123293)
(None, 57.76, 58.67, -1.551048235895694)
(None, 57.61, 57.76, -0.25969529085872334)
(None, 56.97, 57.61, -1.1109182433605287)
(None, 55.44, 56.97, -2.685624012638233)
(None, 56.07, 55.44, 1.1363636363636411)
(None, 56.22, 56.07, 0.26752273943284927)
(None, 56.8, 56.22, 1.031661330487368)
(None, 58.18, 56.8, 2.429577464788737)
(None, 58.55, 58.18, 0.6359573736679227)
(None, 58.72, 58.55, 0.2903501280956477)
(None, 56.6, 58.72, -3.610354223433238)
(None, 57.89, 56.6, 2.279151943462896)
(None, 57.79, 57.89, -0.17274140611504823)
(None, 57.26, 57.79, -0.917113687489187)
(None, 57.21, 57.26, -0.08732099196646378)
(None, 58.1, 57.21, 1.5556720852997736)
(None, 56.97, 58.1, -1.9449225473321903)
(None, 56.01, 56.97, -1.6850974196945776)
(None, 57.74, 56.01, 3.0887341546152545)
(None, 58.96, 57.74, 2.112919986144785)
(None, 59.39, 58.96, 0.7293080054274079)
(None, 60.85, 59.39, 2.4583263175618804)
(None, 61.84, 60.85, 1.6269515201314741)
(None, 59.13, 61.84, -4.382276843467014)
(None, 59.4, 59.13, 0.4566210045662033)
(None, 60.3, 59.4, 1.5151515151515127)
(None, 60.38, 60.3, 0.13266998341626104)
(None, 59.24, 60.38, -1.888042398145082)
(None, 60.7, 59.24, 2.4645509790681985)
(None, 60.46, 60.7, -0.3953871499176309)
(None, 62.04, 60.46, 2.6132980482963917)
(None, 62.75, 62.04, 1.1444229529335925)
(None, 64.77, 62.75, 3.219123505976089)
(None, 64.5, 64.77, -0.41685965724872015)
(None, None, 64.5, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
('2026-01-01', 83.63, None, None)
('2026-01-20', 83.39, 83.63, -0.2869783570488998)
('2026-01-27', 75.6, 83.39, -9.341647679577894)
('2026-02-01', 88.14, 75.6, 16.587301587301596)
('2026-02-01', 80.43, 88.14, -8.747447243022457)
('2026-02-04', 76.34, 80.43, -5.085167226159397)
('2026-02-09', 72.69, 76.34, -4.781241812942108)
('2026-02-10', 31.56, 72.69, -56.58274865868758)
('2026-02-10', 73.85, 31.56, 133.99873257287703)
('2026-02-11', 71.1, 73.85, -3.7237643872714967)
('2026-02-13', 70.34, 71.1, -1.0689170182840941)
('2026-02-13', 75.54, 70.34, 7.3926642024452685)
('2026-02-13', 84.17, 75.54, 11.424410908128136)
('2026-02-17', 70.31, 84.17, -16.466674587145064)
('2026-02-18', 78.47, 70.31, 11.605745982079357)
('2026-02-19', 115.32, 78.47, 46.96062189371734)
('2026-02-19', 79.78, 115.32, -30.818591744710364)
('2026-02-19', 80.71, 79.78, 1.1657056906492762)
('2026-02-20', 82.39, 80.71, 2.081526452732012)
('2026-02-20', 99.11, 82.39, 20.29372496662216)
('2026-02-20', 70.74, 99.11, -28.624760367268696)
('2026-02-21', 73.7, 70.74, 4.184337008764501)
('2026-02-22', 57.86, 73.7, -21.49253731343284)
('2026-02-22', 105.5, 57.86, 82.336674732112)
('2026-02-22', 72.15, 105.5, -31.611374407582932)
('2026-02-22', 84.26, 72.15, 16.784476784476784)
('2026-02-22', 79.61, 84.26, -5.51863280322811)
('2026-02-22', 72.72, 79.61, -8.654691621655571)
('2026-02-23', 61.17, 72.72, -15.88283828382838)
('2026-02-23', 63.0, 61.17, 2.9916625796959266)
('2026-02-23', 63.27, 63.0, 0.42857142857143354)
('2026-02-23', 62.7, 63.27, -0.9009009009009014)
('2026-02-23', 59.65, 62.7, -4.86443381180224)
('2026-02-23', 59.56, 59.65, -0.15088013411566858)
('2026-02-23', 59.02, 59.56, -0.9066487575554049)
('2026-02-23', 58.17, 59.02, -1.440189766180958)
('2026-02-23', 58.34, 58.17, 0.2922468626439775)
('2026-02-23', 58.52, 58.34, 0.30853616729516575)
('2026-02-23', 58.55, 58.52, 0.05126452494872527)
('2026-02-23', 58.25, 58.55, -0.5123825789923094)
('2026-02-23', 56.76, 58.25, -2.5579399141630934)
('2026-02-23', 55.51, 56.76, -2.2022551092318534)
('2026-02-23', 54.09, 55.51, -2.5580976400648434)
('2026-02-23', 53.09, 54.09, -1.848770567572564)
('2026-02-23', 53.33, 53.09, 0.4520625353173759)
('2026-02-23', 53.29, 53.33, -0.07500468779298547)
('2026-02-23', 52.19, 53.29, -2.064177143929445)
('2026-02-23', 51.58, 52.19, -1.1688062847288743)
('2026-02-23', 50.06, 51.58, -2.9468786351298877)
('2026-02-23', 49.59, 50.06, -0.9388733519776246)
('2026-02-23', 50.87, 49.59, 2.581165557572079)
('2026-02-23', 50.94, 50.87, 0.1376056614900733)
('2026-02-23', 50.34, 50.94, -1.177856301531202)
('2026-02-23', 49.59, 50.34, -1.4898688915375446)
('2026-02-23', 50.0, 49.59, 0.8267795926598035)
('2026-02-23', 51.13, 50.0, 2.260000000000005)
('2026-02-23', 51.41, 51.13, 0.547623704283188)
('2026-02-23', 52.03, 51.41, 1.2059910523244595)
('2026-02-23', 52.1, 52.03, 0.13453776667307377)
('2026-02-23', 53.31, 52.1, 2.322456813819579)
('2026-02-23', 53.77, 53.31, 0.8628775089101498)
('2026-02-23', 53.36, 53.77, -0.7625069741491606)
('2026-02-23', 51.36, 53.36, -3.7481259370314843)
('2026-02-23', 49.78, 51.36, -3.0763239875389377)
('2026-02-23', 48.67, 49.78, -2.2298111691442335)
('2026-02-23', 47.17, 48.67, -3.081980686254366)
('2026-02-23', 44.83, 47.17, -4.9607801568793795)
('2026-02-23', 46.78, 44.83, 4.349765781842523)
('2026-02-23', 47.27, 46.78, 1.0474561778537879)
('2026-02-23', 46.78, 47.27, -1.0365982652845398)
('2026-02-23', 45.9, 46.78, -1.8811457887986374)
('2026-02-23', 41.14, 45.9, -10.370370370370365)
('2026-02-23', 31.05, 41.14, -24.52600875060768)
('2026-02-23', 34.47, 31.05, 11.014492753623182)
('2026-02-23', 33.13, 34.47, -3.8874383521903)
('2026-02-23', 31.72, 33.13, -4.255961364322377)
('2026-02-23', 28.96, 31.72, -8.701134930643121)
('2026-02-23', 26.96, 28.96, -6.906077348066298)
('2026-02-23', 20.48, 26.96, -24.03560830860534)
('2026-02-23', 25.09, 20.48, 22.509765624999996)
('2026-02-23', 19.48, 25.09, -22.359505779194897)
('2026-02-23', 23.33, 19.48, 19.763860369609844)
('2026-02-23', 21.03, 23.33, -9.858551221603074)
('2026-02-23', 20.75, 21.03, -1.3314312886352884)
('2026-02-23', 16.6, 20.75, -19.999999999999993)
('2026-02-23', 15.48, 16.6, -6.746987951807235)
('2026-02-23', 14.1, 15.48, -8.914728682170548)
('2026-02-23', 20.51, 14.1, 45.46099290780143)
('2026-02-23', 20.28, 20.51, -1.12140419307655)
('2026-02-23', 25.18, 20.28, 24.16173570019723)
('2026-02-23', 28.36, 25.18, 12.629070691024623)
('2026-02-23', 26.21, 28.36, -7.581100141043719)
('2026-02-23', 23.54, 26.21, -10.186951545211757)
('2026-02-23', 24.97, 23.54, 6.074766355140186)
('2026-02-23', 22.9, 24.97, -8.289947937525032)
('2026-02-23', 22.36, 22.9, -2.358078602620084)
('2026-02-23', 20.15, 22.36, -9.883720930232561)
('2026-02-23', 19.96, 20.15, -0.942928039702222)
('2026-02-23', 19.82, 19.96, -0.7014028056112253)
('2026-02-23', 18.31, 19.82, -7.618567103935427)
('2026-02-23', -36.98, 18.31, -301.9661387220098)
('2026-02-23', 8.91, -36.98, -124.09410492157924)
('2026-02-23', 13.64, 8.91, 53.086419753086425)
('2026-02-23', 15.06, 13.64, 10.410557184750733)
('2026-02-23', 15.99, 15.06, 6.175298804780875)
('2026-02-23', 12.17, 15.99, -23.889931207004377)
('2026-02-23', 12.4, 12.17, 1.889893179950702)
('2026-02-23', 15.04, 12.4, 21.290322580645153)
('2026-02-23', 19.23, 15.04, 27.8590425531915)
('2026-02-23', 19.72, 19.23, 2.548101924076955)
('2026-02-23', 20.47, 19.72, 3.803245436105477)
('2026-02-23', 24.56, 20.47, 19.98045920859795)
('2026-02-23', 23.88, 24.56, -2.76872964169381)
('2026-02-23', 23.68, 23.88, -0.8375209380234476)
('2026-02-23', 24.73, 23.68, 4.434121621621625)
('2026-02-23', 24.02, 24.73, -2.871006874241815)
('2026-02-23', 25.76, 24.02, 7.243963363863456)
('2026-02-23', 25.37, 25.76, -1.5139751552795053)
('2026-02-23', 27.4, 25.37, 8.00157666535277)
('2026-02-23', 29.44, 27.4, 7.445255474452566)
('2026-02-23', 31.83, 29.44, 8.11820652173912)
('2026-02-23', 32.3, 31.83, 1.4765944077913882)
('2026-02-23', 33.56, 32.3, 3.9009287925696756)
('2026-02-23', 34.3, 33.56, 2.205005959475551)
('2026-02-23', 33.49, 34.3, -2.3615160349854087)
('2026-02-23', 34.7, 33.49, 3.61301881158555)
('2026-02-23', 32.8, 34.7, -5.475504322766587)
('2026-02-23', 33.67, 32.8, 2.652439024390258)
('2026-02-23', 35.57, 33.67, 5.643005643005639)
('2026-02-23', 35.49, 35.57, -0.2249086308687048)
('2026-02-23', 36.88, 35.49, 3.9165962242885333)
('2026-02-23', 37.33, 36.88, 1.2201735357917454)
('2026-02-23', 37.42, 37.33, 0.24109295472810988)
('2026-02-23', 39.49, 37.42, 5.531801175841796)
('2026-02-23', 38.17, 39.49, -3.342618384401115)
('2026-02-23', 38.98, 38.17, 2.1220854073879885)
('2026-02-23', 39.54, 38.98, 1.4366341713699393)
('2026-02-23', 36.43, 39.54, -7.865452706120383)
('2026-02-23', 36.24, 36.43, -0.5215481745813827)
('2026-02-23', 37.07, 36.24, 2.2902869757174344)
('2026-02-23', 38.26, 37.07, 3.2101429727542428)
('2026-02-23', 37.91, 38.26, -0.9147935180345046)
('2026-02-23', 38.79, 37.91, 2.3212872592983453)
('2026-02-23', 39.72, 38.79, 2.3975251353441602)
('2026-02-23', 40.6, 39.72, 2.2155085599194426)
('2026-02-23', 40.4, 40.6, -0.49261083743843065)
('2026-02-23', 37.91, 40.4, -6.163366336633668)
('2026-02-23', 38.66, 37.91, 1.9783698232656293)
('2026-02-23', 38.53, 38.66, -0.33626487325399756)
('2026-02-23', 39.67, 38.53, 2.9587334544510786)
('2026-02-23', 39.27, 39.67, -1.0083186286866614)
('2026-02-23', 39.88, 39.27, 1.55334861217214)
('2026-02-23', 40.57, 39.88, 1.7301905717151396)
('2026-02-23', 40.51, 40.57, -0.14789253142716854)
('2026-02-23', 40.59, 40.51, 0.19748210318441226)
('2026-02-23', 40.91, 40.59, 0.7883715200788203)
('2026-02-23', 39.64, 40.91, -3.104375458323139)
('2026-02-23', 40.56, 39.64, 2.3208879919273504)
('2026-02-23', 40.06, 40.56, -1.2327416173570018)
('2026-02-23', 40.3, 40.06, 0.5991013479780202)
('2026-02-23', 41.2, 40.3, 2.233250620347409)

In [97]:
cursor.execute("""
SELECT
    date,
    coin_id,
    price_inr,
    GSPC_Close AS sp500,
    IXIC_Close AS nasdaq
FROM merged_data
WHERE coin_id IN ('bitcoin', 'ethereum', 'tether')
AND date BETWEEN '2026-01-01' AND '2026-12-31'
ORDER BY date
LIMIT 10
""")

results = cursor.fetchall()
for r in results:
    print(r)#Compare top 3 coins daily price trend vs Nifty (^NSEI).

('2026-01-27', 'tether', 84.72143692477849, 4076.60009765625, 11584.5498046875)
('2026-02-01', 'ethereum', 186695.3649137571, 3790.929931640625, 11176.41015625)
('2026-02-01', 'tether', 87.02531092350665, 4411.58984375, 13679.0400390625)
('2026-02-04', 'tether', 85.45426169674982, 3829.25, 10353.23046875)
('2026-02-10', 'bitcoin', 7333947.924555619, 2746.56005859375, 7950.68017578125)
('2026-02-11', 'ethereum', 220583.0677146267, 4567.0, 15537.6904296875)
('2026-02-13', 'bitcoin', 6092367.347486159, 4195.990234375, 13738.0)
('2026-02-13', 'ethereum', 152837.10606631296, 4514.06982421875, 15286.6396484375)
('2026-02-18', 'tether', 86.04341248201443, 3824.139892578125, 10386.98046875)
('2026-02-19', 'ethereum', 341801.10296794504, 3900.7900390625, 11388.5)

In [98]:
cursor.execute("""
SELECT
    date,

    GSPC_Close AS sp500_close,
    Price AS oil_price
FROM merged_data
WHERE date BETWEEN '2026-01-01' AND '2026-12-31'
LIMIT 10
""")

results = cursor.fetchall()
for r in results:
    print(r) #Compare stock prices (^GSPC) with crude oil prices on the same dates

('2026-02-23', None, 61.17)
('2026-02-23', 3257.85009765625, 63.0)
('2026-02-23', 3234.85009765625, 63.27)
('2026-02-23', 3246.280029296875, 62.7)
('2026-02-23', 3237.179931640625, 59.65)
('2026-02-23', 3253.050048828125, 59.56)
('2026-02-23', 3274.699951171875, 59.02)
('2026-02-23', 3265.35009765625, 58.17)
('2026-02-23', 3288.1298828125, 58.34)
('2026-02-22', 3283.14990234375, 57.86)

In [99]:
cursor.execute("""
SELECT
    date,
    price_inr AS bitcoin_price,
    Price AS oil_price
FROM merged_data
WHERE coin_id = 'bitcoin'
AND price_inr IS NOT NULL
AND Price IS NOT NULL
""")


results = cursor.fetchall()
for r in results:
    print(r) #Correlate Bitcoin closing price with crude oil closing price (same date)

('2026-02-23', 8341958.303704703, 61.17)
('2026-02-23', 7922797.740624487, 63.0)
('2026-02-23', 7729282.415455005, 63.27)
('2026-02-23', 7314307.147526646, 62.7)
('2026-02-23', 7397416.663356487, 59.65)
('2026-02-23', 7386259.847331922, 59.56)
('2026-02-23', 7523008.862171689, 59.02)
('2026-02-23', 8244472.61232367, 58.17)
('2026-02-23', 7521257.854514662, 58.34)
('2026-02-22', 7615008.334491884, 57.86)
('2026-02-23', 7869430.047939962, 58.52)
('2026-02-23', 7841736.557001183, 58.55)
('2026-02-23', 7562231.150267524, 58.25)
('2026-02-23', 7503958.351863089, 56.76)
('2026-02-23', 7035607.792612969, 55.51)
('2026-02-23', 6882112.04135304, 54.09)
('2026-02-23', 7220111.199834512, 53.09)
('2026-02-23', 7311397.167011021, 53.33)
('2026-02-23', 7049331.751158462, 53.29)
('2026-02-23', 7301205.756783538, 52.19)
('2026-02-23', 7337203.4861049205, 51.58)
('2026-02-23', 7182714.546311197, 50.06)
('2026-02-23', 7307625.213417549, 49.59)
('2026-02-23', 7166130.900539224, 50.87)
('2026-02-23', 7495414.341859128, 50.94)
('2026-02-23', 7275140.94449613, 50.34)
('2026-02-23', 7224000.906005809, 49.59)
('2026-02-23', 7205763.671408613, 50.0)
('2026-02-23', 7377568.408827406, 51.13)
('2026-02-23', 7471026.999919416, 51.41)
('2026-02-23', 7490943.665690553, 52.03)
('2026-02-23', 7448415.462567322, 52.1)
('2026-02-23', 7474953.075439318, 53.31)
('2026-02-23', 7216289.858225705, 53.77)
('2026-02-23', 7072289.607125187, 53.36)
('2026-02-23', 7044678.366106417, 51.36)
('2026-02-23', 7049110.1215911815, 49.78)
('2026-02-23', 7295181.762562074, 48.67)
('2026-02-23', 7072204.244187081, 47.17)
('2026-02-23', 7092361.1660758825, 44.83)
('2026-02-23', 7177434.935222951, 46.78)
('2026-02-23', 7149914.289024058, 47.27)
('2026-02-23', 6689389.08502666, 46.78)
('2026-02-23', 6810911.664670934, 45.9)
('2026-02-23', 6597493.475585312, 41.14)
('2026-02-23', 7122745.761241968, 31.05)
('2026-02-23', 6866025.560636041, 34.47)
('2026-02-23', 7182775.418149425, 33.13)
('2026-02-10', 7333947.924555619, 31.56)
('2026-02-23', 7187425.846627208, 31.72)
('2026-02-23', 7271599.950976666, 28.96)
('2026-02-23', 7171572.949306771, 26.96)
('2026-02-23', 7201187.29755112, 20.48)
('2026-02-23', 7251703.328254263, 25.09)
('2026-02-23', 7209254.173849113, 19.48)
('2026-02-23', 7268417.49030321, 23.33)
('2026-02-23', 7263849.726468839, 21.03)
('2026-02-23', 7447341.987486609, 20.75)
('2026-02-23', 7975735.892697773, 16.6)
('2026-02-23', 8003280.21321444, 15.48)
('2026-02-23', 8000169.783417303, 14.1)
('2026-02-23', 8092178.475391482, 20.51)
('2026-02-23', 8081159.94608841, 20.28)
('2026-02-23', 8009924.38113424, 25.18)
('2026-02-23', 8092853.390805625, 28.36)
('2026-02-23', 8027696.597798843, 26.21)
('2026-02-23', 7968688.759781316, 23.54)
('2026-02-23', 8167058.515487802, 24.97)
('2026-02-23', 8196935.158997864, 22.9)
('2026-02-23', 8118000.316161074, 22.36)
('2026-02-23', 7973099.086450076, 20.15)
('2026-02-23', 7980688.008703099, 19.96)
('2026-02-23', 8207545.052481962, 19.82)
('2026-02-23', 8229539.783984127, 18.31)
('2026-02-23', 8868161.595114123, -36.98)
('2026-02-23', 8794022.755272726, 8.91)
('2026-02-23', 8936515.44901635, 13.64)
('2026-02-23', 8882429.185761888, 15.06)
('2026-02-23', 8739740.641206343, 15.99)
('2026-02-23', 8860925.91388854, 12.17)
('2026-02-23', 8854656.259617174, 12.4)
('2026-02-23', 8861418.050018335, 15.04)
('2026-02-23', 8862661.820151662, 19.23)
('2026-02-23', 8833249.416670207, 19.72)
('2026-02-23', 9065676.354329923, 20.47)
('2026-02-23', 9017978.28123392, 24.56)
('2026-02-23', 9134061.037906067, 23.88)
('2026-02-23', 9387459.456660772, 23.68)
('2026-02-23', 9591418.421810476, 24.73)
('2026-02-23', 9121570.655984685, 24.02)
('2026-02-23', 9173866.493436038, 25.76)
('2026-02-23', 9274975.732278159, 25.37)
('2026-02-23', 9314436.685236426, 27.4)
('2026-02-23', 9310175.102671716, 29.44)
('2026-02-23', 9208280.990679564, 31.83)
('2026-02-23', 9026592.666677358, 32.3)
('2026-02-23', 8900073.972215421, 33.56)
('2026-02-23', 8957968.682594351, 34.3)
('2026-02-23', 9040802.274014382, 33.49)
('2026-02-23', 9038740.617012177, 34.7)
('2026-02-23', 9036688.899610182, 32.8)
('2026-02-23', 9003749.459208991, 33.67)
('2026-02-23', 8729536.730077919, 35.57)
('2026-02-23', 8957197.574287502, 35.49)
('2026-02-23', 9066295.741750069, 36.88)
('2026-02-23', 9066867.46885247, 37.33)
('2026-02-23', 9455619.179043707, 37.42)
('2026-02-23', 9440056.689266069, 39.49)
('2026-02-23', 9288882.88186932, 38.17)
('2026-02-23', 9081227.025134273, 38.98)
('2026-02-23', 9132702.543985052, 39.54)
('2026-02-23', 9084246.101299008, 36.43)
('2026-02-23', 9090411.27477335, 36.24)
('2026-02-23', 9208980.453923177, 37.07)
('2026-02-23', 9039952.955659283, 38.26)
('2026-02-23', 9070436.848135183, 37.91)
('2026-02-23', 9080584.318377115, 38.79)
('2026-02-23', 8945088.576284403, 39.72)
('2026-02-23', 8792883.07729243, 40.6)
('2026-02-23', 8731873.284684414, 40.4)
('2026-02-23', 9111429.945371069, 37.91)
('2026-02-23', 9111165.38661966, 38.66)
('2026-02-23', 9223086.808659252, 38.53)
('2026-02-23', 9165684.099752242, 39.67)
('2026-02-23', 9156217.740562832, 39.27)
('2026-02-23', 9177823.305095606, 39.88)
('2026-02-23', 9263092.465181679, 40.57)
('2026-02-23', 9181709.414667957, 40.51)
('2026-02-23', 9054321.250569785, 40.59)
('2026-02-23', 9325640.339018358, 40.91)
('2026-02-23', 9360532.463404836, 39.64)
('2026-02-23', 9250500.062624797, 40.56)
('2026-02-23', 9285248.177863376, 40.06)
('2026-02-23', 9337523.923073687, 40.3)
('2026-02-23', 9302203.177316865, 41.2)
('2026-02-23', 9338122.035800587, 40.74)
('2026-02-23', 9541743.483380785, 40.55)
('2026-02-23', 9934947.612549465, 40.83)
('2026-02-23', 10091339.413757524, 41.76)
('2026-02-23', 10078287.164944079, 41.88)
('2026-02-23', 10222853.345055208, 40.99)
('2026-02-23', 10301939.218478084, 41.23)
('2026-02-23', 10119542.204331392, 41.46)
('2026-02-23', 10198739.393321177, 40.89)
('2026-02-23', 10277885.47839658, 41.13)
('2026-02-23', 10164069.670952292, 39.85)
('2026-02-23', 10156547.547410768, 40.1)
('2026-02-23', 10101549.352407157, 40.83)
('2026-02-23', 10136533.758092493, 41.67)
('2026-02-23', 10357349.26643955, 42.25)
('2026-02-23', 10249425.74900696, 41.93)
('2026-02-23', 10229427.683390176, 41.16)
('2026-02-23', 10168020.4311719, 41.94)
('2026-02-23', 10203795.311577797, 41.53)
('2026-02-23', 10330494.375551593, 42.6)
('2026-02-23', 10240072.841855934, 42.26)
('2026-02-23', 10260715.669243045, 42.05)
('2026-02-23', 10330510.927890545, 42.89)
('2026-02-23', 10122552.718401065, 42.89)
('2026-02-23', 9870309.502282668, 42.91)
('2026-02-23', 9811174.470132805, 42.62)
('2026-02-23', 9963363.104407016, 42.32)
('2026-02-23', 10119947.866363142, 42.44)
('2026-02-23', 10011721.5506572, 43.17)
('2026-02-23', 10094655.435390146, 43.21)
('2026-02-23', 10270107.263258504, 42.88)
('2026-02-23', 10236807.855788205, 42.96)
('2026-02-23', 10220759.730383817, 42.61)
('2026-02-23', 10434491.300112702, 42.76)
('2026-02-23', 10412275.449238887, 42.76)
('2026-02-23', 10529495.638104321, 41.39)
('2026-02-23', 10805439.78369676, 39.69)
('2026-02-23', 10383230.847886154, 36.87)
('2026-02-23', 10268856.947554458, 38.05)
('2026-02-23', 10282983.838569582, 37.25)
('2026-02-23', 10286533.101169772, 37.33)
('2026-02-23', 10148644.242275473, 37.23)
('2026-02-23', 9819786.419050021, 38.29)
('2026-02-23', 9942066.543754837, 40.17)
('2026-02-23', 9813063.27750558, 40.99)
('2026-02-23', 10203164.21582744, 41.09)
('2026-02-23', 10074416.19618185, 39.26)
('2026-02-23', 9903221.35080575, 39.55)
('2026-02-23', 9653212.189243559, 39.92)
('2026-02-23', 9801777.668906499, 40.11)
('2026-02-23', 9749130.25886824, 40.06)
('2026-02-23', 9856302.06893481, 40.47)
('2026-02-23', 9564432.013993934, 39.03)
('2026-02-23', 9591794.692119835, 40.05)
('2026-02-23', 9545191.818462053, 38.51)
('2026-02-23', 9606486.0790093, 36.9)
('2026-02-23', 9784574.242949013, 39.12)
('2026-02-23', 9838796.609221794, 40.52)
('2026-02-23', 9765163.284050079, 39.82)
('2026-02-23', 9759026.631183332, 41.04)
('2026-02-23', 9718962.630296323, 40.44)
('2026-02-23', 9800346.003033817, 39.22)
('2026-02-23', 9856054.84901548, 40.03)
('2026-02-23', 9840553.151484529, 40.86)
('2026-02-23', 10035954.764445597, 40.84)
('2026-02-23', 10195205.098488238, 40.7)
('2026-02-23', 10254357.380846838, 40.69)
('2026-02-23', 10237593.3071353, 41.37)
('2026-02-23', 10184894.127284445, 39.88)
('2026-02-23', 10169238.650025213, 40.46)
('2026-02-23', 10261685.530263504, 39.73)
('2026-02-23', 10237752.888404036, 38.39)
('2026-02-23', 10333070.25718556, 39.34)
('2026-02-23', 10189201.725638028, 37.27)
('2026-02-23', 10194461.688819751, 35.94)
('2026-02-23', 10158260.693491202, 35.64)
('2026-02-23', 9951646.271657305, 36.6)
('2026-02-23', 9948492.512889242, 37.44)
('2026-02-23', 10060469.351465985, 38.97)
('2026-02-23', 9673068.167457229, 38.56)
('2026-02-23', 9728251.057537576, 36.97)
('2026-02-23', 9723915.967631772, 40.05)
('2026-02-23', 9944472.608696878, 41.18)
('2026-02-23', 10139763.924082505, 41.23)
('2026-02-23', 10130020.723922314, 40.9)
('2026-02-23', 10509252.859358784, 39.93)
('2026-02-23', 10700725.995237181, 41.14)
('2026-02-23', 10847910.013598107, 41.24)
('2026-02-23', 10859533.642673422, 41.64)
('2026-02-23', 10959365.064936124, 41.57)
('2026-02-23', 11070472.246732509, 41.99)
('2026-02-23', 10783920.730192943, 42.91)
('2026-02-23', 10949945.97908964, 44.71)
('2026-02-23', 10814774.599012492, 45.58)
('2026-02-23', 10047260.111235712, 45.2)
('2026-02-23', 9838358.210748602, 44.54)
('2026-02-23', 10223942.881584922, 45.23)
('2026-02-23', 10216224.051870666, 45.65)
('2026-02-23', 10046351.075825775, 46.23)
('2026-02-23', 9721344.884648668, 45.72)
('2026-02-23', 9509774.024195194, 45.64)
('2026-02-23', 9369768.130232994, 45.48)
('2026-02-23', 9432476.848616607, 46.76)
('2026-02-23', 9558930.877185136, 46.59)
('2026-02-23', 9720308.914971137, 47.02)
('2026-02-23', 9549158.301143315, 47.58)
('2026-02-23', 9442499.946295625, 47.86)
('2026-02-23', 9659976.397607893, 48.34)
('2026-02-23', 9747832.72977752, 49.04)
('2026-02-23', 9802501.15016422, 47.79)
('2026-02-23', 10055171.794296525, 47.02)
('2026-02-23', 10073474.454011032, 47.94)
('2026-02-23', 9965129.220872145, 48.18)
('2026-02-23', 9722166.86543983, 47.5)
('2026-02-23', 9593893.17104472, 47.85)
('2026-02-23', 9734748.91964181, 48.24)
('2026-02-23', 9765788.362963019, 48.35)
('2026-02-23', 9824421.072227614, 47.47)
('2026-02-23', 9450928.858755054, 49.78)
('2026-02-23', 9018317.599498693, 50.45)
('2026-02-23', 9199126.082980732, 50.63)
('2026-02-23', 8984607.813501872, 52.14)
('2026-02-23', 9167651.236387476, 52.15)
('2026-02-23', 9069592.039128657, 53.08)
('2026-02-23', 9283589.00601575, 52.81)
('2026-02-23', 9394913.182233905, 53.47)
('2026-02-23', 9108594.696793688, 52.25)
('2026-02-23', 8994239.327086337, 52.87)
('2026-02-23', 8857694.85444411, 53.16)
('2026-02-23', 8376936.116014769, 53.0)
('2026-02-23', 8470582.749251666, 52.28)
('2026-02-23', 8373085.239387692, 52.78)
('2026-02-23', 8157780.455111292, 52.61)
('2026-02-23', 8219844.429070548, 52.81)
('2026-02-23', 8084502.70583037, 52.26)
('2026-02-23', 7685198.360480496, 52.16)
('2026-02-23', 7622398.708162882, 53.55)
('2026-02-23', 7591078.566298594, 54.77)
('2026-02-23', 7778520.446850556, 55.67)
('2026-02-23', 7865475.253834086, 56.19)
('2026-02-23', 7783791.323601658, 56.8)
('2026-02-23', 8066930.863801428, 57.95)
('2026-02-23', 8157156.351483771, 58.34)
('2026-02-23', 8126220.637986011, 58.69)
('2026-02-23', 8116488.479072998, 58.22)
('2026-02-23', 8078246.317717989, 59.5)
('2026-02-23', 7731939.31508293, 60.07)
('2026-02-23', 8213485.439946512, 61.09)
('2026-02-23', 8441734.894689914, 60.4)
('2026-02-23', 8277612.193785475, 59.12)
('2026-02-23', 8033337.656068311, 61.67)
('2026-02-23', 8028324.929700683, 61.66)
('2026-02-23', 8110183.521497487, 63.21)
('2026-02-23', 8167418.75650716, 63.43)
('2026-02-23', 8337407.11660591, 61.55)
('2026-02-23', 8261440.281355997, 60.54)
('2026-02-23', 8347818.307928058, 59.7)
('2026-02-23', 8175319.49414227, 61.33)
('2026-02-23', 8175924.735194205, 63.81)
('2026-02-23', 7992348.231966222, 66.08)
('2026-02-23', 7844409.288926788, 65.03)
('2026-02-23', 7987315.985984798, 64.02)
('2026-02-23', 7781471.915537124, 64.45)
('2026-02-23', 7712879.171308659, 66.02)
('2026-02-23', 7892110.371399885, 65.59)
('2026-02-23', 7913974.621357582, 65.36)
('2026-02-23', 7933999.65474005, 64.82)
('2026-02-23', 7929162.75966298, 64.55)
('2026-02-23', 7820620.968822208, 59.95)
('2026-02-23', 7872946.774052088, 61.43)
('2026-02-23', 7860175.221034703, 61.48)
('2026-02-23', 7838865.798860937, 57.75)
('2026-02-23', 7886342.002067149, 61.12)
('2026-02-23', 7887770.596681177, 58.47)
('2026-02-23', 7835388.056690424, 60.93)
('2026-02-23', 7936951.056508718, 61.49)
('2026-02-23', 7875103.91153735, 60.55)
('2026-02-23', 7982611.090931888, 59.19)
('2026-02-23', 8094664.567193232, 61.41)
('2026-02-23', 8154755.980058913, 58.73)
('2026-02-23', 8224912.970329631, 59.34)
('2026-02-23', 8475311.204337161, 59.77)
('2026-02-23', 8443838.294347357, 59.61)
('2026-02-23', 8200790.873528976, 59.29)
('2026-02-23', 8179932.125614385, 59.7)
('2026-02-23', 8169727.593041189, 60.2)
('2026-02-23', 8164051.8328820085, 63.15)
('2026-02-23', 8196362.9552232, 63.42)
('2026-02-23', 8214254.506811856, 63.16)
('2026-02-23', 8600260.479528198, 63.33)
('2026-02-23', 8754772.557780331, 62.61)
('2026-02-23', 8637202.771129187, 61.34)
('2026-02-23', 8665871.041073622, 61.45)
('2026-02-23', 8641731.269593248, 62.18)
('2026-02-23', 8504968.615885023, 62.02)
('2026-02-23', 8414003.970645163, 63.03)
('2026-02-23', 8046939.8302773405, 63.81)
('2026-02-23', 8179241.969294843, 65.0)
('2026-02-23', 8189307.776814618, 63.5)
('2026-02-23', 8190756.883147298, 64.46)
('2026-02-23', 8167427.829795334, 65.72)
('2026-02-23', 7931480.8104405, 65.63)
('2026-02-23', 8098992.121060789, 64.73)
('2026-02-23', 8165356.488930265, 64.96)
('2026-02-23', 8206661.924142179, 64.92)
('2026-02-23', 7762053.970031044, 65.31)
('2026-02-23', 7714332.820802952, 65.96)
('2026-02-23', 7217787.461780625, 63.82)
('2026-02-23', 7055170.4747747015, 65.32)
('2026-02-23', 7124353.514366637, 66.24)
('2026-02-23', 6839512.652076184, 65.49)
('2026-02-23', 6617843.606631121, 63.28)
('2026-02-23', 5676634.189757013, 61.95)
('2026-02-23', 6389223.0613750955, 63.61)
('2026-02-23', 6278047.808376017, 66.13)
('2026-02-23', 6388983.809905373, 66.27)
('2026-02-23', 6363124.007122537, 66.41)
('2026-02-23', 6230645.199778009, 66.87)
('2026-02-23', 6073656.888033923, 66.31)
('2026-02-23', 5993963.2553228345, 67.8)
('2026-02-23', 6234117.350281114, 68.79)
('2026-02-23', 6317657.207954805, 68.81)
('2026-02-23', 6222983.54818252, 69.57)
('2026-02-23', 6255749.578602175, 69.21)
('2026-02-23', 6116329.755578176, 70.11)
('2026-02-23', 6033801.7653913135, 69.9)
('2026-02-13', 6092367.347486159, 70.34)
('2026-02-23', 6166730.671036533, 71.0)
('2026-02-23', 6167421.5569663085, 70.94)
('2026-02-23', 6132044.38390857, 72.06)
('2026-02-23', 5977841.234403941, 72.03)

In [100]:
cursor.execute("""
SELECT
    date,
    price_inr AS ethereum_price,
    IXIC_Close AS nasdaq_price
FROM merged_data
WHERE coin_id = 'ethereum'
AND date BETWEEN '2026-01-01' AND '2026-12-31'
""")

results = cursor.fetchall()
for r in results:
    print(r)#Compare NASDAQ (^IXIC) with Ethereum price trends

('2026-02-23', 244834.16977505904, 13756.330078125)
('2026-02-23', 216983.40981432973, 13614.509765625)
('2026-02-23', 217304.159336794, 13814.490234375)
('2026-02-23', 202765.03870967304, 13881.7197265625)
('2026-02-23', 201317.5125202556, 13924.91015625)
('2026-02-23', 195516.66716854277, 13911.75)
('2026-02-23', 193559.06747479382, 14020.330078125)
('2026-02-23', 220175.98842114926, 14069.419921875)
('2026-02-23', 187601.93013882774, 14174.1396484375)
('2026-02-23', 189391.99179852934, 14072.8603515625)
('2026-02-23', 194675.72885365813, 14039.6796875)
('2026-02-23', 191886.11355343607, 14161.349609375)
('2026-02-23', 186564.74028701626, 14030.3798828125)
('2026-02-23', 191643.05645176853, 14141.48046875)
('2026-02-23', 175758.37045736366, 14253.26953125)
('2026-02-23', 164149.389538545, 14271.73046875)
('2026-02-23', 167538.8977230319, 14369.7099609375)
('2026-02-23', 166533.75651871518, 14360.3896484375)
('2026-02-23', 161919.08161409126, 14500.509765625)
('2026-02-23', 166129.37514050907, 14528.330078125)
('2026-02-23', 168649.33224748378, 14503.9501953125)
('2026-02-23', 164134.74219204995, 14522.3798828125)
('2026-02-23', 167679.9006033522, 14639.330078125)
('2026-02-23', 167319.001543521, None)
('2026-02-23', 177917.82793888426, 14663.6396484375)
('2026-02-23', 171006.12473780697, 14665.0595703125)
('2026-02-23', 168930.37673281875, 14559.7802734375)
('2026-02-23', 170229.9761188356, 14701.919921875)
('2026-02-23', 172085.9718554942, 14733.240234375)
('2026-02-23', 177753.92370784696, 14677.650390625)
('2026-02-23', 177052.68464483944, 14644.9501953125)
('2026-02-23', 172151.5682806194, 14543.1298828125)
('2026-02-23', 171697.82772804037, 14427.240234375)
('2026-02-23', 162266.37796915465, 14274.98046875)
('2026-02-23', 156474.22180351955, 14498.8798828125)
('2026-02-23', 154426.70647452315, None)
('2026-02-23', 155840.4924805317, 14684.599609375)
('2026-02-23', 163227.64895741257, 14836.990234375)
('2026-02-23', 153890.04212059852, 14840.7099609375)
('2026-02-23', 155066.27550185894, 14660.580078125)
('2026-02-23', 155313.1292931023, 14762.580078125)
('2026-02-23', 154802.90633012433, 14778.259765625)
('2026-02-23', 134677.50142669896, 14672.6796875)
('2026-02-23', 133837.57278106204, 14681.0703125)
('2026-02-23', 127176.85742857557, 14761.2900390625)
('2026-02-23', 143324.73934384843, 14780.5302734375)
('2026-02-23', 131454.92128790365, 14895.1201171875)
('2026-02-23', 134990.81789744264, 14835.759765625)
('2026-02-23', 141499.98989505236, 14860.1796875)
('2026-02-23', 137163.51905527923, 14788.08984375)
('2026-02-23', 139502.26918137303, 14765.1396484375)
('2026-02-23', 136118.34029958773, 14816.259765625)
('2026-02-23', 135084.25007491114, 14822.900390625)
('2026-02-23', 135202.85645156694, 14793.759765625)
('2026-02-23', 135687.4227659859, 14656.1796875)
('2026-02-23', 137898.7403436233, 14525.91015625)
('2026-02-23', 135372.22120159038, None)
('2026-02-23', 134334.00818529903, 14714.66015625)
('2026-02-23', 149984.44480204728, 14942.650390625)
('2026-02-23', 153384.6912264906, 15019.7998046875)
('2026-02-23', 150793.82263866183, 15041.8603515625)
('2026-02-23', 152736.0854367373, 14945.8095703125)
('2026-02-23', 155508.64352977095, 15129.5)
('2026-02-23', 153154.64715995087, 15265.8896484375)
('2026-02-23', 153246.47199208362, 15259.240234375)
('2026-02-23', 153045.86830616, 15309.3798828125)
('2026-02-23', 151706.98921091956, 15331.1796875)
('2026-02-23', 155745.16924065605, 15363.51953125)
('2026-02-23', 155840.93772632716, None)
('2026-02-23', 155254.81405305702, 15374.330078125)
('2026-02-13', 152837.10606631296, 15286.6396484375)
('2026-02-23', 153282.69389658255, 15248.25)
('2026-02-23', 153903.86052217713, None)
('2026-02-23', 153546.46543390723, 15105.580078125)
('2026-02-23', 189067.0538600533, 15037.759765625)
('2026-02-23', 199979.47617304884, 15161.5302734375)
('2026-02-23', 220672.16056835878, 15181.919921875)
('2026-02-23', 214170.10011952536, 15043.9697265625)
('2026-02-23', 211740.19586880849, 14713.900390625)
('2026-02-23', 227649.06017478785, 14746.400390625)
('2026-02-23', 222550.86125964453, 14896.849609375)
('2026-02-23', 217226.91460543944, 15052.240234375)
('2026-02-23', 217756.90685748137, 15047.7001953125)
('2026-02-23', 211823.19396124792, 14969.9697265625)
('2026-02-20', 210787.9756927576, 14546.6796875)
('2026-02-23', 215738.55684027018, 14512.4404296875)
('2026-02-23', 215915.19935485243, 14448.580078125)
('2026-02-23', 219047.5756337483, 14566.7001953125)
('2026-02-23', 228450.3696380665, 14255.48046875)
('2026-02-23', 214375.8056090152, 14433.830078125)
('2026-02-23', 215195.01779836757, 14501.91015625)
('2026-02-23', 216970.8522801864, 14654.01953125)
('2026-02-23', 218190.67523487698, 14579.5400390625)
('2026-02-23', 227238.5848495167, 14486.2001953125)
('2026-02-23', 228525.93909568293, 14465.919921875)
('2026-02-23', 224768.84403505738, 14571.6396484375)
('2026-02-23', 216016.02336935312, 14823.4296875)
('2026-02-23', 216690.8648491384, None)
('2026-02-23', 217089.5740742275, 15021.8095703125)
('2026-02-23', 222777.49872829148, 15129.08984375)
('2026-02-23', 222455.17860950096, 15121.6796875)
('2026-02-23', 224236.44416331983, 15215.7001953125)
('2026-02-23', 207961.65418872624, 15090.2001953125)
('2026-02-23', 212876.9182145838, 15226.7099609375)
('2026-02-23', 216727.81140618862, 15235.7099609375)
('2026-02-23', 215217.42336418747, 15235.83984375)
('2026-02-23', 230255.54711844953, 15448.1201171875)
('2026-02-23', 240556.86572695823, 15498.3896484375)
('2026-02-23', 237276.58179525606, 15595.919921875)
('2026-02-23', 227345.61024210224, 15649.599609375)
('2026-02-23', 221936.8494721614, 15811.580078125)
('2026-02-23', 218235.52611319744, 15940.3095703125)
('2026-02-23', 219421.86983518038, None)
('2026-02-23', 220541.89744913176, 15982.3603515625)
('2026-02-23', 217182.0562912451, 15886.5400390625)
('2026-02-23', 218382.42014738446, 15622.7099609375)
('2026-02-23', 218767.0130883784, 15704.2802734375)
('2026-02-23', 208337.07852694736, 15860.9599609375)
('2026-02-23', 196636.0383307714, 15853.849609375)
('2026-02-23', 192852.03096719063, 15973.8603515625)
('2026-02-23', 209315.24780590468, 15921.5703125)
('2026-02-23', 210338.28060317386, 15993.7099609375)
('2026-02-23', 207894.42363255343, None)
('2026-02-23', 206903.99097231845, 15854.759765625)
('2026-02-23', 207191.0496905718, 15775.1396484375)
('2026-02-23', 208396.95938860573, 15845.23046875)
('2026-02-23', 213866.80820581852, None)
('2026-02-23', 213247.902753943, 15491.66015625)
('2026-02-23', 206191.53795072352, 15782.830078125)
('2026-02-11', 220583.0677146267, 15537.6904296875)
('2026-02-23', 221209.20718607036, 15254.0498046875)
('2026-02-23', 214841.71925105614, 15381.3203125)
('2026-02-23', 215995.5389160479, 15085.4697265625)
('2026-02-23', 219842.28509645213, 15225.150390625)
('2026-02-23', 218478.50703220506, 15686.919921875)
('2026-02-23', 224192.01293457407, 15786.990234375)
('2026-02-23', 237634.3285912139, 15517.3701171875)
('2026-02-23', 252785.18261104374, 15630.599609375)
('2026-02-23', 253963.71411998925, 15413.2802734375)
('2026-02-23', 252599.85968309751, 15237.6396484375)
('2026-02-23', 255256.0749124428, 15565.580078125)
('2026-02-23', 258953.02296009834, 15180.4296875)
('2026-02-23', 269423.17285168904, 15169.6796875)
('2026-02-23', 289273.06195820443, 14980.9404296875)
('2026-02-23', 299604.7001320289, 15341.08984375)
('2026-02-23', 305580.9799247014, 15521.8896484375)
('2026-02-23', 309629.88231970003, 15653.3701171875)
('2026-02-23', 323799.5635112756, None)
('2026-02-23', 324888.02667051577, 15871.259765625)
('2026-02-23', 323522.2855073287, 15781.7197265625)
('2026-02-23', 313632.80993368995, 15766.2197265625)
('2026-02-23', 320521.28663827025, 15741.5595703125)
('2026-02-23', 322067.53188592376, 15644.9697265625)
('2026-02-23', 323729.6744159729, 15832.7998046875)
('2026-02-23', 334271.3356334813, 15622.7197265625)
('2026-02-23', 328567.3072022601, 15100.169921875)
('2026-02-23', 329848.44489638496, 15080.8603515625)
('2026-02-23', 333798.49786685634, 14935.900390625)
('2026-02-23', 323419.73918441863, 14942.830078125)
('2026-02-23', 303617.9116663577, 15153.4501953125)
('2026-02-23', 296151.6805356246, 15188.3896484375)
('2026-02-23', 305147.6597239278, 14806.8095703125)
('2026-02-23', 326586.85608261486, 14893.75)
('2026-02-23', 316895.55183794844, None)
('2026-02-23', 323322.0010279766, 14506.900390625)
('2026-02-23', 341975.0422938313, 14340.259765625)
('2026-02-23', 352049.4403810017, 14154.01953125)
('2026-02-23', 374193.3376648639, 13768.919921875)
('2026-02-23', 372140.5970629246, 13855.1298828125)
('2026-02-23', 370718.8174494866, 13539.2900390625)
('2026-02-23', 403547.06190802733, None)
('2026-02-23', 416582.6051270567, 13352.7802734375)
('2026-02-23', 399375.2127189976, 13770.5703125)
('2026-02-23', 387732.95356370165, 14239.8798828125)
('2026-02-23', 387408.6664674909, 14346.0)
('2026-02-23', 392681.4189909559, 14417.5498046875)
('2026-02-23', 376878.0982824829, 13878.8203125)
('2026-02-23', 354772.70430919825, 14098.009765625)
('2026-02-23', 376832.66666282027, 14015.669921875)
('2026-02-23', 368766.6639472321, 14194.4501953125)
('2026-02-23', 421737.4738716338, 14490.3701171875)
('2026-02-23', 416904.49092835333, 14185.6396484375)
('2026-02-23', 417273.9071184703, 13791.150390625)
('2026-02-23', 383869.2304155191, 13790.919921875)
('2026-02-23', 403346.84673449927, 14139.759765625)
('2026-02-23', 394479.82107990474, 14124.08984375)
('2026-02-23', 394824.62858350464, 13716.7197265625)
('2026-02-23', 384794.36172029114, 13548.0703125)
('2026-02-23', 385618.86285304534, None)
('2026-02-23', 386992.0744205619, 13381.51953125)
('2026-02-23', 378688.487081064, 13037.490234375)
('2026-02-23', 380669.0608269572, 13473.58984375)
('2026-02-23', 391914.25736500154, 13694.6201171875)
('2026-02-23', 379062.50711160863, 13751.400390625)
('2026-02-23', 379789.69451721257, None)
('2026-02-23', 376830.61714539555, 13752.01953125)
('2026-02-23', 379557.7315665512, 13537.9404296875)
('2026-02-23', 379169.3803941581, 13313.4404296875)
('2026-02-23', 380163.9598970403, 12830.9599609375)
('2026-02-23', 382811.6356012148, 12795.5498046875)
('2026-02-23', 393614.0739117057, 13255.5498046875)
('2026-02-23', 415686.0060768963, 13129.9599609375)
('2026-02-23', 412052.856085073, 12843.8095703125)
('2026-02-23', 406940.596240047, 12581.2197265625)
('2026-02-23', 398693.42995223537, 12948.6201171875)
('2026-02-23', 395856.797622927, 13436.5498046875)
('2026-02-23', 403666.7568900215, 13614.7802734375)
('2026-02-23', 404926.98327490315, None)
('2026-02-23', 393846.3358485685, 13838.4599609375)
('2026-02-23', 394843.6203459821, 14108.8203125)
('2026-02-23', 392295.47524281475, 13922.599609375)
('2026-02-23', 370875.27142150694, 14191.83984375)
('2026-02-23', 369992.0919011612, 14169.2998046875)
('2026-02-23', 368312.96560615575, 14354.900390625)
('2026-02-23', 342937.4440185811, 14619.6396484375)
('2026-02-23', 357978.55612770614, 14442.26953125)
('2026-02-23', 356321.1005771281, 14220.51953125)
('2026-02-23', 367286.12298418215, 14261.5)
('2026-02-23', 373944.85329388455, 14532.5498046875)
('2026-02-23', 368177.3713848715, 14204.169921875)
('2026-02-23', 385235.77973544877, 13888.8203125)
('2026-02-23', 397823.05193989933, 13897.2998046875)
('2026-02-23', 400707.46142882656, 13711.0)
('2026-02-23', 398218.8935895547, 13411.9599609375)
('2026-02-23', 400668.6421398132, 13371.5703125)
('2026-02-23', 416041.06085392536, 13643.58984375)
('2026-02-22', 395289.8026309068, None)
('2026-02-23', 401911.0484708849, 13332.3603515625)
('2026-02-23', 388222.87205311254, 13619.66015625)
('2026-02-23', 340432.9353676543, 13453.0703125)
('2026-02-23', 332747.98798714374, 13174.650390625)
('2026-02-23', 369207.3362657844, 12839.2900390625)
('2026-02-23', 376492.3574048653, 13004.849609375)
('2026-02-23', 366574.05838423775, 12490.740234375)
('2026-02-23', 349761.3884710538, 12488.9296875)
('2026-02-23', 342302.33220614656, 12871.5302734375)
('2026-02-23', 337247.7588866496, 12334.6396484375)
('2026-02-23', 342375.6803081046, 12536.01953125)
('2026-02-23', 350696.6804336402, None)
('2026-02-23', 349657.073530753, 12964.8603515625)
('2026-02-23', 341303.9842640361, 12317.6904296875)
('2026-02-23', 333571.21535914514, 12144.66015625)
('2026-02-23', 338462.9290819708, 11623.25)
('2026-02-23', 345416.6546043208, 11737.669921875)
('2026-02-23', 347083.5922685809, 11364.240234375)
('2026-02-23', 365539.5621120337, 11370.9599609375)
('2026-02-23', 363758.94232227415, 11805.0)
('2026-02-23', 351342.5325721324, 11662.7900390625)
('2026-02-23', 344315.5289450759, 11984.51953125)
('2026-02-23', 337015.4990615576, 11418.150390625)
('2026-02-19', 341801.10296794504, 11388.5)
('2026-02-23', 343730.3913686987, 11354.6201171875)
('2026-02-23', 347169.85800323385, 11535.26953125)
('2026-02-23', 319468.25832003524, 11264.4501953125)
('2026-02-23', 292527.2014230804, 11434.740234375)
('2026-02-23', 303546.1807953054, 11740.650390625)
('2026-02-23', 293412.52766766545, 12131.1298828125)
('2026-02-23', 304507.99491275364, None)
('2026-02-23', 301591.6290594234, 12081.3896484375)
('2026-02-23', 317071.7291616941, 11994.4599609375)
('2026-02-23', 316207.1597353334, 12316.900390625)
('2026-02-23', 302271.19106009, 12012.73046875)
('2026-02-23', 302072.2252489844, 12061.3701171875)
('2026-02-23', 287385.51825001417, 12175.23046875)
('2026-02-23', 275511.26516527805, 12086.26953125)
('2026-02-23', 281155.6844835739, 11754.23046875)
('2026-02-23', 275080.20597856207, 11340.01953125)
('2026-02-23', 267796.5731112152, 10809.23046875)
('2026-02-23', 276052.04898099863, 10828.349609375)
('2026-02-23', 267032.830083096, 11099.150390625)
('2026-02-23', 251183.08126814634, 10646.099609375)
('2026-02-23', 247777.39778764817, 10798.349609375)
('2026-02-23', 248183.09115512334, None)
('2026-02-23', 250950.12836319354, 11069.2998046875)
('2026-02-23', 263283.40358322934, 11053.080078125)
('2026-02-23', 263444.9399900479, 11232.1904296875)
('2026-02-23', 269938.1970950932, 11607.6201171875)
('2026-02-23', 269490.2527975858, 11524.5498046875)
('2026-02-23', 271004.1486761167, 11181.5400390625)
('2026-02-20', 267260.2384447111, 11177.8896484375)
('2026-02-23', 267424.4592587914, 11028.740234375)
('2026-02-23', 250829.94408877468, 11127.849609375)
('2026-02-23', 269370.30418167287, None)
('2026-02-23', 288132.42535713845, 11322.240234375)
('2026-02-23', 281520.95159888716, 11361.849609375)
('2026-02-23', 271893.52182715805, 11621.349609375)
('2026-02-23', 273416.13820120675, 11635.3095703125)
('2026-02-23', 274616.2375638853, 11372.599609375)
('2026-02-23', 281685.69218486216, 11264.73046875)
('2026-02-23', 298746.9630305986, 11247.580078125)
('2026-02-23', 298675.7147486205, 11251.1904296875)
('2026-02-23', 292065.55714175856, 11452.419921875)
('2026-02-23', 279306.9974351619, 11360.0498046875)
('2026-02-23', 282191.1596649078, 11713.150390625)
('2026-02-23', 277686.2575249929, 11897.650390625)
('2026-02-23', 269107.8224748998, 12059.6103515625)
('2026-02-23', 269596.8374095658, 11834.1103515625)
('2026-02-23', 255672.94816147196, 11782.669921875)
('2026-02-23', 255132.82641488407, 11562.5703125)
('2026-02-23', 266653.5750632806, 12032.419921875)
('2026-02-23', 266686.3060581252, 12162.58984375)
('2026-02-23', 268857.45721078233, 12390.6904296875)
('2026-02-23', 269330.66898642445, 12368.98046875)
('2026-02-23', 265308.33057719615, 12348.759765625)
('2026-02-23', 264638.4624631536, 12668.16015625)
('2026-02-23', 261698.83888170918, 12720.580078125)
('2026-02-23', 262776.73658441985, 12657.5498046875)
('2026-02-23', 264850.5744899021, 12644.4599609375)
('2026-02-23', 264760.5504658988, None)
('2026-02-23', 263786.42273046816, 12854.7998046875)
('2026-02-23', 266620.8671552428, 12779.91015625)
('2026-02-23', 266951.6312463789, 13047.1904296875)
('2026-02-23', 269940.3569195695, None)
('2026-02-23', 281016.1719855551, 13102.5498046875)
('2026-02-23', 281388.8695194364, 12938.1201171875)
('2026-02-23', 282560.6030133936, 12965.33984375)
('2026-02-23', 291299.3568651643, 12705.2197265625)
('2026-02-23', 297045.36579862604, 12381.5703125)
('2026-02-23', 284403.12191626645, 12381.2998046875)
('2026-02-23', 279086.945835317, 12431.5302734375)
('2026-02-23', 278309.6101406161, 12639.26953125)
('2026-02-23', 278294.1933407241, 12141.7099609375)
('2026-02-23', 281519.50124331604, 12017.669921875)
('2026-02-23', 278535.9889192714, 11883.1396484375)
('2026-02-23', 299728.9177688779, None)
('2026-02-23', 302917.5844429012, 11785.1298828125)
('2026-02-23', 299838.3615803796, 11630.8603515625)
('2026-02-23', 299041.3190188698, None)
('2026-02-23', 300496.6677650833, 11544.91015625)
('2026-02-23', 297943.7602436932, 11791.900390625)
('2026-02-23', 289592.03165583033, 11862.1298828125)
('2026-02-23', 267489.81096221146, 12112.3095703125)
('2026-02-23', 272419.05713641306, 12266.41015625)
('2026-02-23', 269940.0485702116, 11633.5703125)
('2026-02-23', 270322.79786255566, 11719.6796875)
('2026-02-23', 270125.836049164, 11552.3603515625)
('2026-02-23', 257898.21011062048, 11448.400390625)
('2026-02-23', 268521.1124032741, 11535.01953125)
('2026-02-23', 276537.237355733, 11425.0498046875)
('2026-02-23', 276752.68161058764, 11220.1904296875)
('2026-02-23', 258717.1664228855, 11066.8095703125)
('2026-02-23', 247763.65614624374, 10867.9296875)
('2026-02-23', 224065.64499097393, 10802.919921875)
('2026-02-23', 208098.68569226892, 10829.5)
('2026-02-23', 212055.7416695305, 11051.6396484375)
('2026-02-23', 201371.05394647823, 10737.509765625)
('2026-02-23', 194638.91147198106, 10575.6201171875)
('2026-02-23', 164424.8093049238, 10815.4296875)
('2026-02-01', 186695.3649137571, 11176.41015625)
('2026-02-23', 189440.9269478321, None)
('2026-02-23', 189754.81871261535, 11073.3095703125)
('2026-02-23', 191035.83888725925, 10652.400390625)
('2026-02-23', 182890.5822309681, 10542.099609375)
('2026-02-23', 175976.56404532818, 10426.1904296875)
('2026-02-23', 176214.23834483154, 10417.099609375)
('2026-02-23', 185411.2111430372, 10649.150390625)
('2026-02-23', 188855.60230133013, 10321.3896484375)
('2026-02-23', 177856.25063894037, 10675.7998046875)
('2026-02-23', 181624.1547003928, 10772.400390625)
('2026-02-23', 180528.32834312637, 10680.509765625)
('2026-02-23', 177478.4599141033, 10614.83984375)
('2026-02-23', 177249.2474816647, 10859.7197265625)
('2026-02-23', 178533.39457288812, 10952.6103515625)
('2026-02-23', 179064.34776215904, 11199.1201171875)
('2026-02-23', 177305.13210485573, None)
('2026-02-23', 171295.9730501131, 10792.669921875)

In [101]:
cursor.execute("""
SELECT
    date,
    coin_id,
    price_inr,
    GSPC_Close AS sp500,
    IXIC_Close AS nasdaq
FROM merged_data
WHERE coin_id IN ('bitcoin', 'ethereum', 'tether')
AND date BETWEEN '2026-01-01' AND '2026-12-31'
ORDER BY date
""")


results = cursor.fetchall()
for r in results:
    print(r)#Join top 3 crypto coins with stock indices for 2025

('2026-01-27', 'tether', 84.72143692477849, 4076.60009765625, 11584.5498046875)
('2026-02-01', 'ethereum', 186695.3649137571, 3790.929931640625, 11176.41015625)
('2026-02-01', 'tether', 87.02531092350665, 4411.58984375, 13679.0400390625)
('2026-02-04', 'tether', 85.45426169674982, 3829.25, 10353.23046875)
('2026-02-10', 'bitcoin', 7333947.924555619, 2746.56005859375, 7950.68017578125)
('2026-02-11', 'ethereum', 220583.0677146267, 4567.0, 15537.6904296875)
('2026-02-13', 'bitcoin', 6092367.347486159, 4195.990234375, 13738.0)
('2026-02-13', 'ethereum', 152837.10606631296, 4514.06982421875, 15286.6396484375)
('2026-02-18', 'tether', 86.04341248201443, 3824.139892578125, 10386.98046875)
('2026-02-19', 'ethereum', 341801.10296794504, 3900.7900390625, 11388.5)
('2026-02-19', 'tether', 85.5849496864284, 3821.6201171875, 10547.1103515625)
('2026-02-19', 'tether', 91.01080876764598, 5224.6201171875, 16369.41015625)
('2026-02-20', 'ethereum', 210787.9756927576, 4352.6298828125, 14546.6796875)
('2026-02-20', 'ethereum', 267260.2384447111, 3818.830078125, 11177.8896484375)
('2026-02-21', 'tether', 88.82065097034915, 4373.6298828125, 13567.98046875)
('2026-02-22', 'bitcoin', 7615008.334491884, 3283.14990234375, 9251.330078125)
('2026-02-22', 'ethereum', 395289.8026309068, None, None)
('2026-02-22', 'tether', 89.36495482281371, 4556.6201171875, 14265.8603515625)
('2026-02-22', 'tether', 90.73829171749978, 5104.759765625, 16031.5400390625)
('2026-02-23', 'bitcoin', 8341958.303704703, None, None)
('2026-02-23', 'bitcoin', 7922797.740624487, 3257.85009765625, 9092.1904296875)
('2026-02-23', 'bitcoin', 7729282.415455005, 3234.85009765625, 9020.76953125)
('2026-02-23', 'bitcoin', 7314307.147526646, 3246.280029296875, 9071.4697265625)
('2026-02-23', 'bitcoin', 7397416.663356487, 3237.179931640625, 9068.580078125)
('2026-02-23', 'bitcoin', 7386259.847331922, 3253.050048828125, 9129.240234375)
('2026-02-23', 'bitcoin', 7523008.862171689, 3274.699951171875, 9203.4296875)
('2026-02-23', 'bitcoin', 8244472.61232367, 3265.35009765625, 9178.8603515625)
('2026-02-23', 'bitcoin', 7521257.854514662, 3288.1298828125, 9273.9296875)
('2026-02-23', 'bitcoin', 7869430.047939962, 3289.2900390625, 9258.7001953125)
('2026-02-23', 'bitcoin', 7841736.557001183, 3316.81005859375, 9357.1298828125)
('2026-02-23', 'bitcoin', 7562231.150267524, 3329.6201171875, 9388.9404296875)
('2026-02-23', 'bitcoin', 7503958.351863089, None, None)
('2026-02-23', 'bitcoin', 7035607.792612969, 3320.7900390625, 9370.8095703125)
('2026-02-23', 'bitcoin', 6882112.04135304, 3321.75, 9383.76953125)
('2026-02-23', 'bitcoin', 7220111.199834512, 3325.5400390625, 9402.48046875)
('2026-02-23', 'bitcoin', 7311397.167011021, 3295.469970703125, 9314.91015625)
('2026-02-23', 'bitcoin', 7049331.751158462, 3243.6298828125, 9139.3095703125)
('2026-02-23', 'bitcoin', 7301205.756783538, 3276.239990234375, 9269.6796875)
('2026-02-23', 'bitcoin', 7337203.4861049205, 3273.39990234375, 9275.16015625)
('2026-02-23', 'bitcoin', 7182714.546311197, 3283.659912109375, 9298.9296875)
('2026-02-23', 'bitcoin', 7307625.213417549, 3225.52001953125, 9150.9404296875)
('2026-02-23', 'bitcoin', 7166130.900539224, 3248.919921875, 9273.400390625)
('2026-02-23', 'bitcoin', 7495414.341859128, 3297.590087890625, 9467.9697265625)
('2026-02-23', 'bitcoin', 7275140.94449613, 3334.68994140625, 9508.6796875)
('2026-02-23', 'bitcoin', 7224000.906005809, 3345.780029296875, 9572.150390625)
('2026-02-23', 'bitcoin', 7205763.671408613, 3327.7099609375, 9520.509765625)
('2026-02-23', 'bitcoin', 7377568.408827406, 3352.090087890625, 9628.3896484375)
('2026-02-23', 'bitcoin', 7471026.999919416, 3357.75, 9638.9404296875)
('2026-02-23', 'bitcoin', 7490943.665690553, 3379.449951171875, 9725.9599609375)
('2026-02-23', 'bitcoin', 7448415.462567322, 3373.93994140625, 9711.9697265625)
('2026-02-23', 'bitcoin', 7474953.075439318, 3380.159912109375, 9731.1796875)
('2026-02-23', 'bitcoin', 7216289.858225705, None, None)
('2026-02-23', 'bitcoin', 7072289.607125187, 3370.2900390625, 9732.740234375)
('2026-02-23', 'bitcoin', 7044678.366106417, 3386.14990234375, 9817.1796875)
('2026-02-23', 'bitcoin', 7049110.1215911815, 3373.22998046875, 9750.9697265625)
('2026-02-23', 'bitcoin', 7295181.762562074, None, None)
('2026-02-23', 'bitcoin', 7072204.244187081, 3225.889892578125, 9221.2802734375)
('2026-02-23', 'bitcoin', 7092361.1660758825, 3128.2099609375, 8965.6103515625)
('2026-02-23', 'bitcoin', 7177434.935222951, 3116.389892578125, 8980.7802734375)
('2026-02-23', 'bitcoin', 7149914.289024058, 2978.760009765625, 8566.48046875)
('2026-02-23', 'bitcoin', 6689389.08502666, 2954.219970703125, 8567.3701171875)
('2026-02-23', 'bitcoin', 6810911.664670934, 3090.22998046875, 8952.169921875)
('2026-02-23', 'bitcoin', 6597493.475585312, 3003.3701171875, 8684.08984375)
('2026-02-23', 'bitcoin', 7122745.761241968, 3130.1201171875, 9018.08984375)
('2026-02-23', 'bitcoin', 6866025.560636041, 3023.93994140625, 8738.58984375)
('2026-02-23', 'bitcoin', 7182775.418149425, 2972.3701171875, 8575.6201171875)
('2026-02-23', 'bitcoin', 7187425.846627208, None, None)
('2026-02-23', 'bitcoin', 7271599.950976666, 2741.3798828125, 7952.0498046875)
('2026-02-23', 'bitcoin', 7171572.949306771, 2480.639892578125, 7201.7998046875)
('2026-02-23', 'bitcoin', 7201187.29755112, 2711.02001953125, 7874.8798828125)
('2026-02-23', 'bitcoin', 7251703.328254263, 2386.1298828125, 6904.58984375)
('2026-02-23', 'bitcoin', 7209254.173849113, 2529.18994140625, 7334.77978515625)
('2026-02-23', 'bitcoin', 7268417.49030321, 2398.10009765625, 6989.83984375)
('2026-02-23', 'bitcoin', 7263849.726468839, 2409.389892578125, 7150.580078125)
('2026-02-23', 'bitcoin', 7447341.987486609, 2304.919921875, 6879.52001953125)
('2026-02-23', 'bitcoin', 7975735.892697773, 2237.39990234375, 6860.669921875)
('2026-02-23', 'bitcoin', 8003280.21321444, 2447.330078125, 7417.85986328125)
('2026-02-23', 'bitcoin', 8000169.783417303, 2475.56005859375, 7384.2998046875)
('2026-02-23', 'bitcoin', 8092178.475391482, 2630.070068359375, 7797.5400390625)
('2026-02-23', 'bitcoin', 8081159.94608841, 2541.469970703125, 7502.3798828125)
('2026-02-23', 'bitcoin', 8009924.38113424, 2626.64990234375, 7774.14990234375)
('2026-02-23', 'bitcoin', 8092853.390805625, 2584.590087890625, 7700.10009765625)
('2026-02-23', 'bitcoin', 8027696.597798843, 2470.5, 7360.580078125)
('2026-02-23', 'bitcoin', 7968688.759781316, None, None)
('2026-02-23', 'bitcoin', 8167058.515487802, 2488.64990234375, 7373.080078125)
('2026-02-23', 'bitcoin', 8196935.158997864, None, None)
('2026-02-23', 'bitcoin', 8118000.316161074, 2659.409912109375, 7887.259765625)
('2026-02-23', 'bitcoin', 7973099.086450076, 2749.97998046875, 8090.89990234375)
('2026-02-23', 'bitcoin', 7980688.008703099, 2789.820068359375, 8153.580078125)
('2026-02-23', 'bitcoin', 8207545.052481962, 2761.6298828125, 8192.419921875)
('2026-02-23', 'bitcoin', 8229539.783984127, None, None)
('2026-02-23', 'bitcoin', 8868161.595114123, 2783.360107421875, 8393.1796875)
('2026-02-23', 'bitcoin', 8794022.755272726, 2799.550048828125, 8532.3603515625)
('2026-02-23', 'bitcoin', 8936515.44901635, 2874.56005859375, 8650.1396484375)
('2026-02-23', 'bitcoin', 8882429.185761888, 2823.159912109375, 8560.73046875)
('2026-02-23', 'bitcoin', 8739740.641206343, 2736.56005859375, 8263.23046875)
('2026-02-23', 'bitcoin', 8860925.91388854, 2799.31005859375, 8495.3798828125)
('2026-02-23', 'bitcoin', 8854656.259617174, 2797.800048828125, 8494.75)
('2026-02-23', 'bitcoin', 8861418.050018335, 2836.739990234375, 8634.51953125)
('2026-02-23', 'bitcoin', 8862661.820151662, 2878.47998046875, 8730.16015625)
('2026-02-23', 'bitcoin', 8833249.416670207, 2863.389892578125, 8607.73046875)
('2026-02-23', 'bitcoin', 9065676.354329923, 2939.510009765625, 8914.7099609375)
('2026-02-23', 'bitcoin', 9017978.28123392, 2912.429931640625, 8889.5498046875)
('2026-02-23', 'bitcoin', 9134061.037906067, None, None)
('2026-02-23', 'bitcoin', 9387459.456660772, 2842.739990234375, 8710.7099609375)
('2026-02-23', 'bitcoin', 9591418.421810476, 2868.43994140625, 8809.1201171875)
('2026-02-23', 'bitcoin', 9121570.655984685, 2848.419921875, 8854.3896484375)
('2026-02-23', 'bitcoin', 9173866.493436038, 2881.18994140625, 8979.66015625)
('2026-02-23', 'bitcoin', 9274975.732278159, 2929.800048828125, 9121.3203125)
('2026-02-23', 'bitcoin', 9314436.685236426, 2930.18994140625, 9192.33984375)
('2026-02-23', 'bitcoin', 9310175.102671716, 2870.1201171875, 9002.5498046875)
('2026-02-23', 'bitcoin', 9208280.990679564, 2820.0, 8863.169921875)
('2026-02-23', 'bitcoin', 9026592.666677358, 2852.5, 8943.7197265625)
('2026-02-23', 'bitcoin', 8900073.972215421, 2863.699951171875, 9014.5595703125)
('2026-02-23', 'bitcoin', 8957968.682594351, 2953.909912109375, 9234.830078125)
('2026-02-23', 'bitcoin', 9040802.274014382, 2922.93994140625, 9185.099609375)
('2026-02-23', 'bitcoin', 9038740.617012177, 2971.610107421875, 9375.7802734375)
('2026-02-23', 'bitcoin', 9036688.899610182, 2948.510009765625, 9284.8798828125)
('2026-02-23', 'bitcoin', 9003749.459208991, 2955.449951171875, 9324.58984375)
('2026-02-23', 'bitcoin', 8729536.730077919, 2991.77001953125, 9340.2197265625)
('2026-02-23', 'bitcoin', 8957197.574287502, 3036.1298828125, 9412.3603515625)
('2026-02-23', 'bitcoin', 9066295.741750069, 3029.72998046875, 9368.990234375)
('2026-02-23', 'bitcoin', 9066867.46885247, 3044.31005859375, 9489.8701171875)
('2026-02-23', 'bitcoin', 9455619.179043707, 3055.72998046875, 9552.0498046875)
('2026-02-23', 'bitcoin', 9440056.689266069, 3080.820068359375, 9608.3798828125)
('2026-02-23', 'bitcoin', 9288882.88186932, 3122.8701171875, 9682.91015625)
('2026-02-23', 'bitcoin', 9081227.025134273, 3112.35009765625, 9615.8095703125)
('2026-02-23', 'bitcoin', 9132702.543985052, 3193.929931640625, 9814.080078125)
('2026-02-23', 'bitcoin', 9084246.101299008, 3232.389892578125, 9924.75)
('2026-02-23', 'bitcoin', 9090411.27477335, 3207.179931640625, 9953.75)
('2026-02-23', 'bitcoin', 9208980.453923177, 3190.139892578125, 10020.349609375)
('2026-02-23', 'bitcoin', 9039952.955659283, 3002.10009765625, 9492.73046875)
('2026-02-23', 'bitcoin', 9070436.848135183, 3041.31005859375, 9588.8095703125)
('2026-02-23', 'bitcoin', 9080584.318377115, 3066.590087890625, 9726.01953125)
('2026-02-23', 'bitcoin', 8945088.576284403, 3124.739990234375, 9895.8701171875)
('2026-02-23', 'bitcoin', 8792883.07729243, 3113.489990234375, 9910.5302734375)
('2026-02-23', 'bitcoin', 8731873.284684414, 3115.340087890625, 9943.0498046875)
('2026-02-23', 'bitcoin', 9111429.945371069, 3097.739990234375, 9946.1201171875)
('2026-02-23', 'bitcoin', 9111165.38661966, 3117.860107421875, 10056.48046875)
('2026-02-23', 'bitcoin', 9223086.808659252, 3131.2900390625, 10131.3701171875)
('2026-02-23', 'bitcoin', 9165684.099752242, 3050.330078125, 9909.169921875)
('2026-02-23', 'bitcoin', 9156217.740562832, 3083.760009765625, 10017.0)
('2026-02-23', 'bitcoin', 9177823.305095606, 3009.050048828125, 9757.2197265625)
('2026-02-23', 'bitcoin', 9263092.465181679, 3053.239990234375, 9874.150390625)
('2026-02-23', 'bitcoin', 9181709.414667957, 3100.2900390625, 10058.76953125)
('2026-02-23', 'bitcoin', 9054321.250569785, 3115.860107421875, 10154.6298828125)
('2026-02-23', 'bitcoin', 9325640.339018358, 3130.010009765625, 10207.6298828125)
('2026-02-23', 'bitcoin', 9360532.463404836, None, None)
('2026-02-23', 'bitcoin', 9250500.062624797, 3179.719970703125, 10433.650390625)
('2026-02-23', 'bitcoin', 9285248.177863376, 3145.320068359375, 10343.8896484375)
('2026-02-23', 'bitcoin', 9337523.923073687, 3169.93994140625, 10492.5)
('2026-02-23', 'bitcoin', 9302203.177316865, 3152.050048828125, 10547.75)
('2026-02-23', 'bitcoin', 9338122.035800587, 3185.0400390625, 10617.4404296875)
('2026-02-23', 'bitcoin', 9541743.483380785, 3155.219970703125, 10390.83984375)
('2026-02-23', 'bitcoin', 9934947.612549465, 3197.52001953125, 10488.580078125)
('2026-02-23', 'bitcoin', 10091339.413757524, 3226.56005859375, 10550.490234375)
('2026-02-23', 'bitcoin', 10078287.164944079, 3215.570068359375, 10473.830078125)
('2026-02-23', 'bitcoin', 10222853.345055208, 3224.72998046875, 10503.1904296875)
('2026-02-23', 'bitcoin', 10301939.218478084, 3251.840087890625, 10767.08984375)
('2026-02-23', 'bitcoin', 10119542.204331392, 3257.300048828125, 10680.3603515625)
('2026-02-23', 'bitcoin', 10198739.393321177, 3276.02001953125, 10706.1298828125)
('2026-02-23', 'bitcoin', 10277885.47839658, 3235.659912109375, 10461.419921875)
('2026-02-23', 'bitcoin', 10164069.670952292, 3215.6298828125, 10363.1796875)
('2026-02-23', 'bitcoin', 10156547.547410768, 3239.409912109375, 10536.26953125)
('2026-02-23', 'bitcoin', 10101549.352407157, 3218.43994140625, 10402.08984375)
('2026-02-23', 'bitcoin', 10136533.758092493, 3258.43994140625, 10542.9404296875)
('2026-02-23', 'bitcoin', 10357349.26643955, 3246.219970703125, 10587.8095703125)
('2026-02-23', 'bitcoin', 10249425.74900696, 3271.1201171875, 10745.26953125)
('2026-02-23', 'bitcoin', 10229427.683390176, 3294.610107421875, 10902.7998046875)
('2026-02-23', 'bitcoin', 10168020.4311719, 3306.510009765625, 10941.169921875)
('2026-02-23', 'bitcoin', 10203795.311577797, 3327.77001953125, 10998.400390625)
('2026-02-23', 'bitcoin', 10330494.375551593, 3349.159912109375, 11108.0703125)
('2026-02-23', 'bitcoin', 10240072.841855934, 3351.280029296875, 11010.98046875)
('2026-02-23', 'bitcoin', 10260715.669243045, 3360.469970703125, 10968.3603515625)
('2026-02-23', 'bitcoin', 10330510.927890545, 3333.68994140625, 10782.8203125)
('2026-02-23', 'bitcoin', 10122552.718401065, 3380.35009765625, 11012.240234375)
('2026-02-23', 'bitcoin', 9870309.502282668, 3373.429931640625, 11042.5)
('2026-02-23', 'bitcoin', 9811174.470132805, 3372.85009765625, 11019.2998046875)
('2026-02-23', 'bitcoin', 9963363.104407016, 3381.989990234375, 11129.73046875)
('2026-02-23', 'bitcoin', 10119947.866363142, 3389.780029296875, 11210.83984375)
('2026-02-23', 'bitcoin', 10011721.5506572, 3374.85009765625, 11146.4599609375)
('2026-02-23', 'bitcoin', 10094655.435390146, 3385.510009765625, 11264.9501953125)
('2026-02-23', 'bitcoin', 10270107.263258504, 3397.159912109375, 11311.7998046875)
('2026-02-23', 'bitcoin', 10236807.855788205, 3431.280029296875, 11379.7197265625)
('2026-02-23', 'bitcoin', 10220759.730383817, 3443.6201171875, 11466.4697265625)
('2026-02-23', 'bitcoin', 10434491.300112702, 3478.72998046875, 11665.0595703125)
('2026-02-23', 'bitcoin', 10412275.449238887, 3484.550048828125, 11625.33984375)
('2026-02-23', 'bitcoin', 10529495.638104321, 3508.010009765625, 11695.6298828125)
('2026-02-23', 'bitcoin', 10805439.78369676, 3500.31005859375, 11775.4599609375)
('2026-02-23', 'bitcoin', 10383230.847886154, 3526.64990234375, 11939.669921875)
('2026-02-23', 'bitcoin', 10268856.947554458, 3580.840087890625, 12056.4404296875)
('2026-02-23', 'bitcoin', 10282983.838569582, 3455.06005859375, 11458.099609375)
('2026-02-23', 'bitcoin', 10286533.101169772, 3426.9599609375, 11313.1298828125)
('2026-02-23', 'bitcoin', 10148644.242275473, None, None)
('2026-02-23', 'bitcoin', 9819786.419050021, 3331.840087890625, 10847.6904296875)
('2026-02-23', 'bitcoin', 9942066.543754837, 3398.9599609375, 11141.5595703125)
('2026-02-23', 'bitcoin', 9813063.27750558, 3339.18994140625, 10919.58984375)
('2026-02-23', 'bitcoin', 10203164.21582744, 3340.969970703125, 10853.5498046875)
('2026-02-23', 'bitcoin', 10074416.19618185, 3383.5400390625, 11056.650390625)
('2026-02-23', 'bitcoin', 9903221.35080575, 3401.199951171875, 11190.3203125)
('2026-02-23', 'bitcoin', 9653212.189243559, 3385.489990234375, 11050.4697265625)
('2026-02-23', 'bitcoin', 9801777.668906499, 3357.010009765625, 10910.2802734375)
('2026-02-23', 'bitcoin', 9749130.25886824, 3319.469970703125, 10793.2802734375)
('2026-02-23', 'bitcoin', 9856302.06893481, 3281.06005859375, 10778.7998046875)
('2026-02-23', 'bitcoin', 9564432.013993934, 3315.570068359375, 10963.6396484375)
('2026-02-23', 'bitcoin', 9591794.692119835, 3236.919921875, 10632.990234375)
('2026-02-23', 'bitcoin', 9545191.818462053, 3246.590087890625, 10672.26953125)
('2026-02-23', 'bitcoin', 9606486.0790093, 3298.4599609375, 10913.5595703125)
('2026-02-23', 'bitcoin', 9784574.242949013, 3351.60009765625, 11117.5302734375)
('2026-02-23', 'bitcoin', 9838796.609221794, 3335.469970703125, 11085.25)
('2026-02-23', 'bitcoin', 9765163.284050079, 3363.0, 11167.509765625)
('2026-02-23', 'bitcoin', 9759026.631183332, 3380.800048828125, 11326.509765625)
('2026-02-23', 'bitcoin', 9718962.630296323, None, None)
('2026-02-23', 'bitcoin', 9800346.003033817, 3408.60009765625, 11332.490234375)
('2026-02-23', 'bitcoin', 9856054.84901548, 3360.969970703125, 11154.599609375)
('2026-02-23', 'bitcoin', 9840553.151484529, 3419.43994140625, 11364.599609375)
('2026-02-23', 'bitcoin', 10035954.764445597, 3446.830078125, 11420.98046875)
('2026-02-23', 'bitcoin', 10195205.098488238, 3477.139892578125, 11579.9404296875)
('2026-02-23', 'bitcoin', 10254357.380846838, 3534.219970703125, 11876.259765625)
('2026-02-23', 'bitcoin', 10237593.3071353, 3511.929931640625, 11863.900390625)
('2026-02-23', 'bitcoin', 10184894.127284445, 3488.669921875, 11768.73046875)
('2026-02-23', 'bitcoin', 10169238.650025213, 3483.340087890625, 11713.8701171875)
('2026-02-23', 'bitcoin', 10261685.530263504, 3483.81005859375, 11671.5595703125)
('2026-02-23', 'bitcoin', 10237752.888404036, 3426.919921875, 11478.8798828125)
('2026-02-23', 'bitcoin', 10333070.25718556, 3443.1201171875, 11516.490234375)
('2026-02-23', 'bitcoin', 10189201.725638028, 3435.56005859375, 11484.6904296875)
('2026-02-23', 'bitcoin', 10194461.688819751, 3453.489990234375, 11506.009765625)
('2026-02-23', 'bitcoin', 10158260.693491202, 3465.389892578125, 11548.2802734375)
('2026-02-23', 'bitcoin', 9951646.271657305, 3400.969970703125, 11358.9404296875)
('2026-02-23', 'bitcoin', 9948492.512889242, 3390.679931640625, 11431.349609375)
('2026-02-23', 'bitcoin', 10060469.351465985, 3271.030029296875, 11004.8701171875)
('2026-02-23', 'bitcoin', 9673068.167457229, 3310.110107421875, 11185.58984375)
('2026-02-23', 'bitcoin', 9728251.057537576, 3269.9599609375, 10911.58984375)
('2026-02-23', 'bitcoin', 9723915.967631772, 3310.239990234375, 10957.6103515625)
('2026-02-23', 'bitcoin', 9944472.608696878, 3369.159912109375, 11160.5703125)
('2026-02-23', 'bitcoin', 10139763.924082505, 3443.43994140625, 11590.7802734375)
('2026-02-23', 'bitcoin', 10130020.723922314, 3510.449951171875, 11890.9296875)
('2026-02-23', 'bitcoin', 10509252.859358784, 3509.43994140625, 11895.23046875)
('2026-02-23', 'bitcoin', 10700725.995237181, 3550.5, 11713.7802734375)
('2026-02-23', 'bitcoin', 10847910.013598107, 3545.530029296875, 11553.8603515625)
('2026-02-23', 'bitcoin', 10859533.642673422, 3572.659912109375, 11786.4296875)
('2026-02-23', 'bitcoin', 10959365.064936124, 3537.010009765625, 11709.58984375)
('2026-02-23', 'bitcoin', 11070472.246732509, 3585.14990234375, 11829.2900390625)
('2026-02-23', 'bitcoin', 10783920.730192943, None, None)
('2026-02-23', 'bitcoin', 10949945.97908964, 3609.530029296875, 11899.33984375)
('2026-02-23', 'bitcoin', 10814774.599012492, 3567.7900390625, 11801.599609375)
('2026-02-23', 'bitcoin', 10047260.111235712, 3581.8701171875, 11904.7099609375)
('2026-02-23', 'bitcoin', 9838358.210748602, 3557.5400390625, 11854.9697265625)
('2026-02-23', 'bitcoin', 10223942.881584922, 3577.590087890625, 11880.6298828125)
('2026-02-23', 'bitcoin', 10216224.051870666, 3635.409912109375, 12036.7900390625)
('2026-02-23', 'bitcoin', 10046351.075825775, 3629.64990234375, 12094.400390625)
('2026-02-23', 'bitcoin', 9721344.884648668, None, None)
('2026-02-23', 'bitcoin', 9509774.024195194, 3638.35009765625, 12205.849609375)
('2026-02-23', 'bitcoin', 9369768.130232994, None, None)
('2026-02-23', 'bitcoin', 9432476.848616607, 3662.449951171875, 12355.1103515625)
('2026-02-23', 'bitcoin', 9558930.877185136, 3669.010009765625, 12349.3701171875)

In [102]:
cursor.execute("""
SELECT
     date,
    price_inr AS bitcoin_price,
    GSPC_Close AS sp500,
    IXIC_Close AS nasdaq,
    Price AS oil_price
FROM merged_data
WHERE coin_id = 'bitcoin'
ORDER BY date
LIMIT 10
""")



results = cursor.fetchall()

for r in results:
    print(r)##Multi-join: stock prices, oil prices, and Bitcoin prices for daily comparison

('2026-02-10', 7333947.924555619, 2746.56005859375, 7950.68017578125, 31.56)
('2026-02-13', 6092367.347486159, 4195.990234375, 13738.0, 70.34)
('2026-02-22', 7615008.334491884, 3283.14990234375, 9251.330078125, 57.86)
('2026-02-23', 8341958.303704703, None, None, 61.17)
('2026-02-23', 7922797.740624487, 3257.85009765625, 9092.1904296875, 63.0)
('2026-02-23', 7729282.415455005, 3234.85009765625, 9020.76953125, 63.27)
('2026-02-23', 7314307.147526646, 3246.280029296875, 9071.4697265625, 62.7)
('2026-02-23', 7397416.663356487, 3237.179931640625, 9068.580078125, 59.65)
('2026-02-23', 7386259.847331922, 3253.050048828125, 9129.240234375, 59.56)
('2026-02-23', 7523008.862171689, 3274.699951171875, 9203.4296875, 59.02)

# Streamlit App

In [103]:
!pip install -q streamlit
!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared-linux-amd64
import subprocess
subprocess.Popen(["./cloudflared-linux-amd64", "tunnel", "--url", "http://localhost:8501"])
!nohup /content/cloudflared-linux-amd64 tunnel --url http://localhost:8501 &

--2026-02-23 09:20:10--  https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/cloudflare/cloudflared/releases/download/2026.2.0/cloudflared-linux-amd64 [following]
--2026-02-23 09:20:10--  https://github.com/cloudflare/cloudflared/releases/download/2026.2.0/cloudflared-linux-amd64
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/106867604/f9298ca8-89c8-41fe-a51f-e24cb2059878?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-02-23T10%3A06%3A57Z&rscd=attachment%3B+filename%3Dcloudflared-linux-amd64&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-02-23T09%3A06%3A57Z&ske=2026-02-23T10%3A06%3A57Z&sks=b&skv=2018-11-09&sig=JwcYVbwrA4jfwzHk69HudzPK5ZhGw3nRqxuh5uITgrU%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3MTg0MDIwNiwibmJmIjoxNzcxODM4NDA2LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.f28BHDOgZj47WdKzvRhETmBKr_jRlZ2XIfXhJqDIIMc&response-content-disposition=attachment%3B%20filename%3Dcloudflared-linux-amd64&response-content-type=application%2Foctet-stream [following]
--2026-02-23 09:20:10--  https://release-assets.githubusercontent.com/github-production-release-asset/106867604/f9298ca8-89c8-41fe-a51f-e24cb2059878?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-02-23T10%3A06%3A57Z&rscd=attachment%3B+filename%3Dcloudflared-linux-amd64&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-02-23T09%3A06%3A57Z&ske=2026-02-23T10%3A06%3A57Z&sks=b&skv=2018-11-09&sig=JwcYVbwrA4jfwzHk69HudzPK5ZhGw3nRqxuh5uITgrU%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3MTg0MDIwNiwibmJmIjoxNzcxODM4NDA2LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.f28BHDOgZj47WdKzvRhETmBKr_jRlZ2XIfXhJqDIIMc&response-content-disposition=attachment%3B%20filename%3Dcloudflared-linux-amd64&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 39289207 (37M) [application/octet-stream]
Saving to: ‘cloudflared-linux-amd64.1’

cloudflared-linux-a 100%[===================>]  37.47M   179MB/s    in 0.2s

2026-02-23 09:20:10 (179 MB/s) - ‘cloudflared-linux-amd64.1’ saved [39289207/39289207]

nohup: appending output to 'nohup.out'

In [104]:
!pip install streamlit-option-menu

Requirement already satisfied: streamlit-option-menu in /usr/local/lib/python3.12/dist-packages (0.4.0)
Requirement already satisfied: streamlit>=1.36 in /usr/local/lib/python3.12/dist-packages (from streamlit-option-menu) (1.54.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (1.9.0)
Requirement already satisfied: cachetools<7,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (8.3.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (3.1.46)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (26.0)
Requirement already satisfied: pandas<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (11.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (0.9.1)
Requirement already satisfied: protobuf<7,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (0.10.2)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (6.5.1)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (2.16.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.36->streamlit-option-menu) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (2026.1.4)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.36->streamlit-option-menu) (5.0.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (0.30.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (1.17.0)

In [133]:
%%writefile project.py

Overwriting project.py

In [134]:
%%writefile project.py

import streamlit as st
import pandas as pd
import sqlite3
from streamlit_option_menu import option_menu

# DB connection
conn = sqlite3.connect("merged_data.db")

# Page config
st.set_page_config(layout='wide')

# Menu
selected = option_menu(
    menu_title=None,
    options=["Home", "Data Exploration", "SQL Query Runner", "Top 5 Crypto Analysis"],
    orientation="horizontal"
)

# Home Page
if selected == "Home":
    st.title("Cross-Market Analysis: Crypto, Oil & Stocks with python & SQL ")

Overwriting project.py

In [135]:
%%writefile project.py


import streamlit as st
import pandas as pd
import sqlite3
from streamlit_option_menu import option_menu

# MENU
selected = option_menu(
    menu_title=None,
    options=["Home", "Data Exploration", "SQL Query Runner", "Top 5 Crypto Analysis"],
    orientation="horizontal"
)

if selected == "Home":
    st.title("Cross Market Analysis")

elif selected == "Data Exploration":
    st.title("Cross Market Overview")

    # DB connection
    conn = sqlite3.connect("merged_data.db")

    # Load data
    df = pd.read_sql_query("SELECT * FROM merged_data", conn)

    # Convert date
    df['date'] = pd.to_datetime(df['date'])

    # DATE FILTER
    start_date = st.date_input("Start Date", df['date'].min(), key="start")
    end_date = st.date_input("End Date", df['date'].max(), key="end")

    # Filter data
    filtered_df = df[
        (df['date'] >= pd.to_datetime(start_date)) &
        (df['date'] <= pd.to_datetime(end_date))
    ]

    # SELECT BOX
    option = st.selectbox(
        "Select Analysis",
        [
            "Bitcoin Avg Price",
            "Oil Avg Price",
            "S&P 500 Avg",
            "NIFTY Avg"
        ],
        key="analysis"
    )

    # CALCULATIONS
    if option == "Bitcoin Avg Price":
        result = filtered_df[filtered_df['coin_id'] == 'bitcoin']['price_inr'].mean()
        st.metric("Bitcoin Average Price", round(result, 2))

    elif option == "Oil Avg Price":
        result = filtered_df['Price'].mean()
        st.metric("Oil Average Price", round(result, 2))

    elif option == "S&P 500 Avg":
        result = filtered_df['GSPC_Close'].mean()
        st.metric("S&P 500 Avg Close", round(result, 2))

    elif option == "NIFTY Avg":
        result = filtered_df['NSEI_Close'].mean()
        st.metric("NIFTY Avg Close", round(result, 2))

    # SHOW DATA
    st.subheader("Filtered Data")
    st.dataframe(filtered_df)

Overwriting project.py

In [136]:
%%writefile project.py


import streamlit as st
import pandas as pd
import sqlite3
from streamlit_option_menu import option_menu

# MENU
selected = option_menu(
    menu_title=None,
    options=["Home", "Data Exploration", "SQL Query Runner", "Top 5 Crypto Analysis"],
    orientation="horizontal"
)




if selected == "Home":
    st.title("Cross Market Analysis")

elif selected == "Data Exploration":
    st.title("Cross Market Overview")



elif selected == "SQL Query Runner":
    st.title("SQL Query Runner")

    conn = sqlite3.connect("Cryptocurrencies.db")



    queries = {

    # ------------------ CRYPTOCURRENCIES ------------------
    "Top 3 Cryptos by Market Cap": {
        "query": """SELECT * FROM Cryptocurrencies
                    ORDER BY market_cap_rank ASC
                    LIMIT 3""",
        "db": "Cryptocurrencies.db"
    },

    "Circulating Supply > 90%": {
        "query": """SELECT id,symbol,name,circulating_supply,total_supply
                    FROM Cryptocurrencies
                    WHERE circulating_supply > 0.9 * total_supply""",
        "db": "Cryptocurrencies.db"
    },

    "Coins Near ATH": {
        "query": """SELECT name,symbol,current_price,ath
                    FROM Cryptocurrencies
                    WHERE current_price >= 0.9 * ath""",
        "db": "Cryptocurrencies.db"
    },

    "Avg Market Rank (>1B Volume)": {
        "query": """SELECT AVG(market_cap_rank)
                    FROM Cryptocurrencies
                    WHERE total_volume > 1000000000""",
        "db": "Cryptocurrencies.db"
    },

    "Most Recent Coin": {
        "query": """SELECT name,symbol,date
                    FROM Cryptocurrencies
                    ORDER BY date DESC
                    LIMIT 1""",
        "db": "Cryptocurrencies.db"
    },

    # ------------------ CRYPTO PRICES ------------------
    "Bitcoin Max Price": {
        "query": """SELECT coin_id,date,MAX(price_inr)
                    FROM Crypto_prices
                    WHERE coin_id='bitcoin'""",
        "db": "Crypto_prices.db"
    },

    "Bitcoin Feb 2025 Prices": {
        "query": """SELECT coin_id,date,price_inr
                    FROM Crypto_prices
                    WHERE coin_id='bitcoin'
                    AND date BETWEEN '2025-02-01' AND '2025-02-28'""",
        "db": "Crypto_prices.db"
    },

    "Highest Avg Price Coin": {
        "query": """SELECT coin_id,AVG(price_inr)
                    FROM Crypto_prices
                    GROUP BY coin_id
                    ORDER BY AVG(price_inr) DESC
                    LIMIT 1""",
        "db": "Crypto_prices.db"
    },

    "Bitcoin Avg Feb 2025": {
        "query": """SELECT AVG(price_inr)
                    FROM Crypto_prices
                    WHERE coin_id='bitcoin'
                    AND date LIKE '2025-02-%'""",
        "db": "Crypto_prices.db"
    },

    "Bitcoin Avg Feb 2026": {
        "query": """SELECT AVG(price_inr)
                    FROM Crypto_prices
                    WHERE coin_id='bitcoin'
                    AND date LIKE '2026-02-%'""",
        "db": "Crypto_prices.db"
    },

    # ------------------ OIL ------------------
    "Highest Oil Price (5Y)": {
        "query": """SELECT date,price_inr
                    FROM Oil_prices
                    WHERE date >= date('now','-5 years')
                    ORDER BY price_inr DESC
                    LIMIT 1""",
        "db": "Oil_prices.db"
    },

    "Oil Avg Per Year": {
        "query": """SELECT substr(date,1,4) AS year,AVG(price_inr)
                    FROM Oil_prices
                    GROUP BY year""",
        "db": "Oil_prices.db"
    },

    "Oil COVID Crash": {
        "query": """SELECT date,price_inr
                    FROM Oil_prices
                    WHERE date BETWEEN '2020-03-01' AND '2020-04-30'""",
        "db": "Oil_prices.db"
    },

    "Lowest Oil (10Y)": {
        "query": """SELECT MIN(price_inr)
                    FROM Oil_prices
                    WHERE date >= date('now','-10 years')""",
        "db": "Oil_prices.db"
    },

    "Oil Volatility": {
        "query": """SELECT strftime('%Y',date) AS year,
                           MAX(price_inr)-MIN(price_inr) AS volatility
                    FROM Oil_prices
                    GROUP BY year""",
        "db": "Oil_prices.db"
    },

    # ------------------ STOCKS ------------------
    "NSEI Stock Data": {
        "query": """SELECT date,open,high,low,close,volume
                    FROM stocks
                    WHERE ticker='^NSEI'""",
        "db": "stocks.db"
    },

    "NASDAQ Highest Close": {
        "query": """SELECT date,ticker,close
                    FROM stocks
                    WHERE ticker='^IXIC'
                    ORDER BY close DESC
                    LIMIT 1""",
        "db": "stocks.db"
    },

    "S&P500 Volatility Days": {
        "query": """SELECT date,high,low,(high-low) AS diff
                    FROM stocks
                    WHERE ticker='^GSPC'
                    ORDER BY diff DESC
                    LIMIT 5""",
        "db": "stocks.db"
    },

    "Monthly Avg Stocks": {
        "query": """SELECT ticker,strftime('%Y-%m',date) AS month,
                           AVG(close)
                    FROM stocks
                    GROUP BY ticker,month""",
        "db": "stocks.db"
    },

    "NSEI Volume 2024": {
        "query": """SELECT AVG(volume)
                    FROM stocks
                    WHERE ticker='^NSEI'
                    AND date BETWEEN '2024-01-01' AND '2024-12-31'""",
        "db": "stocks.db"
    },

    # ------------------ MERGED DATA ------------------
    "Bitcoin vs Oil 2026": {
        "query": """SELECT 'Bitcoin' AS asset,AVG(price_inr)
                    FROM merged_data
                    WHERE coin_id='bitcoin'
                    UNION ALL
                    SELECT 'Oil',AVG(price)
                    FROM merged_data""",
        "db": "merged_data.db"
    },

    "Bitcoin vs S&P500": {
        "query": """SELECT date,price_inr,GSPC_Close
                    FROM merged_data
                    WHERE coin_id='bitcoin'""",
        "db": "merged_data.db"
    },

    "Ethereum vs NASDAQ": {
        "query": """SELECT date,price_inr,IXIC_Close
                    FROM merged_data
                    WHERE coin_id='ethereum'""",
        "db": "merged_data.db"
    },

    "Bitcoin Oil Correlation Data": {
        "query": """SELECT date,price_inr AS bitcoin_price,Price AS oil_price
                    FROM merged_data
                    WHERE coin_id='bitcoin'""",
        "db": "merged_data.db"
    },

    "Top 3 Coins vs Market": {
        "query": """SELECT date,coin_id,price_inr,GSPC_Close,IXIC_Close
                    FROM merged_data
                    WHERE coin_id IN ('bitcoin','ethereum','tether')
                    LIMIT 10""",
        "db": "merged_data.db"
    },

    "Stock vs Oil": {
        "query": """SELECT date,GSPC_Close,Price
                    FROM merged_data
                    LIMIT 10""",
        "db": "merged_data.db"
    },

    "Bitcoin Full Market View": {
        "query": """SELECT date,price_inr,GSPC_Close,IXIC_Close,Price
                    FROM merged_data
                    WHERE coin_id='bitcoin'
                    LIMIT 10""",
        "db": "merged_data.db"
    }
}

    #  ALL QUERIES
    selected_query = st.selectbox("Select SQL Query", list(queries.keys()))

    st.code(queries[selected_query]["query"], language="sql")

    if st.button("Run Query"):
      query = queries[selected_query]["query"]
      db = queries[selected_query]["db"]

      conn = sqlite3.connect(db)

      result = pd.read_sql_query(query, conn)
      st.dataframe(result)

Overwriting project.py

In [137]:
%%writefile project.py


import streamlit as st
import pandas as pd
import sqlite3
from streamlit_option_menu import option_menu

# MENU
selected = option_menu(
    menu_title=None,
    options=["Home", "Data Exploration", "SQL Query Runner", "Top 5 Crypto Analysis"],
    orientation="horizontal"
)

if selected == "Home":
    st.title("Cross Market Analysis")

elif selected == "Data Exploration":
    st.title("Cross Market Overview")

elif selected == "SQL Query Runner":
    st.title("SQL Query Runner")

elif selected == "Top 5 Crypto Analysis":
    st.title("Top 5 Crypto Analysis")

    import sqlite3
    import pandas as pd

    conn = sqlite3.connect("Crypto_prices.db")

    # ---- Get Top 3 coins ----
    top_crypto_query = """
        SELECT DISTINCT coin_id
        FROM Crypto_prices
        LIMIT 3
    """
    top_crypto_df = pd.read_sql_query(top_crypto_query, conn)

    crypto_list = top_crypto_df["coin_id"].tolist()

    # ---- Select Crypto ----
    selected_crypto = st.selectbox("Select Cryptocurrency", crypto_list)

    # ---- Load Data for selected crypto ----
    query = f"""
        SELECT date, price_inr
        FROM Crypto_prices
        WHERE coin_id = '{selected_crypto}'
    """
    df = pd.read_sql_query(query, conn)

    # ---- Convert Date ----
    df["date"] = pd.to_datetime(df["date"])

    # ---- Date Filter ----
    start_date = st.date_input("Start Date", df["date"].min())
    end_date = st.date_input("End Date", df["date"].max())

    filtered_df = df[(df["date"] >= pd.to_datetime(start_date)) &
                     (df["date"] <= pd.to_datetime(end_date))]

    # ---- Line Chart (Optional) ----
    st.subheader("Daily Price Trend")
    st.line_chart(filtered_df.set_index("date")["price_inr"])

    # ---- Table ----
    st.subheader("Daily Price Data")
    st.dataframe(filtered_df)

    conn.close()

Overwriting project.py

In [106]:
!ls

cloudflared-linux-amd64    Crypto_prices.db  nohup.out	    sample_data
cloudflared-linux-amd64.1  logs.txt	     Oil_prices.db  stocks.db
Cryptocurrencies.db	   merged_data.db    project.py

In [128]:
!streamlit run /content/project.py &>/content/logs.txt &

In [108]:
!grep -o 'https://.*\.trycloudflare.com' nohup.out | head -n 1 | xargs -I {} echo "Your tunnel url {}"

Your tunnel url https://beginning-electrical-drove-larger.trycloudflare.com