<a href="https://colab.research.google.com/github/vaidegiarch/my-projects/blob/cross-market-analysis-project-1/project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install requests

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)

In [ ]:
import requests
import time

In [ ]:

base_url="https://api.coingecko.com/api/v3/coins/markets"
all_records=[]

for page in range(1,6):#shows data 1 to 5 page

  url=(f"{base_url}?vs_currency=inr&per_page=250&order=market_cap_desc&page={page}&sparkline=False")
  response=requests.get(url)#gets data from url

  if response.status_code==200:
    data=response.json()
    all_records.extend(data)
    print (f"page{page} fetched successfully")

  else:
    print (f"failed to fetch page{page}")

  time.sleep(30)

print ("total records collected:",len (all_records))

page1 fetched successfully
page2 fetched successfully
page3 fetched successfully
page4 fetched successfully
page5 fetched successfully
total records collected: 1250

In [ ]:
len(all_records)

1250

In [ ]:
data=all_records

records=[]

for i in data:
  records.append(dict(id=i["id"],
                     symbol=i["symbol"],
                     name=i["name"],
                     current_price=i["current_price"],
                     market_cap=i["market_cap"],
                     market_cap_rank=i["market_cap_rank"],
                     total_volume=i["total_volume"],
                     circulating_supply=i["circulating_supply"],
                     total_supply=i["total_supply"],
                     ath=i["ath"],
                     atl=i["atl"],
                     last_updated=i["last_updated"]))

In [ ]:
import pandas as pd
Cryptocurrencies_df=pd.DataFrame(records)
Cryptocurrencies_df

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,6.878855e+06,137593653306772,1,5.024783e+12,2.000304e+07,2.000304e+07,11187013.00,3993.420000,2026-03-17T18:31:10.978Z
1,ethereum,eth,Ethereum,2.156630e+05,26026523841219,2,2.773542e+12,1.206919e+08,1.206919e+08,431946.00,28.130000,2026-03-17T18:31:10.985Z
2,tether,usdt,Tether,9.241000e+01,17010782833133,3,8.500853e+12,1.840709e+11,1.895378e+11,105.52,36.860000,2026-03-17T18:31:19.474Z
3,ripple,xrp,XRP,1.412000e+02,8645814013079,4,4.497152e+11,6.122783e+10,9.998570e+10,313.99,0.159343,2026-03-17T18:31:17.945Z
4,binancecoin,bnb,BNB,6.215000e+04,8474126353407,5,1.222935e+11,1.363578e+08,1.363578e+08,121422.00,2.580000,2026-03-17T18:31:10.876Z
...,...,...,...,...,...,...,...,...,...,...,...,...
1245,tutorial,tut,Tutorial,1.029000e+00,859763677,1246,2.545654e+08,8.357810e+08,8.357810e+08,14.95,0.025182,2026-03-17T18:33:12.299Z
1246,chainbase,c,Chainbase,5.360000e+00,858712436,1245,1.001865e+09,1.600000e+08,1.000000e+09,44.82,4.230000,2026-03-17T18:33:12.303Z
1247,dialectic-eth-vault,deth,Dialectic ETH Vault,2.171370e+05,858697057,1247,4.081440e+03,3.961882e+03,3.961882e+03,422188.00,161106.000000,2026-03-17T18:33:12.274Z
1248,seth,seth,sETH,7.407400e+04,857770218,1248,1.993040e+03,1.157991e+04,1.157991e+04,423415.00,0.945060,2026-03-17T18:33:12.252Z
1249,wolf-2,wolf,WOLF,8.571000e-01,857072097,1249,3.305823e+06,9.999790e+08,9.999790e+08,4.19,0.247676,2026-03-17T18:33:12.264Z

In [ ]:
Cryptocurrencies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1250 entries, 0 to 1249
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  1250 non-null   object
 1   symbol              1250 non-null   object
 2   name                1250 non-null   object
 3   current_price       1250 non-null   float64
 4   market_cap          1250 non-null   int64
 5   market_cap_rank     1250 non-null   int64
 6   total_volume        1232 non-null   float64
 7   circulating_supply  1250 non-null   float64
 8   total_supply        1249 non-null   float64
 9   ath                 1250 non-null   float64
 10  atl                 1250 non-null   float64
 11  last_updated        1250 non-null   object
dtypes: float64(6), int64(2), object(4)
memory usage: 117.3+ KB

In [ ]:
Cryptocurrencies_df["last_updated"]=pd.to_datetime(Cryptocurrencies_df["last_updated"]).dt.date
Cryptocurrencies_df["last_updated"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1250 entries, 0 to 1249
Series name: last_updated
Non-Null Count  Dtype
--------------  -----
1250 non-null   object
dtypes: object(1)
memory usage: 9.9+ KB

In [ ]:
Cryptocurrencies_df.rename(columns={"last_updated": "date"}, inplace=True)

In [ ]:
Cryptocurrencies_df # 1.data frame of all cryptocoins

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,date
0,bitcoin,btc,Bitcoin,6.878855e+06,137593653306772,1,5.024783e+12,2.000304e+07,2.000304e+07,11187013.00,3993.420000,2026-03-17
1,ethereum,eth,Ethereum,2.156630e+05,26026523841219,2,2.773542e+12,1.206919e+08,1.206919e+08,431946.00,28.130000,2026-03-17
2,tether,usdt,Tether,9.241000e+01,17010782833133,3,8.500853e+12,1.840709e+11,1.895378e+11,105.52,36.860000,2026-03-17
3,ripple,xrp,XRP,1.412000e+02,8645814013079,4,4.497152e+11,6.122783e+10,9.998570e+10,313.99,0.159343,2026-03-17
4,binancecoin,bnb,BNB,6.215000e+04,8474126353407,5,1.222935e+11,1.363578e+08,1.363578e+08,121422.00,2.580000,2026-03-17
...,...,...,...,...,...,...,...,...,...,...,...,...
1245,tutorial,tut,Tutorial,1.029000e+00,859763677,1246,2.545654e+08,8.357810e+08,8.357810e+08,14.95,0.025182,2026-03-17
1246,chainbase,c,Chainbase,5.360000e+00,858712436,1245,1.001865e+09,1.600000e+08,1.000000e+09,44.82,4.230000,2026-03-17
1247,dialectic-eth-vault,deth,Dialectic ETH Vault,2.171370e+05,858697057,1247,4.081440e+03,3.961882e+03,3.961882e+03,422188.00,161106.000000,2026-03-17
1248,seth,seth,sETH,7.407400e+04,857770218,1248,1.993040e+03,1.157991e+04,1.157991e+04,423415.00,0.945060,2026-03-17
1249,wolf-2,wolf,WOLF,8.571000e-01,857072097,1249,3.305823e+06,9.999790e+08,9.999790e+08,4.19,0.247676,2026-03-17

historical price for three coins

In [ ]:
import requests
from datetime import datetime
import time

coin_ids = ["bitcoin", "ethereum", "tether"]
all_price_records = []  # ✅ must be empty

for coin_id in coin_ids:
    url = f"https://api.coingecko.com/api/v3/coins/{coin_id}/market_chart?vs_currency=inr&days=365"

    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()
        # Loop through daily prices
        for price_entry in data['prices']:
            timestamp, price = price_entry
            date = datetime.utcfromtimestamp(timestamp / 1000).date()

            # Add to our list
            all_price_records.append({
                "coin_id": coin_id,
                "date": date,
                "price_inr": price
            })
        print(f"{coin_id} prices fetched")
    else:
        print(f"Failed to fetch {coin_id}")

    time.sleep(30)  # polite delay to avoid API rate limits

/tmp/ipykernel_3626/90423288.py:18: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
  date = datetime.utcfromtimestamp(timestamp / 1000).date()

bitcoin prices fetched
ethereum prices fetched
tether prices fetched

In [ ]:
Crypto_prices_df=pd.DataFrame(all_price_records)

In [ ]:
Crypto_prices_df["coin_id"].value_counts()

coin_id
bitcoin     366
ethereum    366
tether      366
Name: count, dtype: int64

In [ ]:
Crypto_prices_df  # 2. data frame of top 3 coins -historical prices for 1 year (each coin)

      coin_id        date     price_inr
0     bitcoin  2025-03-18  7.307625e+06
1     bitcoin  2025-03-19  7.166131e+06
2     bitcoin  2025-03-20  7.495414e+06
3     bitcoin  2025-03-21  7.275141e+06
4     bitcoin  2025-03-22  7.224001e+06
...       ...         ...           ...
1093   tether  2026-03-14  9.261318e+01
1094   tether  2026-03-15  9.259796e+01
1095   tether  2026-03-16  9.257168e+01
1096   tether  2026-03-17  9.226888e+01
1097   tether  2026-03-17  9.240820e+01

[1098 rows x 3 columns]

oil prices

In [ ]:
import pandas as pd
oil_df = pd.read_csv("https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv")

oil_df

oil_df["Date"]=pd.to_datetime(oil_df["Date"])


Oil_prices_df=oil_df[
    (oil_df["Date"]>="2020-01-01")&
    (oil_df["Date"]<="2026-01-31")]

In [ ]:
Oil_prices_df

            Date  Price
8569  2020-01-02  61.17
8570  2020-01-03  63.00
8571  2020-01-06  63.27
8572  2020-01-07  62.70
8573  2020-01-08  59.65
...          ...    ...
10084 2026-01-26  60.46
10085 2026-01-27  62.04
10086 2026-01-28  62.75
10087 2026-01-29  64.77
10088 2026-01-30  64.50

[1520 rows x 2 columns]

In [ ]:
Oil_prices_df.reset_index(drop=True, inplace=True)
Oil_prices_df # 3.data frame of oil prices from Jan 2020 – Jan 2026.

           Date  Price
0    2020-01-02  61.17
1    2020-01-03  63.00
2    2020-01-06  63.27
3    2020-01-07  62.70
4    2020-01-08  59.65
...         ...    ...
1515 2026-01-26  60.46
1516 2026-01-27  62.04
1517 2026-01-28  62.75
1518 2026-01-29  64.77
1519 2026-01-30  64.50

[1520 rows x 2 columns]

Stock Prices (Yahoo Finance API)

In [ ]:
import yfinance as yf
import pandas as pd

tickers = ["^GSPC", "^IXIC", "^NSEI"]
start_date = "2020-01-01"
end_date = "2026-01-12"

stocks_df = yf.download(tickers, start=start_date, end=end_date, group_by="ticker")
stocks_df.head()

/tmp/ipykernel_3626/2364413695.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  stocks_df = yf.download(tickers, start=start_date, end=end_date, group_by="ticker")
[*********************100%***********************]  3 of 3 completed

Ticker             ^NSEI                                                      \
Price               Open          High           Low         Close    Volume
Date
2020-01-01  12202.150391  12222.200195  12165.299805  12182.500000  304100.0
2020-01-02  12198.549805  12289.900391  12195.250000  12282.200195  407700.0
2020-01-03  12261.099609  12265.599609  12191.349609  12226.650391  428800.0
2020-01-06  12170.599609  12179.099609  11974.200195  11993.049805  396500.0
2020-01-07  12079.099609  12152.150391  12005.349609  12052.950195  447800.0

Ticker            ^IXIC                                                       \
Price              Open         High          Low        Close        Volume
Date
2020-01-01          NaN          NaN          NaN          NaN           NaN
2020-01-02  9039.459961  9093.429688  9010.889648  9092.190430  2.862700e+09
2020-01-03  8976.429688  9065.759766  8976.429688  9020.769531  2.586520e+09
2020-01-06  8943.500000  9072.410156  8943.500000  9071.469727  2.810450e+09
2020-01-07  9076.639648  9091.929688  9042.549805  9068.580078  2.381740e+09

Ticker            ^GSPC
Price              Open         High          Low        Close        Volume
Date
2020-01-01          NaN          NaN          NaN          NaN           NaN
2020-01-02  3244.669922  3258.139893  3235.530029  3257.850098  3.459930e+09
2020-01-03  3226.360107  3246.149902  3222.340088  3234.850098  3.484700e+09
2020-01-06  3217.550049  3246.840088  3214.639893  3246.280029  3.702460e+09
2020-01-07  3241.860107  3244.909912  3232.429932  3237.179932  3.435910e+09

In [ ]:
stock_prices_df=stocks_df[["^GSPC", "^IXIC", "^NSEI"]].reset_index().dropna()#dropped null values using list
stock_prices_df # 4 data frame --of yahoo finace stock prices

Ticker       Date        ^GSPC                                         \
Price                     Open         High          Low        Close
1      2020-01-02  3244.669922  3258.139893  3235.530029  3257.850098
2      2020-01-03  3226.360107  3246.149902  3222.340088  3234.850098
3      2020-01-06  3217.550049  3246.840088  3214.639893  3246.280029
4      2020-01-07  3241.860107  3244.909912  3232.429932  3237.179932
5      2020-01-08  3238.590088  3267.070068  3236.669922  3253.050049
...           ...          ...          ...          ...          ...
1558   2026-01-05  6892.189941  6920.379883  6891.560059  6902.049805
1559   2026-01-06  6908.029785  6948.689941  6904.020020  6944.819824
1560   2026-01-07  6945.069824  6965.689941  6919.189941  6920.930176
1561   2026-01-08  6914.109863  6931.279785  6899.330078  6921.459961
1562   2026-01-09  6927.830078  6978.359863  6917.640137  6966.279785

Ticker                       ^IXIC                                            \
Price         Volume          Open          High           Low         Close
1       3.459930e+09   9039.459961   9093.429688   9010.889648   9092.190430
2       3.484700e+09   8976.429688   9065.759766   8976.429688   9020.769531
3       3.702460e+09   8943.500000   9072.410156   8943.500000   9071.469727
4       3.435910e+09   9076.639648   9091.929688   9042.549805   9068.580078
5       3.726840e+09   9068.030273   9168.889648   9059.379883   9129.240234
...              ...           ...           ...           ...           ...
1558    5.771930e+09  23449.669922  23476.509766  23332.230469  23395.820312
1559    5.509680e+09  23446.960938  23559.150391  23389.570312  23547.169922
1560    5.214480e+09  23544.890625  23723.369141  23504.210938  23584.279297
1561    5.333200e+09  23548.880859  23558.169922  23353.460938  23480.019531
1562    5.163900e+09  23496.210938  23721.150391  23426.480469  23671.349609

Ticker                       ^NSEI                                            \
Price         Volume          Open          High           Low         Close
1       2.862700e+09  12198.549805  12289.900391  12195.250000  12282.200195
2       2.586520e+09  12261.099609  12265.599609  12191.349609  12226.650391
3       2.810450e+09  12170.599609  12179.099609  11974.200195  11993.049805
4       2.381740e+09  12079.099609  12152.150391  12005.349609  12052.950195
5       2.472620e+09  11939.099609  12044.950195  11929.599609  12025.349609
...              ...           ...           ...           ...           ...
1558    8.737320e+09  26333.699219  26373.199219  26210.050781  26250.300781
1559    9.012640e+09  26189.699219  26273.949219  26124.750000  26178.699219
1560    8.396920e+09  26143.099609  26187.150391  26067.900391  26140.750000
1561    7.723140e+09  26106.500000  26133.199219  25858.449219  25876.849609
1562    8.124420e+09  25840.400391  25940.599609  25623.000000  25683.300781

Ticker
Price     Volume
1       407700.0
2       428800.0
3       396500.0
4       447800.0
5       446000.0
...          ...
1558    338800.0
1559    383000.0
1560    338200.0
1561    328500.0
1562    348800.0

[1444 rows x 16 columns]

sql queries

In [ ]:
pip install pymysql

Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.3/45.3 kB 1.7 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2

In [ ]:
import sqlite3
conn = sqlite3.connect("Cryptocurrencies.db")
cursor = conn.cursor()
print("SQLite connected")

SQLite connected

In [ ]:
# Pushing dataframe into sql

Cryptocurrencies_df.to_sql("Cryptocurrencies", conn, if_exists="replace", index=False)

1250

In [ ]:
print(Cryptocurrencies_df.columns)

Index(['id', 'symbol', 'name', 'current_price', 'market_cap',
       'market_cap_rank', 'total_volume', 'circulating_supply', 'total_supply',
       'ath', 'atl', 'date'],
      dtype='object')

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS Cryptocurrencies (
    id VARCHAR(50) PRIMARY KEY,
    symbol VARCHAR(10),
    name VARCHAR(100),
    current_price DECIMAL(18, 6),
    market_cap BIGINT,
    market_cap_rank INT,
    total_volume BIGINT,
    circulating_supply DECIMAL(20, 6),
    total_supply DECIMAL(20, 6),
    ath DECIMAL(18, 6),
    atl DECIMAL(18, 6),
    date DATE)""")

In [ ]:
sql = """
INSERT or REPLACE INTO Cryptocurrencies (id, symbol, name, current_price,market_cap,
       market_cap_rank, total_volume, circulating_supply, total_supply,
       ath, atl, date)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )
"""

In [ ]:
data = Cryptocurrencies_df[["id","symbol","name","current_price", 'market_cap',
       'market_cap_rank', 'total_volume', 'circulating_supply', 'total_supply',
       'ath', 'atl', 'date']].values.tolist()

In [ ]:
cursor.executemany(sql, data)
conn.commit()

In [ ]:
cursor.execute("SELECT * FROM Cryptocurrencies LIMIT 10")
rows = cursor.fetchall()

for row in rows:
    print(row)

('bitcoin', 'btc', 'Bitcoin', 6878855.0, 137593653306772, 1, 5024783289501.0, 20003043.0, 20003043.0, 11187013.0, 3993.42, '2026-03-17')
('ethereum', 'eth', 'Ethereum', 215663.0, 26026523841219, 2, 2773542000824.0, 120691856.225145, 120691856.225145, 431946.0, 28.13, '2026-03-17')
('tether', 'usdt', 'Tether', 92.41, 17010782833133, 3, 8500853312739.0, 184070904426.6213, 189537843241.5662, 105.52, 36.86, '2026-03-17')
('ripple', 'xrp', 'XRP', 141.2, 8645814013079, 4, 449715229358.0, 61227832454.0, 99985701766.0, 313.99, 0.159343, '2026-03-17')
('binancecoin', 'bnb', 'BNB', 62150.0, 8474126353407, 5, 122293470237.0, 136357838.75, 136357838.75, 121422.0, 2.58, '2026-03-17')
('usd-coin', 'usdc', 'USDC', 92.4, 7350073178497, 6, 783948019037.0, 79549317200.16331, 79552312452.01044, 92.72, 65.31, '2026-03-17')
('solana', 'sol', 'Solana', 8782.73, 5019694616349, 7, 442466649413.0, 571484906.9407045, 571484912.1745219, 25396.0, 38.03, '2026-03-17')
('tron', 'trx', 'TRON', 28.17, 2669479166577, 8, 56872786463.0, 94750568487.5679, 94750574572.95, 36.53, 0.117589, '2026-03-17')
('figure-heloc', 'figr_heloc', 'Figure Heloc', 95.37, 1510981900672, 9, 4197732713.0, 15843541913.347, 15843541913.347, 96.67, 13.78, '2026-03-17')
('dogecoin', 'doge', 'Dogecoin', 9.29, 1425494484784, 10, 146622854361.0, 153449466383.7052, 153449476383.7052, 53.62, 0.00552883, '2026-03-17')

In [ ]:
cursor.execute("""SELECT * from Cryptocurrencies
order by market_cap_rank asc
limit 3""")

rows = cursor.fetchall()

for row in rows:
    print(row)    # Find the top 3 cryptocurrencies by market cap.

('bitcoin', 'btc', 'Bitcoin', 6878855.0, 137593653306772, 1, 5024783289501.0, 20003043.0, 20003043.0, 11187013.0, 3993.42, '2026-03-17')
('bitcoin', 'btc', 'Bitcoin', 6878855.0, 137593653306772, 1, 5024783289501.0, 20003043.0, 20003043.0, 11187013.0, 3993.42, '2026-03-17')
('ethereum', 'eth', 'Ethereum', 215663.0, 26026523841219, 2, 2773542000824.0, 120691856.225145, 120691856.225145, 431946.0, 28.13, '2026-03-17')

In [ ]:
cursor.execute("""SELECT id,symbol,name,circulating_supply, total_supply
from Cryptocurrencies
where circulating_supply > 0.9 * total_supply""")

rows = cursor.fetchall()

for row in rows:
    print(row)  #List all coins where circulating supply exceeds 90% of total supply.

('bitcoin', 'btc', 'Bitcoin', 20003043.0, 20003043.0)
('ethereum', 'eth', 'Ethereum', 120691856.225145, 120691856.225145)
('tether', 'usdt', 'Tether', 184070904426.6213, 189537843241.5662)
('binancecoin', 'bnb', 'BNB', 136357838.75, 136357838.75)
('usd-coin', 'usdc', 'USDC', 79549317200.16331, 79552312452.01044)
('solana', 'sol', 'Solana', 571484906.9407045, 571484912.1745219)
('tron', 'trx', 'TRON', 94750568487.5679, 94750574572.95)
('figure-heloc', 'figr_heloc', 'Figure Heloc', 15843541913.347, 15843541913.347)
('dogecoin', 'doge', 'Dogecoin', 153449466383.7052, 153449476383.7052)
('usds', 'usds', 'USDS', 11241503489.59847, 11241503489.59847)
('bitcoin-cash', 'bch', 'Bitcoin Cash', 20008606.14665078, 20008874.89665078)
('leo-token', 'leo', 'LEO Token', 921095396.9, 985239504.0)
('monero', 'xmr', 'Monero', 18446744.07370955, 18446744.07370955)
('ethena-usde', 'usde', 'Ethena USDe', 5921319338.987329, 5921319338.987329)
('canton-network', 'cc', 'Canton', 38062187829.30478, 38062187829.30478)
('zcash', 'zec', 'Zcash', 16607856.4155448, 16608148.6030448)
('usd1-wlfi', 'usd1', 'USD1', 4525900963.92404, 4525900963.92404)
('litecoin', 'ltc', 'Litecoin', 76952601.98347135, 76959758.23347135)
('avalanche-2', 'avax', 'Avalanche', 431771961.1772119, 463441061.1772119)
('dai', 'dai', 'Dai', 4301947370.116359, 4301947370.116359)
('paypal-usd', 'pyusd', 'PayPal USD', 4090361008.249145, 4090361008.249145)
('shiba-inu', 'shib', 'Shiba Inu', 589243651290999.5, 589500199349037.1)
('polkadot', 'dot', 'Polkadot', 1673554555.120947, 1673554555.120947)
('pax-gold', 'paxg', 'PAX Gold', 501150.394, 501150.394)
('hashnote-usyc', 'usyc', 'Circle USYC', 2154018487.518962, 2154018487.518962)
('blackrock-usd-institutional-digital-liquidity-fund', 'buidl', 'BlackRock USD Institutional Digital Liquidity Fund', 2001290941.310449, 2001290941.310449)
('okb', 'okb', 'OKB', 21000000.0, 21000000.0)
('near', 'near', 'NEAR Protocol', 1290446876.0, 1290446891.0)
('aave', 'aave', 'Aave', 15183429.873537349, 16000000.0)
('global-dollar', 'usdg', 'Global Dollar', 1761618666.410992, 1761618666.410992)
('falcon-finance', 'usdf', 'Falcon USD', 1753083020.374202, 1753083020.374202)
('sky', 'sky', 'Sky', 23072957351.22428, 23462665147.36596)
('pepe', 'pepe', 'Pepe', 420690000000000.0, 420690000000000.0)
('ripple-usd', 'rlusd', 'Ripple USD', 1549571407.127284, 1549571407.127284)
('htx-dao', 'htx', 'HTX DAO', 916533066327098.8, 916533066327098.8)
('internet-computer', 'icp', 'Internet Computer', 550513737.949494, 550514500.8483882)
('ethereum-classic', 'etc', 'Ethereum Classic', 155937478.0461943, 155937478.0461943)
('bfusd', 'bfusd', 'BFUSD', 1320000000.0, 1320000000.0)
('ondo-us-dollar-yield', 'usdy', 'Ondo US Dollar Yield', 1170556747.325068, 1170556747.325068)
('gatechain-token', 'gt', 'Gate', 115180573.04885802, 115180573.04885802)
('kucoin-shares', 'kcs', 'KuCoin', 132155021.7355671, 142155021.7355671)
('superstate-short-duration-us-government-securities-fund-ustb', 'ustb', 'Superstate Short Duration U.S. Government Securities Fund (USTB)', 98042220.270805, 98042220.270805)
('polygon-ecosystem-token', 'pol', 'POL (ex-MATIC)', 10609407169.81502, 10609407169.81502)
('quant-network', 'qnt', 'Quant', 14544176.164081175, 14612493.0)
('eutbl', 'eutbl', 'Spiko EU T-Bills Money Market Fund', 817602213.91529, 817602213.91529)
('kaspa', 'kas', 'Kaspa', 26777148610.50726, 27288854137.44135)
('cosmos', 'atom', 'Cosmos Hub', 498540191.039641, 498540191.039641)
('render-token', 'render', 'Render', 518743261.0140742, 533503434.2940742)
('nexo', 'nexo', 'NEXO', 1000000000.0, 1000000000.0)
('algorand', 'algo', 'Algorand', 8890708014.89448, 8890721482.008408)
('usdtb', 'usdtb', 'USDtb', 835539762.7461826, 835539762.7461826)
('janus-henderson-anemoy-treasury-fund', 'jtrsy', 'Janus Henderson Anemoy Treasury Fund', 742159349.124733, 742159349.124733)
('usdd', 'usdd', 'USDD', 744602022.25, 744812003.25)
('ousg', 'ousg', 'OUSG', 6288072.37950775, 6288072.37950775)
('vechain', 'vet', 'VeChain', 85985041177.0, 85985041177.0)
('gho', 'gho', 'GHO', 584000000.0, 584000000.0)
('bonk', 'bonk', 'Bonk', 87994756491484.12, 87994756651114.97)
('ylds', 'ylds', 'YLDS', 568973931.9, 568973931.9)
('usual-usd', 'usd0', 'Usual USD', 562791550.408157, 562791550.408157)
('siren-2', 'siren', 'Siren', 728213818.6911135, 728213818.6911135)
('true-usd', 'tusd', 'TrueUSD', 494515083.0, 494515083.0)
('pancakeswap-token', 'cake', 'PancakeSwap', 329483815.4946629, 342748423.4723409)
('just', 'jst', 'JUST', 8815108920.581306, 8815108920.581306)
('blockstack', 'stx', 'Stacks', 1835435421.06695, 1835435421.06695)
('a7a5', 'a7a5', 'A7A5', 39196598573.57074, 39196598573.57074)
('decred', 'dcr', 'Decred', 17326238.44989612, 17326260.76293856)
('dash', 'dash', 'Dash', 12628524.93995398, 12628984.17146325)
('euro-coin', 'eurc', 'EURC', 375244228.0358601, 375244226.0158601)
('tezos', 'xtz', 'Tezos', 1078754440.976565, 1098806689.705827)
('janus-henderson-anemoy-aaa-clo-fund', 'jaaa', 'Janus Henderson Anemoy AAA CLO Fund', 407241624.558788, 407241595.135557)
('chiliz', 'chz', 'Chiliz', 10334831735.0, 10334831735.0)
('kinesis-gold', 'kau', 'Kinesis Gold', 2386227.8342, 2386227.8342)
('first-digital-usd', 'fdusd', 'First Digital USD', 381165430.923712, 381165430.923712)
('usx', 'usx', 'USX', 371703331.704459, 371703331.704459)
('bittorrent', 'btt', 'BitTorrent', 987037885840674.8, 990000000000000.0)
('sun-token', 'sun', 'Sun Token', 19220938035.69119, 19900730000.0)
('conflux-token', 'cfx', 'Conflux', 5189835932.13, 5192774128.89)
('apenft', 'nft', 'AINFT', 990105667256391.5, 990105667256391.5)
('hastra-prime', 'prime', 'PRIME', 318809627.479687, 318831966.374242)
('usdai', 'usdai', 'USDai', 327702805.5136058, 327702805.5136058)
('kaia', 'kaia', 'Kaia', 5856641747.106198, 5856641936.044253)
('injective-protocol', 'inj', 'Injective', 100000000.0, 100000000.0)
('spx6900', 'spx', 'SPX6900', 930993080.908372, 930993080.908372)
('bitcoin-cash-sv', 'bsv', 'Bitcoin SV', 20002468.75, 20002468.75)
('syrup', 'syrup', 'Maple Finance', 1157190702.5885315, 1216127147.998563)
('floki', 'floki', 'FLOKI', 9654485859831.0, 10000000000000.0)
('the-graph', 'grt', 'The Graph', 10747585695.26097, 10800262816.04821)
('jasmycoin', 'jasmy', 'JasmyCoin', 49444999677.59027, 50000000000.0)
('frax', 'frax', 'Legacy Frax Dollar', 275935184.0102677, 275935184.0102677)
('official-fo', 'fo', 'Official FO', 997490221.15, 997490221.15)
('crvusd', 'crvusd', 'crvUSD', 263559765.6463969, 263559765.6463969)
('ape-and-pepe', 'apepe', 'Ape and Pepe', 210000000000000.0, 210000000000000.0)
('thetrumptoken', 'great', 'TheTrumpToken', 21000000.0, 21000000.0)
('telcoin', 'tel', 'Telcoin', 95077236366.71, 100000000000.0)
('helium', 'hnt', 'Helium', 184791073.138691, 184791073.138691)
('build-on', 'b', 'BUILDon', 1000000000.0, 1000000000.0)
('usda-2', 'usda', 'USDa', 220698083.2106699, 220698083.2106699)
('agora-dollar', 'ausd', 'AUSD', 216456853.0, 216456853.0)
('swissborg', 'borg', 'SwissBorg', 981852443.4419999, 981852443.4419999)
('newton-project', 'ab', 'AB', 98823661261.46, 98823661261.46)
('fartcoin', 'fartcoin', 'Fartcoin', 999978970.338633, 999978970.338633)
('blockchain-capital', 'bcap', 'Blockchain Capital', 9112111.0, 9112111.0)
('nusd-2', 'nusd', 'Neutrl USD', 207643474.6062259, 207643474.6062259)
('zebec-network', 'zbcn', 'Zebec Network', 97951717939.67068, 99997616501.2309)
('reallink', 'real', 'RealLink', 3158391475.0, 3158391475.0)
('spiko-us-t-bills-money-market-fund', 'ustbl', 'Spiko US T-Bills Money Market Fund', 181387167.26536, 181387167.26536)
('tradable-na-rent-financing-platform-sstn', 'pc0000031', 'Tradable NA Rent Financing Platform SSTN', 189500000.0, 189500000.0)
('convex-finance', 'cvx', 'Convex Finance', 91758226.73956148, 99957803.56768332)
('theta-token', 'theta', 'Theta Network', 1000000000.0, 1000000000.0)
('compound-governance-token', 'comp', 'Compound', 9668189.278360886, 10000000.0)
('dogwifcoin', 'wif', 'dogwifhat', 998926392.0, 998926392.0)
('re-protocol-reusd', 'reusd', 'Re Protocol reUSD', 174474772.2100287, 174474772.2100287)
('sonic-3', 's', 'Sonic', 3784775845.0, 3885497663.0)
('fidelity-digital-interest-token', 'fdit', 'Fidelity Digital Interest Token', 177970494.48, 177970494.48)
('infinifi-usd', 'iusd', 'InfiniFi USD', 175206932.4725754, 175206932.4725754)
('gala', 'gala', 'GALA', 47467909455.65924, 47467909518.98255)
('comedian', 'ban', 'Comedian', 999961859.27, 999961859.27)
('bnb48-club-token', 'koge', 'KOGE', 3379998.56, 3379998.56)
('basic-attention-token', 'bat', 'Basic Attention', 1495724656.9526057, 1500000000.0)
('satoshi-stablecoin', 'satusd', 'Satoshi Stablecoin', 159256711.7155544, 159256711.7155544)
('ribbita-by-virtuals', 'tibbir', 'Ribbita by Virtuals', 999904783.797368, 999904783.797368)
('safepal', 'sfp', 'SafePal', 500000000.0, 500000000.0)
('stasis-eurs', 'eurs', 'STASIS EURO', 124125940.0, 124125940.0)
('ecash', 'xec', 'eCash', 20002279672580.0, 20002301547580.0)
('1inch', '1inch', '1INCH', 1404597681.661079, 1499999999.997)
('pippin', 'pippin', 'pippin', 999937218.935898, 999937218.935898)
('akash-network', 'akt', 'Akash Network', 289254334.040396, 290024866.734339)
('golem', 'glm', 'Golem', 1000000000.0, 1000000000.0)
('onyc', 'onyc', 'Onchain Yield Coin', 126709983.7105298, 126709983.7105298)
('gekko', 'gekko', 'GEKKO', 200000000000000.0, 200000000000000.0)
('theo-short-duration-us-treasury-fund', 'thbill', 'Theo Short Duration US Treasury Fund', 129713301.738355, 129713301.738355)
('apollo-diversified-credit-securitize-fund', 'acred', 'Apollo Diversified Credit Securitize Fund', 119800.351277, 119800.351277)
('astherus-usdf', 'usdf', 'Aster USDF', 130691867.8560444, 130691867.8560444)
('elrond-erd-2', 'egld', 'MultiversX', 29538761.0, 29538761.0)
('cash-4', 'cash', 'CASH', 127635354.120561, 127635354.120561)
('avant-usd', 'avusd', 'Avant USD', 126806986.2190007, 126806986.2190007)
('gmt-token', 'gomining', 'GoMining Token', 405275709.1636765, 405275709.1636765)
('frax-usd', 'frxusd', 'Frax USD', 126240322.6858699, 126250015.7324722)
('ozone-chain', 'ozo', 'Ozone Chain', 954291648.0, 1000000000.0)
('arweave', 'ar', 'Arweave', 65652466.0, 65652466.0)
('quantum-resistant-ledger', 'qrl', 'Quantum Resistant Ledger', 78392960.0, 78392960.0)
('pleasing-usd', 'pusd', 'Pleasing USD', 120000000.0, 120000000.0)
('livepeer', 'lpt', 'Livepeer', 49688954.55, 49688954.55)
('chutes', 'sn64', 'Chutes', 4611192.591382396, 4611192.591382396)
('melania-meme', 'melania', 'Melania Meme', 952496375.911841, 999996276.697247)
('tradable-singapore-fintech-ssl-2', 'pc0000023', 'Tradable Singapore Fintech SSL', 114500000.0, 114500000.0)
('havven', 'snx', 'Synthetix', 344516234.4572882, 344939867.5556631)
('nxm', 'nxm', 'Nexus Mutual', 1847387.70325461, 1847387.70325461)
('precious-metals-usd', 'pmusd', 'Precious Metals USD', 109701203.6222222, 109701203.6222222)
('gas', 'gas', 'Gas', 65093580.54427269, 65093580.54427269)
('stp-network', 'awe', 'AWE Network', 1942420283.0270672, 1942420283.0270672)
('securitize-tokenized-aaa-clo-fund', 'stac', 'Securitize Tokenized AAA CLO Fund', 105099.694673, 105099.694673)
('zano', 'zano', 'Zano', 15201712.49, 15201942.41)
('cheems-token', 'cheems', 'Cheems Token', 203672952113698.72, 203672952113698.72)
('cap-usd', 'cusd', 'Cap USD', 106143973.0591033, 106143973.0591033)
('resolv-usr', 'usr', 'Resolv USR', 103986922.5258163, 103986922.5258163)
('banana-for-scale-2', 'bananas31', 'Banana For Scale', 10000000000.0, 10000000000.0)
('societe-generale-forge-eurcv', 'eurcv', 'EUR CoinVertible', 88171332.89, 88171332.89)
('qtum', 'qtum', 'Qtum', 105985177.75, 107822406.0)
('grx-chain', 'grx', 'GRX Chain', 9512449.0, 9998071.0)
('apecoin', 'ape', 'ApeCoin', 985156250.0, 1000000000.0)
('mnee-usd-stablecoin', 'mnee', 'MNEE USD Stablecoin', 100544580.2323, 100544580.2323)
('ring-usd', 'usdr', 'Ring USD', 100400000.0, 100400000.0)
('standx-dusd', 'dusd', 'StandX DUSD', 100268205.551709, 100268205.551709)
('unity-usd', 'uusd', 'Unity USD', 100000000.0, 100000000.0)
('pleasing-gold', 'pgold', 'Pleasing Gold', 19505.0, 19505.0)
('rollbit-coin', 'rlb', 'Rollbit Coin', 1730330604.24078, 1730330604.24078)
('unitas', 'up', 'Unitas', 921121896.78337, 1000000000.0)
('exod', 'exod', 'EXOD', 10446000.0, 10446000.0)
('midas-mf-one', 'mf-one', 'Midas mF-ONE', 91031934.48603103, 91031934.48603103)
('lovebit', 'lb', 'LoveBit', 420000000000000.0, 420000000000000.0)
('yearn-finance', 'yfi', 'yearn.finance', 35742.54399985384, 36666.0)
('theta-fuel', 'tfuel', 'Theta Fuel', 7263940128.0, 7263983108.0)
('ravencoin', 'rvn', 'Ravencoin', 16138461420.94731, 16138461420.94731)
('toshi', 'toshi', 'Toshi', 420690000000.0, 420690000000.0)
('xdai', 'xdai', 'XDAI', 93972570.52241121, 93972570.52241121)
('mimblewimblecoin', 'mwc', 'MimbleWimbleCoin', 11003011.01778801, 11003011.01778801)
('mag7-ssi', 'mag7.ssi', 'MAG7.ssi', 169135919.2566094, 169135919.2566094)
('verge', 'xvg', 'Verge', 16521951235.74134, 16555000000.0)
('usda-3', 'usda', 'USDA', 89105026.95797583, 89105026.95797583)
('brz', 'brz', 'Brazilian Digital', 463648484.5409616, 463648484.5409616)
('circle-internet-group-ondo-tokenized-stock', 'crclon', 'Circle Internet Group (Ondo Tokenized Stock)', 647907.3465032831, 648514.2199531774)
('zilliqa', 'zil', 'Zilliqa', 19950252425.51919, 20392213840.33794)
('aioz-network', 'aioz', 'AIOZ Network', 1240390860.394986, 1242006213.05901)
('usdu', 'usdu', 'USDu', 85333867.47684695, 85333867.47684695)
('kusama', 'ksm', 'Kusama', 17894973.33602802, 17894973.33602802)
('luxxcoin', 'lux', 'Luxxcoin', 100000000000.0, 100000000000.0)
('meta-2-2', 'meta', 'MetaDAO', 22684699.022953, 22684699.022953)
('dog-go-to-the-moon-rune', 'dog', 'Dog (Bitcoin)', 100000000000.0, 100000000000.0)
('swop-2', 'swop', 'Swop', 9999998190.509241, 9999998190.509241)
('templar', 'sn3', 'τemplar', 4230194.587539522, 4230194.587539522)
('based-brett', 'brett', 'Brett', 9909609171.0065, 9909609171.0065)
('matrixdock-gold', 'xaum', 'Matrixdock Gold', 16074.0, 16074.0)
('threshold-network-token', 't', 'Threshold Network', 11155000000.0, 11155000000.0)
('mina-protocol', 'mina', 'Mina Protocol', 1278381365.840039, 1278381365.840039)
('nervos-network', 'ckb', 'Nervos Network', 48406548693.9053, 49183710462.79286)
('coinex-token', 'cet', 'CoinEx', 2535351772.86, 2535351772.86)
('railgun', 'rail', 'Railgun', 57500000.0, 57500000.0)
('holotoken', 'hot', 'Holo', 177619433541.1413, 177619433541.1413)
('digibyte', 'dgb', 'DigiByte', 18187854053.23141, 18197188558.40029)
('helio-protocol-hay', 'lisusd', 'Lista USD', 76326033.88619556, 76326033.88619556)
('non-playable-coin', 'npc', 'Non-Playable Coin', 8050126520.0, 8050126520.0)
('cygnus-finance-global-usd', 'cgusd', 'Cygnus Finance Global USD', 75115845.42096, 75115845.42096)
('temple', 'temple', 'TempleDAO', 23722422.590706147, 23769704.54225455)
('jupusd', 'jupusd', 'JupUSD', 72458307.778071, 72458307.778071)
('turbo', 'turbo', 'Turbo', 69000000000.0, 69000000000.0)
('agentfun-ai', 'agentfun', 'AgentFun.AI', 100000000.0, 100000000.0)
('gmx', 'gmx', 'GMX', 10369514.68372571, 10369514.68372571)
('bc-token', 'bc', 'BCGame Coin', 9989388857.287811, 9989388857.287811)
('proton', 'xpr', 'XPR Network', 28616300799.6672, 31618717247.6413)
('astar', 'astr', 'Astar', 8570876379.0, 8663112188.0)
('tdccp', 'tdccp', 'TDCCP', 639999980.9, 639999980.9)
('mog-coin', 'mog', 'Mog Coin', 390561998053223.3, 390561998053223.3)
('deso', 'deso', 'Decentralized Social', 10532253.8854, 10808492.6854)
('basedhype', 'basedhype', 'BasedHype', 10000000000.0, 10000000000.0)
('polymesh', 'polyx', 'Polymesh', 1254538206.486415, 1254538206.486415)
('puff-the-dragon', 'puff', 'Puff The Dragon', 888888888.0, 888888888.0)
('axelar', 'axl', 'Axelar', 1136846487.420585, 1234410044.349242)
('nano', 'xno', 'Nano', 133248297.0, 133248297.0)
('kava', 'kava', 'Kava', 1082847245.0, 1082847245.0)
('rekt-4', 'rekt', 'Rekt', 420690000000000.0, 420690000000000.0)
('megausd', 'usdm', 'MegaUSD', 62997610.47718, 62997610.47718)
('freysa-ai', 'fai', 'Freysa AI', 8189700000.0, 8189700000.0)
('vaneck-treasury-fund', 'vbill', 'VanEck Treasury Fund', 63031364.83279, 63031364.83279)
('vethor-token', 'vtho', 'VeThor', 98648319333.0, 98686147850.0)
('verus-coin', 'vrsc', 'Verus', 80062689.23043773, 80066562.31537193)
('pythia', 'pythia', 'PYTHIA', 998160852.022029, 998160852.022029)
('usdx', 'usdx', 'USDX', 111568045.0, 111568045.0)
('frax-share', 'frax', 'Frax (prev. FXS)', 95340266.28229406, 99681495.5911336)
('sushi', 'sushi', 'Sushi', 273012266.12632084, 287676365.3148028)
('bianrensheng', '币安人生', '币安人生 (BinanceLife)', 1000000000.0, 1000000000.0)
('targon', 'sn4', 'Targon', 4368156.81663572, 4368156.81663572)
('affine', 'sn120', 'affine', 2650246.708256148, 2650246.708256148)
('cat-in-a-dogs-world', 'mew', 'cat in a dogs world', 88888888888.88, 88888888888.88)
('strategic-oil-supply-2', 'sos', 'Strategic Oil Supply', 100000000000.0, 100000000000.0)
('dai-on-pulsechain', 'dai', 'DAI on PulseChain', 44358367634.06843, 44358367634.06843)
('purr-2', 'purr', 'Purr', 595578506.85291, 595578547.55335)
('flow', 'flow', 'Flow', 1648000577.808296, 1648000577.808296)
('blur', 'blur', 'Blur', 2756320128.852739, 3000000000.0)
('ordinals', 'ordi', 'ORDI', 21000000.0, 21000000.0)
('xyo-network', 'xyo', 'XYO Network', 13931216938.01129, 13931216938.01129)
('ondo-u-s-dollar-token', 'usdon', 'Ondo U.S. Dollar Token', 56355223.32793773, 53523170.03398139)
('burnedfi', 'burn', 'BurnedFi', 12360997.245107507, 12360997.245107507)
('popcat', 'popcat', 'Popcat', 979978669.96, 979978669.96)
('anchored-coins-eur', 'aeur', 'Anchored Coins AEUR', 47929494.59999999, 47929494.59999999)
('siacoin', 'sc', 'Siacoin', 49751295000.0225, 49751295000.0225)
('alphabet-class-a-ondo-tokenized-stock', 'googlon', 'Alphabet Class A (Ondo Tokenized Stock)', 176109.7606702784, 176109.7606702784)
('ai-companions', 'aic', 'AI Companions', 1000000000.0, 1000000000.0)
('moo-deng', 'moodeng', 'Moo Deng', 989938419.942311, 989938419.942311)
('eurite', 'euri', 'Eurite', 46968932.99990108, 46968932.99990108)
('jelly-my-jelly', 'jellyjelly', 'Jelly-My-Jelly', 999999099.34, 999999099.34)
('fidelity-digital-dollar', 'fidd', 'Fidelity Digital Dollar', 51601077.59, 51601077.59)
('apxusd', 'apxusd', 'apxUSD', 51478449.99999999, 51478449.99999999)
('bankercoin-2', 'bnkr', 'BankrCoin', 99999999999.99998, 99999999999.99998)
('usdkg', 'usdkg', 'USDKG', 50000000.0, 50000000.0)
('alloy-tether', 'ausdt', 'Alloy Tether', 50000005.0, 50000005.0)
('pirate-chain', 'arrr', 'Pirate Chain', 196213797.97055, 200000000.0)
('straitsx-xusd', 'xusd', 'StraitsX XUSD', 49801209.551, 49801209.551)
('niza-global-2', 'niza', 'Niza Global', 1150000000.0, 1150000000.0)
('atomone', 'atone', 'AtomOne', 125985415.369374, 137793327.029374)
('openeden-open-dollar', 'usdo', 'OpenEden OpenDollar', 49528746.17353272, 49528746.17353272)
('iotex', 'iotx', 'IoTeX', 9441368979.0, 9441368983.0)
('ankr', 'ankr', 'Ankr Network', 10000000000.0, 10000000000.0)
('mask-network', 'mask', 'Mask Network', 100000000.0, 100000000.0)
('casper-network', 'cspr', 'Casper Network', 14436393550.0, 14436393548.0)
('peanut-the-squirrel', 'pnut', 'Peanut the Squirrel', 999842421.317821, 999842421.317821)
('wiki-cat', 'wkc', 'Wiki Cat', 539961732621557.9, 539961732621557.9)
('waves', 'waves', 'Waves', 100000000.0, 100000000.0)
('usd', 'usd+', 'Overnight.fi USD+', 48085096.3705041, 48085096.3705041)
('skyai', 'skyai', 'SkyAI', 1000000000.0, 1000000000.0)
('dusk-network', 'dusk', 'DUSK', 500000000.0, 500000000.0)
('sygnum-fiusd-liquidity-fund', 'fiusd', 'Sygnum FIUSD Liquidity Fund', 3997.66, 3997.66)
('ardor', 'ardr', 'Ardor', 998466231.0, 998466231.0)
('midas-mtbill', 'mtbill', 'Midas mTBILL', 44440245.63317438, 44440245.63317438)
('tellor', 'trb', 'Tellor Tributes', 2764550.0927944304, 2840003.319747911)
('rocket-pool', 'rpl', 'Rocket Pool', 22283476.39765067, 22283476.39765067)
('midas-mhyper', 'mhyper', 'Midas mHYPER', 42053467.7833667, 42053467.7833667)

In [ ]:
cursor.execute("""SELECT name,symbol,current_price,ath
from Cryptocurrencies
where current_price >=0.9* ath """)

rows = cursor.fetchall()

for row in rows:
    print(row) #Get coins that are within 10% of their all-time-high (ATH).

('USDC', 'usdc', 92.4, 92.72)
('Figure Heloc', 'figr_heloc', 95.37, 96.67)
('WhiteBIT Coin', 'wbt', 5377.26, 5758.63)
('USDS', 'usds', 92.4, 92.7)
('LEO Token', 'leo', 837.42, 888.26)
('Ethena USDe', 'usde', 92.42, 92.91)
('USD1', 'usd1', 92.33, 92.67)
('Dai', 'dai', 92.38, 92.71)
('PayPal USD', 'pyusd', 92.39, 92.71)
('Tether Gold', 'xaut', 459426.0, 506656.0)
('Circle USYC', 'usyc', 103.31, 103.38)
('BlackRock USD Institutional Digital Liquidity Fund', 'buidl', 92.4, 92.72)
('Falcon USD', 'usdf', 92.26, 92.49)
('Ripple USD', 'rlusd', 92.4, 92.73)
('BFUSD', 'bfusd', 92.35, 92.67)
('Ondo US Dollar Yield', 'usdy', 103.06, 105.8)
('Superstate Short Duration U.S. Government Securities Fund (USTB)', 'ustb', 1018.49, 1021.56)
('Spiko EU T-Bills Money Market Fund', 'eutbl', 111.84, 115.38)
('USDtb', 'usdtb', 92.38, 95.66)
('Janus Henderson Anemoy Treasury Fund', 'jtrsy', 101.41, 101.72)
('USDD', 'usdd', 92.44, 92.72)
('OUSG', 'ousg', 10590.46, 10622.24)
('GHO', 'gho', 92.4, 92.85)
('YLDS', 'ylds', 92.4, 92.72)
('Siren', 'siren', 66.76, 72.81)
('EURC', 'eurc', 106.67, 111.47)
('Janus Henderson Anemoy AAA CLO Fund', 'jaaa', 94.89, 95.09)
('First Digital USD', 'fdusd', 92.43, 100.07)
('USX', 'usx', 92.36, 95.56)
('Legacy Frax Dollar', 'frax', 91.75, 92.22)
('crvUSD', 'crvusd', 92.33, 96.91)
('TheTrumpToken', 'great', 1121.44, 1123.24)
('USDa', 'usda', 90.94, 91.13)
('AUSD', 'ausd', 92.39, 92.72)
('The9bit', '9bit', 2.36, 2.39)
('Neutrl USD', 'nusd', 92.34, 94.55)
('Spiko US T-Bills Money Market Fund', 'ustbl', 99.55, 99.78)
('Re Protocol reUSD', 'reusd', 98.59, 98.92)
('Fidelity Digital Interest Token', 'fdit', 92.4, 92.72)
('GUSD', 'gusd', 92.28, 94.12)
('Onchain Yield Coin', 'onyc', 100.28, 100.52)
('Theo Short Duration US Treasury Fund', 'thbill', 94.18, 98.66)
('Apollo Diversified Credit Securitize Fund', 'acred', 100847.0, 101459.0)
('Aster USDF', 'usdf', 92.3, 94.12)
('CASH', 'cash', 92.38, 95.43)
('Avant USD', 'avusd', 92.37, 93.96)
('Frax USD', 'frxusd', 92.46, 92.72)
('Pleasing USD', 'pusd', 92.74, 95.47)
('Tradable Singapore Fintech SSL', 'pc0000023', 92.4, 92.72)
('Precious Metals USD', 'pmusd', 90.65, 95.56)
('Securitize Tokenized AAA CLO Fund', 'stac', 93139.0, 93303.0)
('Resolv USR', 'usr', 92.25, 92.69)
('EUR CoinVertible', 'eurcv', 106.57, 111.87)
('MNEE USD Stablecoin', 'mnee', 92.39, 93.6)
('Ring USD', 'usdr', 92.46, 97.09)
('StandX DUSD', 'dusd', 92.37, 92.65)
('Unity USD', 'uusd', 92.4, 93.17)
('Pleasing Gold', 'pgold', 463822.0, 506532.0)
('UnifAI Network', 'uai', 37.66, 40.03)
('Midas mF-ONE', 'mf-one', 98.6, 98.81)
('JUSD', 'jusd', 92.42, 92.72)
('USDu', 'usdu', 92.45, 92.73)
('Cygnus Finance Global USD', 'cgusd', 92.08, 93.4)
('Felix feUSD', 'feusd', 92.0, 94.32)
('TRIA', 'tria', 3.18, 3.26)
('JupUSD', 'jupusd', 92.41, 93.14)
('Bitway', 'btw', 2.86, 3.17)
('The Game Company', 'gmrt', 17.14, 17.14)
('MegaUSD', 'usdm', 92.58, 92.84)
('VanEck Treasury Fund', 'vbill', 92.4, 92.72)
('Ondo U.S. Dollar Token', 'usdon', 92.4, 92.72)
('Alphabet Class A (Ondo Tokenized Stock)', 'googlon', 28614.0, 31792.0)
('Eurite', 'euri', 106.55, 110.43)
('Fidelity Digital Dollar', 'fidd', 92.43, 92.7)
('apxUSD', 'apxusd', 92.45, 93.48)
('USDKG', 'usdkg', 92.4, 93.85)
('Alloy Tether', 'ausdt', 92.3, 93.99)
('Sygnum FIUSD Liquidity Fund', 'fiusd', 1091017.0, 1094264.0)
('Midas mTBILL', 'mtbill', 97.5, 97.78)
('Midas mHYPER', 'mhyper', 100.17, 100.51)
('Crown BRLV', 'brlv', 17.84, 17.89)
('Hippius', 'sn75', 986.35, 1052.84)
('Resolv Liquidity Provider Token', 'rlp', 118.63, 119.07)
('Pax Dollar', 'usdp', 92.4, 99.13)
('PumpMeme', 'pm', 109.6, 111.3)
('Frankencoin', 'zchf', 117.4, 120.88)
('Main Street Yield', 'msy', 95.41, 95.64)
('MimboGameGroup', 'mgg', 0.278115, 0.293933)
('SPDR S&P 500 ETF (Ondo Tokenized ETF)', 'spyon', 62237.0, 64397.0)
('Compounding OpenDollar', 'cusdo', 96.28, 97.25)
('AIntivirus', 'ainti', 2.86, 2.89)
('Ryze', 'ryze', 14.11, 14.52)
('Yield Optimizer USD', 'yousd', 99.02, 99.3)
('Micron Technology (Ondo Tokenized Stock)', 'muon', 42408.0, 42433.0)
('USTBL', 'ustbl', 96.81, 97.41)
('Liquity USD', 'lusd', 93.68, 94.31)
('BOLD', 'bold', 92.75, 93.48)
('Monerium EUR emoney', 'eure', 106.25, 110.77)
('Nest Basis Vault', 'nbasis', 97.26, 97.57)
('infiniFi Locked iUSD (1week)', 'liusd', 107.69, 111.36)
('USAT', 'usat', 92.4, 92.73)
('MAI', 'mimatic', 92.32, 98.03)
('Monerium EUR emoney [OLD]', 'eure', 106.48, 110.85)
('Invesco QQQ ETF (Ondo Tokenized ETF)', 'qqqon', 55748.0, 58660.0)
('MetaMask USD', 'musd', 92.4, 96.53)
('Predictions', 'prdt', 101.29, 111.64)
('Goldfish Gold', 'ggbr', 463.24, 494.23)
('NVIDIA (Ondo Tokenized Stock)', 'nvdaon', 16914.73, 18732.02)
('Noble Dollar (USDN)', 'usdn', 92.4, 92.83)
('USD CoinVertible', 'usdcv', 92.34, 100.53)
('Electronic USD', 'eusd', 92.39, 94.57)
('iShares Core S&P 500 ETF (Ondo Tokenized ETF)', 'ivvon', 62532.0, 64683.0)
('NVIDIA xStock', 'nvdax', 16924.83, 18702.52)
('USDH', 'usdh', 92.35, 98.73)
('Unity', 'uty', 92.33, 93.56)
('Decentralized Validator Token', 'dvsteth', 130535.0, 132190.0)
('SP500 xStock', 'spyx', 62267.0, 64229.0)
('Orizon', 'ori', 5104.28, 5582.12)
('f(x) Protocol fxUSD', 'fxusd', 92.65, 94.86)
('Mezo USD', 'musd', 91.8, 93.66)
('iShares 20+ Year Treasury Bond ETF (Ondo Tokenized ETF)', 'tlton', 8280.9, 8487.5)
('Alphabet xStock', 'googlx', 28609.0, 31754.0)
('Hylo USD', 'hyusd', 92.37, 92.85)
('Carrot', 'crt', 10604.43, 11681.45)
('Anzen USDz', 'usdz', 91.88, 94.1)
('QIE Blockchain', 'qie', 18.09, 19.27)
('HUNDRED', 'hundred', 0.01678123, 0.01687307)
('Coldint', 'sn29', 374.61, 394.36)
('Midas mAPOLLO', 'mapollo', 99.6, 99.84)
('BRLA Digital BRLA', 'brla', 17.74, 17.88)
('USP Yield Optimized Stablecoin', 'usp', 99.56, 100.72)
('DIAMOND TOKEN 💎', 'dit', 13.7, 13.83)
('Mento Dollar', 'usdm', 92.4, 97.99)
('Midas msyrupUSDp', 'msyrupusdp', 96.27, 96.48)
('iShares Core US Aggregate Bond ETF (Ondo Tokenized ETF)', 'aggon', 9430.65, 9809.75)
('Midas mMEV', 'mmev', 102.84, 103.13)
('Stable Coin', 'sbc', 92.48, 92.71)
('Midas mRe7YIELD', 'mre7yield', 100.85, 101.19)
('SigmaDotMoney', 'sigma', 8.29, 8.76)
('Spiko Digital Assets Cash & Carry Fund', 'spkcc', 93.48, 93.8)
('VCRED', 'vcred', 92.2, 92.41)
('Superfortune', 'gua', 25.78, 27.02)
('Worldwide USD', 'wusd', 92.38, 92.65)
('Hydrated Dollar', 'hollar', 92.21, 93.64)
('JPY Coin', 'jpyc', 0.579425, 0.599801)
('Tokenised GBP', 'tgbp', 124.12, 127.2)
('Hermetica USDh', 'usdh', 92.23, 94.37)
('Theros', 'theros', 26.33, 26.99)
('iShares TIPS Bond ETF (Ondo Tokenized ETF)', 'tipon', 10478.32, 10799.32)
('eSui Dollar', 'suiusde', 92.52, 97.48)
('iShares Core S&P Total US Stock Market ETF (Ondo Tokenized ETF)', 'itoton', 13596.18, 14175.06)
('Balsa MM Fund', 'bmmf', 7.51, 7.78)
('Nest BlackOpal LiquidStone II Vault', 'nopal', 96.06, 96.27)
('Ember Third Eye', 'ethird', 95.76, 95.86)
('Mu Digital AZND', 'aznd', 92.22, 92.45)
('Nest Alpha Vault (LP)', 'inalpha', 88.17, 94.2)
('iShares MSCI EAFE ETF (Ondo Tokenized ETF)', 'efaon', 9141.3, 9800.53)
('Defi.money', 'money', 93.3, 93.52)
('eUSD', 'eusd', 92.43, 93.78)
('USDC', 'usdc', 92.4, 92.72)
('Figure Heloc', 'figr_heloc', 95.37, 96.67)
('WhiteBIT Coin', 'wbt', 5377.26, 5758.63)
('USDS', 'usds', 92.4, 92.7)
('LEO Token', 'leo', 837.42, 888.26)
('Ethena USDe', 'usde', 92.42, 92.91)
('USD1', 'usd1', 92.33, 92.67)
('Dai', 'dai', 92.38, 92.71)
('PayPal USD', 'pyusd', 92.39, 92.71)
('Tether Gold', 'xaut', 459426.0, 506656.0)
('Circle USYC', 'usyc', 103.31, 103.38)
('BlackRock USD Institutional Digital Liquidity Fund', 'buidl', 92.4, 92.72)
('Falcon USD', 'usdf', 92.26, 92.49)
('Ripple USD', 'rlusd', 92.4, 92.73)
('BFUSD', 'bfusd', 92.35, 92.67)
('Ondo US Dollar Yield', 'usdy', 103.06, 105.8)
('Superstate Short Duration U.S. Government Securities Fund (USTB)', 'ustb', 1018.49, 1021.56)
('Spiko EU T-Bills Money Market Fund', 'eutbl', 111.84, 115.38)
('USDtb', 'usdtb', 92.38, 95.66)
('Janus Henderson Anemoy Treasury Fund', 'jtrsy', 101.41, 101.72)
('USDD', 'usdd', 92.44, 92.72)
('OUSG', 'ousg', 10590.46, 10622.24)
('GHO', 'gho', 92.4, 92.85)
('YLDS', 'ylds', 92.4, 92.72)
('Siren', 'siren', 66.76, 72.81)
('EURC', 'eurc', 106.67, 111.47)
('Janus Henderson Anemoy AAA CLO Fund', 'jaaa', 94.89, 95.09)
('First Digital USD', 'fdusd', 92.43, 100.07)
('USX', 'usx', 92.36, 95.56)
('Legacy Frax Dollar', 'frax', 91.75, 92.22)
('crvUSD', 'crvusd', 92.33, 96.91)
('TheTrumpToken', 'great', 1121.44, 1123.24)
('USDa', 'usda', 90.94, 91.13)
('AUSD', 'ausd', 92.39, 92.72)
('The9bit', '9bit', 2.36, 2.39)
('Neutrl USD', 'nusd', 92.34, 94.55)
('Spiko US T-Bills Money Market Fund', 'ustbl', 99.55, 99.78)
('Re Protocol reUSD', 'reusd', 98.59, 98.92)
('Fidelity Digital Interest Token', 'fdit', 92.4, 92.72)
('GUSD', 'gusd', 92.28, 94.12)
('Onchain Yield Coin', 'onyc', 100.28, 100.52)
('Theo Short Duration US Treasury Fund', 'thbill', 94.18, 98.66)
('Apollo Diversified Credit Securitize Fund', 'acred', 100847.0, 101459.0)
('Aster USDF', 'usdf', 92.3, 94.12)
('CASH', 'cash', 92.38, 95.43)
('Avant USD', 'avusd', 92.37, 93.96)
('Frax USD', 'frxusd', 92.46, 92.72)
('Pleasing USD', 'pusd', 92.74, 95.47)
('Tradable Singapore Fintech SSL', 'pc0000023', 92.4, 92.72)
('Precious Metals USD', 'pmusd', 90.65, 95.56)
('Securitize Tokenized AAA CLO Fund', 'stac', 93139.0, 93303.0)
('Resolv USR', 'usr', 92.25, 92.69)
('EUR CoinVertible', 'eurcv', 106.57, 111.87)
('MNEE USD Stablecoin', 'mnee', 92.39, 93.6)
('Ring USD', 'usdr', 92.46, 97.09)
('StandX DUSD', 'dusd', 92.37, 92.65)
('Unity USD', 'uusd', 92.4, 93.17)
('Pleasing Gold', 'pgold', 463822.0, 506532.0)
('UnifAI Network', 'uai', 37.66, 40.03)
('Midas mF-ONE', 'mf-one', 98.6, 98.81)
('JUSD', 'jusd', 92.42, 92.72)
('USDu', 'usdu', 92.45, 92.73)
('Cygnus Finance Global USD', 'cgusd', 92.08, 93.4)
('Felix feUSD', 'feusd', 92.0, 94.32)
('TRIA', 'tria', 3.18, 3.26)
('JupUSD', 'jupusd', 92.41, 93.14)
('Bitway', 'btw', 2.86, 3.17)
('The Game Company', 'gmrt', 17.14, 17.14)
('MegaUSD', 'usdm', 92.58, 92.84)
('VanEck Treasury Fund', 'vbill', 92.4, 92.72)
('Ondo U.S. Dollar Token', 'usdon', 92.4, 92.72)
('Alphabet Class A (Ondo Tokenized Stock)', 'googlon', 28614.0, 31792.0)
('Eurite', 'euri', 106.55, 110.43)
('Fidelity Digital Dollar', 'fidd', 92.43, 92.7)
('apxUSD', 'apxusd', 92.45, 93.48)
('USDKG', 'usdkg', 92.4, 93.85)
('Alloy Tether', 'ausdt', 92.3, 93.99)
('Sygnum FIUSD Liquidity Fund', 'fiusd', 1091017.0, 1094264.0)
('Midas mTBILL', 'mtbill', 97.5, 97.78)
('Midas mHYPER', 'mhyper', 100.17, 100.51)
('Crown BRLV', 'brlv', 17.84, 17.89)
('Hippius', 'sn75', 986.35, 1052.84)
('Resolv Liquidity Provider Token', 'rlp', 118.63, 119.07)
('Pax Dollar', 'usdp', 92.4, 99.13)
('PumpMeme', 'pm', 109.6, 111.3)
('Frankencoin', 'zchf', 117.4, 120.88)
('Main Street Yield', 'msy', 95.41, 95.64)
('MimboGameGroup', 'mgg', 0.278115, 0.293933)
('SPDR S&P 500 ETF (Ondo Tokenized ETF)', 'spyon', 62237.0, 64397.0)
('Compounding OpenDollar', 'cusdo', 96.28, 97.25)
('AIntivirus', 'ainti', 2.86, 2.89)
('Ryze', 'ryze', 14.11, 14.52)
('Yield Optimizer USD', 'yousd', 99.02, 99.3)
('Micron Technology (Ondo Tokenized Stock)', 'muon', 42408.0, 42433.0)
('USTBL', 'ustbl', 96.81, 97.41)
('Liquity USD', 'lusd', 93.68, 94.31)
('BOLD', 'bold', 92.75, 93.48)
('Monerium EUR emoney', 'eure', 106.25, 110.77)
('Nest Basis Vault', 'nbasis', 97.26, 97.57)
('infiniFi Locked iUSD (1week)', 'liusd', 107.69, 111.36)
('USAT', 'usat', 92.4, 92.73)
('MAI', 'mimatic', 92.32, 98.03)
('Monerium EUR emoney [OLD]', 'eure', 106.48, 110.85)
('Invesco QQQ ETF (Ondo Tokenized ETF)', 'qqqon', 55748.0, 58660.0)
('MetaMask USD', 'musd', 92.4, 96.53)
('Predictions', 'prdt', 101.29, 111.64)
('Goldfish Gold', 'ggbr', 463.24, 494.23)
('NVIDIA (Ondo Tokenized Stock)', 'nvdaon', 16914.73, 18732.02)
('Noble Dollar (USDN)', 'usdn', 92.4, 92.83)
('USD CoinVertible', 'usdcv', 92.34, 100.53)
('Electronic USD', 'eusd', 92.39, 94.57)
('iShares Core S&P 500 ETF (Ondo Tokenized ETF)', 'ivvon', 62532.0, 64683.0)
('NVIDIA xStock', 'nvdax', 16924.83, 18702.52)
('USDH', 'usdh', 92.35, 98.73)
('Unity', 'uty', 92.33, 93.56)
('Decentralized Validator Token', 'dvsteth', 130535.0, 132190.0)
('SP500 xStock', 'spyx', 62267.0, 64229.0)
('Orizon', 'ori', 5104.28, 5582.12)
('f(x) Protocol fxUSD', 'fxusd', 92.65, 94.86)
('Mezo USD', 'musd', 91.8, 93.66)
('iShares 20+ Year Treasury Bond ETF (Ondo Tokenized ETF)', 'tlton', 8280.9, 8487.5)
('Alphabet xStock', 'googlx', 28609.0, 31754.0)
('Hylo USD', 'hyusd', 92.37, 92.85)
('Carrot', 'crt', 10604.43, 11681.45)
('Anzen USDz', 'usdz', 91.88, 94.1)
('QIE Blockchain', 'qie', 18.09, 19.27)
('HUNDRED', 'hundred', 0.01678123, 0.01687307)
('Coldint', 'sn29', 374.61, 394.36)
('Midas mAPOLLO', 'mapollo', 99.6, 99.84)
('BRLA Digital BRLA', 'brla', 17.74, 17.88)
('USP Yield Optimized Stablecoin', 'usp', 99.56, 100.72)
('DIAMOND TOKEN 💎', 'dit', 13.7, 13.83)
('Mento Dollar', 'usdm', 92.4, 97.99)
('Midas msyrupUSDp', 'msyrupusdp', 96.27, 96.48)
('iShares Core US Aggregate Bond ETF (Ondo Tokenized ETF)', 'aggon', 9430.65, 9809.75)
('Midas mMEV', 'mmev', 102.84, 103.13)
('Stable Coin', 'sbc', 92.48, 92.71)
('Midas mRe7YIELD', 'mre7yield', 100.85, 101.19)
('SigmaDotMoney', 'sigma', 8.29, 8.76)
('Spiko Digital Assets Cash & Carry Fund', 'spkcc', 93.48, 93.8)
('VCRED', 'vcred', 92.2, 92.41)
('Superfortune', 'gua', 25.78, 27.02)
('Worldwide USD', 'wusd', 92.38, 92.65)
('Hydrated Dollar', 'hollar', 92.21, 93.64)
('JPY Coin', 'jpyc', 0.579425, 0.599801)
('Tokenised GBP', 'tgbp', 124.12, 127.2)
('Hermetica USDh', 'usdh', 92.23, 94.37)
('Theros', 'theros', 26.33, 26.99)
('iShares TIPS Bond ETF (Ondo Tokenized ETF)', 'tipon', 10478.32, 10799.32)
('eSui Dollar', 'suiusde', 92.52, 97.48)
('iShares Core S&P Total US Stock Market ETF (Ondo Tokenized ETF)', 'itoton', 13596.18, 14175.06)
('Balsa MM Fund', 'bmmf', 7.51, 7.78)
('Nest BlackOpal LiquidStone II Vault', 'nopal', 96.06, 96.27)
('Ember Third Eye', 'ethird', 95.76, 95.86)
('Mu Digital AZND', 'aznd', 92.22, 92.45)
('Nest Alpha Vault (LP)', 'inalpha', 88.17, 94.2)
('iShares MSCI EAFE ETF (Ondo Tokenized ETF)', 'efaon', 9141.3, 9800.53)
('Defi.money', 'money', 93.3, 93.52)
('eUSD', 'eusd', 92.43, 93.78)

In [ ]:
cursor.execute("""SELECT name, avg(market_cap_rank)
from Cryptocurrencies
where total_volume > 1000000000 """)

rows = cursor.fetchall()

for row in rows:
    print(row) #Find the average market cap rank of coins with volume above $1B.

('Bitcoin', 310.85185185185185)

In [ ]:
cursor.execute("""SELECT name,symbol,date
from Cryptocurrencies
order by date desc
limit 1 """)

rows = cursor.fetchall()

for row in rows:
    print(row) #Get the most recently updated coin.

('Bitcoin', 'btc', '2026-03-17')

In [ ]:
print(Crypto_prices_df.columns) # 2 data frame top 3

Index(['coin_id', 'date', 'price_inr'], dtype='object')

In [ ]:
import sqlite3

conn = sqlite3.connect("Crypto_prices.db")
cursor = conn.cursor()

In [ ]:
# Pushing dataframe into sql

Crypto_prices_df.to_sql("Crypto_prices", conn, if_exists="replace", index=False)

1098

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS Crypto_prices  (
    coin_id VARCHAR(50) ,
    date DATE,
    price_inr DECIMAL(18, 6),
    FOREIGN KEY (coin_id) REFERENCES Cryptocurrencies(id))
    """)

In [ ]:
Crypto_prices_df["date"] =  pd.to_datetime(Crypto_prices_df["date"]).dt.strftime("%Y-%m-%d") #converts data order

In [ ]:
sql = ("""
INSERT or REPLACE INTO  Crypto_prices (coin_id, date, price_inr)
VALUES (?, ?, ? )
""")
data = Crypto_prices_df[['coin_id', 'date', 'price_inr']].values.tolist()


cursor.executemany(sql, data)
conn.commit()

In [ ]:
cursor.execute("SELECT * FROM Crypto_prices LIMIT 10")
rows = cursor.fetchall()

for row in rows:
    print(row)

('bitcoin', '2025-03-18', 7307625.213417549)
('bitcoin', '2025-03-19', 7166130.900539224)
('bitcoin', '2025-03-20', 7495414.341859128)
('bitcoin', '2025-03-21', 7275140.94449613)
('bitcoin', '2025-03-22', 7224000.906005809)
('bitcoin', '2025-03-23', 7205763.671408613)
('bitcoin', '2025-03-24', 7377568.408827406)
('bitcoin', '2025-03-25', 7471026.999919416)
('bitcoin', '2025-03-26', 7490943.665690553)
('bitcoin', '2025-03-27', 7448415.462567322)

In [ ]:
cursor.execute("""SELECT coin_id,date, MAX(price_inr)
               FROM Crypto_prices
               WHERE coin_id="bitcoin"
                """)
rows = cursor.fetchall()

for row in rows:
    print(row) #Find the highest daily price of Bitcoin in the last 365 days.

('bitcoin', '2025-10-07', 11070472.246732509)

In [ ]:
cursor.execute("""SELECT coin_id,date, AVG(price_inr)
               FROM Crypto_prices
               WHERE coin_id="ethereum"
               AND date >= date('now','-365 day')
               ORDER BY date
                """)
rows = cursor.fetchall()

for row in rows:
    print(row) #Calculate the average daily price of Ethereum in the past 1 year.

('ethereum', '2025-03-18', 263707.71995287307)

In [ ]:
cursor.execute("""
SELECT coin_id, date, price_inr
FROM Crypto_prices
WHERE coin_id = "bitcoin"
AND date BETWEEN '2025-02-01' AND '2025-02-28'
ORDER BY date
""")

rows = cursor.fetchall()

for row in rows:
    print(row) #Show the daily price trend of Bitcoin in January 2025./ since data for jan not available took for feb

In [ ]:
cursor.execute("""
SELECT coin_id, date,
AVG (price_inr)
FROM Crypto_prices
GROUP BY coin_id
ORDER BY avg(price_inr) DESC
LIMIT 1
""")

rows = cursor.fetchall()

for row in rows:
    print(row)#Find the coin with the highest average price over 1 year.

('bitcoin', '2025-03-18', 8617070.031517716)

In [ ]:
cursor.execute("""
SELECT AVG(price_inr)
FROM Crypto_prices
WHERE coin_id='bitcoin'
AND date LIKE '2025-03-%'
""")#Any date that starts with %

feb2025_price = cursor.fetchone()[0]
print("feb 2025 Avg Price:", feb2025_price)#avg price of feb 2025

feb 2025 Avg Price: 7305017.244401984

In [ ]:
cursor.execute("""
SELECT AVG(price_inr)
FROM Crypto_prices
WHERE coin_id='bitcoin'
AND date LIKE '2026-02-%'
""")

feb2026_price = cursor.fetchone()[0]
print("feb 2026 Avg Price:", feb2026_price)#avg price of feb 2026

feb 2026 Avg Price: 6286123.5091402745

In [ ]:
percent_change = ((feb2026_price - feb2025_price) / feb2025_price) * 100
print("Percentage Change:",round(percent_change,2), "%")#Get the % change in Bitcoin’s price between feb 2025 and feb 2026.

Percentage Change: -13.95 %

In [ ]:
print((Oil_prices_df.columns))

Index(['Date', 'Price'], dtype='object')

In [ ]:
import sqlite3
conn = sqlite3.connect("Oil_prices.db")
cursor = conn.cursor()
print("SQLite connected")

SQLite connected

In [ ]:
# Pushing dataframe into sql

Oil_prices_df.to_sql("Oil_prices", conn, if_exists="replace", index=False)

1520

In [ ]:
Oil_prices_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1520 entries, 0 to 1519
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1520 non-null   datetime64[ns]
 1   Price   1520 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 23.9 KB

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS Oil_prices (
    Date DATE PRIMARY KEY,
   Price DECIMAL(18,6)
)
""")

In [ ]:
Oil_prices_df = Oil_prices_df.copy()
Oil_prices_df["Date"] = pd.to_datetime(Oil_prices_df["Date"]).dt.strftime("%Y-%m-%d")

In [ ]:
sql = """
INSERT OR REPLACE INTO Oil_prices (Date, Price)
VALUES (?, ?)
"""



data = Oil_prices_df[['Date','Price']].values.tolist()

cursor.executemany(sql, data)
conn.commit()

In [ ]:
cursor.execute("""
ALTER TABLE Oil_prices
RENAME COLUMN Date TO date
""")
cursor.execute("""
ALTER TABLE Oil_prices
RENAME COLUMN Price TO price_inr
""")

In [ ]:
cursor.execute("""
SELECT date,price_inr
FROM Oil_prices
WHERE Date >= date('now','-5 years')
ORDER BY price_inr DESC
LIMIT 1
""")

rows = cursor.fetchall()

for row in rows:
    print(row)#Find the highest oil price in the last 5 years.

('2022-03-08 00:00:00', 123.64)

In [ ]:
cursor.execute("""
SELECT substr(date,1,4) AS year,
       AVG(price_inr)
FROM Oil_prices
GROUP BY substr(date,1,4)
ORDER BY year
LIMIT 5
""")

rows = cursor.fetchall()

for row in rows:
    print(row) #Get the average oil price per year.

('2020', 39.16043650793649)
('2021', 68.13509960159365)
('2022', 94.9028685258964)
('2023', 77.5765322580645)
('2024', 76.6322400000001)

In [ ]:
cursor.execute("""
SELECT date, price_inr
FROM Oil_prices
WHERE date BETWEEN '2020-03-01' AND '2020-04-30'
ORDER BY date
""")

rows = cursor.fetchall()

for row in rows:
    print(row) #Show oil prices during COVID crash (March–April 2020).

('2020-03-02', 46.78)
('2020-03-02 00:00:00', 46.78)
('2020-03-03', 47.27)
('2020-03-03 00:00:00', 47.27)
('2020-03-04', 46.78)
('2020-03-04 00:00:00', 46.78)
('2020-03-05', 45.9)
('2020-03-05 00:00:00', 45.9)
('2020-03-06', 41.14)
('2020-03-06 00:00:00', 41.14)
('2020-03-09', 31.05)
('2020-03-09 00:00:00', 31.05)
('2020-03-10', 34.47)
('2020-03-10 00:00:00', 34.47)
('2020-03-11', 33.13)
('2020-03-11 00:00:00', 33.13)
('2020-03-12', 31.56)
('2020-03-12 00:00:00', 31.56)
('2020-03-13', 31.72)
('2020-03-13 00:00:00', 31.72)
('2020-03-16', 28.96)
('2020-03-16 00:00:00', 28.96)
('2020-03-17', 26.96)
('2020-03-17 00:00:00', 26.96)
('2020-03-18', 20.48)
('2020-03-18 00:00:00', 20.48)
('2020-03-19', 25.09)
('2020-03-19 00:00:00', 25.09)
('2020-03-20', 19.48)
('2020-03-20 00:00:00', 19.48)
('2020-03-23', 23.33)
('2020-03-23 00:00:00', 23.33)
('2020-03-24', 21.03)
('2020-03-24 00:00:00', 21.03)
('2020-03-25', 20.75)
('2020-03-25 00:00:00', 20.75)
('2020-03-26', 16.6)
('2020-03-26 00:00:00', 16.6)
('2020-03-27', 15.48)
('2020-03-27 00:00:00', 15.48)
('2020-03-30', 14.1)
('2020-03-30 00:00:00', 14.1)
('2020-03-31', 20.51)
('2020-03-31 00:00:00', 20.51)
('2020-04-01', 20.28)
('2020-04-01 00:00:00', 20.28)
('2020-04-02', 25.18)
('2020-04-02 00:00:00', 25.18)
('2020-04-03', 28.36)
('2020-04-03 00:00:00', 28.36)
('2020-04-06', 26.21)
('2020-04-06 00:00:00', 26.21)
('2020-04-07', 23.54)
('2020-04-07 00:00:00', 23.54)
('2020-04-08', 24.97)
('2020-04-08 00:00:00', 24.97)
('2020-04-09', 22.9)
('2020-04-09 00:00:00', 22.9)
('2020-04-13', 22.36)
('2020-04-13 00:00:00', 22.36)
('2020-04-14', 20.15)
('2020-04-14 00:00:00', 20.15)
('2020-04-15', 19.96)
('2020-04-15 00:00:00', 19.96)
('2020-04-16', 19.82)
('2020-04-16 00:00:00', 19.82)
('2020-04-17', 18.31)
('2020-04-17 00:00:00', 18.31)
('2020-04-20', -36.98)
('2020-04-20 00:00:00', -36.98)
('2020-04-21', 8.91)
('2020-04-21 00:00:00', 8.91)
('2020-04-22', 13.64)
('2020-04-22 00:00:00', 13.64)
('2020-04-23', 15.06)
('2020-04-23 00:00:00', 15.06)
('2020-04-24', 15.99)
('2020-04-24 00:00:00', 15.99)
('2020-04-27', 12.17)
('2020-04-27 00:00:00', 12.17)
('2020-04-28', 12.4)
('2020-04-28 00:00:00', 12.4)
('2020-04-29', 15.04)
('2020-04-29 00:00:00', 15.04)
('2020-04-30', 19.23)

In [ ]:
cursor.execute("""
SELECT MIN(price_inr)
FROM Oil_prices
WHERE date >= date('now','-10 years')
""")

rows = cursor.fetchall()
for row in rows:
    print(row) #Find the lowest price of oil in the last 10 years.

(-36.98,)

In [ ]:
cursor.execute("""
SELECT
    strftime('%Y', date) AS year,
    MAX(price_inr) - MIN(price_inr) AS volatility
FROM Oil_prices
GROUP BY year
ORDER BY year;
""")

rows = cursor.fetchall()#highest oil price in that year-lowest oil price in that year = volatility val
for row in rows:
    print(row) #Calculate the volatility of oil prices (max-min difference per year).

('2020', 100.25)
('2021', 38.17)
('2022', 52.59)
('2023', 27.060000000000002)
('2024', 20.959999999999994)
('2025', 25.290000000000006)
('2026', 8.759999999999998)

In [ ]:
print((stock_prices_df.columns))

MultiIndex([( 'Date',       ''),
            ('^GSPC',   'Open'),
            ('^GSPC',   'High'),
            ('^GSPC',    'Low'),
            ('^GSPC',  'Close'),
            ('^GSPC', 'Volume'),
            ('^IXIC',   'Open'),
            ('^IXIC',   'High'),
            ('^IXIC',    'Low'),
            ('^IXIC',  'Close'),
            ('^IXIC', 'Volume'),
            ('^NSEI',   'Open'),
            ('^NSEI',   'High'),
            ('^NSEI',    'Low'),
            ('^NSEI',  'Close'),
            ('^NSEI', 'Volume')],
           names=['Ticker', 'Price'])

In [ ]:
gspc = stock_prices_df[
    [('Date',''),
     ('^GSPC','Open'),
     ('^GSPC','High'),
     ('^GSPC','Low'),
     ('^GSPC','Close'),
     ('^GSPC','Volume')]
].copy()

gspc.columns = ['date','open','high','low','close','volume']
gspc['ticker'] = '^GSPC'


ixic = stock_prices_df[
    [('Date',''),
     ('^IXIC','Open'),
     ('^IXIC','High'),
     ('^IXIC','Low'),
     ('^IXIC','Close'),
     ('^IXIC','Volume')]
].copy()

ixic.columns = ['date','open','high','low','close','volume']
ixic['ticker'] = '^IXIC'


nsei = stock_prices_df[
    [('Date',''),
     ('^NSEI','Open'),
     ('^NSEI','High'),
     ('^NSEI','Low'),
     ('^NSEI','Close'),
     ('^NSEI','Volume')]
].copy()

nsei.columns = ['date','open','high','low','close','volume']
nsei['ticker'] = '^NSEI'

In [ ]:
stock_final_df = pd.concat([gspc, ixic, nsei])

In [ ]:
stock_final_df.head()

,date,open,high,low,close,volume,ticker
1,2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09,^GSPC
2,2020-01-03,3226.360107,3246.149902,3222.340088,3234.850098,3.484700e+09,^GSPC
3,2020-01-06,3217.550049,3246.840088,3214.639893,3246.280029,3.702460e+09,^GSPC
4,2020-01-07,3241.860107,3244.909912,3232.429932,3237.179932,3.435910e+09,^GSPC
5,2020-01-08,3238.590088,3267.070068,3236.669922,3253.050049,3.726840e+09,^GSPC

In [ ]:
import sqlite3

# Connect to database (creates if not exists)
conn = sqlite3.connect('stocks.db')
cursor = conn.cursor()

# Insert dataframe into table
stock_final_df.to_sql('stocks', conn, if_exists='replace', index=False)

# Create table if not exists
cursor.execute('''
CREATE TABLE IF NOT EXISTS stocks (
    date DATE,
    open DECIMAL(18, 6),
    high DECIMAL(18, 6),
    low DECIMAL(18, 6),
    close DECIMAL(18, 6),
    volume BIGINT,
    ticker VARCHAR(20)
)
''')
stock_final_df["date"] =  pd.to_datetime(stock_final_df["date"]).dt.date

# Check inserted data
cursor.execute("SELECT * FROM stocks LIMIT 5")
print(cursor.fetchall())

# Close connection
conn.close()

[('2020-01-02 00:00:00', 3244.669921875, 3258.139892578125, 3235.530029296875, 3257.85009765625, 3459930000.0, '^GSPC'), ('2020-01-03 00:00:00', 3226.360107421875, 3246.14990234375, 3222.340087890625, 3234.85009765625, 3484700000.0, '^GSPC'), ('2020-01-06 00:00:00', 3217.550048828125, 3246.840087890625, 3214.639892578125, 3246.280029296875, 3702460000.0, '^GSPC'), ('2020-01-07 00:00:00', 3241.860107421875, 3244.909912109375, 3232.429931640625, 3237.179931640625, 3435910000.0, '^GSPC'), ('2020-01-08 00:00:00', 3238.590087890625, 3267.070068359375, 3236.669921875, 3253.050048828125, 3726840000.0, '^GSPC')]

In [ ]:
import sqlite3

# Re-establish connection to the database
conn = sqlite3.connect('stocks.db')
cursor = conn.cursor()

cursor.execute("""
SELECT date, open, high, low, close, volume
FROM stocks
WHERE ticker = '^NSEI'
ORDER BY date
""")#Get all stock prices for a given ticker

rows = cursor.fetchall()

for row in rows:
    print(row)

# Close the connection after use
conn.close()

('2020-01-02 00:00:00', 12198.5498046875, 12289.900390625, 12195.25, 12282.2001953125, 407700.0)
('2020-01-03 00:00:00', 12261.099609375, 12265.599609375, 12191.349609375, 12226.650390625, 428800.0)
('2020-01-06 00:00:00', 12170.599609375, 12179.099609375, 11974.2001953125, 11993.0498046875, 396500.0)
('2020-01-07 00:00:00', 12079.099609375, 12152.150390625, 12005.349609375, 12052.9501953125, 447800.0)
('2020-01-08 00:00:00', 11939.099609375, 12044.9501953125, 11929.599609375, 12025.349609375, 446000.0)
('2020-01-09 00:00:00', 12153.150390625, 12224.0498046875, 12132.5498046875, 12215.900390625, 477500.0)
('2020-01-10 00:00:00', 12271.0, 12311.2001953125, 12213.2001953125, 12256.7998046875, 660600.0)
('2020-01-13 00:00:00', 12296.7001953125, 12337.75, 12285.7998046875, 12329.5498046875, 501000.0)
('2020-01-14 00:00:00', 12333.099609375, 12374.25, 12308.7001953125, 12362.2998046875, 616300.0)
('2020-01-15 00:00:00', 12349.400390625, 12355.150390625, 12278.75, 12343.2998046875, 684400.0)
('2020-01-16 00:00:00', 12347.099609375, 12389.0498046875, 12315.7998046875, 12355.5, 395700.0)
('2020-01-17 00:00:00', 12328.400390625, 12385.4501953125, 12321.400390625, 12352.349609375, 502100.0)
('2020-01-21 00:00:00', 12195.2998046875, 12230.0498046875, 12162.2998046875, 12169.849609375, 400.0)
('2020-01-22 00:00:00', 12218.349609375, 12225.0498046875, 12087.900390625, 12106.900390625, 500.0)
('2020-01-23 00:00:00', 12123.75, 12189.0, 12094.099609375, 12180.349609375, 867700.0)
('2020-01-24 00:00:00', 12174.5498046875, 12272.150390625, 12149.650390625, 12248.25, 593200.0)
('2020-01-27 00:00:00', 12197.099609375, 12216.599609375, 12107.0, 12119.0, 441200.0)
('2020-01-28 00:00:00', 12148.099609375, 12163.5498046875, 12024.5, 12055.7998046875, 478500.0)
('2020-01-29 00:00:00', 12114.900390625, 12169.599609375, 12103.7998046875, 12129.5, 514400.0)
('2020-01-30 00:00:00', 12147.75, 12150.2998046875, 12010.599609375, 12035.7998046875, 538100.0)
('2020-01-31 00:00:00', 12100.400390625, 12103.5498046875, 11945.849609375, 11962.099609375, 771300.0)
('2020-02-03 00:00:00', 11627.4501953125, 11749.849609375, 11614.5, 11707.900390625, 669800.0)
('2020-02-04 00:00:00', 11786.25, 11986.150390625, 11783.400390625, 11979.650390625, 560400.0)
('2020-02-05 00:00:00', 12005.849609375, 12098.150390625, 11953.349609375, 12089.150390625, 758000.0)
('2020-02-06 00:00:00', 12120.0, 12160.599609375, 12084.650390625, 12137.9501953125, 565100.0)
('2020-02-07 00:00:00', 12151.150390625, 12154.7001953125, 12073.9501953125, 12098.349609375, 473500.0)
('2020-02-10 00:00:00', 12102.349609375, 12103.5498046875, 11990.75, 12031.5, 524700.0)
('2020-02-11 00:00:00', 12108.400390625, 12172.2998046875, 12099.0, 12107.900390625, 480000.0)
('2020-02-12 00:00:00', 12151.0, 12231.75, 12144.2998046875, 12201.2001953125, 411700.0)
('2020-02-13 00:00:00', 12219.5498046875, 12225.650390625, 12139.7998046875, 12174.650390625, 501200.0)
('2020-02-14 00:00:00', 12190.150390625, 12246.7001953125, 12091.2001953125, 12113.4501953125, 622800.0)
('2020-02-18 00:00:00', 12028.25, 12030.75, 11908.0498046875, 11992.5, 676900.0)
('2020-02-19 00:00:00', 12090.599609375, 12134.7001953125, 12042.099609375, 12125.900390625, 513600.0)
('2020-02-20 00:00:00', 12119.0, 12152.0, 12071.4501953125, 12080.849609375, 502600.0)
('2020-02-24 00:00:00', 12012.5498046875, 12012.5498046875, 11813.400390625, 11829.400390625, 490800.0)
('2020-02-25 00:00:00', 11877.5, 11883.0498046875, 11779.900390625, 11797.900390625, 461000.0)
('2020-02-26 00:00:00', 11738.5498046875, 11783.25, 11639.599609375, 11678.5, 567600.0)
('2020-02-27 00:00:00', 11661.25, 11663.849609375, 11536.7001953125, 11633.2998046875, 608600.0)
('2020-02-28 00:00:00', 11382.0, 11384.7998046875, 11175.0498046875, 11201.75, 809900.0)
('2020-03-02 00:00:00', 11387.349609375, 11433.0, 11036.25, 11132.75, 680800.0)
('2020-03-03 00:00:00', 11217.5498046875, 11342.25, 11152.5498046875, 11303.2998046875, 696500.0)
('2020-03-04 00:00:00', 11351.349609375, 11356.599609375, 11082.150390625, 11251.0, 797700.0)
('2020-03-05 00:00:00', 11306.0498046875, 11389.5, 11244.599609375, 11269.0, 1352500.0)
('2020-03-06 00:00:00', 10942.650390625, 11035.099609375, 10827.400390625, 10989.4501953125, 1811000.0)
('2020-03-09 00:00:00', 10742.0498046875, 10751.5498046875, 10294.4501953125, 10451.4501953125, 1565500.0)
('2020-03-11 00:00:00', 10334.2998046875, 10545.099609375, 10334.0, 10458.400390625, 1218500.0)
('2020-03-12 00:00:00', 10039.9501953125, 10040.75, 9508.0, 9590.150390625, 1343500.0)
('2020-03-13 00:00:00', 9107.599609375, 10159.400390625, 8555.150390625, 9955.2001953125, 1388000.0)
('2020-03-16 00:00:00', 9587.7998046875, 9602.2001953125, 9165.099609375, 9197.400390625, 897700.0)
('2020-03-17 00:00:00', 9285.400390625, 9403.7998046875, 8915.599609375, 8967.0498046875, 935600.0)
('2020-03-18 00:00:00', 9088.4501953125, 9127.5498046875, 8407.0498046875, 8468.7998046875, 1516600.0)
('2020-03-19 00:00:00', 8063.2998046875, 8575.4501953125, 7832.5498046875, 8263.4501953125, 925700.0)
('2020-03-20 00:00:00', 8284.4501953125, 8883.0, 8178.2001953125, 8745.4501953125, 1071500.0)
('2020-03-23 00:00:00', 7945.7001953125, 8159.25, 7583.60009765625, 7610.25, 653500.0)
('2020-03-24 00:00:00', 7848.2998046875, 8036.9501953125, 7511.10009765625, 7801.0498046875, 738400.0)
('2020-03-25 00:00:00', 7735.14990234375, 8376.75, 7714.75, 8317.849609375, 736900.0)
('2020-03-26 00:00:00', 8451.0, 8749.0498046875, 8304.900390625, 8641.4501953125, 865600.0)
('2020-03-27 00:00:00', 8949.099609375, 9038.900390625, 8522.900390625, 8660.25, 801500.0)
('2020-03-30 00:00:00', 8385.9501953125, 8576.0, 8244.0, 8281.099609375, 593300.0)
('2020-03-31 00:00:00', 8529.349609375, 8678.2998046875, 8358.0, 8597.75, 712700.0)
('2020-04-01 00:00:00', 8584.099609375, 8588.099609375, 8198.349609375, 8253.7998046875, 506300.0)
('2020-04-03 00:00:00', 8356.5498046875, 8356.5498046875, 8055.7998046875, 8083.7998046875, 697000.0)
('2020-04-07 00:00:00', 8446.2998046875, 8819.400390625, 8360.9501953125, 8792.2001953125, 814200.0)
('2020-04-08 00:00:00', 8688.900390625, 9131.7001953125, 8653.900390625, 8748.75, 896500.0)
('2020-04-09 00:00:00', 8973.0498046875, 9128.349609375, 8904.5498046875, 9111.900390625, 742100.0)
('2020-04-13 00:00:00', 9103.9501953125, 9112.0498046875, 8912.400390625, 8993.849609375, 644000.0)
('2020-04-15 00:00:00', 9196.400390625, 9261.2001953125, 8874.099609375, 8925.2998046875, 879100.0)
('2020-04-16 00:00:00', 8851.25, 9053.75, 8821.900390625, 8992.7998046875, 719400.0)
('2020-04-17 00:00:00', 9323.4501953125, 9324.0, 9091.349609375, 9266.75, 684200.0)
('2020-04-20 00:00:00', 9390.2001953125, 9390.849609375, 9230.7998046875, 9261.849609375, 726400.0)
('2020-04-21 00:00:00', 9016.9501953125, 9044.400390625, 8909.400390625, 8981.4501953125, 655100.0)
('2020-04-22 00:00:00', 9026.75, 9209.75, 8946.25, 9187.2998046875, 734400.0)
('2020-04-23 00:00:00', 9232.349609375, 9343.599609375, 9170.150390625, 9313.900390625, 666700.0)
('2020-04-24 00:00:00', 9163.900390625, 9296.900390625, 9141.2998046875, 9154.400390625, 659400.0)
('2020-04-27 00:00:00', 9259.7001953125, 9377.099609375, 9250.349609375, 9282.2998046875, 512800.0)
('2020-04-28 00:00:00', 9389.7998046875, 9404.400390625, 9260.0, 9380.900390625, 614500.0)
('2020-04-29 00:00:00', 9408.599609375, 9599.849609375, 9392.349609375, 9553.349609375, 653000.0)
('2020-04-30 00:00:00', 9753.5, 9889.0498046875, 9731.5, 9859.900390625, 931200.0)
('2020-05-04 00:00:00', 9533.5, 9533.5, 9266.9501953125, 9293.5, 687500.0)
('2020-05-05 00:00:00', 9429.400390625, 9450.900390625, 9190.75, 9205.599609375, 725200.0)
('2020-05-06 00:00:00', 9226.7998046875, 9346.900390625, 9116.5, 9270.900390625, 722200.0)
('2020-05-07 00:00:00', 9234.0498046875, 9277.849609375, 9175.900390625, 9199.0498046875, 708700.0)
('2020-05-08 00:00:00', 9376.9501953125, 9382.650390625, 9238.2001953125, 9251.5, 609100.0)
('2020-05-11 00:00:00', 9348.150390625, 9439.900390625, 9219.9501953125, 9239.2001953125, 704600.0)
('2020-05-12 00:00:00', 9168.849609375, 9240.849609375, 9043.9501953125, 9196.5498046875, 805500.0)
('2020-05-13 00:00:00', 9584.2001953125, 9584.5, 9351.099609375, 9383.5498046875, 846400.0)
('2020-05-14 00:00:00', 9213.9501953125, 9281.099609375, 9119.75, 9142.75, 602600.0)
('2020-05-15 00:00:00', 9182.400390625, 9182.400390625, 9050.0, 9136.849609375, 575900.0)
('2020-05-18 00:00:00', 9158.2998046875, 9158.2998046875, 8806.75, 8823.25, 773000.0)
('2020-05-19 00:00:00', 8961.7001953125, 9030.349609375, 8855.2998046875, 8879.099609375, 762200.0)
('2020-05-20 00:00:00', 8889.150390625, 9093.7998046875, 8875.349609375, 9066.5498046875, 622300.0)
('2020-05-21 00:00:00', 9079.4501953125, 9178.5498046875, 9056.099609375, 9106.25, 631500.0)
('2020-05-22 00:00:00', 9067.900390625, 9149.599609375, 8968.5498046875, 9039.25, 675800.0)
('2020-05-26 00:00:00', 9099.75, 9161.650390625, 8996.650390625, 9029.0498046875, 655000.0)
('2020-05-27 00:00:00', 9082.2001953125, 9334.0, 9004.25, 9314.9501953125, 763500.0)
('2020-05-28 00:00:00', 9364.9501953125, 9511.25, 9336.5, 9490.099609375, 837900.0)
('2020-05-29 00:00:00', 9422.2001953125, 9598.849609375, 9376.900390625, 9580.2998046875, 967000.0)
('2020-06-01 00:00:00', 9726.849609375, 9931.599609375, 9706.9501953125, 9826.150390625, 794200.0)
('2020-06-02 00:00:00', 9880.849609375, 9995.599609375, 9824.0498046875, 9979.099609375, 770200.0)
('2020-06-03 00:00:00', 10108.2998046875, 10176.2001953125, 10035.5498046875, 10061.5498046875, 794700.0)
('2020-06-04 00:00:00', 10054.25, 10123.849609375, 9944.25, 10029.099609375, 775100.0)
('2020-06-05 00:00:00', 10093.7998046875, 10177.7998046875, 10040.75, 10142.150390625, 987100.0)
('2020-06-08 00:00:00', 10326.75, 10328.5, 10120.25, 10167.4501953125, 936500.0)
('2020-06-09 00:00:00', 10181.150390625, 10291.150390625, 10021.4501953125, 10046.650390625, 754200.0)
('2020-06-10 00:00:00', 10072.599609375, 10148.75, 10036.849609375, 10116.150390625, 632400.0)
('2020-06-11 00:00:00', 10094.099609375, 10112.0498046875, 9885.0498046875, 9902.0, 715500.0)
('2020-06-12 00:00:00', 9544.9501953125, 9996.0498046875, 9544.349609375, 9972.900390625, 796300.0)
('2020-06-15 00:00:00', 9919.349609375, 9943.349609375, 9726.349609375, 9813.7001953125, 716100.0)
('2020-06-16 00:00:00', 10014.7998046875, 10046.150390625, 9728.5, 9914.0, 899900.0)
('2020-06-17 00:00:00', 9876.7001953125, 10003.599609375, 9833.7998046875, 9881.150390625, 685400.0)
('2020-06-18 00:00:00', 9863.25, 10111.2001953125, 9845.0498046875, 10091.650390625, 622900.0)
('2020-06-19 00:00:00', 10119.0, 10272.400390625, 10072.650390625, 10244.400390625, 892100.0)
('2020-06-22 00:00:00', 10318.75, 10393.650390625, 10277.599609375, 10311.2001953125, 685400.0)
('2020-06-23 00:00:00', 10347.9501953125, 10484.7001953125, 10301.75, 10471.0, 669200.0)
('2020-06-24 00:00:00', 10529.25, 10553.150390625, 10281.9501953125, 10305.2998046875, 854800.0)
('2020-06-25 00:00:00', 10235.5498046875, 10361.7998046875, 10194.5, 10288.900390625, 994200.0)
('2020-06-26 00:00:00', 10378.900390625, 10409.849609375, 10311.25, 10383.0, 671900.0)
('2020-06-29 00:00:00', 10311.9501953125, 10337.9501953125, 10223.599609375, 10312.400390625, 574500.0)
('2020-06-30 00:00:00', 10382.599609375, 10401.0498046875, 10267.349609375, 10302.099609375, 556200.0)
('2020-07-01 00:00:00', 10323.7998046875, 10447.0498046875, 10299.599609375, 10430.0498046875, 573600.0)
('2020-07-02 00:00:00', 10493.0498046875, 10598.2001953125, 10485.5498046875, 10551.7001953125, 597400.0)
('2020-07-06 00:00:00', 10723.849609375, 10811.400390625, 10695.099609375, 10763.650390625, 571200.0)
('2020-07-07 00:00:00', 10802.849609375, 10813.7998046875, 10689.7001953125, 10799.650390625, 636800.0)
('2020-07-08 00:00:00', 10818.650390625, 10847.849609375, 10676.5498046875, 10705.75, 767900.0)
('2020-07-09 00:00:00', 10755.5498046875, 10836.849609375, 10733.0, 10813.4501953125, 618700.0)
('2020-07-10 00:00:00', 10764.099609375, 10819.400390625, 10713.0, 10768.0498046875, 590700.0)
('2020-07-13 00:00:00', 10851.849609375, 10894.0498046875, 10756.0498046875, 10802.7001953125, 554100.0)
('2020-07-14 00:00:00', 10750.849609375, 10755.650390625, 10562.900390625, 10607.349609375, 532400.0)
('2020-07-15 00:00:00', 10701.0, 10827.4501953125, 10577.75, 10618.2001953125, 715900.0)
('2020-07-16 00:00:00', 10706.2001953125, 10755.2998046875, 10595.2001953125, 10739.9501953125, 694400.0)
('2020-07-17 00:00:00', 10752.0, 10933.4501953125, 10749.650390625, 10901.7001953125, 676900.0)
('2020-07-20 00:00:00', 10999.4501953125, 11037.900390625, 10953.0, 11022.2001953125, 554300.0)
('2020-07-21 00:00:00', 11126.099609375, 11179.5498046875, 11113.25, 11162.25, 772000.0)
('2020-07-22 00:00:00', 11231.2001953125, 11238.099609375, 11056.5498046875, 11132.599609375, 765100.0)
('2020-07-23 00:00:00', 11135.0, 11239.7998046875, 11103.150390625, 11215.4501953125, 621600.0)
('2020-07-24 00:00:00', 11149.9501953125, 11225.400390625, 11090.2998046875, 11194.150390625, 678900.0)
('2020-07-27 00:00:00', 11225.0, 11225.0, 11087.849609375, 11131.7998046875, 588100.0)
('2020-07-28 00:00:00', 11154.099609375, 11317.75, 11151.400390625, 11300.5498046875, 683900.0)
('2020-07-29 00:00:00', 11276.900390625, 11341.400390625, 11149.75, 11202.849609375, 600700.0)
('2020-07-30 00:00:00', 11254.2998046875, 11299.9501953125, 11084.9501953125, 11102.150390625, 677800.0)
('2020-07-31 00:00:00', 11139.5, 11150.400390625, 11026.650390625, 11073.4501953125, 642600.0)
('2020-08-03 00:00:00', 11057.5498046875, 11058.0498046875, 10882.25, 10891.599609375, 680900.0)
('2020-08-04 00:00:00', 10946.650390625, 11112.25, 10908.099609375, 11095.25, 625700.0)
('2020-08-05 00:00:00', 11155.75, 11225.650390625, 11064.0498046875, 11101.650390625, 667600.0)
('2020-08-06 00:00:00', 11185.7001953125, 11256.7998046875, 11127.2998046875, 11200.150390625, 600400.0)
('2020-08-07 00:00:00', 11186.650390625, 11231.900390625, 11142.0498046875, 11214.0498046875, 452600.0)
('2020-08-10 00:00:00', 11270.25, 11337.2998046875, 11238.0, 11270.150390625, 492000.0)
('2020-08-11 00:00:00', 11322.25, 11373.599609375, 11299.150390625, 11322.5, 586100.0)
('2020-08-12 00:00:00', 11289.0, 11322.0, 11242.650390625, 11308.400390625, 609900.0)
('2020-08-13 00:00:00', 11334.849609375, 11359.2998046875, 11269.9501953125, 11300.4501953125, 562400.0)
('2020-08-14 00:00:00', 11353.2998046875, 11366.25, 11111.4501953125, 11178.400390625, 645100.0)
('2020-08-17 00:00:00', 11248.900390625, 11267.099609375, 11144.5, 11247.099609375, 634000.0)
('2020-08-18 00:00:00', 11259.7998046875, 11401.7001953125, 11253.150390625, 11385.349609375, 579200.0)
('2020-08-19 00:00:00', 11452.150390625, 11460.349609375, 11394.099609375, 11408.400390625, 626200.0)
('2020-08-20 00:00:00', 11317.4501953125, 11361.4501953125, 11289.7998046875, 11312.2001953125, 791600.0)
('2020-08-21 00:00:00', 11409.650390625, 11418.5, 11362.2001953125, 11371.599609375, 668700.0)
('2020-08-24 00:00:00', 11412.0, 11497.25, 11410.650390625, 11466.4501953125, 532900.0)
('2020-08-25 00:00:00', 11513.099609375, 11525.900390625, 11423.349609375, 11472.25, 638200.0)
('2020-08-26 00:00:00', 11512.849609375, 11561.75, 11461.849609375, 11549.599609375, 743400.0)
('2020-08-27 00:00:00', 11609.2998046875, 11617.349609375, 11540.599609375, 11559.25, 719800.0)
('2020-08-28 00:00:00', 11602.9501953125, 11686.0498046875, 11589.400390625, 11647.599609375, 807000.0)
('2020-08-31 00:00:00', 11777.5498046875, 11794.25, 11325.849609375, 11387.5, 1371800.0)
('2020-09-01 00:00:00', 11464.2998046875, 11553.5498046875, 11366.900390625, 11470.25, 783800.0)
('2020-09-02 00:00:00', 11478.5498046875, 11554.75, 11430.400390625, 11535.0, 593500.0)
('2020-09-03 00:00:00', 11566.2001953125, 11584.9501953125, 11507.650390625, 11527.4501953125, 607100.0)
('2020-09-04 00:00:00', 11354.400390625, 11452.0498046875, 11303.650390625, 11333.849609375, 681300.0)
('2020-09-08 00:00:00', 11378.5498046875, 11437.25, 11290.4501953125, 11317.349609375, 572200.0)
('2020-09-09 00:00:00', 11218.599609375, 11298.150390625, 11185.150390625, 11278.0, 728900.0)
('2020-09-10 00:00:00', 11363.2998046875, 11464.0498046875, 11327.400390625, 11449.25, 679400.0)
('2020-09-11 00:00:00', 11447.7998046875, 11493.5, 11419.900390625, 11464.4501953125, 554800.0)
('2020-09-14 00:00:00', 11540.150390625, 11568.900390625, 11383.5498046875, 11440.0498046875, 642300.0)
('2020-09-15 00:00:00', 11487.2001953125, 11535.9501953125, 11442.25, 11521.7998046875, 506700.0)
('2020-09-16 00:00:00', 11538.4501953125, 11618.099609375, 11516.75, 11604.5498046875, 527800.0)
('2020-09-17 00:00:00', 11539.400390625, 11587.2001953125, 11498.5, 11516.099609375, 0.0)
('2020-09-18 00:00:00', 11584.099609375, 11584.099609375, 11446.099609375, 11504.9501953125, 764200.0)
('2020-09-21 00:00:00', 11503.7998046875, 11535.25, 11218.5, 11250.5498046875, 602900.0)
('2020-09-22 00:00:00', 11301.75, 11302.2001953125, 11084.650390625, 11153.650390625, 672200.0)
('2020-09-23 00:00:00', 11258.75, 11259.5498046875, 11024.400390625, 11131.849609375, 714900.0)
('2020-09-24 00:00:00', 11011.0, 11015.2998046875, 10790.2001953125, 10805.5498046875, 706100.0)
('2020-09-25 00:00:00', 10910.400390625, 11072.599609375, 10854.849609375, 11050.25, 559600.0)
('2020-09-28 00:00:00', 11140.849609375, 11239.349609375, 11099.849609375, 11227.5498046875, 472800.0)
('2020-09-29 00:00:00', 11288.599609375, 11305.400390625, 11181.0, 11222.400390625, 498300.0)
('2020-09-30 00:00:00', 11244.4501953125, 11295.400390625, 11184.5498046875, 11247.5498046875, 499300.0)
('2020-10-01 00:00:00', 11364.4501953125, 11428.599609375, 11347.0498046875, 11416.9501953125, 447700.0)
('2020-10-05 00:00:00', 11487.7998046875, 11578.0498046875, 11452.2998046875, 11503.349609375, 530600.0)
('2020-10-06 00:00:00', 11603.4501953125, 11680.2998046875, 11564.2998046875, 11662.400390625, 561400.0)
('2020-10-07 00:00:00', 11679.25, 11763.0498046875, 11629.349609375, 11738.849609375, 513400.0)
('2020-10-08 00:00:00', 11835.400390625, 11905.7001953125, 11791.150390625, 11834.599609375, 608800.0)
('2020-10-09 00:00:00', 11852.0498046875, 11938.599609375, 11805.2001953125, 11914.2001953125, 611100.0)
('2020-10-12 00:00:00', 11973.5498046875, 12022.0498046875, 11867.2001953125, 11930.9501953125, 522600.0)
('2020-10-13 00:00:00', 11934.650390625, 11988.2001953125, 11888.900390625, 11934.5, 458300.0)
('2020-10-14 00:00:00', 11917.400390625, 11997.2001953125, 11822.150390625, 11971.0498046875, 569200.0)
('2020-10-15 00:00:00', 12023.4501953125, 12025.4501953125, 11661.2998046875, 11680.349609375, 608900.0)
('2020-10-16 00:00:00', 11727.400390625, 11789.75, 11667.849609375, 11762.4501953125, 555800.0)
('2020-10-19 00:00:00', 11879.2001953125, 11898.25, 11820.400390625, 11873.0498046875, 541400.0)
('2020-10-20 00:00:00', 11861.0, 11949.25, 11837.25, 11896.7998046875, 453600.0)
('2020-10-21 00:00:00', 11958.5498046875, 12018.650390625, 11775.75, 11937.650390625, 623700.0)
('2020-10-22 00:00:00', 11890.0, 11939.5498046875, 11823.4501953125, 11896.4501953125, 544900.0)
('2020-10-23 00:00:00', 11957.900390625, 11974.5498046875, 11908.75, 11930.349609375, 502300.0)
('2020-10-26 00:00:00', 11937.400390625, 11942.849609375, 11711.7001953125, 11767.75, 519800.0)
('2020-10-27 00:00:00', 11807.099609375, 11899.0498046875, 11723.0, 11889.400390625, 616300.0)
('2020-10-28 00:00:00', 11922.599609375, 11929.400390625, 11684.849609375, 11729.599609375, 704000.0)
('2020-10-29 00:00:00', 11633.2998046875, 11744.150390625, 11606.4501953125, 11670.7998046875, 555000.0)
('2020-10-30 00:00:00', 11678.4501953125, 11748.9501953125, 11535.4501953125, 11642.400390625, 553700.0)
('2020-11-02 00:00:00', 11697.349609375, 11725.650390625, 11557.400390625, 11669.150390625, 568400.0)
('2020-11-03 00:00:00', 11734.4501953125, 11836.2001953125, 11723.2998046875, 11813.5, 674300.0)
('2020-11-04 00:00:00', 11783.349609375, 11929.650390625, 11756.400390625, 11908.5, 667300.0)

In [ ]:
import sqlite3

# Re-establish connection to the database
conn = sqlite3.connect('stocks.db')
cursor = conn.cursor()

cursor.execute("""
SELECT date, ticker,close
FROM stocks
WHERE ticker = '^IXIC'
ORDER BY close DESC
LIMIT 1
""")


rows = cursor.fetchall()

for row in rows:
    print(row)#Find the highest closing price for NASDAQ (^IXIC)

('2025-10-29 00:00:00', '^IXIC', 23958.470703125)

In [ ]:






cursor.execute("""
SELECT date, high,low,
(high - low) AS price_difference
FROM stocks
WHERE ticker = '^GSPC'
ORDER BY price_difference DESC
LIMIT 5
""")


rows = cursor.fetchall()

for row in rows:
    print(row)#List top 5 days with highest price difference (high - low) for S&P 500 (^GSPC)

('2025-04-09 00:00:00', 5481.33984375, 4948.43017578125, 532.90966796875)
('2025-04-07 00:00:00', 5246.56982421875, 4835.0400390625, 411.52978515625)
('2025-04-08 00:00:00', 5267.47021484375, 4910.419921875, 357.05029296875)
('2025-11-20 00:00:00', 6770.35009765625, 6534.0498046875, 236.30029296875)
('2025-04-04 00:00:00', 5292.14013671875, 5069.89990234375, 222.240234375)

In [ ]:




cursor.execute("""
SELECT
    ticker,
    strftime('%Y-%m', date) AS month,
    AVG(close)
FROM stocks
GROUP BY ticker, month
ORDER BY ticker, month
LIMIT 20
""")


rows = cursor.fetchall()

for row in rows:
    print(row)#Get monthly average closing price for each ticker

('^GSPC', '2020-01', 3278.202857607887)
('^GSPC', '2020-02', 3273.956637912326)
('^GSPC', '2020-03', 2641.449044363839)
('^GSPC', '2020-04', 2775.8244357638887)
('^GSPC', '2020-05', 2924.287353515625)
('^GSPC', '2020-06', 3104.6609330610795)
('^GSPC', '2020-07', 3207.6190962357955)
('^GSPC', '2020-08', 3391.7100190662204)
('^GSPC', '2020-09', 3365.516671316964)
('^GSPC', '2020-10', 3422.0466657366073)
('^GSPC', '2020-11', 3540.628323025174)
('^GSPC', '2020-12', 3695.3100142045455)
('^GSPC', '2021-01', 3790.6444498697915)
('^GSPC', '2021-02', 3883.4321160567433)
('^GSPC', '2021-03', 3906.25048828125)
('^GSPC', '2021-04', 4140.348427220395)
('^GSPC', '2021-05', 4170.762669613487)
('^GSPC', '2021-06', 4238.48954634233)
('^GSPC', '2021-07', 4363.963940429688)
('^GSPC', '2021-08', 4456.259556361607)

In [ ]:
cursor.execute("""
SELECT
    AVG(volume)
FROM stocks
WHERE ticker = '^NSEI'
AND date BETWEEN '2024-01-01' AND '2024-12-31'
""")

rows = cursor.fetchall()

for row in rows:
    print(row)#Get average trading volume of NSEI in 2024

(316511.39240506326,)

merge 4 datas

In [ ]:
for db in ["Crypto_prices.db","Cryptocurrencies.db","Oil_prices.db","stocks.db"]:
    conn = sqlite3.connect(db)
    cursor = conn.cursor()

    cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
    print(db, "->", cursor.fetchall())

    conn.close()

Crypto_prices.db -> [('Crypto_prices',)]
Cryptocurrencies.db -> [('Cryptocurrencies',)]
Oil_prices.db -> [('Oil_prices',)]
stocks.db -> [('stocks',)]

In [ ]:
merged_df = pd.concat(
    [Cryptocurrencies_df,Crypto_prices_df,Oil_prices_df,stock_prices_df],
    axis=1
)


Cryptocurrencies_df,Crypto_prices_df,Oil_prices_df,stock_prices_df

(                       id symbol                 name  current_price  \
 0                 bitcoin    btc              Bitcoin   6.878855e+06
 1                ethereum    eth             Ethereum   2.156630e+05
 2                  tether   usdt               Tether   9.241000e+01
 3                  ripple    xrp                  XRP   1.412000e+02
 4             binancecoin    bnb                  BNB   6.215000e+04
 ...                   ...    ...                  ...            ...
 1245             tutorial    tut             Tutorial   1.029000e+00
 1246            chainbase      c            Chainbase   5.360000e+00
 1247  dialectic-eth-vault   deth  Dialectic ETH Vault   2.171370e+05
 1248                 seth   seth                 sETH   7.407400e+04
 1249               wolf-2   wolf                 WOLF   8.571000e-01

            market_cap  market_cap_rank  total_volume  circulating_supply  \
 0     137593653306772                1  5.024783e+12        2.000304e+07
 1      26026523841219                2  2.773542e+12        1.206919e+08
 2      17010782833133                3  8.500853e+12        1.840709e+11
 3       8645814013079                4  4.497152e+11        6.122783e+10
 4       8474126353407                5  1.222935e+11        1.363578e+08
 ...               ...              ...           ...                 ...
 1245        859763677             1246  2.545654e+08        8.357810e+08
 1246        858712436             1245  1.001865e+09        1.600000e+08
 1247        858697057             1247  4.081440e+03        3.961882e+03
 1248        857770218             1248  1.993040e+03        1.157991e+04
 1249        857072097             1249  3.305823e+06        9.999790e+08

       total_supply          ath            atl        date
 0     2.000304e+07  11187013.00    3993.420000  2026-03-17
 1     1.206919e+08    431946.00      28.130000  2026-03-17
 2     1.895378e+11       105.52      36.860000  2026-03-17
 3     9.998570e+10       313.99       0.159343  2026-03-17
 4     1.363578e+08    121422.00       2.580000  2026-03-17
 ...            ...          ...            ...         ...
 1245  8.357810e+08        14.95       0.025182  2026-03-17
 1246  1.000000e+09        44.82       4.230000  2026-03-17
 1247  3.961882e+03    422188.00  161106.000000  2026-03-17
 1248  1.157991e+04    423415.00       0.945060  2026-03-17
 1249  9.999790e+08         4.19       0.247676  2026-03-17

 [1250 rows x 12 columns],
       coin_id        date     price_inr
 0     bitcoin  2025-03-18  7.307625e+06
 1     bitcoin  2025-03-19  7.166131e+06
 2     bitcoin  2025-03-20  7.495414e+06
 3     bitcoin  2025-03-21  7.275141e+06
 4     bitcoin  2025-03-22  7.224001e+06
 ...       ...         ...           ...
 1093   tether  2026-03-14  9.261318e+01
 1094   tether  2026-03-15  9.259796e+01
 1095   tether  2026-03-16  9.257168e+01
 1096   tether  2026-03-17  9.226888e+01
 1097   tether  2026-03-17  9.240820e+01

 [1098 rows x 3 columns],
             Date  Price
 0     2020-01-02  61.17
 1     2020-01-03  63.00
 2     2020-01-06  63.27
 3     2020-01-07  62.70
 4     2020-01-08  59.65
 ...          ...    ...
 1515  2026-01-26  60.46
 1516  2026-01-27  62.04
 1517  2026-01-28  62.75
 1518  2026-01-29  64.77
 1519  2026-01-30  64.50

 [1520 rows x 2 columns],
 Ticker       Date        ^GSPC                                         \
 Price                     Open         High          Low        Close
 1      2020-01-02  3244.669922  3258.139893  3235.530029  3257.850098
 2      2020-01-03  3226.360107  3246.149902  3222.340088  3234.850098
 3      2020-01-06  3217.550049  3246.840088  3214.639893  3246.280029
 4      2020-01-07  3241.860107  3244.909912  3232.429932  3237.179932
 5      2020-01-08  3238.590088  3267.070068  3236.669922  3253.050049
 ...           ...          ...          ...          ...          ...
 1558   2026-01-05  6892.189941  6920.379883  6891.560059  6902.049805
 1559   2026-01-06  6908.029785  6948.689941  6904.020020  6944.819824
 1560   2026-01-07  6945.069824  6965.689941  6919.189941  6920.930176
 1561   2026-01-08  6914.109863  6931.279785  6899.330078  6921.459961
 1562   2026-01-09  6927.830078  6978.359863  6917.640137  6966.279785

 Ticker                       ^IXIC                                            \
 Price         Volume          Open          High           Low         Close
 1       3.459930e+09   9039.459961   9093.429688   9010.889648   9092.190430
 2       3.484700e+09   8976.429688   9065.759766   8976.429688   9020.769531
 3       3.702460e+09   8943.500000   9072.410156   8943.500000   9071.469727
 4       3.435910e+09   9076.639648   9091.929688   9042.549805   9068.580078
 5       3.726840e+09   9068.030273   9168.889648   9059.379883   9129.240234
 ...              ...           ...           ...           ...           ...
 1558    5.771930e+09  23449.669922  23476.509766  23332.230469  23395.820312
 1559    5.509680e+09  23446.960938  23559.150391  23389.570312  23547.169922
 1560    5.214480e+09  23544.890625  23723.369141  23504.210938  23584.279297
 1561    5.333200e+09  23548.880859  23558.169922  23353.460938  23480.019531
 1562    5.163900e+09  23496.210938  23721.150391  23426.480469  23671.349609

 Ticker                       ^NSEI                                            \
 Price         Volume          Open          High           Low         Close
 1       2.862700e+09  12198.549805  12289.900391  12195.250000  12282.200195
 2       2.586520e+09  12261.099609  12265.599609  12191.349609  12226.650391
 3       2.810450e+09  12170.599609  12179.099609  11974.200195  11993.049805
 4       2.381740e+09  12079.099609  12152.150391  12005.349609  12052.950195
 5       2.472620e+09  11939.099609  12044.950195  11929.599609  12025.349609
 ...              ...           ...           ...           ...           ...
 1558    8.737320e+09  26333.699219  26373.199219  26210.050781  26250.300781
 1559    9.012640e+09  26189.699219  26273.949219  26124.750000  26178.699219
 1560    8.396920e+09  26143.099609  26187.150391  26067.900391  26140.750000
 1561    7.723140e+09  26106.500000  26133.199219  25858.449219  25876.849609
 1562    8.124420e+09  25840.400391  25940.599609  25623.000000  25683.300781

 Ticker
 Price     Volume
 1       407700.0
 2       428800.0
 3       396500.0
 4       447800.0
 5       446000.0
 ...          ...
 1558    338800.0
 1559    383000.0
 1560    338200.0
 1561    328500.0
 1562    348800.0

 [1444 rows x 16 columns])

In [ ]:
merged_df.head()

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,...,"(^IXIC, Open)","(^IXIC, High)","(^IXIC, Low)","(^IXIC, Close)","(^IXIC, Volume)","(^NSEI, Open)","(^NSEI, High)","(^NSEI, Low)","(^NSEI, Close)","(^NSEI, Volume)"
0,bitcoin,btc,Bitcoin,6878855.00,1.375937e+14,1.0,5.024783e+12,2.000304e+07,2.000304e+07,11187013.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ethereum,eth,Ethereum,215663.00,2.602652e+13,2.0,2.773542e+12,1.206919e+08,1.206919e+08,431946.00,...,9039.459961,9093.429688,9010.889648,9092.190430,2.862700e+09,12198.549805,12289.900391,12195.250000,12282.200195,407700.0
2,tether,usdt,Tether,92.41,1.701078e+13,3.0,8.500853e+12,1.840709e+11,1.895378e+11,105.52,...,8976.429688,9065.759766,8976.429688,9020.769531,2.586520e+09,12261.099609,12265.599609,12191.349609,12226.650391,428800.0
3,ripple,xrp,XRP,141.20,8.645814e+12,4.0,4.497152e+11,6.122783e+10,9.998570e+10,313.99,...,8943.500000,9072.410156,8943.500000,9071.469727,2.810450e+09,12170.599609,12179.099609,11974.200195,11993.049805,396500.0
4,binancecoin,bnb,BNB,62150.00,8.474126e+12,5.0,1.222935e+11,1.363578e+08,1.363578e+08,121422.00,...,9076.639648,9091.929688,9042.549805,9068.580078,2.381740e+09,12079.099609,12152.150391,12005.349609,12052.950195,447800.0

In [ ]:
print(merged_df.columns)

Index([                'id',             'symbol',               'name',
            'current_price',         'market_cap',    'market_cap_rank',
             'total_volume', 'circulating_supply',       'total_supply',
                      'ath',                'atl',               'date',
                  'coin_id',               'date',          'price_inr',
                     'Date',              'Price',         ('Date', ''),
          ('^GSPC', 'Open'),    ('^GSPC', 'High'),     ('^GSPC', 'Low'),
         ('^GSPC', 'Close'),  ('^GSPC', 'Volume'),    ('^IXIC', 'Open'),
          ('^IXIC', 'High'),     ('^IXIC', 'Low'),   ('^IXIC', 'Close'),
        ('^IXIC', 'Volume'),    ('^NSEI', 'Open'),    ('^NSEI', 'High'),
           ('^NSEI', 'Low'),   ('^NSEI', 'Close'),  ('^NSEI', 'Volume')],
      dtype='object')

In [ ]:
gspc.rename(columns={('Date',''): 'date'}, inplace=True)
ixic.rename(columns={('Date',''): 'date'}, inplace=True)
nsei.rename(columns={('Date',''): 'date'}, inplace=True)

In [ ]:
merged_df.columns = [
             'id',             'symbol',               'name',
            'current_price',         'market_cap',    'market_cap_rank',
             'total_volume', 'circulating_supply',       'total_supply',
                      'ath',                'atl',               'date',
                  'coin_id',               'date',          'price_inr',
                     'date',              'Price',         ('Date', ''),
          ('^GSPC', 'Open'),    ('^GSPC', 'High'),     ('^GSPC', 'Low'),
         ('^GSPC', 'Close'),  ('^GSPC', 'Volume'),    ('^IXIC', 'Open'),
          ('^IXIC', 'High'),     ('^IXIC', 'Low'),   ('^IXIC', 'Close'),
        ('^IXIC', 'Volume'),    ('^NSEI', 'Open'),    ('^NSEI', 'High'),
           ('^NSEI', 'Low'),   ('^NSEI', 'Close'),  ('^NSEI', 'Volume')]

In [ ]:
merged_df.columns = [
    '_'.join(col).replace('^','') if isinstance(col, tuple) else col.replace('^','')
    for col in merged_df.columns
]

In [ ]:
merged_df = merged_df.loc[:, ~merged_df.columns.duplicated()] #removes duplicate date column

In [ ]:
import sqlite3

# Re-establish connection to the database
conn = sqlite3.connect('merged_data.db')
cursor = conn.cursor()

In [ ]:
merged_df.to_sql("merged_data",conn,if_exists="replace", index=False)

 # Pushing dataframe into sql

1561

In [ ]:
cursor.execute("""
SELECT
    'Bitcoin' AS asset,
    AVG(price_inr) AS avg_price_2025
FROM merged_data
WHERE coin_id = 'bitcoin'
  AND date BETWEEN '2026-01-01' AND '2026-12-31'

UNION ALL

SELECT
    'Oil' AS asset,
    AVG(price) AS avg_price_2025
FROM  merged_data
WHERE date BETWEEN '2026-01-01' AND '2026-12-31'
""")

results = cursor.fetchall()
for r in results:
    print(r)#Compare Bitcoin vs Oil average price in 2026.

('Bitcoin', 8617070.031517716)
('Oil', 71.23506399999997)

In [ ]:
print(merged_df.columns)

Index(['id', 'symbol', 'name', 'current_price', 'market_cap',
       'market_cap_rank', 'total_volume', 'circulating_supply', 'total_supply',
       'ath', 'atl', 'date', 'coin_id', 'price_inr', 'Price', 'Date_',
       'GSPC_Open', 'GSPC_High', 'GSPC_Low', 'GSPC_Close', 'GSPC_Volume',
       'IXIC_Open', 'IXIC_High', 'IXIC_Low', 'IXIC_Close', 'IXIC_Volume',
       'NSEI_Open', 'NSEI_High', 'NSEI_Low', 'NSEI_Close', 'NSEI_Volume'],
      dtype='object')

In [ ]:
import pandas as pd#Get Bitcoin data,#Get S&P 500 close prices

cursor.execute("""
SELECT Date, price_inr, GSPC_Close AS sp500_close
FROM merged_data
WHERE coin_id = 'bitcoin'
""")

correlation = merged_df["price_inr"].corr(
    merged_df["GSPC_Close"]
)

print("Correlation between Bitcoin and S&P 500:", correlation)#Check if Bitcoin moves with S&P 500 (correlation idea).

Correlation between Bitcoin and S&P 500: -0.7711399367817395

In [ ]:
cursor.execute("""
SELECT
date, Price,price_inr,
IXIC_Close AS nasdaq_close
FROM merged_data
WHERE coin_id = 'ethereum'
AND date BETWEEN '2026-01-01' AND '2026-12-31'

""")


daily_prices = cursor.fetchall()

for row in daily_prices:
    print(row)

 # Compare Ethereum and NASDAQ daily prices for 2025.

('2026-03-17', 71.06, 167679.9006033522, 13756.330078125)
('2026-03-17', 71.64, 167319.001543521, 13614.509765625)
('2026-03-17', 73.64, 177917.82793888426, 13814.490234375)
('2026-03-17', 73.15, 171006.12473780697, 13881.7197265625)
('2026-03-17', 73.11, 168930.37673281875, 13924.91015625)
('2026-03-17', 73.31, 170229.9761188356, 13911.75)
('2026-03-17', 74.21, 172085.9718554942, 14020.330078125)
('2026-03-17', 72.98, 177753.92370784696, 14069.419921875)
('2026-03-17', 73.14, 177052.68464483944, 14174.1396484375)
('2026-03-17', 73.52, 172151.5682806194, 14072.8603515625)
('2026-03-17', 75.33, 171697.82772804037, 14039.6796875)
('2026-03-17', 75.37, 162266.37796915465, 14161.349609375)
('2026-03-17', 73.62, 156474.22180351955, 14030.3798828125)
('2026-03-17', 72.22, 154426.70647452315, 14141.48046875)
('2026-03-17', 72.98, 155840.4924805317, 14253.26953125)
('2026-03-17', 74.56, 163227.64895741257, 14271.73046875)
('2026-03-17', 74.21, 153890.04212059852, 14369.7099609375)
('2026-03-17', 75.24, 155066.27550185894, 14360.3896484375)
('2026-03-02', 73.06, 155313.1292931023, 14500.509765625)
('2026-03-17', 71.67, 154802.90633012433, 14528.330078125)
('2026-03-17', 71.76, 134677.50142669896, 14503.9501953125)
('2026-03-17', 66.45, 133837.57278106204, 14522.3798828125)
('2026-03-17', 67.32, 127176.85742857557, 14639.330078125)
('2026-03-17', 70.26, 143324.73934384843, None)
('2026-03-17', 72.15, 131454.92128790365, 14663.6396484375)
('2026-03-17', 72.24, 134990.81789744264, 14665.0595703125)
('2026-03-17', 72.15, 141499.98989505236, 14559.7802734375)
('2026-03-17', 71.68, 137163.51905527923, 14701.919921875)
('2026-03-17', 72.37, 139502.26918137303, 14733.240234375)
('2026-03-17', 73.62, 136118.34029958773, 14677.650390625)
('2026-03-17', 73.93, 135084.25007491114, 14644.9501953125)
('2026-03-17', 71.31, 135202.85645156694, 14543.1298828125)
('2026-03-17', 70.64, 135687.4227659859, 14427.240234375)
('2026-03-17', 68.19, 137898.7403436233, 14274.98046875)
('2026-03-17', 69.1, 135372.22120159038, 14498.8798828125)
('2026-03-17', 68.26, 134334.00818529903, None)
('2026-03-17', 66.56, 149984.44480204728, 14684.599609375)
('2026-03-17', 68.33, 153384.6912264906, 14836.990234375)
('2026-03-17', 69.3, 150793.82263866183, 14840.7099609375)
('2026-03-17', 69.12, 152736.0854367373, 14660.580078125)
('2026-03-17', 68.36, 155508.64352977095, 14762.580078125)
('2026-03-17', 67.44, 153154.64715995087, 14778.259765625)
('2026-03-17', 66.5, 153246.47199208362, 14672.6796875)
('2026-03-17', 65.36, 153045.86830616, 14681.0703125)
('2026-03-17', 63.69, 151706.98921091956, 14761.2900390625)
('2026-03-17', 62.25, 155745.16924065605, 14780.5302734375)
('2026-03-17', 65.65, 155840.93772632716, 14895.1201171875)
('2026-03-17', 67.5, 155254.81405305702, 14835.759765625)
('2026-03-17', 68.54, 152837.10606631296, 14860.1796875)
('2026-03-17', 67.42, 153282.69389658255, 14788.08984375)
('2026-03-17', 68.84, 153903.86052217713, 14765.1396484375)
('2026-03-17', 69.28, 153546.46543390723, 14816.259765625)
('2026-03-17', 68.43, 189067.0538600533, 14822.900390625)
('2026-03-17', 68.63, 199979.47617304884, 14793.759765625)
('2026-03-17', 70.07, 220672.16056835878, 14656.1796875)
('2026-03-17', 69.34, 214170.10011952536, 14525.91015625)
('2026-03-17', 68.49, 211740.19586880849, None)
('2026-03-17', 69.36, 227649.06017478785, 14714.66015625)
('2026-03-17', 68.26, 222550.86125964453, 14942.650390625)
('2026-03-17', 69.82, 217226.91460543944, 15019.7998046875)
('2026-03-17', 70.54, 217756.90685748137, 15041.8603515625)
('2026-03-17', 70.53, 211823.19396124792, 14945.8095703125)
('2026-03-17', 72.59, 210787.9756927576, 15129.5)
('2026-03-17', 72.69, 215738.55684027018, 15265.8896484375)
('2026-03-17', 72.09, 215915.19935485243, 15259.240234375)
('2026-03-17', 70.41, 219047.5756337483, 15309.3798828125)
('2026-03-17', 70.51, 228450.3696380665, 15331.1796875)
('2026-03-17', 72.37, 214375.8056090152, 15363.51953125)
('2026-03-17', 73.43, 215195.01779836757, None)
('2026-03-17', 74.18, 216970.8522801864, 15374.330078125)
('2026-03-17', 75.54, 218190.67523487698, 15286.6396484375)
('2026-03-17', 75.44, 227238.5848495167, 15248.25)
('2026-03-17', 75.06, 228525.93909568293, None)
('2026-03-17', 75.22, 224768.84403505738, 15105.580078125)
('2026-03-17', 76.01, 216016.02336935312, 15037.759765625)
('2026-03-17', 77.68, 216690.8648491384, 15161.5302734375)
('2026-03-17', 79.17, 217089.5740742275, 15181.919921875)
('2026-03-17', 77.66, 222777.49872829148, 15043.9697265625)
('2026-03-17', 78.46, 222455.17860950096, 14713.900390625)
('2026-03-17', 79.55, 224236.44416331983, 14746.400390625)
('2026-03-17', 80.64, 207961.65418872624, 14896.849609375)
('2026-03-17', 80.75, 212876.9182145838, 15052.240234375)
('2026-03-17', 80.67, 216727.81140618862, 15047.7001953125)
('2026-03-17', 81.43, 215217.42336418747, 14969.9697265625)
('2026-03-17', 82.39, 230255.54711844953, 14546.6796875)
('2026-03-17', 82.62, 240556.86572695823, 14512.4404296875)
('2026-03-17', 83.19, 237276.58179525606, 14448.580078125)
('2026-03-17', 84.4, 227345.61024210224, 14566.7001953125)
('2026-03-17', 82.64, 221936.8494721614, 14255.48046875)
('2026-03-17', 84.53, 218235.52611319744, 14433.830078125)
('2026-03-17', 84.64, 219421.86983518038, 14501.91015625)
('2026-03-17', 85.64, 220541.89744913176, 14654.01953125)
('2026-03-17', 82.66, 217182.0562912451, 14579.5400390625)
('2026-03-17', 82.78, 218382.42014738446, 14486.2001953125)
('2026-03-17', 83.5, 218767.0130883784, 14465.919921875)
('2026-03-17', 84.08, 208337.07852694736, 14571.6396484375)
('2026-03-17', 83.91, 196636.0383307714, 14823.4296875)
('2026-03-17', 80.82, 192852.03096719063, None)
('2026-03-17', 78.88, 209315.24780590468, 15021.8095703125)
('2026-03-17', 81.25, 210338.28060317386, 15129.08984375)
('2026-03-17', 81.96, 207894.42363255343, 15121.6796875)
('2026-03-17', 84.12, 206903.99097231845, 15215.7001953125)
('2026-03-17', 81.23, 207191.0496905718, 15090.2001953125)
('2026-03-17', 81.47, 208396.95938860573, 15226.7099609375)
('2026-03-17', 80.87, 213866.80820581852, 15235.7099609375)
('2026-03-17', 80.85, 213247.902753943, 15235.83984375)
('2026-03-17', 80.76, 206191.53795072352, 15448.1201171875)
('2026-03-17', 78.32, 220583.0677146267, 15498.3896484375)
('2026-03-17', 78.92, 221209.20718607036, 15595.919921875)
('2026-03-17', 76.11, 214841.71925105614, 15649.599609375)
('2026-03-17', 76.74, 215995.5389160479, 15811.580078125)
('2026-03-17', 78.32, 219842.28509645213, 15940.3095703125)
('2026-03-17', 78.32, 218478.50703220506, None)
('2026-03-17', 69.88, 224192.01293457407, 15982.3603515625)
('2026-03-17', 66.14, 237634.3285912139, 15886.5400390625)
('2026-03-17', 65.44, 252785.18261104374, 15622.7099609375)
('2026-03-17', 66.6, 253963.71411998925, 15704.2802734375)
('2026-03-17', 66.39, 252599.85968309751, 15860.9599609375)
('2026-03-17', 69.62, 255256.0749124428, 15853.849609375)
('2026-03-17', 71.94, 258953.02296009834, 15973.8603515625)
('2026-03-17', 72.43, 269423.17285168904, 15921.5703125)
('2026-03-17', 70.87, 289273.06195820443, 15993.7099609375)
('2026-03-17', 71.71, 299604.7001320289, None)
('2026-03-17', 71.19, 305580.9799247014, 15854.759765625)
('2026-03-17', 70.57, 309629.88231970003, 15775.1396484375)
('2026-03-17', 70.89, 323799.5635112756, 15845.23046875)
('2026-03-17', 72.34, 324888.02667051577, None)
('2026-03-17', 70.93, 323522.2855073287, 15491.66015625)
('2026-03-17', 68.69, 313632.80993368995, 15782.830078125)
('2026-03-17', 71.1, 320521.28663827025, 15537.6904296875)
('2026-03-17', 72.82, 322067.53188592376, 15254.0498046875)
('2026-03-17', 73.89, 323729.6744159729, 15381.3203125)
('2026-03-17', 75.49, 334271.3356334813, 15085.4697265625)
('2026-03-17', 76.01, 328567.3072022601, 15225.150390625)
('2026-03-17', 76.58, 329848.44489638496, 15686.919921875)
('2026-03-17', 76.83, 333798.49786685634, 15786.990234375)
('2026-03-17', 75.33, 323419.73918441863, 15517.3701171875)
('2026-03-17', 75.99, 303617.9116663577, 15630.599609375)
('2026-03-17', 77.0, 296151.6805356246, 15413.2802734375)
('2026-03-17', 77.83, 305147.6597239278, 15237.6396484375)
('2026-03-17', 79.47, 326586.85608261486, 15565.580078125)
('2026-03-17', 79.0, 316895.55183794844, 15180.4296875)
('2026-03-17', 78.11, 323322.0010279766, 15169.6796875)
('2026-03-17', 81.17, 341975.0422938313, 14980.9404296875)
('2026-03-17', 82.51, 352049.4403810017, 15341.08984375)
('2026-03-17', 81.97, 374193.3376648639, 15521.8896484375)
('2026-03-17', 83.82, 372140.5970629246, 15653.3701171875)
('2026-03-17', 85.42, 370718.8174494866, None)
('2026-03-17', 86.84, 403547.06190802733, 15871.259765625)
('2026-03-17', 86.29, 416582.6051270567, 15781.7197265625)
('2026-03-17', 85.16, 399375.2127189976, 15766.2197265625)
('2026-03-17', 84.48, 387732.95356370165, 15741.5595703125)
('2026-03-17', 86.61, 387408.6664674909, 15644.9697265625)
('2026-03-17', 88.33, 392681.4189909559, 15832.7998046875)
('2026-03-17', 87.61, 376878.0982824829, 15622.7197265625)
('2026-03-17', 87.67, 354772.70430919825, 15100.169921875)
('2026-03-17', 89.16, 376832.66666282027, 15080.8603515625)
('2026-03-17', 88.22, 368766.6639472321, 14935.900390625)
('2026-03-17', 88.16, 421737.4738716338, 14942.830078125)
('2026-03-17', 90.17, 416904.49092835333, 15153.4501953125)
('2026-03-17', 92.27, 417273.9071184703, 15188.3896484375)
('2026-03-17', 91.25, 383869.2304155191, 14806.8095703125)
('2026-03-17', 89.32, 403346.84673449927, 14893.75)
('2026-03-17', 89.57, 394479.82107990474, None)
('2026-03-17', 89.83, 394824.62858350464, 14506.900390625)
('2026-03-17', 93.1, 384794.36172029114, 14340.259765625)
('2026-03-17', 95.52, 385618.86285304534, 14154.01953125)
('2026-03-17', 92.07, 386992.0744205619, 13768.919921875)
('2026-03-17', 93.83, 378688.487081064, 13855.1298828125)
('2026-03-17', 91.78, 380669.0608269572, 13539.2900390625)
('2026-03-17', 91.26, 391914.25736500154, None)
('2026-03-17', 92.11, 379062.50711160863, 13352.7802734375)
('2026-03-17', 92.14, 379789.69451721257, 13770.5703125)
('2026-03-17', 92.77, 376830.61714539555, 14239.8798828125)
('2026-03-17', 91.68, 379557.7315665512, 14346.0)
('2026-03-17', 96.13, 379169.3803941581, 14417.5498046875)
('2026-03-17', 103.66, 380163.9598970403, 13878.8203125)
('2026-03-17', 110.74, 382811.6356012148, 14098.009765625)
('2026-03-17', 107.69, 393614.0739117057, 14015.669921875)
('2026-03-17', 115.77, 415686.0060768963, 14194.4501953125)
('2026-03-17', 119.26, 412052.856085073, 14490.3701171875)
('2026-03-17', 123.64, 406940.596240047, 14185.6396484375)
('2026-03-17', 108.81, 398693.42995223537, 13791.150390625)
('2026-03-17', 105.93, 395856.797622927, 13790.919921875)
('2026-03-17', 109.31, 403666.7568900215, 14139.759765625)
('2026-03-17', 103.22, 404926.98327490315, 14124.08984375)
('2026-03-17', 96.42, 393846.3358485685, 13716.7197265625)
('2026-03-17', 94.85, 394843.6203459821, 13548.0703125)
('2026-03-17', 102.97, 392295.47524281475, None)
('2026-03-17', 104.69, 370875.27142150694, 13381.51953125)
('2026-03-17', 112.14, 369992.0919011612, 13037.490234375)
('2026-03-17', 111.03, 368312.96560615575, 13473.58984375)
('2026-03-17', 114.89, 342937.4440185811, 13694.6201171875)
('2026-03-17', 114.2, 357978.55612770614, 13751.400390625)
('2026-03-17', 116.2, 356321.1005771281, None)
('2026-03-17', 107.55, 367286.12298418215, 13752.01953125)
('2026-03-17', 104.25, 373944.85329388455, 13537.9404296875)
('2026-03-17', 107.81, 368177.3713848715, 13313.4404296875)
('2026-03-17', 100.53, 385235.77973544877, 12830.9599609375)
('2026-03-17', 99.32, 397823.05193989933, 12795.5498046875)
('2026-03-17', 103.29, 400707.46142882656, 13255.5498046875)
('2026-03-17', 101.98, 398218.8935895547, 13129.9599609375)
('2026-03-17', 96.39, 400668.6421398132, 12843.8095703125)
('2026-03-17', 96.05, 416041.06085392536, 12581.2197265625)
('2026-03-17', 98.35, 395289.8026309068, 12948.6201171875)
('2026-03-17', 94.22, 401911.0484708849, 13436.5498046875)
('2026-03-17', 100.52, 388222.87205311254, 13614.7802734375)
('2026-03-17', 104.26, 340432.9353676543, None)
('2026-03-17', 106.84, 332747.98798714374, 13838.4599609375)
('2026-03-17', 108.24, 369207.3362657844, 14108.8203125)
('2026-03-17', 102.54, 376492.3574048653, 13922.599609375)
('2026-03-17', 102.56, 366574.05838423775, 14191.83984375)
('2026-03-17', 103.89, 349761.3884710538, 14169.2998046875)
('2026-03-17', 102.86, 342302.33220614656, 14354.900390625)
('2026-03-17', 99.6, 337247.7588866496, 14619.6396484375)
('2026-03-17', 102.62, 342375.6803081046, 14442.26953125)
('2026-03-17', 101.96, 350696.6804336402, 14220.51953125)
('2026-03-17', 105.47, 349657.073530753, 14261.5)
('2026-03-17', 104.59, 341303.9842640361, 14532.5498046875)
('2026-03-17', 105.18, 333571.21535914514, 14204.169921875)
('2026-03-17', 102.53, 338462.9290819708, 13888.8203125)
('2026-03-17', 107.84, 345416.6546043208, 13897.2998046875)
('2026-03-17', 108.17, 347083.5922685809, 13711.0)
('2026-03-17', 109.72, 365539.5621120337, 13411.9599609375)
('2026-03-17', 103.08, 363758.94232227415, 13371.5703125)
('2026-03-17', 99.74, 351342.5325721324, 13643.58984375)
('2026-03-17', 105.5, 344315.5289450759, None)
('2026-03-17', 106.15, 337015.4990615576, 13332.3603515625)
('2026-03-17', 110.52, 341801.10296794504, 13619.66015625)
('2026-03-17', 114.07, 343730.3913686987, 13453.0703125)
('2026-03-17', 112.31, 347169.85800323385, 13174.650390625)
('2026-03-17', 109.67, 319468.25832003524, 12839.2900390625)
('2026-03-17', 112.21, 292527.2014230804, 13004.849609375)
('2026-03-17', 112.63, 303546.1807953054, 12490.740234375)
('2026-03-17', 110.32, 293412.52766766545, 12488.9296875)
('2026-03-17', 112.55, 304507.99491275364, 12871.5302734375)
('2026-03-17', 112.88, 301591.6290594234, 12334.6396484375)
('2026-03-17', 116.19, 317071.7291616941, 12536.01953125)
('2026-03-17', 114.96, 316207.1597353334, None)
('2026-03-17', 114.38, 302271.19106009, 12964.8603515625)
('2026-03-17', 115.26, 302072.2252489844, 12317.6904296875)
('2026-03-17', 116.88, 287385.51825001417, 12144.66015625)
('2026-03-17', 118.97, 275511.26516527805, 11623.25)
('2026-03-17', 118.41, 281155.6844835739, 11737.669921875)
('2026-03-17', 119.55, 275080.20597856207, 11364.240234375)
('2026-03-17', 121.94, 267796.5731112152, 11370.9599609375)
('2026-03-17', 121.52, 276052.04898099863, 11805.0)
('2026-03-17', 120.73, 267032.830083096, 11662.7900390625)
('2026-03-17', 120.92, 251183.08126814634, 11984.51953125)
('2026-03-17', 118.92, 247777.39778764817, 11418.150390625)
('2026-03-17', 115.32, 248183.09115512334, 11388.5)
('2026-03-17', 117.56, 250950.12836319354, 11354.6201171875)
('2026-03-17', 109.56, 263283.40358322934, 11535.26953125)
('2026-03-17', 110.49, 263444.9399900479, 11264.4501953125)
('2026-03-17', 106.22, 269938.1970950932, 11434.740234375)
('2026-03-17', 105.75, 269490.2527975858, 11740.650390625)
('2026-03-17', 109.07, 271004.1486761167, 12131.1298828125)
('2026-03-17', 111.44, 267260.2384447111, None)
('2026-03-17', 113.66, 267424.4592587914, 12081.3896484375)
('2026-03-17', 111.65, 250829.94408877468, 11994.4599609375)
('2026-03-17', 107.76, 269370.30418167287, 12316.900390625)
('2026-03-17', 110.3, 288132.42535713845, 12012.73046875)
('2026-03-17', 101.55, 281520.95159888716, 12061.3701171875)
('2026-03-17', 100.31, 271893.52182715805, 12175.23046875)
('2026-03-17', 104.62, 273416.13820120675, 12086.26953125)
('2026-03-17', 106.78, 274616.2375638853, 11754.23046875)
('2026-03-17', 106.09, 281685.69218486216, 11340.01953125)
('2026-03-17', 97.69, 298746.9630305986, 10809.23046875)
('2026-03-17', 98.44, 298675.7147486205, 10828.349609375)
('2026-03-17', 97.79, 292065.55714175856, 11099.150390625)
('2026-03-12', 99.59, 279306.9974351619, 10646.099609375)
('2026-03-17', 104.48, 282191.1596649078, 10798.349609375)
('2026-03-17', 106.12, 277686.2575249929, None)
('2026-03-17', 104.45, 269107.8224748998, 11069.2998046875)
('2026-03-17', 98.44, 269596.8374095658, 11053.080078125)
('2026-03-17', 97.71, 255672.94816147196, 11232.1904296875)
('2026-03-17', 99.83, 255132.82641488407, 11607.6201171875)
('2026-03-17', 97.74, 266653.5750632806, 11524.5498046875)
('2026-03-17', 100.03, 266686.3060581252, 11181.5400390625)
('2026-03-17', 99.11, 268857.45721078233, 11177.8896484375)
('2026-03-17', 101.31, 269330.66898642445, 11028.740234375)
('2026-03-17', 96.59, 265308.33057719615, 11127.849609375)
('2026-03-17', 97.14, 264638.4624631536, None)
('2026-03-17', 93.25, 261698.83888170918, 11322.240234375)
('2026-03-17', 91.29, 262776.73658441985, 11361.849609375)
('2026-03-17', 91.77, 264850.5744899021, 11621.349609375)
('2026-03-17', 93.52, 264760.5504658988, 11635.3095703125)
('2026-03-17', 93.18, 263786.42273046816, 11372.599609375)
('2026-03-17', 94.68, 266620.8671552428, 11264.73046875)
('2026-03-17', 97.02, 266951.6312463789, 11247.580078125)
('2026-03-17', 94.86, 269940.3569195695, 11251.1904296875)
('2026-03-17', 92.24, 281016.1719855551, 11452.419921875)
('2026-03-17', 89.23, 281388.8695194364, 11360.0498046875)
('2026-03-17', 90.85, 282560.6030133936, 11713.150390625)
('2026-03-17', 93.2, 291299.3568651643, 11897.650390625)
('2026-03-15', 93.55, 297045.36579862604, 12059.6103515625)
('2026-03-17', 93.42, 284403.12191626645, 11834.1103515625)
('2026-03-17', 96.46, 279086.945835317, 11782.669921875)
('2026-03-17', 95.52, 278309.6101406161, 11562.5703125)
('2026-03-17', 93.33, 278294.1933407241, 12032.419921875)
('2026-03-17', 93.63, 281519.50124331604, 12162.58984375)
('2026-03-17', 97.4, 278535.9889192714, 12390.6904296875)
('2026-03-17', 92.08, 299728.9177688779, 12368.98046875)
('2026-03-17', 90.09, 302917.5844429012, 12348.759765625)
('2026-03-17', 87.09, 299838.3615803796, 12668.16015625)
('2026-03-17', 87.29, 299041.3190188698, 12720.580078125)
('2026-03-17', 87.35, 300496.6677650833, 12657.5498046875)
('2026-03-17', 82.5, 297943.7602436932, 12644.4599609375)
('2026-03-17', 84.04, 289592.03165583033, None)
('2026-03-17', 87.27, 267489.81096221146, 12854.7998046875)
('2026-03-17', 88.18, 272419.05713641306, 12779.91015625)
('2026-03-17', 87.84, 269940.0485702116, 13047.1904296875)
('2026-03-17', 88.88, 270322.79786255566, None)
('2026-03-17', 85.72, 270125.836049164, 13102.5498046875)
('2026-03-17', 85.57, 257898.21011062048, 12938.1201171875)
('2026-03-17', 86.15, 268521.1124032741, 12965.33984375)
('2026-03-14', 84.69, 276537.237355733, 12705.2197265625)
('2026-03-17', 83.38, 276752.68161058764, 12381.5703125)
('2026-03-17', 84.02, 258717.1664228855, 12381.2998046875)
('2026-03-17', 79.07, 247763.65614624374, 12431.5302734375)
('2026-03-17', 77.17, 224065.64499097393, 12639.26953125)
('2026-03-17', 78.91, 208098.68569226892, 12141.7099609375)
('2026-03-17', 82.61, 212055.7416695305, 12017.669921875)
('2026-03-17', 81.78, 201371.05394647823, 11883.1396484375)
('2026-03-17', 79.91, 194638.91147198106, None)
('2026-03-17', 84.05, 164424.8093049238, 11785.1298828125)
('2026-03-17', 86.87, 186695.3649137571, 11630.8603515625)
('2026-03-17', 88.22, 189440.9269478321, None)
('2026-03-17', 88.9, 189754.81871261535, 11544.91015625)
('2026-03-17', 93.07, 191035.83888725925, 11791.900390625)
('2026-03-17', 91.6, 182890.5822309681, 11862.1298828125)
('2026-03-17', 89.75, 175976.56404532818, 12112.3095703125)
('2026-03-17', 87.83, 176214.23834483154, 12266.41015625)
('2026-03-17', 89.59, 185411.2111430372, 11633.5703125)
('2026-03-17', 86.1, 188855.60230133013, 11719.6796875)
('2026-03-17', 86.0, 177856.25063894037, 11552.3603515625)
('2026-03-17', 83.29, 181624.1547003928, 11448.400390625)
('2026-03-17', 86.0, 180528.32834312637, 11535.01953125)
('2026-03-17', 86.02, 177478.4599141033, 11425.0498046875)
('2026-03-17', 85.47, 177249.2474816647, 11220.1904296875)
('2026-03-17', 86.12, 178533.39457288812, 11066.8095703125)
('2026-03-17', 86.93, 179064.34776215904, 10867.9296875)
('2026-03-17', 89.39, 177305.13210485573, 10802.919921875)
('2026-03-17', 89.06, 168724.9961412896, 10829.5)
('2026-03-17', 87.85, 168454.26945512652, 11051.6396484375)
('2026-03-17', 86.54, 186740.27349943476, 10737.509765625)

In [ ]:
cursor.execute("""
SELECT
    date,
    Price,
    LAG(Price) OVER (ORDER BY date) AS prev_price,
    (Price - LAG(Price) OVER (ORDER BY date)) * 100.0
        / LAG(Price) OVER (ORDER BY date) AS pct_change
FROM merged_data
""")

rows = cursor.fetchall()#Find days when oil price spiked and compare with Bitcoin price change.

for r in rows:
    print(r)

(None, 71.73, None, None)
(None, 72.44, 71.73, 0.9898229471629635)
(None, 73.79, 72.44, 1.8636112644947662)
(None, 74.64, 73.79, 1.1519176040113759)
(None, 74.31, 74.64, -0.44212218649517454)
(None, 74.99, 74.31, 0.9150854528327178)
(None, 73.99, 74.99, -1.3335111348179758)
(None, 77.27, 73.99, 4.433031490741994)
(None, 79.57, 77.27, 2.97657564384625)
(None, 78.2, 79.57, -1.721754430061569)
(None, 80.73, 78.2, 3.23529411764706)
(None, 79.35, 80.73, -1.7094017094017213)
(None, 78.56, 79.35, -0.9955891619407587)
(None, 76.79, 78.56, -2.2530549898166954)
(None, 76.12, 76.79, -0.8725094413335092)
(None, 75.03, 76.12, -1.431949553336841)
(None, 74.97, 75.03, -0.07996801279488508)
(None, 73.51, 74.97, -1.9474456449246282)
(None, 74.15, 73.51, 0.8706298462794185)
(None, 72.94, 74.15, -1.6318273769386484)
(None, 73.1, 72.94, 0.2193583767480074)
(None, 72.84, 73.1, -0.3556771545827509)
(None, 73.52, 72.84, 0.9335529928610552)
(None, 73.04, 73.52, -0.6528835690968305)
(None, 71.39, 73.04, -2.259036144578321)
(None, 70.97, 71.39, -0.5883176915534413)
(None, 71.32, 70.97, 0.4931661265323296)
(None, 72.73, 71.32, 1.9770050476724774)
(None, 73.67, 72.73, 1.2924515330675068)
(None, 71.72, 73.67, -2.6469390525315633)
(None, 71.66, 71.72, -0.083658672615731)
(None, 71.05, 71.66, -0.8512419759977665)
(None, 72.21, 71.05, 1.6326530612244852)
(None, 72.58, 72.21, 0.5123944052070414)
(None, 72.88, 72.58, 0.41333700744006224)
(None, 70.72, 72.88, -2.9637760702524654)
(None, 71.06, 70.72, 0.4807692307692356)
(None, 69.15, 71.06, -2.687869406135655)
(None, 68.87, 69.15, -0.404916847433118)
(None, 70.62, 68.87, 2.541019311746769)
(None, 69.97, 70.62, -0.9204191447182182)
(None, 68.63, 69.97, -1.9151064742032349)
(None, 68.47, 68.63, -0.2331341978726455)
(None, 66.58, 68.47, -2.7603329925514832)
(None, 66.62, 66.58, 0.06007810153200098)
(None, 67.29, 66.62, 1.005703992794959)
(None, 66.31, 67.29, -1.456382820627142)
(None, 66.52, 66.31, 0.31669431458300973)
(None, 67.65, 66.52, 1.6987372218881687)
(None, 66.82, 67.65, -1.2269031781227087)
(None, 67.43, 66.82, 0.9129003292427622)
(None, 67.84, 67.43, 0.6080379652973402)
(None, 67.49, 67.84, -0.5159198113207673)
(None, 67.4, 67.49, -0.13335308934655388)
(None, 68.55, 67.4, 1.706231454005922)
(None, 68.52, 68.55, -0.043763676148798156)
(None, 69.46, 68.52, 1.3718622300058345)
(None, 69.48, 69.46, 0.02879355024475991)
(None, 70.05, 69.48, 0.8203799654576758)
(None, 70.3, 70.05, 0.35688793718772305)
(None, 69.74, 70.3, -0.7965860597439578)
(None, 71.87, 69.74, 3.0542013191855606)
(None, 71.61, 71.87, -0.3617642966467303)
(None, 72.12, 71.61, 0.7121910347716871)
(None, 67.43, 72.12, -6.503050471436491)
(None, 62.42, 67.43, -7.429927332048057)
(None, 61.05, 62.42, -2.194809355975656)
(None, 60.04, 61.05, -1.6543816543816512)
(None, 62.63, 60.04, 4.313790806129253)
(None, 60.57, 62.63, -3.2891585502155554)
(None, 61.91, 60.57, 2.212316328215282)
(None, 61.99, 61.91, 0.1292198352447188)
(None, 61.74, 61.99, -0.4032908533634457)
(None, 62.88, 61.74, 1.846452866861031)
(None, 65.07, 62.88, 3.482824427480901)
(None, 63.48, 65.07, -2.443522360534803)
(None, 64.6, 63.48, 1.7643352236924976)
(None, 62.64, 64.6, -3.03405572755417)
(None, 63.55, 62.64, 1.452745849297568)
(None, 63.85, 63.55, 0.4720692368214072)
(None, 63.3, 63.85, -0.8613938919342274)
(None, 61.84, 63.3, -2.3064770932069414)
(None, 59.55, 61.84, -3.703104786545935)
(None, 60.59, 59.55, 1.7464315701091626)
(None, 59.67, 60.59, -1.5184023766298096)
(None, 58.5, 59.67, -1.960784313725493)
(None, 60.42, 58.5, 3.282051282051285)
(None, 59.42, 60.42, -1.6550810989738496)
(None, 61.25, 59.42, 3.079771120834733)
(None, 62.37, 61.25, 1.8285714285714243)
(None, 63.32, 62.37, 1.523168189834861)
(None, 65.04, 63.32, 2.7163613392293207)
(None, 64.48, 65.04, -0.8610086100861043)
(None, 63.03, 64.48, -2.2487593052109225)
(None, 63.84, 63.03, 1.2851023322227546)
(None, 63.98, 63.84, 0.21929824561402483)
(None, 63.97, 63.98, -0.015629884338852783)
(None, 62.93, 63.97, -1.625762075973111)
(None, 62.55, 62.93, -0.6038455426664588)
(None, 62.89, 62.55, 0.5435651478817001)
(None, 61.61, 62.89, -2.0352997296867565)
(None, 62.54, 61.61, 1.5094952118162632)
(None, 61.66, 62.54, -1.4070994563479415)
(None, 61.46, 61.66, -0.3243593902043395)
(None, 63.27, 61.46, 2.945004881223564)
(None, 64.1, 63.27, 1.3118381539434032)
(None, 63.57, 64.1, -0.8268330733229237)
(None, 64.06, 63.57, 0.770803838288504)
(None, 65.3, 64.06, 1.9356852950358958)
(None, 65.99, 65.3, 1.0566615620214361)
(None, 65.66, 65.99, -0.500075769055915)
(None, 68.91, 65.66, 4.949741090466038)
(None, 68.73, 68.91, -0.26121027427077725)
(None, 73.84, 68.73, 7.4348901498617765)
(None, 72.53, 73.84, -1.7741061755146292)
(None, 75.62, 72.53, 4.260306080242663)
(None, 75.89, 75.62, 0.3570483998942026)
(None, 75.72, 75.89, -0.2240084332586661)
(None, 69.36, 75.72, -8.399366085578446)
(None, 65.45, 69.36, -5.637254901960779)
(None, 65.98, 65.45, 0.8097784568372821)
(None, 66.44, 65.98, 0.6971809639284536)
(None, 66.66, 66.44, 0.33112582781456784)
(None, 66.3, 66.66, -0.5400540054005393)
(None, 66.64, 66.3, 0.512820512820518)
(None, 68.66, 66.64, 3.0312124849939917)
(None, 68.13, 68.66, -0.7719196038450352)
(None, 69.16, 68.13, 1.5118156465580526)
(None, 69.55, 69.16, 0.563909774436091)
(None, 69.61, 69.55, 0.08626887131560355)
(None, 67.78, 69.61, -2.628932624622897)
(None, 69.63, 67.78, 2.7294187075833496)
(None, 68.19, 69.63, -2.068074105988795)
(None, 67.76, 68.19, -0.6305909957471661)
(None, 67.13, 67.76, -0.9297520661157167)
(None, 68.76, 67.13, 2.4281245344853417)
(None, 68.53, 68.76, -0.3344968004653926)
(None, 68.39, 68.53, -0.2042900919305422)
(None, 67.56, 68.39, -1.2136277233513646)
(None, 66.05, 67.56, -2.235050325636479)
(None, 67.16, 66.05, 1.6805450416351242)
(None, 66.38, 67.16, -1.1614055985705796)
(None, 67.81, 66.38, 2.154263332329025)
(None, 70.27, 67.81, 3.6277835127562215)
(None, 71.09, 70.27, 1.1669275651060302)
(None, 70.36, 71.09, -1.0268673512449065)
(None, 68.39, 70.36, -2.79988629903354)
(None, 67.33, 68.39, -1.5499342009065686)
(None, 66.2, 67.33, -1.6783009059854381)
(None, 65.38, 66.2, -1.2386706948640593)
(None, 64.9, 65.38, -0.7341694707861576)
(None, 64.94, 64.9, 0.061633281972252756)
(None, 65.03, 64.94, 0.13858946720049803)
(None, 64.22, 65.03, -1.2455789635552856)
(None, 63.68, 64.22, -0.8408595453129853)
(None, 64.99, 63.68, 2.057160804020093)
(None, 63.78, 64.99, -1.8618248961378578)
(None, 64.51, 63.78, 1.1445594230166258)
(None, 63.38, 64.51, -1.7516664083087932)
(None, 64.19, 63.38, 1.2780056800252368)
(None, 64.56, 64.19, 0.5764137716155235)
(None, 64.08, 64.56, -0.7434944237918277)
(None, 65.18, 64.08, 1.7166042446941456)
(None, 63.6, 65.18, -2.4240564590365223)
(None, 64.49, 63.6, 1.3993710691823795)
(None, 64.96, 64.49, 0.7287951620406248)
(None, 64.36, 64.96, -0.9236453201970357)
(None, 65.95, 64.36, 2.470478558110633)
(None, 64.36, 65.95, -2.410917361637609)
(None, 63.81, 64.36, -0.8545680546923511)
(None, 62.22, 63.81, -2.491772449459338)
(None, 62.6, 62.22, 0.6107360977177797)
(None, 62.97, 62.6, 0.5910543130990374)
(None, 64.01, 62.97, 1.6515801175162876)
(None, 62.71, 64.01, -2.0309326667708234)
(None, 63.02, 62.71, 0.49433902088981385)
(None, 63.66, 63.02, 1.0155506188511478)
(None, 64.89, 63.66, 1.932139491046189)
(None, 64.41, 64.89, -0.7397133610725904)
(None, 63.91, 64.41, -0.776276975624903)
(None, 63.02, 63.91, -1.3925833202941535)
(None, 62.99, 63.02, -0.04760393525864985)
(None, 63.76, 62.99, 1.2224162565486523)
(None, 65.4, 63.76, 2.57214554579675)
(None, 65.51, 65.4, 0.16819571865443336)
(None, 66.5, 65.51, 1.5112196611204316)
(None, 64.27, 66.5, -3.3533834586466225)
(None, 63.17, 64.27, -1.7115294849852098)
(None, 62.59, 63.17, -0.9181573531739723)
(None, 61.28, 62.59, -2.0929861000159806)
(None, 61.65, 61.28, 0.6037859007832856)
(None, 62.49, 61.65, 1.3625304136253098)
(None, 62.52, 62.49, 0.048007681228998456)
(None, 63.37, 62.52, 1.3595649392194407)
(None, 62.36, 63.37, -1.5938141076219001)
(None, 59.75, 62.36, -4.185375240538806)
(None, 59.52, 59.75, -0.38493723849371864)
(None, 59.08, 59.52, -0.7392473118279651)
(None, 58.29, 59.08, -1.3371699390656722)
(None, 58.3, 58.29, 0.017155601303822286)
(None, 58.34, 58.3, 0.06861063464838123)
(None, 58.66, 58.34, 0.5485087418580616)
(None, 59.3, 58.66, 1.091033071939994)
(None, 62.44, 59.3, 5.295109612141654)
(None, 62.27, 62.44, -0.2722613709160708)
(None, 62.13, 62.27, -0.22482736470210465)
(None, 60.97, 62.13, -1.867052953484635)
(None, 61.26, 60.97, 0.4756437592258474)
(None, 61.36, 61.26, 0.16323865491348583)
(None, 61.75, 61.36, 0.635593220338984)
(None, 61.79, 61.75, 0.06477732793522128)
(None, 61.38, 61.79, -0.6635377892862868)
(None, 60.4, 61.38, -1.5966112740306353)
(None, 60.24, 60.4, -0.26490066225165)
(None, 60.54, 60.24, 0.4980079681274853)
(None, 60.94, 60.54, 0.6607201850016494)
(None, 59.3, 60.94, -2.6911716442402374)
(None, 59.54, 59.3, 0.40472175379426983)
(None, 60.87, 59.54, 2.2337924084648946)
(None, 60.66, 60.87, -0.34499753573188907)
(None, 61.51, 60.66, 1.4012528849324126)
(None, 60.27, 61.51, -2.015932368720525)
(None, 60.07, 60.27, -0.33184005309441317)
(None, 58.86, 60.07, -2.0143166305976377)
(None, 59.11, 58.86, 0.42473666326877335)
(None, 58.25, 59.11, -1.454914566063271)
(None, 58.81, 58.25, 0.9613733905579438)
(None, 58.58, 58.81, -0.39108995068866514)
(None, 59.47, 58.58, 1.5192898600204858)
(None, 58.81, 59.47, -1.109803262148977)
(None, 59.09, 58.81, 0.4761095051861947)
(None, 59.82, 59.09, 1.235403621594173)
(None, 60.23, 59.82, 0.6853895018388442)
(None, 59.04, 60.23, -1.975759588245057)
(None, 58.4, 59.04, -1.084010840108402)
(None, 58.67, 58.4, 0.462328767123293)
(None, 57.76, 58.67, -1.551048235895694)
(None, 57.61, 57.76, -0.25969529085872334)
(None, 56.97, 57.61, -1.1109182433605287)
(None, 55.44, 56.97, -2.685624012638233)
(None, 56.07, 55.44, 1.1363636363636411)
(None, 56.22, 56.07, 0.26752273943284927)
(None, 56.8, 56.22, 1.031661330487368)
(None, 58.18, 56.8, 2.429577464788737)
(None, 58.55, 58.18, 0.6359573736679227)
(None, 58.72, 58.55, 0.2903501280956477)
(None, 56.6, 58.72, -3.610354223433238)
(None, 57.89, 56.6, 2.279151943462896)
(None, 57.79, 57.89, -0.17274140611504823)
(None, 57.26, 57.79, -0.917113687489187)
(None, 57.21, 57.26, -0.08732099196646378)
(None, 58.1, 57.21, 1.5556720852997736)
(None, 56.97, 58.1, -1.9449225473321903)
(None, 56.01, 56.97, -1.6850974196945776)
(None, 57.74, 56.01, 3.0887341546152545)
(None, 58.96, 57.74, 2.112919986144785)
(None, 59.39, 58.96, 0.7293080054274079)
(None, 60.85, 59.39, 2.4583263175618804)
(None, 61.84, 60.85, 1.6269515201314741)
(None, 59.13, 61.84, -4.382276843467014)
(None, 59.4, 59.13, 0.4566210045662033)
(None, 60.3, 59.4, 1.5151515151515127)
(None, 60.38, 60.3, 0.13266998341626104)
(None, 59.24, 60.38, -1.888042398145082)
(None, 60.7, 59.24, 2.4645509790681985)
(None, 60.46, 60.7, -0.3953871499176309)
(None, 62.04, 60.46, 2.6132980482963917)
(None, 62.75, 62.04, 1.1444229529335925)
(None, 64.77, 62.75, 3.219123505976089)
(None, 64.5, 64.77, -0.41685965724872015)
(None, None, 64.5, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
(None, None, None, None)
('2026-02-26', 76.53, None, None)
('2026-03-02', 73.06, 76.53, -4.5341696066901855)
('2026-03-04', 78.96, 73.06, 8.075554338899522)
('2026-03-04', 76.46, 78.96, -3.1661600810536985)
('2026-03-12', 99.59, 76.46, 30.251111692388193)
('2026-03-13', 70.1, 99.59, -29.611406767747773)
('2026-03-14', 68.79, 70.1, -1.8687589158345053)
('2026-03-14', 84.69, 68.79, 23.113824683820308)
('2026-03-14', 73.4, 84.69, -13.330971779430856)
('2026-03-15', 93.55, 73.4, 27.452316076294263)
('2026-03-15', 70.02, 93.55, -25.152324959914484)
('2026-03-16', 47.27, 70.02, -32.4907169380177)
('2026-03-16', 47.02, 47.27, -0.5288766659614977)
('2026-03-16', 60.4, 47.02, 28.455976180348777)
('2026-03-17', 61.17, 60.4, 1.274834437086098)
('2026-03-17', 63.0, 61.17, 2.9916625796959266)
('2026-03-17', 63.27, 63.0, 0.42857142857143354)
('2026-03-17', 62.7, 63.27, -0.9009009009009014)
('2026-03-17', 59.65, 62.7, -4.86443381180224)
('2026-03-17', 59.56, 59.65, -0.15088013411566858)
('2026-03-17', 59.02, 59.56, -0.9066487575554049)
('2026-03-17', 58.17, 59.02, -1.440189766180958)
('2026-03-17', 58.34, 58.17, 0.2922468626439775)
('2026-03-17', 57.86, 58.34, -0.8227631127871168)
('2026-03-17', 58.52, 57.86, 1.1406844106463943)
('2026-03-17', 58.55, 58.52, 0.05126452494872527)
('2026-03-17', 58.25, 58.55, -0.5123825789923094)
('2026-03-17', 56.76, 58.25, -2.5579399141630934)
('2026-03-17', 55.51, 56.76, -2.2022551092318534)
('2026-03-17', 54.09, 55.51, -2.5580976400648434)
('2026-03-17', 53.09, 54.09, -1.848770567572564)
('2026-03-17', 53.33, 53.09, 0.4520625353173759)
('2026-03-17', 53.29, 53.33, -0.07500468779298547)
('2026-03-17', 52.19, 53.29, -2.064177143929445)
('2026-03-17', 51.58, 52.19, -1.1688062847288743)
('2026-03-17', 50.06, 51.58, -2.9468786351298877)
('2026-03-17', 49.59, 50.06, -0.9388733519776246)
('2026-03-17', 50.87, 49.59, 2.581165557572079)
('2026-03-17', 50.94, 50.87, 0.1376056614900733)
('2026-03-17', 50.34, 50.94, -1.177856301531202)
('2026-03-17', 49.59, 50.34, -1.4898688915375446)
('2026-03-17', 50.0, 49.59, 0.8267795926598035)
('2026-03-17', 51.13, 50.0, 2.260000000000005)
('2026-03-17', 51.41, 51.13, 0.547623704283188)
('2026-03-17', 52.03, 51.41, 1.2059910523244595)
('2026-03-17', 52.1, 52.03, 0.13453776667307377)
('2026-03-17', 53.31, 52.1, 2.322456813819579)
('2026-03-17', 53.77, 53.31, 0.8628775089101498)
('2026-03-17', 53.36, 53.77, -0.7625069741491606)
('2026-03-17', 51.36, 53.36, -3.7481259370314843)
('2026-03-17', 49.78, 51.36, -3.0763239875389377)
('2026-03-17', 48.67, 49.78, -2.2298111691442335)
('2026-03-17', 47.17, 48.67, -3.081980686254366)
('2026-03-17', 44.83, 47.17, -4.9607801568793795)
('2026-03-17', 46.78, 44.83, 4.349765781842523)
('2026-03-17', 46.78, 46.78, 0.0)
('2026-03-17', 45.9, 46.78, -1.8811457887986374)
('2026-03-17', 41.14, 45.9, -10.370370370370365)
('2026-03-17', 31.05, 41.14, -24.52600875060768)
('2026-03-17', 34.47, 31.05, 11.014492753623182)
('2026-03-17', 33.13, 34.47, -3.8874383521903)
('2026-03-17', 31.56, 33.13, -4.7389073347419375)
('2026-03-17', 31.72, 31.56, 0.5069708491761729)
('2026-03-17', 28.96, 31.72, -8.701134930643121)
('2026-03-17', 26.96, 28.96, -6.906077348066298)
('2026-03-17', 20.48, 26.96, -24.03560830860534)
('2026-03-17', 25.09, 20.48, 22.509765624999996)
('2026-03-17', 19.48, 25.09, -22.359505779194897)
('2026-03-17', 23.33, 19.48, 19.763860369609844)
('2026-03-17', 21.03, 23.33, -9.858551221603074)
('2026-03-17', 20.75, 21.03, -1.3314312886352884)
('2026-03-17', 16.6, 20.75, -19.999999999999993)
('2026-03-17', 15.48, 16.6, -6.746987951807235)
('2026-03-17', 14.1, 15.48, -8.914728682170548)
('2026-03-17', 20.51, 14.1, 45.46099290780143)
('2026-03-17', 20.28, 20.51, -1.12140419307655)
('2026-03-17', 25.18, 20.28, 24.16173570019723)
('2026-03-17', 28.36, 25.18, 12.629070691024623)
('2026-03-17', 26.21, 28.36, -7.581100141043719)
('2026-03-17', 23.54, 26.21, -10.186951545211757)
('2026-03-17', 24.97, 23.54, 6.074766355140186)
('2026-03-17', 22.9, 24.97, -8.289947937525032)
('2026-03-17', 22.36, 22.9, -2.358078602620084)
('2026-03-17', 20.15, 22.36, -9.883720930232561)
('2026-03-17', 19.96, 20.15, -0.942928039702222)
('2026-03-17', 19.82, 19.96, -0.7014028056112253)
('2026-03-17', 18.31, 19.82, -7.618567103935427)
('2026-03-17', -36.98, 18.31, -301.9661387220098)
('2026-03-17', 8.91, -36.98, -124.09410492157924)
('2026-03-17', 13.64, 8.91, 53.086419753086425)
('2026-03-17', 15.06, 13.64, 10.410557184750733)
('2026-03-17', 15.99, 15.06, 6.175298804780875)
('2026-03-17', 12.17, 15.99, -23.889931207004377)
('2026-03-17', 12.4, 12.17, 1.889893179950702)
('2026-03-17', 15.04, 12.4, 21.290322580645153)
('2026-03-17', 19.23, 15.04, 27.8590425531915)
('2026-03-17', 19.72, 19.23, 2.548101924076955)
('2026-03-17', 20.47, 19.72, 3.803245436105477)
('2026-03-17', 24.56, 20.47, 19.98045920859795)
('2026-03-17', 23.88, 24.56, -2.76872964169381)
('2026-03-17', 23.68, 23.88, -0.8375209380234476)
('2026-03-17', 24.73, 23.68, 4.434121621621625)
('2026-03-17', 24.02, 24.73, -2.871006874241815)
('2026-03-17', 25.76, 24.02, 7.243963363863456)
('2026-03-17', 25.37, 25.76, -1.5139751552795053)
('2026-03-17', 27.4, 25.37, 8.00157666535277)
('2026-03-17', 29.44, 27.4, 7.445255474452566)
('2026-03-17', 31.83, 29.44, 8.11820652173912)
('2026-03-17', 32.3, 31.83, 1.4765944077913882)
('2026-03-17', 33.56, 32.3, 3.9009287925696756)
('2026-03-17', 34.3, 33.56, 2.205005959475551)
('2026-03-17', 33.49, 34.3, -2.3615160349854087)
('2026-03-17', 34.7, 33.49, 3.61301881158555)
('2026-03-17', 32.8, 34.7, -5.475504322766587)
('2026-03-17', 33.67, 32.8, 2.652439024390258)
('2026-03-17', 35.57, 33.67, 5.643005643005639)
('2026-03-17', 35.49, 35.57, -0.2249086308687048)
('2026-03-17', 36.88, 35.49, 3.9165962242885333)
('2026-03-17', 37.33, 36.88, 1.2201735357917454)
('2026-03-17', 37.42, 37.33, 0.24109295472810988)
('2026-03-17', 39.49, 37.42, 5.531801175841796)
('2026-03-17', 38.17, 39.49, -3.342618384401115)
('2026-03-17', 38.98, 38.17, 2.1220854073879885)
('2026-03-17', 39.54, 38.98, 1.4366341713699393)
('2026-03-17', 36.43, 39.54, -7.865452706120383)
('2026-03-17', 36.24, 36.43, -0.5215481745813827)
('2026-03-17', 37.07, 36.24, 2.2902869757174344)
('2026-03-17', 38.26, 37.07, 3.2101429727542428)
('2026-03-17', 37.91, 38.26, -0.9147935180345046)
('2026-03-17', 38.79, 37.91, 2.3212872592983453)
('2026-03-17', 39.72, 38.79, 2.3975251353441602)
('2026-03-17', 40.6, 39.72, 2.2155085599194426)
('2026-03-17', 40.4, 40.6, -0.49261083743843065)
('2026-03-17', 37.91, 40.4, -6.163366336633668)
('2026-03-17', 38.66, 37.91, 1.9783698232656293)
('2026-03-17', 38.53, 38.66, -0.33626487325399756)
('2026-03-17', 39.67, 38.53, 2.9587334544510786)
('2026-03-17', 39.27, 39.67, -1.0083186286866614)
('2026-03-17', 39.88, 39.27, 1.55334861217214)
('2026-03-17', 40.57, 39.88, 1.7301905717151396)
('2026-03-17', 40.51, 40.57, -0.14789253142716854)
('2026-03-17', 40.59, 40.51, 0.19748210318441226)
('2026-03-17', 40.91, 40.59, 0.7883715200788203)
('2026-03-17', 39.64, 40.91, -3.104375458323139)
('2026-03-17', 40.56, 39.64, 2.3208879919273504)
('2026-03-17', 40.06, 40.56, -1.2327416173570018)
('2026-03-17', 40.3, 40.06, 0.5991013479780202)
('2026-03-17', 41.2, 40.3, 2.233250620347409)
('2026-03-17', 40.74, 41.2, -1.116504854368934)
('2026-03-17', 40.55, 40.74, -0.46637211585666377)
('2026-03-17', 40.83, 40.55, 0.6905055487053049)
('2026-03-17', 41.76, 40.83, 2.2777369581190294)
('2026-03-17', 41.88, 41.76, 0.2873563218390914)
('2026-03-17', 40.99, 41.88, -2.125119388729705)
('2026-03-17', 41.23, 40.99, 0.5855086606489263)
('2026-03-17', 41.46, 41.23, 0.5578462284744216)
('2026-03-17', 40.89, 41.46, -1.3748191027496388)
('2026-03-17', 41.13, 40.89, 0.5869405722670629)
('2026-03-17', 39.85, 41.13, -3.1120836372477534)
('2026-03-17', 40.1, 39.85, 0.6273525721455457)
('2026-03-17', 40.83, 40.1, 1.8204488778054784)

In [ ]:
cursor.execute("""
SELECT
    date,
    coin_id,
    price_inr,
    GSPC_Close AS sp500,
    IXIC_Close AS nasdaq
FROM merged_data
WHERE coin_id IN ('bitcoin', 'ethereum', 'tether')
AND date BETWEEN '2026-01-01' AND '2026-12-31'
ORDER BY date
LIMIT 10
""")

results = cursor.fetchall()
for r in results:
    print(r)#Compare top 3 coins daily price trend vs Nifty (^NSEI).

('2026-03-02', 'ethereum', 155313.1292931023, 4290.60986328125, 14500.509765625)
('2026-03-12', 'ethereum', 279306.9974351619, 3666.77001953125, 10646.099609375)
('2026-03-14', 'bitcoin', 6184943.552139279, 4127.830078125, 13303.6396484375)
('2026-03-14', 'ethereum', 276537.237355733, 4228.47998046875, 12705.2197265625)
('2026-03-14', 'tether', 84.56842522735435, 3849.280029296875, 10478.08984375)
('2026-03-15', 'ethereum', 297045.36579862604, 3998.949951171875, 12059.6103515625)
('2026-03-15', 'tether', 85.8931511462235, None, None)
('2026-03-16', 'bitcoin', 8009924.38113424, 2978.760009765625, 8566.48046875)
('2026-03-16', 'bitcoin', 8157780.455111292, 3663.4599609375, 12377.8701171875)
('2026-03-16', 'bitcoin', 7860175.221034703, 3871.739990234375, 13777.740234375)

In [ ]:
cursor.execute("""
SELECT
    date,

    GSPC_Close AS sp500_close,
    Price AS oil_price
FROM merged_data
WHERE date BETWEEN '2026-01-01' AND '2026-12-31'
LIMIT 10
""")

results = cursor.fetchall()
for r in results:
    print(r) #Compare stock prices (^GSPC) with crude oil prices on the same dates

('2026-03-17', None, 61.17)
('2026-03-17', 3257.85009765625, 63.0)
('2026-03-17', 3234.85009765625, 63.27)
('2026-03-17', 3246.280029296875, 62.7)
('2026-03-17', 3237.179931640625, 59.65)
('2026-03-17', 3253.050048828125, 59.56)
('2026-03-17', 3274.699951171875, 59.02)
('2026-03-17', 3265.35009765625, 58.17)
('2026-03-17', 3288.1298828125, 58.34)
('2026-03-17', 3283.14990234375, 57.86)

In [ ]:
cursor.execute("""
SELECT
    date,
    price_inr AS bitcoin_price,
    Price AS oil_price
FROM merged_data
WHERE coin_id = 'bitcoin'
AND price_inr IS NOT NULL
AND Price IS NOT NULL
""")


results = cursor.fetchall()
for r in results:
    print(r) #Correlate Bitcoin closing price with crude oil closing price (same date)

('2026-03-17', 7307625.213417549, 61.17)
('2026-03-17', 7166130.900539224, 63.0)
('2026-03-17', 7495414.341859128, 63.27)
('2026-03-17', 7275140.94449613, 62.7)
('2026-03-17', 7224000.906005809, 59.65)
('2026-03-17', 7205763.671408613, 59.56)
('2026-03-17', 7377568.408827406, 59.02)
('2026-03-17', 7471026.999919416, 58.17)
('2026-03-17', 7490943.665690553, 58.34)
('2026-03-17', 7448415.462567322, 57.86)
('2026-03-17', 7474953.075439318, 58.52)
('2026-03-17', 7216289.858225705, 58.55)
('2026-03-17', 7072289.607125187, 58.25)
('2026-03-17', 7044678.366106417, 56.76)
('2026-03-17', 7049110.1215911815, 55.51)
('2026-03-17', 7295181.762562074, 54.09)
('2026-03-17', 7072204.244187081, 53.09)
('2026-03-17', 7092361.1660758825, 53.33)
('2026-03-17', 7177434.935222951, 53.29)
('2026-03-17', 7149914.289024058, 52.19)
('2026-03-17', 6689389.08502666, 51.58)
('2026-03-17', 6810911.664670934, 50.06)
('2026-03-17', 6597493.475585312, 49.59)
('2026-03-17', 7122745.761241968, 50.87)
('2026-03-17', 6866025.560636041, 50.94)
('2026-03-17', 7182775.418149425, 50.34)
('2026-03-17', 7333947.924555619, 49.59)
('2026-03-17', 7187425.846627208, 50.0)
('2026-03-17', 7271599.950976666, 51.13)
('2026-03-17', 7171572.949306771, 51.41)
('2026-03-17', 7201187.29755112, 52.03)
('2026-03-17', 7251703.328254263, 52.1)
('2026-03-17', 7209254.173849113, 53.31)
('2026-03-17', 7268417.49030321, 53.77)
('2026-03-17', 7263849.726468839, 53.36)
('2026-03-17', 7447341.987486609, 51.36)
('2026-03-17', 7975735.892697773, 49.78)
('2026-03-17', 8003280.21321444, 48.67)
('2026-03-17', 8000169.783417303, 47.17)
('2026-03-17', 8092178.475391482, 44.83)
('2026-03-17', 8081159.94608841, 46.78)
('2026-03-16', 8009924.38113424, 47.27)
('2026-03-17', 8092853.390805625, 46.78)
('2026-03-17', 8027696.597798843, 45.9)
('2026-03-17', 7968688.759781316, 41.14)
('2026-03-17', 8167058.515487802, 31.05)
('2026-03-17', 8196935.158997864, 34.47)
('2026-03-17', 8118000.316161074, 33.13)
('2026-03-17', 7973099.086450076, 31.56)
('2026-03-17', 7980688.008703099, 31.72)
('2026-03-17', 8207545.052481962, 28.96)
('2026-03-17', 8229539.783984127, 26.96)
('2026-03-17', 8868161.595114123, 20.48)
('2026-03-17', 8794022.755272726, 25.09)
('2026-03-17', 8936515.44901635, 19.48)
('2026-03-17', 8882429.185761888, 23.33)
('2026-03-17', 8739740.641206343, 21.03)
('2026-03-17', 8860925.91388854, 20.75)
('2026-03-17', 8854656.259617174, 16.6)
('2026-03-17', 8861418.050018335, 15.48)
('2026-03-17', 8862661.820151662, 14.1)
('2026-03-17', 8833249.416670207, 20.51)
('2026-03-17', 9065676.354329923, 20.28)
('2026-03-17', 9017978.28123392, 25.18)
('2026-03-17', 9134061.037906067, 28.36)
('2026-03-17', 9387459.456660772, 26.21)
('2026-03-17', 9591418.421810476, 23.54)
('2026-03-17', 9121570.655984685, 24.97)
('2026-03-17', 9173866.493436038, 22.9)
('2026-03-17', 9274975.732278159, 22.36)
('2026-03-17', 9314436.685236426, 20.15)
('2026-03-17', 9310175.102671716, 19.96)
('2026-03-17', 9208280.990679564, 19.82)
('2026-03-17', 9026592.666677358, 18.31)
('2026-03-17', 8900073.972215421, -36.98)
('2026-03-17', 8957968.682594351, 8.91)
('2026-03-17', 9040802.274014382, 13.64)
('2026-03-17', 9038740.617012177, 15.06)
('2026-03-17', 9036688.899610182, 15.99)
('2026-03-17', 9003749.459208991, 12.17)
('2026-03-17', 8729536.730077919, 12.4)
('2026-03-17', 8957197.574287502, 15.04)
('2026-03-17', 9066295.741750069, 19.23)
('2026-03-17', 9066867.46885247, 19.72)
('2026-03-17', 9455619.179043707, 20.47)
('2026-03-17', 9440056.689266069, 24.56)
('2026-03-17', 9288882.88186932, 23.88)
('2026-03-17', 9081227.025134273, 23.68)
('2026-03-17', 9132702.543985052, 24.73)
('2026-03-17', 9084246.101299008, 24.02)
('2026-03-17', 9090411.27477335, 25.76)
('2026-03-17', 9208980.453923177, 25.37)
('2026-03-17', 9039952.955659283, 27.4)
('2026-03-17', 9070436.848135183, 29.44)
('2026-03-17', 9080584.318377115, 31.83)
('2026-03-17', 8945088.576284403, 32.3)
('2026-03-17', 8792883.07729243, 33.56)
('2026-03-17', 8731873.284684414, 34.3)
('2026-03-17', 9111429.945371069, 33.49)
('2026-03-17', 9111165.38661966, 34.7)
('2026-03-17', 9223086.808659252, 32.8)
('2026-03-17', 9165684.099752242, 33.67)
('2026-03-17', 9156217.740562832, 35.57)
('2026-03-17', 9177823.305095606, 35.49)
('2026-03-17', 9263092.465181679, 36.88)
('2026-03-17', 9181709.414667957, 37.33)
('2026-03-17', 9054321.250569785, 37.42)
('2026-03-17', 9325640.339018358, 39.49)
('2026-03-17', 9360532.463404836, 38.17)
('2026-03-17', 9250500.062624797, 38.98)
('2026-03-17', 9285248.177863376, 39.54)
('2026-03-17', 9337523.923073687, 36.43)
('2026-03-17', 9302203.177316865, 36.24)
('2026-03-17', 9338122.035800587, 37.07)
('2026-03-17', 9541743.483380785, 38.26)
('2026-03-17', 9934947.612549465, 37.91)
('2026-03-17', 10091339.413757524, 38.79)
('2026-03-17', 10078287.164944079, 39.72)
('2026-03-17', 10222853.345055208, 40.6)
('2026-03-17', 10301939.218478084, 40.4)
('2026-03-17', 10119542.204331392, 37.91)
('2026-03-17', 10198739.393321177, 38.66)
('2026-03-17', 10277885.47839658, 38.53)
('2026-03-17', 10164069.670952292, 39.67)
('2026-03-17', 10156547.547410768, 39.27)
('2026-03-17', 10101549.352407157, 39.88)
('2026-03-17', 10136533.758092493, 40.57)
('2026-03-17', 10357349.26643955, 40.51)
('2026-03-17', 10249425.74900696, 40.59)
('2026-03-17', 10229427.683390176, 40.91)
('2026-03-17', 10168020.4311719, 39.64)
('2026-03-17', 10203795.311577797, 40.56)
('2026-03-17', 10330494.375551593, 40.06)
('2026-03-17', 10240072.841855934, 40.3)
('2026-03-17', 10260715.669243045, 41.2)
('2026-03-17', 10330510.927890545, 40.74)
('2026-03-17', 10122552.718401065, 40.55)
('2026-03-17', 9870309.502282668, 40.83)
('2026-03-17', 9811174.470132805, 41.76)
('2026-03-17', 9963363.104407016, 41.88)
('2026-03-17', 10119947.866363142, 40.99)
('2026-03-17', 10011721.5506572, 41.23)
('2026-03-17', 10094655.435390146, 41.46)
('2026-03-17', 10270107.263258504, 40.89)
('2026-03-17', 10236807.855788205, 41.13)
('2026-03-17', 10220759.730383817, 39.85)
('2026-03-17', 10434491.300112702, 40.1)
('2026-03-17', 10412275.449238887, 40.83)
('2026-03-17', 10529495.638104321, 41.67)
('2026-03-17', 10805439.78369676, 42.25)
('2026-03-17', 10383230.847886154, 41.93)
('2026-03-17', 10268856.947554458, 41.16)
('2026-03-17', 10282983.838569582, 41.94)
('2026-03-17', 10286533.101169772, 41.53)
('2026-03-17', 10148644.242275473, 42.6)
('2026-03-17', 9819786.419050021, 42.26)
('2026-03-17', 9942066.543754837, 42.05)
('2026-03-17', 9813063.27750558, 42.89)
('2026-03-17', 10203164.21582744, 42.89)
('2026-03-17', 10074416.19618185, 42.91)
('2026-03-17', 9903221.35080575, 42.62)
('2026-03-17', 9653212.189243559, 42.32)
('2026-03-17', 9801777.668906499, 42.44)
('2026-03-17', 9749130.25886824, 43.17)
('2026-03-17', 9856302.06893481, 43.21)
('2026-03-17', 9564432.013993934, 42.88)
('2026-03-17', 9591794.692119835, 42.96)
('2026-03-17', 9545191.818462053, 42.61)
('2026-03-17', 9606486.0790093, 42.76)
('2026-03-17', 9784574.242949013, 42.76)
('2026-03-17', 9838796.609221794, 41.39)
('2026-03-17', 9765163.284050079, 39.69)
('2026-03-17', 9759026.631183332, 36.87)
('2026-03-17', 9718962.630296323, 38.05)
('2026-03-17', 9800346.003033817, 37.25)
('2026-03-17', 9856054.84901548, 37.33)
('2026-03-17', 9840553.151484529, 37.23)
('2026-03-17', 10035954.764445597, 38.29)
('2026-03-17', 10195205.098488238, 40.17)
('2026-03-17', 10254357.380846838, 40.99)
('2026-03-17', 10237593.3071353, 41.09)
('2026-03-17', 10184894.127284445, 39.26)
('2026-03-17', 10169238.650025213, 39.55)
('2026-03-17', 10261685.530263504, 39.92)
('2026-03-17', 10237752.888404036, 40.11)
('2026-03-17', 10333070.25718556, 40.06)
('2026-03-17', 10189201.725638028, 40.47)
('2026-03-17', 10194461.688819751, 39.03)
('2026-03-17', 10158260.693491202, 40.05)
('2026-03-17', 9951646.271657305, 38.51)
('2026-03-17', 9948492.512889242, 36.9)
('2026-03-17', 10060469.351465985, 39.12)
('2026-03-17', 9673068.167457229, 40.52)
('2026-03-17', 9728251.057537576, 39.82)
('2026-03-17', 9723915.967631772, 41.04)
('2026-03-17', 9944472.608696878, 40.44)
('2026-03-17', 10139763.924082505, 39.22)
('2026-03-17', 10130020.723922314, 40.03)
('2026-03-17', 10509252.859358784, 40.86)
('2026-03-17', 10700725.995237181, 40.84)
('2026-03-17', 10847910.013598107, 40.7)
('2026-03-17', 10859533.642673422, 40.69)
('2026-03-17', 10959365.064936124, 41.37)
('2026-03-17', 11070472.246732509, 39.88)
('2026-03-17', 10783920.730192943, 40.46)
('2026-03-17', 10949945.97908964, 39.73)
('2026-03-17', 10814774.599012492, 38.39)
('2026-03-17', 10047260.111235712, 39.34)
('2026-03-17', 9838358.210748602, 37.27)
('2026-03-17', 10223942.881584922, 35.94)
('2026-03-17', 10216224.051870666, 35.64)
('2026-03-17', 10046351.075825775, 36.6)
('2026-03-17', 9721344.884648668, 37.44)
('2026-03-17', 9509774.024195194, 38.97)
('2026-03-17', 9369768.130232994, 38.56)
('2026-03-17', 9432476.848616607, 36.97)
('2026-03-17', 9558930.877185136, 40.05)
('2026-03-17', 9720308.914971137, 41.18)
('2026-03-17', 9549158.301143315, 41.23)
('2026-03-17', 9442499.946295625, 40.9)
('2026-03-17', 9659976.397607893, 39.93)
('2026-03-17', 9747832.72977752, 41.14)
('2026-03-17', 9802501.15016422, 41.24)
('2026-03-17', 10055171.794296525, 41.64)
('2026-03-17', 10073474.454011032, 41.57)
('2026-03-17', 9965129.220872145, 41.99)
('2026-03-17', 9722166.86543983, 42.91)
('2026-03-17', 9593893.17104472, 44.71)
('2026-03-17', 9734748.91964181, 45.58)
('2026-03-17', 9765788.362963019, 45.2)
('2026-03-17', 9824421.072227614, 44.54)
('2026-03-17', 9450928.858755054, 45.23)
('2026-03-17', 9018317.599498693, 45.65)
('2026-03-17', 9199126.082980732, 46.23)
('2026-03-17', 8984607.813501872, 45.72)
('2026-03-17', 9167651.236387476, 45.64)
('2026-03-17', 9069592.039128657, 45.48)
('2026-03-17', 9283589.00601575, 46.76)
('2026-03-17', 9394913.182233905, 46.59)
('2026-03-17', 9108594.696793688, 47.02)
('2026-03-17', 8994239.327086337, 47.58)
('2026-03-17', 8857694.85444411, 47.86)
('2026-03-17', 8376936.116014769, 48.34)
('2026-03-17', 8470582.749251666, 49.04)
('2026-03-17', 8373085.239387692, 47.79)
('2026-03-16', 8157780.455111292, 47.02)
('2026-03-17', 8219844.429070548, 47.94)
('2026-03-17', 8084502.70583037, 48.18)
('2026-03-17', 7685198.360480496, 47.5)
('2026-03-17', 7622398.708162882, 47.85)
('2026-03-17', 7591078.566298594, 48.24)
('2026-03-17', 7778520.446850556, 48.35)
('2026-03-17', 7865475.253834086, 47.47)
('2026-03-17', 7783791.323601658, 49.78)
('2026-03-17', 8066930.863801428, 50.45)
('2026-03-17', 8157156.351483771, 50.63)
('2026-03-17', 8126220.637986011, 52.14)
('2026-03-17', 8116488.479072998, 52.15)
('2026-03-17', 8078246.317717989, 53.08)
('2026-03-17', 7731939.31508293, 52.81)
('2026-03-17', 8213485.439946512, 53.47)
('2026-03-17', 8441734.894689914, 52.25)
('2026-03-17', 8277612.193785475, 52.87)
('2026-03-17', 8033337.656068311, 53.16)
('2026-03-17', 8028324.929700683, 53.0)
('2026-03-17', 8110183.521497487, 52.28)
('2026-03-17', 8167418.75650716, 52.78)
('2026-03-17', 8337407.11660591, 52.61)
('2026-03-17', 8261440.281355997, 52.81)
('2026-03-17', 8347818.307928058, 52.26)
('2026-03-17', 8175319.49414227, 52.16)
('2026-03-17', 8175924.735194205, 53.55)
('2026-03-17', 7992348.231966222, 54.77)
('2026-03-17', 7844409.288926788, 55.67)
('2026-03-17', 7987315.985984798, 56.19)
('2026-03-17', 7781471.915537124, 56.8)
('2026-03-17', 7712879.171308659, 57.95)
('2026-03-17', 7892110.371399885, 58.34)
('2026-03-17', 7913974.621357582, 58.69)
('2026-03-17', 7933999.65474005, 58.22)
('2026-03-17', 7929162.75966298, 59.5)
('2026-03-17', 7820620.968822208, 60.07)
('2026-03-17', 7872946.774052088, 61.09)
('2026-03-16', 7860175.221034703, 60.4)
('2026-03-17', 7838865.798860937, 59.12)
('2026-03-17', 7886342.002067149, 61.67)
('2026-03-17', 7887770.596681177, 61.66)
('2026-03-17', 7835388.056690424, 63.21)
('2026-03-17', 7936951.056508718, 63.43)
('2026-03-17', 7875103.91153735, 61.55)
('2026-03-17', 7982611.090931888, 60.54)
('2026-03-17', 8094664.567193232, 59.7)
('2026-03-17', 8154755.980058913, 61.33)
('2026-03-17', 8224912.970329631, 63.81)
('2026-03-17', 8475311.204337161, 66.08)
('2026-03-17', 8443838.294347357, 65.03)
('2026-03-17', 8200790.873528976, 64.02)
('2026-03-17', 8179932.125614385, 64.45)
('2026-03-17', 8169727.593041189, 66.02)
('2026-03-17', 8164051.8328820085, 65.59)
('2026-03-17', 8196362.9552232, 65.36)
('2026-03-17', 8214254.506811856, 64.82)
('2026-03-17', 8600260.479528198, 64.55)
('2026-03-17', 8754772.557780331, 59.95)
('2026-03-17', 8637202.771129187, 61.43)
('2026-03-17', 8665871.041073622, 61.48)
('2026-03-17', 8641731.269593248, 57.75)
('2026-03-17', 8504968.615885023, 61.12)
('2026-03-17', 8414003.970645163, 58.47)
('2026-03-17', 8046939.8302773405, 60.93)
('2026-03-17', 8179241.969294843, 61.49)
('2026-03-17', 8189307.776814618, 60.55)
('2026-03-17', 8190756.883147298, 59.19)
('2026-03-17', 8167427.829795334, 61.41)
('2026-03-17', 7931480.8104405, 58.73)
('2026-03-17', 8098992.121060789, 59.34)
('2026-03-17', 8165356.488930265, 59.77)
('2026-03-17', 8206661.924142179, 59.61)
('2026-03-17', 7762053.970031044, 59.29)
('2026-03-17', 7714332.820802952, 59.7)
('2026-03-17', 7217787.461780625, 60.2)
('2026-03-17', 7055170.4747747015, 63.15)
('2026-03-17', 7124353.514366637, 63.42)
('2026-03-17', 6839512.652076184, 63.16)
('2026-03-17', 6617843.606631121, 63.33)
('2026-03-17', 5676634.189757013, 62.61)
('2026-03-17', 6389223.0613750955, 61.34)
('2026-03-17', 6278047.808376017, 61.45)
('2026-03-17', 6388983.809905373, 62.18)
('2026-03-17', 6363124.007122537, 62.02)
('2026-03-17', 6230645.199778009, 63.03)
('2026-03-17', 6073656.888033923, 63.81)
('2026-03-17', 5993963.2553228345, 65.0)
('2026-03-17', 6234117.350281114, 63.5)
('2026-03-17', 6317657.207954805, 64.46)
('2026-03-17', 6222983.54818252, 65.72)
('2026-03-17', 6255749.578602175, 65.63)
('2026-03-17', 6116329.755578176, 64.73)
('2026-03-17', 6033801.7653913135, 64.96)
('2026-03-17', 6092367.347486159, 64.92)
('2026-03-17', 6166730.671036533, 65.31)
('2026-03-17', 6167421.5569663085, 65.96)
('2026-03-17', 6132044.38390857, 63.82)
('2026-03-17', 5877904.816486458, 65.32)
('2026-03-17', 5825506.041087636, 66.24)
('2026-03-17', 6179906.746479165, 65.49)
('2026-03-17', 6139221.658943246, 63.28)
('2026-03-17', 6000769.898243445, 61.95)
('2026-03-17', 6102895.493287365, 63.61)
('2026-03-17', 5984275.487394328, 66.13)
('2026-03-17', 6305544.630558076, 66.27)
('2026-03-17', 6286193.4883730775, 66.41)
('2026-03-17', 6694568.0647264635, 66.87)
('2026-03-17', 6505413.051213356, 66.31)
('2026-03-17', 6265583.842492761, 67.8)
('2026-03-14', 6184943.552139279, 68.79)
('2026-03-17', 6071162.609842083, 68.81)
('2026-03-17', 6319544.712079575, 69.57)
('2026-03-17', 6427459.132593709, 69.21)
('2026-03-17', 6476952.781587672, 70.11)
('2026-03-17', 6517601.8570237355, 69.9)
('2026-03-17', 6571729.3213031115, 70.34)
('2026-03-17', 6593624.616147389, 71.0)
('2026-03-17', 6727548.65801573, 70.94)
('2026-03-17', 6906940.623961062, 72.06)
('2026-03-17', 6896413.404012382, 72.03)

In [ ]:
cursor.execute("""
SELECT
    date,
    price_inr AS ethereum_price,
    IXIC_Close AS nasdaq_price
FROM merged_data
WHERE coin_id = 'ethereum'
AND date BETWEEN '2026-01-01' AND '2026-12-31'
""")

results = cursor.fetchall()
for r in results:
    print(r)#Compare NASDAQ (^IXIC) with Ethereum price trends

('2026-03-17', 167679.9006033522, 13756.330078125)
('2026-03-17', 167319.001543521, 13614.509765625)
('2026-03-17', 177917.82793888426, 13814.490234375)
('2026-03-17', 171006.12473780697, 13881.7197265625)
('2026-03-17', 168930.37673281875, 13924.91015625)
('2026-03-17', 170229.9761188356, 13911.75)
('2026-03-17', 172085.9718554942, 14020.330078125)
('2026-03-17', 177753.92370784696, 14069.419921875)
('2026-03-17', 177052.68464483944, 14174.1396484375)
('2026-03-17', 172151.5682806194, 14072.8603515625)
('2026-03-17', 171697.82772804037, 14039.6796875)
('2026-03-17', 162266.37796915465, 14161.349609375)
('2026-03-17', 156474.22180351955, 14030.3798828125)
('2026-03-17', 154426.70647452315, 14141.48046875)
('2026-03-17', 155840.4924805317, 14253.26953125)
('2026-03-17', 163227.64895741257, 14271.73046875)
('2026-03-17', 153890.04212059852, 14369.7099609375)
('2026-03-17', 155066.27550185894, 14360.3896484375)
('2026-03-02', 155313.1292931023, 14500.509765625)
('2026-03-17', 154802.90633012433, 14528.330078125)
('2026-03-17', 134677.50142669896, 14503.9501953125)
('2026-03-17', 133837.57278106204, 14522.3798828125)
('2026-03-17', 127176.85742857557, 14639.330078125)
('2026-03-17', 143324.73934384843, None)
('2026-03-17', 131454.92128790365, 14663.6396484375)
('2026-03-17', 134990.81789744264, 14665.0595703125)
('2026-03-17', 141499.98989505236, 14559.7802734375)
('2026-03-17', 137163.51905527923, 14701.919921875)
('2026-03-17', 139502.26918137303, 14733.240234375)
('2026-03-17', 136118.34029958773, 14677.650390625)
('2026-03-17', 135084.25007491114, 14644.9501953125)
('2026-03-17', 135202.85645156694, 14543.1298828125)
('2026-03-17', 135687.4227659859, 14427.240234375)
('2026-03-17', 137898.7403436233, 14274.98046875)
('2026-03-17', 135372.22120159038, 14498.8798828125)
('2026-03-17', 134334.00818529903, None)
('2026-03-17', 149984.44480204728, 14684.599609375)
('2026-03-17', 153384.6912264906, 14836.990234375)
('2026-03-17', 150793.82263866183, 14840.7099609375)
('2026-03-17', 152736.0854367373, 14660.580078125)
('2026-03-17', 155508.64352977095, 14762.580078125)
('2026-03-17', 153154.64715995087, 14778.259765625)
('2026-03-17', 153246.47199208362, 14672.6796875)
('2026-03-17', 153045.86830616, 14681.0703125)
('2026-03-17', 151706.98921091956, 14761.2900390625)
('2026-03-17', 155745.16924065605, 14780.5302734375)
('2026-03-17', 155840.93772632716, 14895.1201171875)
('2026-03-17', 155254.81405305702, 14835.759765625)
('2026-03-17', 152837.10606631296, 14860.1796875)
('2026-03-17', 153282.69389658255, 14788.08984375)
('2026-03-17', 153903.86052217713, 14765.1396484375)
('2026-03-17', 153546.46543390723, 14816.259765625)
('2026-03-17', 189067.0538600533, 14822.900390625)
('2026-03-17', 199979.47617304884, 14793.759765625)
('2026-03-17', 220672.16056835878, 14656.1796875)
('2026-03-17', 214170.10011952536, 14525.91015625)
('2026-03-17', 211740.19586880849, None)
('2026-03-17', 227649.06017478785, 14714.66015625)
('2026-03-17', 222550.86125964453, 14942.650390625)
('2026-03-17', 217226.91460543944, 15019.7998046875)
('2026-03-17', 217756.90685748137, 15041.8603515625)
('2026-03-17', 211823.19396124792, 14945.8095703125)
('2026-03-17', 210787.9756927576, 15129.5)
('2026-03-17', 215738.55684027018, 15265.8896484375)
('2026-03-17', 215915.19935485243, 15259.240234375)
('2026-03-17', 219047.5756337483, 15309.3798828125)
('2026-03-17', 228450.3696380665, 15331.1796875)
('2026-03-17', 214375.8056090152, 15363.51953125)
('2026-03-17', 215195.01779836757, None)
('2026-03-17', 216970.8522801864, 15374.330078125)
('2026-03-17', 218190.67523487698, 15286.6396484375)
('2026-03-17', 227238.5848495167, 15248.25)
('2026-03-17', 228525.93909568293, None)
('2026-03-17', 224768.84403505738, 15105.580078125)
('2026-03-17', 216016.02336935312, 15037.759765625)
('2026-03-17', 216690.8648491384, 15161.5302734375)
('2026-03-17', 217089.5740742275, 15181.919921875)
('2026-03-17', 222777.49872829148, 15043.9697265625)
('2026-03-17', 222455.17860950096, 14713.900390625)
('2026-03-17', 224236.44416331983, 14746.400390625)
('2026-03-17', 207961.65418872624, 14896.849609375)
('2026-03-17', 212876.9182145838, 15052.240234375)
('2026-03-17', 216727.81140618862, 15047.7001953125)
('2026-03-17', 215217.42336418747, 14969.9697265625)
('2026-03-17', 230255.54711844953, 14546.6796875)
('2026-03-17', 240556.86572695823, 14512.4404296875)
('2026-03-17', 237276.58179525606, 14448.580078125)
('2026-03-17', 227345.61024210224, 14566.7001953125)
('2026-03-17', 221936.8494721614, 14255.48046875)
('2026-03-17', 218235.52611319744, 14433.830078125)
('2026-03-17', 219421.86983518038, 14501.91015625)
('2026-03-17', 220541.89744913176, 14654.01953125)
('2026-03-17', 217182.0562912451, 14579.5400390625)
('2026-03-17', 218382.42014738446, 14486.2001953125)
('2026-03-17', 218767.0130883784, 14465.919921875)
('2026-03-17', 208337.07852694736, 14571.6396484375)
('2026-03-17', 196636.0383307714, 14823.4296875)
('2026-03-17', 192852.03096719063, None)
('2026-03-17', 209315.24780590468, 15021.8095703125)
('2026-03-17', 210338.28060317386, 15129.08984375)
('2026-03-17', 207894.42363255343, 15121.6796875)
('2026-03-17', 206903.99097231845, 15215.7001953125)
('2026-03-17', 207191.0496905718, 15090.2001953125)
('2026-03-17', 208396.95938860573, 15226.7099609375)
('2026-03-17', 213866.80820581852, 15235.7099609375)
('2026-03-17', 213247.902753943, 15235.83984375)
('2026-03-17', 206191.53795072352, 15448.1201171875)
('2026-03-17', 220583.0677146267, 15498.3896484375)
('2026-03-17', 221209.20718607036, 15595.919921875)
('2026-03-17', 214841.71925105614, 15649.599609375)
('2026-03-17', 215995.5389160479, 15811.580078125)
('2026-03-17', 219842.28509645213, 15940.3095703125)
('2026-03-17', 218478.50703220506, None)
('2026-03-17', 224192.01293457407, 15982.3603515625)
('2026-03-17', 237634.3285912139, 15886.5400390625)
('2026-03-17', 252785.18261104374, 15622.7099609375)
('2026-03-17', 253963.71411998925, 15704.2802734375)
('2026-03-17', 252599.85968309751, 15860.9599609375)
('2026-03-17', 255256.0749124428, 15853.849609375)
('2026-03-17', 258953.02296009834, 15973.8603515625)
('2026-03-17', 269423.17285168904, 15921.5703125)
('2026-03-17', 289273.06195820443, 15993.7099609375)
('2026-03-17', 299604.7001320289, None)
('2026-03-17', 305580.9799247014, 15854.759765625)
('2026-03-17', 309629.88231970003, 15775.1396484375)
('2026-03-17', 323799.5635112756, 15845.23046875)
('2026-03-17', 324888.02667051577, None)
('2026-03-17', 323522.2855073287, 15491.66015625)
('2026-03-17', 313632.80993368995, 15782.830078125)
('2026-03-17', 320521.28663827025, 15537.6904296875)
('2026-03-17', 322067.53188592376, 15254.0498046875)
('2026-03-17', 323729.6744159729, 15381.3203125)
('2026-03-17', 334271.3356334813, 15085.4697265625)
('2026-03-17', 328567.3072022601, 15225.150390625)
('2026-03-17', 329848.44489638496, 15686.919921875)
('2026-03-17', 333798.49786685634, 15786.990234375)
('2026-03-17', 323419.73918441863, 15517.3701171875)
('2026-03-17', 303617.9116663577, 15630.599609375)
('2026-03-17', 296151.6805356246, 15413.2802734375)
('2026-03-17', 305147.6597239278, 15237.6396484375)
('2026-03-17', 326586.85608261486, 15565.580078125)
('2026-03-17', 316895.55183794844, 15180.4296875)
('2026-03-17', 323322.0010279766, 15169.6796875)
('2026-03-17', 341975.0422938313, 14980.9404296875)
('2026-03-17', 352049.4403810017, 15341.08984375)
('2026-03-17', 374193.3376648639, 15521.8896484375)
('2026-03-17', 372140.5970629246, 15653.3701171875)
('2026-03-17', 370718.8174494866, None)
('2026-03-17', 403547.06190802733, 15871.259765625)
('2026-03-17', 416582.6051270567, 15781.7197265625)
('2026-03-17', 399375.2127189976, 15766.2197265625)
('2026-03-17', 387732.95356370165, 15741.5595703125)
('2026-03-17', 387408.6664674909, 15644.9697265625)
('2026-03-17', 392681.4189909559, 15832.7998046875)
('2026-03-17', 376878.0982824829, 15622.7197265625)
('2026-03-17', 354772.70430919825, 15100.169921875)
('2026-03-17', 376832.66666282027, 15080.8603515625)
('2026-03-17', 368766.6639472321, 14935.900390625)
('2026-03-17', 421737.4738716338, 14942.830078125)
('2026-03-17', 416904.49092835333, 15153.4501953125)
('2026-03-17', 417273.9071184703, 15188.3896484375)
('2026-03-17', 383869.2304155191, 14806.8095703125)
('2026-03-17', 403346.84673449927, 14893.75)
('2026-03-17', 394479.82107990474, None)
('2026-03-17', 394824.62858350464, 14506.900390625)
('2026-03-17', 384794.36172029114, 14340.259765625)
('2026-03-17', 385618.86285304534, 14154.01953125)
('2026-03-17', 386992.0744205619, 13768.919921875)
('2026-03-17', 378688.487081064, 13855.1298828125)
('2026-03-17', 380669.0608269572, 13539.2900390625)
('2026-03-17', 391914.25736500154, None)
('2026-03-17', 379062.50711160863, 13352.7802734375)
('2026-03-17', 379789.69451721257, 13770.5703125)
('2026-03-17', 376830.61714539555, 14239.8798828125)
('2026-03-17', 379557.7315665512, 14346.0)
('2026-03-17', 379169.3803941581, 14417.5498046875)
('2026-03-17', 380163.9598970403, 13878.8203125)
('2026-03-17', 382811.6356012148, 14098.009765625)
('2026-03-17', 393614.0739117057, 14015.669921875)
('2026-03-17', 415686.0060768963, 14194.4501953125)
('2026-03-17', 412052.856085073, 14490.3701171875)
('2026-03-17', 406940.596240047, 14185.6396484375)
('2026-03-17', 398693.42995223537, 13791.150390625)
('2026-03-17', 395856.797622927, 13790.919921875)
('2026-03-17', 403666.7568900215, 14139.759765625)
('2026-03-17', 404926.98327490315, 14124.08984375)
('2026-03-17', 393846.3358485685, 13716.7197265625)
('2026-03-17', 394843.6203459821, 13548.0703125)
('2026-03-17', 392295.47524281475, None)
('2026-03-17', 370875.27142150694, 13381.51953125)
('2026-03-17', 369992.0919011612, 13037.490234375)
('2026-03-17', 368312.96560615575, 13473.58984375)
('2026-03-17', 342937.4440185811, 13694.6201171875)
('2026-03-17', 357978.55612770614, 13751.400390625)
('2026-03-17', 356321.1005771281, None)
('2026-03-17', 367286.12298418215, 13752.01953125)
('2026-03-17', 373944.85329388455, 13537.9404296875)
('2026-03-17', 368177.3713848715, 13313.4404296875)
('2026-03-17', 385235.77973544877, 12830.9599609375)
('2026-03-17', 397823.05193989933, 12795.5498046875)
('2026-03-17', 400707.46142882656, 13255.5498046875)
('2026-03-17', 398218.8935895547, 13129.9599609375)
('2026-03-17', 400668.6421398132, 12843.8095703125)
('2026-03-17', 416041.06085392536, 12581.2197265625)
('2026-03-17', 395289.8026309068, 12948.6201171875)
('2026-03-17', 401911.0484708849, 13436.5498046875)
('2026-03-17', 388222.87205311254, 13614.7802734375)
('2026-03-17', 340432.9353676543, None)
('2026-03-17', 332747.98798714374, 13838.4599609375)
('2026-03-17', 369207.3362657844, 14108.8203125)
('2026-03-17', 376492.3574048653, 13922.599609375)
('2026-03-17', 366574.05838423775, 14191.83984375)
('2026-03-17', 349761.3884710538, 14169.2998046875)
('2026-03-17', 342302.33220614656, 14354.900390625)
('2026-03-17', 337247.7588866496, 14619.6396484375)
('2026-03-17', 342375.6803081046, 14442.26953125)
('2026-03-17', 350696.6804336402, 14220.51953125)
('2026-03-17', 349657.073530753, 14261.5)
('2026-03-17', 341303.9842640361, 14532.5498046875)
('2026-03-17', 333571.21535914514, 14204.169921875)
('2026-03-17', 338462.9290819708, 13888.8203125)
('2026-03-17', 345416.6546043208, 13897.2998046875)
('2026-03-17', 347083.5922685809, 13711.0)
('2026-03-17', 365539.5621120337, 13411.9599609375)
('2026-03-17', 363758.94232227415, 13371.5703125)
('2026-03-17', 351342.5325721324, 13643.58984375)
('2026-03-17', 344315.5289450759, None)
('2026-03-17', 337015.4990615576, 13332.3603515625)
('2026-03-17', 341801.10296794504, 13619.66015625)
('2026-03-17', 343730.3913686987, 13453.0703125)
('2026-03-17', 347169.85800323385, 13174.650390625)
('2026-03-17', 319468.25832003524, 12839.2900390625)
('2026-03-17', 292527.2014230804, 13004.849609375)
('2026-03-17', 303546.1807953054, 12490.740234375)
('2026-03-17', 293412.52766766545, 12488.9296875)
('2026-03-17', 304507.99491275364, 12871.5302734375)
('2026-03-17', 301591.6290594234, 12334.6396484375)
('2026-03-17', 317071.7291616941, 12536.01953125)
('2026-03-17', 316207.1597353334, None)
('2026-03-17', 302271.19106009, 12964.8603515625)
('2026-03-17', 302072.2252489844, 12317.6904296875)
('2026-03-17', 287385.51825001417, 12144.66015625)
('2026-03-17', 275511.26516527805, 11623.25)
('2026-03-17', 281155.6844835739, 11737.669921875)
('2026-03-17', 275080.20597856207, 11364.240234375)
('2026-03-17', 267796.5731112152, 11370.9599609375)
('2026-03-17', 276052.04898099863, 11805.0)
('2026-03-17', 267032.830083096, 11662.7900390625)
('2026-03-17', 251183.08126814634, 11984.51953125)
('2026-03-17', 247777.39778764817, 11418.150390625)
('2026-03-17', 248183.09115512334, 11388.5)
('2026-03-17', 250950.12836319354, 11354.6201171875)
('2026-03-17', 263283.40358322934, 11535.26953125)
('2026-03-17', 263444.9399900479, 11264.4501953125)
('2026-03-17', 269938.1970950932, 11434.740234375)
('2026-03-17', 269490.2527975858, 11740.650390625)
('2026-03-17', 271004.1486761167, 12131.1298828125)
('2026-03-17', 267260.2384447111, None)
('2026-03-17', 267424.4592587914, 12081.3896484375)
('2026-03-17', 250829.94408877468, 11994.4599609375)
('2026-03-17', 269370.30418167287, 12316.900390625)
('2026-03-17', 288132.42535713845, 12012.73046875)
('2026-03-17', 281520.95159888716, 12061.3701171875)
('2026-03-17', 271893.52182715805, 12175.23046875)
('2026-03-17', 273416.13820120675, 12086.26953125)
('2026-03-17', 274616.2375638853, 11754.23046875)
('2026-03-17', 281685.69218486216, 11340.01953125)
('2026-03-17', 298746.9630305986, 10809.23046875)
('2026-03-17', 298675.7147486205, 10828.349609375)
('2026-03-17', 292065.55714175856, 11099.150390625)
('2026-03-12', 279306.9974351619, 10646.099609375)
('2026-03-17', 282191.1596649078, 10798.349609375)
('2026-03-17', 277686.2575249929, None)
('2026-03-17', 269107.8224748998, 11069.2998046875)
('2026-03-17', 269596.8374095658, 11053.080078125)
('2026-03-17', 255672.94816147196, 11232.1904296875)
('2026-03-17', 255132.82641488407, 11607.6201171875)
('2026-03-17', 266653.5750632806, 11524.5498046875)
('2026-03-17', 266686.3060581252, 11181.5400390625)
('2026-03-17', 268857.45721078233, 11177.8896484375)
('2026-03-17', 269330.66898642445, 11028.740234375)
('2026-03-17', 265308.33057719615, 11127.849609375)
('2026-03-17', 264638.4624631536, None)
('2026-03-17', 261698.83888170918, 11322.240234375)
('2026-03-17', 262776.73658441985, 11361.849609375)
('2026-03-17', 264850.5744899021, 11621.349609375)
('2026-03-17', 264760.5504658988, 11635.3095703125)
('2026-03-17', 263786.42273046816, 11372.599609375)
('2026-03-17', 266620.8671552428, 11264.73046875)
('2026-03-17', 266951.6312463789, 11247.580078125)
('2026-03-17', 269940.3569195695, 11251.1904296875)
('2026-03-17', 281016.1719855551, 11452.419921875)
('2026-03-17', 281388.8695194364, 11360.0498046875)
('2026-03-17', 282560.6030133936, 11713.150390625)
('2026-03-17', 291299.3568651643, 11897.650390625)
('2026-03-15', 297045.36579862604, 12059.6103515625)
('2026-03-17', 284403.12191626645, 11834.1103515625)
('2026-03-17', 279086.945835317, 11782.669921875)
('2026-03-17', 278309.6101406161, 11562.5703125)
('2026-03-17', 278294.1933407241, 12032.419921875)
('2026-03-17', 281519.50124331604, 12162.58984375)
('2026-03-17', 278535.9889192714, 12390.6904296875)
('2026-03-17', 299728.9177688779, 12368.98046875)
('2026-03-17', 302917.5844429012, 12348.759765625)
('2026-03-17', 299838.3615803796, 12668.16015625)
('2026-03-17', 299041.3190188698, 12720.580078125)
('2026-03-17', 300496.6677650833, 12657.5498046875)
('2026-03-17', 297943.7602436932, 12644.4599609375)
('2026-03-17', 289592.03165583033, None)
('2026-03-17', 267489.81096221146, 12854.7998046875)
('2026-03-17', 272419.05713641306, 12779.91015625)
('2026-03-17', 269940.0485702116, 13047.1904296875)
('2026-03-17', 270322.79786255566, None)
('2026-03-17', 270125.836049164, 13102.5498046875)
('2026-03-17', 257898.21011062048, 12938.1201171875)
('2026-03-17', 268521.1124032741, 12965.33984375)
('2026-03-14', 276537.237355733, 12705.2197265625)
('2026-03-17', 276752.68161058764, 12381.5703125)
('2026-03-17', 258717.1664228855, 12381.2998046875)
('2026-03-17', 247763.65614624374, 12431.5302734375)
('2026-03-17', 224065.64499097393, 12639.26953125)
('2026-03-17', 208098.68569226892, 12141.7099609375)
('2026-03-17', 212055.7416695305, 12017.669921875)
('2026-03-17', 201371.05394647823, 11883.1396484375)
('2026-03-17', 194638.91147198106, None)
('2026-03-17', 164424.8093049238, 11785.1298828125)
('2026-03-17', 186695.3649137571, 11630.8603515625)
('2026-03-17', 189440.9269478321, None)
('2026-03-17', 189754.81871261535, 11544.91015625)
('2026-03-17', 191035.83888725925, 11791.900390625)
('2026-03-17', 182890.5822309681, 11862.1298828125)
('2026-03-17', 175976.56404532818, 12112.3095703125)
('2026-03-17', 176214.23834483154, 12266.41015625)
('2026-03-17', 185411.2111430372, 11633.5703125)
('2026-03-17', 188855.60230133013, 11719.6796875)
('2026-03-17', 177856.25063894037, 11552.3603515625)
('2026-03-17', 181624.1547003928, 11448.400390625)
('2026-03-17', 180528.32834312637, 11535.01953125)
('2026-03-17', 177478.4599141033, 11425.0498046875)
('2026-03-17', 177249.2474816647, 11220.1904296875)
('2026-03-17', 178533.39457288812, 11066.8095703125)
('2026-03-17', 179064.34776215904, 10867.9296875)
('2026-03-17', 177305.13210485573, 10802.919921875)
('2026-03-17', 168724.9961412896, 10829.5)
('2026-03-17', 168454.26945512652, 11051.6396484375)
('2026-03-17', 186740.27349943476, 10737.509765625)
('2026-03-17', 184470.53087042045, 10575.6201171875)
('2026-03-17', 175906.3206947476, 10815.4296875)
('2026-03-17', 178968.6577342996, 11176.41015625)
('2026-03-17', 176523.67517814328, None)
('2026-03-17', 185826.30723370606, 11073.3095703125)
('2026-03-17', 182403.7063918738, 10652.400390625)
('2026-03-17', 195838.5762971537, 10542.099609375)
('2026-03-17', 190414.48477250861, 10426.1904296875)
('2026-03-17', 182113.64679332406, 10417.099609375)
('2026-03-17', 181094.53416839553, 10649.150390625)
('2026-03-17', 178231.25313766958, 10321.3896484375)
('2026-03-17', 183916.21187136925, 10675.7998046875)
('2026-03-17', 187187.4516331626, 10772.400390625)
('2026-03-17', 189229.2165179718, 10680.509765625)
('2026-03-17', 191849.4049405151, 10614.83984375)
('2026-03-17', 193822.53813563587, 10859.7197265625)
('2026-03-17', 194109.35694618177, 10952.6103515625)
('2026-03-17', 201326.8605615016, 11199.1201171875)
('2026-03-17', 216935.79260143827, None)
('2026-03-17', 216163.9790967055, 10792.669921875)

In [ ]:
cursor.execute("""
SELECT
    date,
    coin_id,
    price_inr,
    GSPC_Close AS sp500,
    IXIC_Close AS nasdaq
FROM merged_data
WHERE coin_id IN ('bitcoin', 'ethereum', 'tether')
AND date BETWEEN '2026-01-01' AND '2026-12-31'
ORDER BY date
""")


results = cursor.fetchall()
for r in results:
    print(r)#Join top 3 crypto coins with stock indices for 2025

('2026-03-02', 'ethereum', 155313.1292931023, 4290.60986328125, 14500.509765625)
('2026-03-12', 'ethereum', 279306.9974351619, 3666.77001953125, 10646.099609375)
('2026-03-14', 'bitcoin', 6184943.552139279, 4127.830078125, 13303.6396484375)
('2026-03-14', 'ethereum', 276537.237355733, 4228.47998046875, 12705.2197265625)
('2026-03-14', 'tether', 84.56842522735435, 3849.280029296875, 10478.08984375)
('2026-03-15', 'ethereum', 297045.36579862604, 3998.949951171875, 12059.6103515625)
('2026-03-15', 'tether', 85.8931511462235, None, None)
('2026-03-16', 'bitcoin', 8009924.38113424, 2978.760009765625, 8566.48046875)
('2026-03-16', 'bitcoin', 8157780.455111292, 3663.4599609375, 12377.8701171875)
('2026-03-16', 'bitcoin', 7860175.221034703, 3871.739990234375, 13777.740234375)
('2026-03-17', 'bitcoin', 7307625.213417549, None, None)
('2026-03-17', 'bitcoin', 7166130.900539224, 3257.85009765625, 9092.1904296875)
('2026-03-17', 'bitcoin', 7495414.341859128, 3234.85009765625, 9020.76953125)
('2026-03-17', 'bitcoin', 7275140.94449613, 3246.280029296875, 9071.4697265625)
('2026-03-17', 'bitcoin', 7224000.906005809, 3237.179931640625, 9068.580078125)
('2026-03-17', 'bitcoin', 7205763.671408613, 3253.050048828125, 9129.240234375)
('2026-03-17', 'bitcoin', 7377568.408827406, 3274.699951171875, 9203.4296875)
('2026-03-17', 'bitcoin', 7471026.999919416, 3265.35009765625, 9178.8603515625)
('2026-03-17', 'bitcoin', 7490943.665690553, 3288.1298828125, 9273.9296875)
('2026-03-17', 'bitcoin', 7448415.462567322, 3283.14990234375, 9251.330078125)
('2026-03-17', 'bitcoin', 7474953.075439318, 3289.2900390625, 9258.7001953125)
('2026-03-17', 'bitcoin', 7216289.858225705, 3316.81005859375, 9357.1298828125)
('2026-03-17', 'bitcoin', 7072289.607125187, 3329.6201171875, 9388.9404296875)
('2026-03-17', 'bitcoin', 7044678.366106417, None, None)
('2026-03-17', 'bitcoin', 7049110.1215911815, 3320.7900390625, 9370.8095703125)
('2026-03-17', 'bitcoin', 7295181.762562074, 3321.75, 9383.76953125)
('2026-03-17', 'bitcoin', 7072204.244187081, 3325.5400390625, 9402.48046875)
('2026-03-17', 'bitcoin', 7092361.1660758825, 3295.469970703125, 9314.91015625)
('2026-03-17', 'bitcoin', 7177434.935222951, 3243.6298828125, 9139.3095703125)
('2026-03-17', 'bitcoin', 7149914.289024058, 3276.239990234375, 9269.6796875)
('2026-03-17', 'bitcoin', 6689389.08502666, 3273.39990234375, 9275.16015625)
('2026-03-17', 'bitcoin', 6810911.664670934, 3283.659912109375, 9298.9296875)
('2026-03-17', 'bitcoin', 6597493.475585312, 3225.52001953125, 9150.9404296875)
('2026-03-17', 'bitcoin', 7122745.761241968, 3248.919921875, 9273.400390625)
('2026-03-17', 'bitcoin', 6866025.560636041, 3297.590087890625, 9467.9697265625)
('2026-03-17', 'bitcoin', 7182775.418149425, 3334.68994140625, 9508.6796875)
('2026-03-17', 'bitcoin', 7333947.924555619, 3345.780029296875, 9572.150390625)
('2026-03-17', 'bitcoin', 7187425.846627208, 3327.7099609375, 9520.509765625)
('2026-03-17', 'bitcoin', 7271599.950976666, 3352.090087890625, 9628.3896484375)
('2026-03-17', 'bitcoin', 7171572.949306771, 3357.75, 9638.9404296875)
('2026-03-17', 'bitcoin', 7201187.29755112, 3379.449951171875, 9725.9599609375)
('2026-03-17', 'bitcoin', 7251703.328254263, 3373.93994140625, 9711.9697265625)
('2026-03-17', 'bitcoin', 7209254.173849113, 3380.159912109375, 9731.1796875)
('2026-03-17', 'bitcoin', 7268417.49030321, None, None)
('2026-03-17', 'bitcoin', 7263849.726468839, 3370.2900390625, 9732.740234375)
('2026-03-17', 'bitcoin', 7447341.987486609, 3386.14990234375, 9817.1796875)
('2026-03-17', 'bitcoin', 7975735.892697773, 3373.22998046875, 9750.9697265625)
('2026-03-17', 'bitcoin', 8003280.21321444, None, None)
('2026-03-17', 'bitcoin', 8000169.783417303, 3225.889892578125, 9221.2802734375)
('2026-03-17', 'bitcoin', 8092178.475391482, 3128.2099609375, 8965.6103515625)
('2026-03-17', 'bitcoin', 8081159.94608841, 3116.389892578125, 8980.7802734375)
('2026-03-17', 'bitcoin', 8092853.390805625, 2954.219970703125, 8567.3701171875)
('2026-03-17', 'bitcoin', 8027696.597798843, 3090.22998046875, 8952.169921875)
('2026-03-17', 'bitcoin', 7968688.759781316, 3003.3701171875, 8684.08984375)
('2026-03-17', 'bitcoin', 8167058.515487802, 3130.1201171875, 9018.08984375)
('2026-03-17', 'bitcoin', 8196935.158997864, 3023.93994140625, 8738.58984375)
('2026-03-17', 'bitcoin', 8118000.316161074, 2972.3701171875, 8575.6201171875)
('2026-03-17', 'bitcoin', 7973099.086450076, 2746.56005859375, 7950.68017578125)
('2026-03-17', 'bitcoin', 7980688.008703099, None, None)
('2026-03-17', 'bitcoin', 8207545.052481962, 2741.3798828125, 7952.0498046875)
('2026-03-17', 'bitcoin', 8229539.783984127, 2480.639892578125, 7201.7998046875)
('2026-03-17', 'bitcoin', 8868161.595114123, 2711.02001953125, 7874.8798828125)
('2026-03-17', 'bitcoin', 8794022.755272726, 2386.1298828125, 6904.58984375)
('2026-03-17', 'bitcoin', 8936515.44901635, 2529.18994140625, 7334.77978515625)
('2026-03-17', 'bitcoin', 8882429.185761888, 2398.10009765625, 6989.83984375)
('2026-03-17', 'bitcoin', 8739740.641206343, 2409.389892578125, 7150.580078125)
('2026-03-17', 'bitcoin', 8860925.91388854, 2304.919921875, 6879.52001953125)
('2026-03-17', 'bitcoin', 8854656.259617174, 2237.39990234375, 6860.669921875)
('2026-03-17', 'bitcoin', 8861418.050018335, 2447.330078125, 7417.85986328125)
('2026-03-17', 'bitcoin', 8862661.820151662, 2475.56005859375, 7384.2998046875)
('2026-03-17', 'bitcoin', 8833249.416670207, 2630.070068359375, 7797.5400390625)
('2026-03-17', 'bitcoin', 9065676.354329923, 2541.469970703125, 7502.3798828125)
('2026-03-17', 'bitcoin', 9017978.28123392, 2626.64990234375, 7774.14990234375)
('2026-03-17', 'bitcoin', 9134061.037906067, 2584.590087890625, 7700.10009765625)
('2026-03-17', 'bitcoin', 9387459.456660772, 2470.5, 7360.580078125)
('2026-03-17', 'bitcoin', 9591418.421810476, None, None)
('2026-03-17', 'bitcoin', 9121570.655984685, 2488.64990234375, 7373.080078125)
('2026-03-17', 'bitcoin', 9173866.493436038, None, None)
('2026-03-17', 'bitcoin', 9274975.732278159, 2659.409912109375, 7887.259765625)
('2026-03-17', 'bitcoin', 9314436.685236426, 2749.97998046875, 8090.89990234375)
('2026-03-17', 'bitcoin', 9310175.102671716, 2789.820068359375, 8153.580078125)
('2026-03-17', 'bitcoin', 9208280.990679564, 2761.6298828125, 8192.419921875)
('2026-03-17', 'bitcoin', 9026592.666677358, None, None)
('2026-03-17', 'bitcoin', 8900073.972215421, 2783.360107421875, 8393.1796875)
('2026-03-17', 'bitcoin', 8957968.682594351, 2799.550048828125, 8532.3603515625)
('2026-03-17', 'bitcoin', 9040802.274014382, 2874.56005859375, 8650.1396484375)
('2026-03-17', 'bitcoin', 9038740.617012177, 2823.159912109375, 8560.73046875)
('2026-03-17', 'bitcoin', 9036688.899610182, 2736.56005859375, 8263.23046875)
('2026-03-17', 'bitcoin', 9003749.459208991, 2799.31005859375, 8495.3798828125)
('2026-03-17', 'bitcoin', 8729536.730077919, 2797.800048828125, 8494.75)
('2026-03-17', 'bitcoin', 8957197.574287502, 2836.739990234375, 8634.51953125)
('2026-03-17', 'bitcoin', 9066295.741750069, 2878.47998046875, 8730.16015625)
('2026-03-17', 'bitcoin', 9066867.46885247, 2863.389892578125, 8607.73046875)
('2026-03-17', 'bitcoin', 9455619.179043707, 2939.510009765625, 8914.7099609375)
('2026-03-17', 'bitcoin', 9440056.689266069, 2912.429931640625, 8889.5498046875)
('2026-03-17', 'bitcoin', 9288882.88186932, None, None)
('2026-03-17', 'bitcoin', 9081227.025134273, 2842.739990234375, 8710.7099609375)
('2026-03-17', 'bitcoin', 9132702.543985052, 2868.43994140625, 8809.1201171875)
('2026-03-17', 'bitcoin', 9084246.101299008, 2848.419921875, 8854.3896484375)
('2026-03-17', 'bitcoin', 9090411.27477335, 2881.18994140625, 8979.66015625)
('2026-03-17', 'bitcoin', 9208980.453923177, 2929.800048828125, 9121.3203125)
('2026-03-17', 'bitcoin', 9039952.955659283, 2930.18994140625, 9192.33984375)
('2026-03-17', 'bitcoin', 9070436.848135183, 2870.1201171875, 9002.5498046875)
('2026-03-17', 'bitcoin', 9080584.318377115, 2820.0, 8863.169921875)
('2026-03-17', 'bitcoin', 8945088.576284403, 2852.5, 8943.7197265625)
('2026-03-17', 'bitcoin', 8792883.07729243, 2863.699951171875, 9014.5595703125)
('2026-03-17', 'bitcoin', 8731873.284684414, 2953.909912109375, 9234.830078125)
('2026-03-17', 'bitcoin', 9111429.945371069, 2922.93994140625, 9185.099609375)
('2026-03-17', 'bitcoin', 9111165.38661966, 2971.610107421875, 9375.7802734375)
('2026-03-17', 'bitcoin', 9223086.808659252, 2948.510009765625, 9284.8798828125)
('2026-03-17', 'bitcoin', 9165684.099752242, 2955.449951171875, 9324.58984375)
('2026-03-17', 'bitcoin', 9156217.740562832, 2991.77001953125, 9340.2197265625)
('2026-03-17', 'bitcoin', 9177823.305095606, 3036.1298828125, 9412.3603515625)
('2026-03-17', 'bitcoin', 9263092.465181679, 3029.72998046875, 9368.990234375)
('2026-03-17', 'bitcoin', 9181709.414667957, 3044.31005859375, 9489.8701171875)
('2026-03-17', 'bitcoin', 9054321.250569785, 3055.72998046875, 9552.0498046875)
('2026-03-17', 'bitcoin', 9325640.339018358, 3080.820068359375, 9608.3798828125)
('2026-03-17', 'bitcoin', 9360532.463404836, 3122.8701171875, 9682.91015625)
('2026-03-17', 'bitcoin', 9250500.062624797, 3112.35009765625, 9615.8095703125)
('2026-03-17', 'bitcoin', 9285248.177863376, 3193.929931640625, 9814.080078125)
('2026-03-17', 'bitcoin', 9337523.923073687, 3232.389892578125, 9924.75)
('2026-03-17', 'bitcoin', 9302203.177316865, 3207.179931640625, 9953.75)
('2026-03-17', 'bitcoin', 9338122.035800587, 3190.139892578125, 10020.349609375)
('2026-03-17', 'bitcoin', 9541743.483380785, 3002.10009765625, 9492.73046875)
('2026-03-17', 'bitcoin', 9934947.612549465, 3041.31005859375, 9588.8095703125)
('2026-03-17', 'bitcoin', 10091339.413757524, 3066.590087890625, 9726.01953125)
('2026-03-17', 'bitcoin', 10078287.164944079, 3124.739990234375, 9895.8701171875)
('2026-03-17', 'bitcoin', 10222853.345055208, 3113.489990234375, 9910.5302734375)
('2026-03-17', 'bitcoin', 10301939.218478084, 3115.340087890625, 9943.0498046875)
('2026-03-17', 'bitcoin', 10119542.204331392, 3097.739990234375, 9946.1201171875)
('2026-03-17', 'bitcoin', 10198739.393321177, 3117.860107421875, 10056.48046875)
('2026-03-17', 'bitcoin', 10277885.47839658, 3131.2900390625, 10131.3701171875)
('2026-03-17', 'bitcoin', 10164069.670952292, 3050.330078125, 9909.169921875)
('2026-03-17', 'bitcoin', 10156547.547410768, 3083.760009765625, 10017.0)
('2026-03-17', 'bitcoin', 10101549.352407157, 3009.050048828125, 9757.2197265625)
('2026-03-17', 'bitcoin', 10136533.758092493, 3053.239990234375, 9874.150390625)
('2026-03-17', 'bitcoin', 10357349.26643955, 3100.2900390625, 10058.76953125)
('2026-03-17', 'bitcoin', 10249425.74900696, 3115.860107421875, 10154.6298828125)
('2026-03-17', 'bitcoin', 10229427.683390176, 3130.010009765625, 10207.6298828125)
('2026-03-17', 'bitcoin', 10168020.4311719, None, None)
('2026-03-17', 'bitcoin', 10203795.311577797, 3179.719970703125, 10433.650390625)
('2026-03-17', 'bitcoin', 10330494.375551593, 3145.320068359375, 10343.8896484375)
('2026-03-17', 'bitcoin', 10240072.841855934, 3169.93994140625, 10492.5)
('2026-03-17', 'bitcoin', 10260715.669243045, 3152.050048828125, 10547.75)
('2026-03-17', 'bitcoin', 10330510.927890545, 3185.0400390625, 10617.4404296875)
('2026-03-17', 'bitcoin', 10122552.718401065, 3155.219970703125, 10390.83984375)
('2026-03-17', 'bitcoin', 9870309.502282668, 3197.52001953125, 10488.580078125)
('2026-03-17', 'bitcoin', 9811174.470132805, 3226.56005859375, 10550.490234375)
('2026-03-17', 'bitcoin', 9963363.104407016, 3215.570068359375, 10473.830078125)
('2026-03-17', 'bitcoin', 10119947.866363142, 3224.72998046875, 10503.1904296875)
('2026-03-17', 'bitcoin', 10011721.5506572, 3251.840087890625, 10767.08984375)
('2026-03-17', 'bitcoin', 10094655.435390146, 3257.300048828125, 10680.3603515625)
('2026-03-17', 'bitcoin', 10270107.263258504, 3276.02001953125, 10706.1298828125)
('2026-03-17', 'bitcoin', 10236807.855788205, 3235.659912109375, 10461.419921875)
('2026-03-17', 'bitcoin', 10220759.730383817, 3215.6298828125, 10363.1796875)
('2026-03-17', 'bitcoin', 10434491.300112702, 3239.409912109375, 10536.26953125)
('2026-03-17', 'bitcoin', 10412275.449238887, 3218.43994140625, 10402.08984375)
('2026-03-17', 'bitcoin', 10529495.638104321, 3258.43994140625, 10542.9404296875)
('2026-03-17', 'bitcoin', 10805439.78369676, 3246.219970703125, 10587.8095703125)
('2026-03-17', 'bitcoin', 10383230.847886154, 3271.1201171875, 10745.26953125)
('2026-03-17', 'bitcoin', 10268856.947554458, 3294.610107421875, 10902.7998046875)
('2026-03-17', 'bitcoin', 10282983.838569582, 3306.510009765625, 10941.169921875)
('2026-03-17', 'bitcoin', 10286533.101169772, 3327.77001953125, 10998.400390625)
('2026-03-17', 'bitcoin', 10148644.242275473, 3349.159912109375, 11108.0703125)
('2026-03-17', 'bitcoin', 9819786.419050021, 3351.280029296875, 11010.98046875)
('2026-03-17', 'bitcoin', 9942066.543754837, 3360.469970703125, 10968.3603515625)
('2026-03-17', 'bitcoin', 9813063.27750558, 3333.68994140625, 10782.8203125)
('2026-03-17', 'bitcoin', 10203164.21582744, 3380.35009765625, 11012.240234375)
('2026-03-17', 'bitcoin', 10074416.19618185, 3373.429931640625, 11042.5)
('2026-03-17', 'bitcoin', 9903221.35080575, 3372.85009765625, 11019.2998046875)
('2026-03-17', 'bitcoin', 9653212.189243559, 3381.989990234375, 11129.73046875)
('2026-03-17', 'bitcoin', 9801777.668906499, 3389.780029296875, 11210.83984375)
('2026-03-17', 'bitcoin', 9749130.25886824, 3374.85009765625, 11146.4599609375)
('2026-03-17', 'bitcoin', 9856302.06893481, 3385.510009765625, 11264.9501953125)
('2026-03-17', 'bitcoin', 9564432.013993934, 3397.159912109375, 11311.7998046875)
('2026-03-17', 'bitcoin', 9591794.692119835, 3431.280029296875, 11379.7197265625)
('2026-03-17', 'bitcoin', 9545191.818462053, 3443.6201171875, 11466.4697265625)
('2026-03-17', 'bitcoin', 9606486.0790093, 3478.72998046875, 11665.0595703125)
('2026-03-17', 'bitcoin', 9784574.242949013, 3484.550048828125, 11625.33984375)
('2026-03-17', 'bitcoin', 9838796.609221794, 3508.010009765625, 11695.6298828125)
('2026-03-17', 'bitcoin', 9765163.284050079, 3500.31005859375, 11775.4599609375)
('2026-03-17', 'bitcoin', 9759026.631183332, 3526.64990234375, 11939.669921875)
('2026-03-17', 'bitcoin', 9718962.630296323, 3580.840087890625, 12056.4404296875)
('2026-03-17', 'bitcoin', 9800346.003033817, 3455.06005859375, 11458.099609375)
('2026-03-17', 'bitcoin', 9856054.84901548, 3426.9599609375, 11313.1298828125)
('2026-03-17', 'bitcoin', 9840553.151484529, None, None)
('2026-03-17', 'bitcoin', 10035954.764445597, 3331.840087890625, 10847.6904296875)
('2026-03-17', 'bitcoin', 10195205.098488238, 3398.9599609375, 11141.5595703125)
('2026-03-17', 'bitcoin', 10254357.380846838, 3339.18994140625, 10919.58984375)
('2026-03-17', 'bitcoin', 10237593.3071353, 3340.969970703125, 10853.5498046875)
('2026-03-17', 'bitcoin', 10184894.127284445, 3383.5400390625, 11056.650390625)
('2026-03-17', 'bitcoin', 10169238.650025213, 3401.199951171875, 11190.3203125)
('2026-03-17', 'bitcoin', 10261685.530263504, 3385.489990234375, 11050.4697265625)
('2026-03-17', 'bitcoin', 10237752.888404036, 3357.010009765625, 10910.2802734375)
('2026-03-17', 'bitcoin', 10333070.25718556, 3319.469970703125, 10793.2802734375)
('2026-03-17', 'bitcoin', 10189201.725638028, 3281.06005859375, 10778.7998046875)
('2026-03-17', 'bitcoin', 10194461.688819751, 3315.570068359375, 10963.6396484375)
('2026-03-17', 'bitcoin', 10158260.693491202, 3236.919921875, 10632.990234375)
('2026-03-17', 'bitcoin', 9951646.271657305, 3246.590087890625, 10672.26953125)
('2026-03-17', 'bitcoin', 9948492.512889242, 3298.4599609375, 10913.5595703125)
('2026-03-17', 'bitcoin', 10060469.351465985, 3351.60009765625, 11117.5302734375)
('2026-03-17', 'bitcoin', 9673068.167457229, 3335.469970703125, 11085.25)
('2026-03-17', 'bitcoin', 9728251.057537576, 3363.0, 11167.509765625)
('2026-03-17', 'bitcoin', 9723915.967631772, 3380.800048828125, 11326.509765625)
('2026-03-17', 'bitcoin', 9944472.608696878, None, None)
('2026-03-17', 'bitcoin', 10139763.924082505, 3408.60009765625, 11332.490234375)
('2026-03-17', 'bitcoin', 10130020.723922314, 3360.969970703125, 11154.599609375)
('2026-03-17', 'bitcoin', 10509252.859358784, 3419.43994140625, 11364.599609375)
('2026-03-17', 'bitcoin', 10700725.995237181, 3446.830078125, 11420.98046875)
('2026-03-17', 'bitcoin', 10847910.013598107, 3477.139892578125, 11579.9404296875)
('2026-03-17', 'bitcoin', 10859533.642673422, 3534.219970703125, 11876.259765625)
('2026-03-17', 'bitcoin', 10959365.064936124, 3511.929931640625, 11863.900390625)
('2026-03-17', 'bitcoin', 11070472.246732509, 3488.669921875, 11768.73046875)
('2026-03-17', 'bitcoin', 10783920.730192943, 3483.340087890625, 11713.8701171875)
('2026-03-17', 'bitcoin', 10949945.97908964, 3483.81005859375, 11671.5595703125)
('2026-03-17', 'bitcoin', 10814774.599012492, 3426.919921875, 11478.8798828125)
('2026-03-17', 'bitcoin', 10047260.111235712, 3443.1201171875, 11516.490234375)
('2026-03-17', 'bitcoin', 9838358.210748602, 3435.56005859375, 11484.6904296875)
('2026-03-17', 'bitcoin', 10223942.881584922, 3453.489990234375, 11506.009765625)
('2026-03-17', 'bitcoin', 10216224.051870666, 3465.389892578125, 11548.2802734375)
('2026-03-17', 'bitcoin', 10046351.075825775, 3400.969970703125, 11358.9404296875)
('2026-03-17', 'bitcoin', 9721344.884648668, 3390.679931640625, 11431.349609375)
('2026-03-17', 'bitcoin', 9509774.024195194, 3271.030029296875, 11004.8701171875)
('2026-03-17', 'bitcoin', 9369768.130232994, 3310.110107421875, 11185.58984375)
('2026-03-17', 'bitcoin', 9432476.848616607, 3269.9599609375, 10911.58984375)
('2026-03-17', 'bitcoin', 9558930.877185136, 3310.239990234375, 10957.6103515625)
('2026-03-17', 'bitcoin', 9720308.914971137, 3369.159912109375, 11160.5703125)
('2026-03-17', 'bitcoin', 9549158.301143315, 3443.43994140625, 11590.7802734375)
('2026-03-17', 'bitcoin', 9442499.946295625, 3510.449951171875, 11890.9296875)
('2026-03-17', 'bitcoin', 9659976.397607893, 3509.43994140625, 11895.23046875)
('2026-03-17', 'bitcoin', 9747832.72977752, 3550.5, 11713.7802734375)
('2026-03-17', 'bitcoin', 9802501.15016422, 3545.530029296875, 11553.8603515625)
('2026-03-17', 'bitcoin', 10055171.794296525, 3572.659912109375, 11786.4296875)
('2026-03-17', 'bitcoin', 10073474.454011032, 3537.010009765625, 11709.58984375)
('2026-03-17', 'bitcoin', 9965129.220872145, 3585.14990234375, 11829.2900390625)
('2026-03-17', 'bitcoin', 9722166.86543983, None, None)
('2026-03-17', 'bitcoin', 9593893.17104472, 3609.530029296875, 11899.33984375)
('2026-03-17', 'bitcoin', 9734748.91964181, 3567.7900390625, 11801.599609375)
('2026-03-17', 'bitcoin', 9765788.362963019, 3581.8701171875, 11904.7099609375)
('2026-03-17', 'bitcoin', 9824421.072227614, 3557.5400390625, 11854.9697265625)
('2026-03-17', 'bitcoin', 9450928.858755054, 3577.590087890625, 11880.6298828125)
('2026-03-17', 'bitcoin', 9018317.599498693, 3635.409912109375, 12036.7900390625)
('2026-03-17', 'bitcoin', 9199126.082980732, 3629.64990234375, 12094.400390625)
('2026-03-17', 'bitcoin', 8984607.813501872, None, None)
('2026-03-17', 'bitcoin', 9167651.236387476, 3638.35009765625, 12205.849609375)
('2026-03-17', 'bitcoin', 9069592.039128657, None, None)
('2026-03-17', 'bitcoin', 9283589.00601575, 3662.449951171875, 12355.1103515625)
('2026-03-17', 'bitcoin', 9394913.182233905, 3669.010009765625, 12349.3701171875)
('2026-03-17', 'bitcoin', 9108594.696793688, 3666.719970703125, 12377.1796875)
('2026-03-17', 'bitcoin', 8994239.327086337, 3699.1201171875, 12464.23046875)
('2026-03-17', 'bitcoin', 8857694.85444411, 3691.9599609375, 12519.9501953125)
('2026-03-17', 'bitcoin', 8376936.116014769, 3702.25, 12582.76953125)
('2026-03-17', 'bitcoin', 8470582.749251666, 3672.820068359375, 12338.9501953125)
('2026-03-17', 'bitcoin', 8373085.239387692, 3668.10009765625, 12405.8095703125)
('2026-03-17', 'bitcoin', 8219844.429070548, 3647.489990234375, 12440.0400390625)
('2026-03-17', 'bitcoin', 8084502.70583037, 3694.6201171875, 12595.0595703125)

In [ ]:
cursor.execute("""
SELECT
     date,
    price_inr AS bitcoin_price,
    GSPC_Close AS sp500,
    IXIC_Close AS nasdaq,
    Price AS oil_price
FROM merged_data
WHERE coin_id = 'bitcoin'
ORDER BY date
LIMIT 10
""")



results = cursor.fetchall()

for r in results:
    print(r)##Multi-join: stock prices, oil prices, and Bitcoin prices for daily comparison

('2026-03-14', 6184943.552139279, 4127.830078125, 13303.6396484375, 68.79)
('2026-03-16', 8009924.38113424, 2978.760009765625, 8566.48046875, 47.27)
('2026-03-16', 8157780.455111292, 3663.4599609375, 12377.8701171875, 47.02)
('2026-03-16', 7860175.221034703, 3871.739990234375, 13777.740234375, 60.4)
('2026-03-17', 7307625.213417549, None, None, 61.17)
('2026-03-17', 7166130.900539224, 3257.85009765625, 9092.1904296875, 63.0)
('2026-03-17', 7495414.341859128, 3234.85009765625, 9020.76953125, 63.27)
('2026-03-17', 7275140.94449613, 3246.280029296875, 9071.4697265625, 62.7)
('2026-03-17', 7224000.906005809, 3237.179931640625, 9068.580078125, 59.65)
('2026-03-17', 7205763.671408613, 3253.050048828125, 9129.240234375, 59.56)

# Streamlit App

In [1]:
!pip install -q streamlit
!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared-linux-amd64
import subprocess
subprocess.Popen(["./cloudflared-linux-amd64", "tunnel", "--url", "http://localhost:8501"])
!nohup /content/cloudflared-linux-amd64 tunnel --url http://localhost:8501 &

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 80.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 122.8 MB/s eta 0:00:00
--2026-03-18 05:25:21--  https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/cloudflare/cloudflared/releases/download/2026.3.0/cloudflared-linux-amd64 [following]
--2026-03-18 05:25:21--  https://github.com/cloudflare/cloudflared/releases/download/2026.3.0/cloudflared-linux-amd64
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/106867604/731ab2f8-6b77-4adb-a7b3-1104525e9d72?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-18T06%3A25%3A26Z&rscd=attachment%3B+filename%3Dcloudflared-linux-amd64&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-18T05%3A24%3A36Z&ske=2026-03-18T06%3A25%3A26Z&sks=b&skv=2018-11-09&sig=1hh798Ys4xb03%2Bf510%2FRvwXjSKU%2Bclj1mNl1MJxYZ3c%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3MzgxMzMyMSwibmJmIjoxNzczODExNTIxLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.YF_dt1hc3gOK2Ohc015EB1qJOIKud26jvq8iVj_z7vI&response-content-disposition=attachment%3B%20filename%3Dcloudflared-linux-amd64&response-content-type=application%2Foctet-stream [following]
--2026-03-18 05:25:21--  https://release-assets.githubusercontent.com/github-production-release-asset/106867604/731ab2f8-6b77-4adb-a7b3-1104525e9d72?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-18T06%3A25%3A26Z&rscd=attachment%3B+filename%3Dcloudflared-linux-amd64&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-18T05%3A24%3A36Z&ske=2026-03-18T06%3A25%3A26Z&sks=b&skv=2018-11-09&sig=1hh798Ys4xb03%2Bf510%2FRvwXjSKU%2Bclj1mNl1MJxYZ3c%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3MzgxMzMyMSwibmJmIjoxNzczODExNTIxLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.YF_dt1hc3gOK2Ohc015EB1qJOIKud26jvq8iVj_z7vI&response-content-disposition=attachment%3B%20filename%3Dcloudflared-linux-amd64&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 39667364 (38M) [application/octet-stream]
Saving to: ‘cloudflared-linux-amd64’

cloudflared-linux-a 100%[===================>]  37.83M  --.-KB/s    in 0.1s

2026-03-18 05:25:21 (255 MB/s) - ‘cloudflared-linux-amd64’ saved [39667364/39667364]

nohup: appending output to 'nohup.out'

In [2]:
!pip install streamlit-option-menu

Collecting streamlit-option-menu
  Downloading streamlit_option_menu-0.4.0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: streamlit>=1.36 in /usr/local/lib/python3.12/dist-packages (from streamlit-option-menu) (1.55.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (8.3.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (3.1.46)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (26.0)
Requirement already satisfied: pandas<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (11.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (0.9.1)
Requirement already satisfied: protobuf<7,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (0.10.2)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (6.5.1)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (2.18.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.36->streamlit-option-menu) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (2026.2.25)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.36->streamlit-option-menu) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (0.30.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (1.17.0)
Downloading streamlit_option_menu-0.4.0-py3-none-any.whl (829 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 829.3/829.3 kB 14.7 MB/s eta 0:00:00
Installing collected packages: streamlit-option-menu
Successfully installed streamlit-option-menu-0.4.0

In [3]:
%%writefile project.py

Writing project.py

In [20]:
%%writefile project.py

import streamlit as st
import pandas as pd
import sqlite3
from streamlit_option_menu import option_menu

# DB connection
conn = sqlite3.connect("merged_data.db")

# Page config
st.set_page_config(layout='wide')

# Menu
selected = option_menu(
    menu_title=None,
    options=["Home", "Data Exploration", "SQL Query Runner", "Top 5 Crypto Analysis"],
    orientation="horizontal"
)

# Home Page
if selected == "Home":
    st.title("Cross-Market Analysis: Crypto, Oil & Stocks with python & SQL ")


elif selected == "Data Exploration":
    st.title("Cross Market Overview")

    # DB connection
    conn = sqlite3.connect("merged_data.db")

    # Load data
    df = pd.read_sql_query("SELECT * FROM merged_data", conn)

    # Convert date
    df['date'] = pd.to_datetime(df['date'])

    # DATE FILTER
    start_date = st.date_input("Start Date", df['date'].min(), key="start")
    end_date = st.date_input("End Date", df['date'].max(), key="end")

    # Filter data
    filtered_df = df[
        (df['date'] >= pd.to_datetime(start_date)) &
        (df['date'] <= pd.to_datetime(end_date))
    ]

    # SELECT BOX
    option = st.selectbox(
        "Select Analysis",
        [
            "Bitcoin Avg Price",
            "Oil Avg Price",
            "S&P 500 Avg",
            "NIFTY Avg"
        ],
        key="analysis"
    )

    # CALCULATIONS
    if option == "Bitcoin Avg Price":
        result = filtered_df[filtered_df['coin_id'] == 'bitcoin']['price_inr'].mean()
        st.metric("Bitcoin Average Price", round(result, 2))

    elif option == "Oil Avg Price":
        result = filtered_df['Price'].mean()
        st.metric("Oil Average Price", round(result, 2))

    elif option == "S&P 500 Avg":
        result = filtered_df['GSPC_Close'].mean()
        st.metric("S&P 500 Avg Close", round(result, 2))

    elif option == "NIFTY Avg":
        result = filtered_df['NSEI_Close'].mean()
        st.metric("NIFTY Avg Close", round(result, 2))

    # SHOW DATA
    st.subheader("Filtered Data")
    st.dataframe(filtered_df)

elif selected == "SQL Query Runner":
    st.title("SQL Query Runner")

    conn = sqlite3.connect("Cryptocurrencies.db")



    queries = {

    # ------------------ CRYPTOCURRENCIES ------------------
    "Top 3 Cryptos by Market Cap": {
        "query": """SELECT * FROM Cryptocurrencies
                    ORDER BY market_cap_rank ASC
                    LIMIT 3""",
        "db": "Cryptocurrencies.db"
    },

    "Circulating Supply > 90%": {
        "query": """SELECT id,symbol,name,circulating_supply,total_supply
                    FROM Cryptocurrencies
                    WHERE circulating_supply > 0.9 * total_supply""",
        "db": "Cryptocurrencies.db"
    },

    "Coins Near ATH": {
        "query": """SELECT name,symbol,current_price,ath
                    FROM Cryptocurrencies
                    WHERE current_price >= 0.9 * ath""",
        "db": "Cryptocurrencies.db"
    },

    "Avg Market Rank (>1B Volume)": {
        "query": """SELECT AVG(market_cap_rank)
                    FROM Cryptocurrencies
                    WHERE total_volume > 1000000000""",
        "db": "Cryptocurrencies.db"
    },

    "Most Recent Coin": {
        "query": """SELECT name,symbol,date
                    FROM Cryptocurrencies
                    ORDER BY date DESC
                    LIMIT 1""",
        "db": "Cryptocurrencies.db"
    },

    # ------------------ CRYPTO PRICES ------------------
    "Bitcoin Max Price": {
        "query": """SELECT coin_id,date,MAX(price_inr)
                    FROM Crypto_prices
                    WHERE coin_id='bitcoin'""",
        "db": "Crypto_prices.db"
    },

    "Bitcoin Feb 2025 Prices": {
        "query": """SELECT coin_id,date,price_inr
                    FROM Crypto_prices
                    WHERE coin_id='bitcoin'
                    AND date BETWEEN '2025-02-01' AND '2025-02-28'""",
        "db": "Crypto_prices.db"
    },

    "Highest Avg Price Coin": {
        "query": """SELECT coin_id,AVG(price_inr)
                    FROM Crypto_prices
                    GROUP BY coin_id
                    ORDER BY AVG(price_inr) DESC
                    LIMIT 1""",
        "db": "Crypto_prices.db"
    },

    "Bitcoin Avg Feb 2025": {
        "query": """SELECT AVG(price_inr)
                    FROM Crypto_prices
                    WHERE coin_id='bitcoin'
                    AND date LIKE '2025-02-%'""",
        "db": "Crypto_prices.db"
    },

    "Bitcoin Avg Feb 2026": {
        "query": """SELECT AVG(price_inr)
                    FROM Crypto_prices
                    WHERE coin_id='bitcoin'
                    AND date LIKE '2026-02-%'""",
        "db": "Crypto_prices.db"
    },

    # ------------------ OIL ------------------
    "Highest Oil Price (5Y)": {
        "query": """SELECT date,price_inr
                    FROM Oil_prices
                    WHERE date >= date('now','-5 years')
                    ORDER BY price_inr DESC
                    LIMIT 1""",
        "db": "Oil_prices.db"
    },

    "Oil Avg Per Year": {
        "query": """SELECT substr(date,1,4) AS year,AVG(price_inr)
                    FROM Oil_prices
                    GROUP BY year""",
        "db": "Oil_prices.db"
    },

    "Oil COVID Crash": {
        "query": """SELECT date,price_inr
                    FROM Oil_prices
                    WHERE date BETWEEN '2020-03-01' AND '2020-04-30'""",
        "db": "Oil_prices.db"
    },

    "Lowest Oil (10Y)": {
        "query": """SELECT MIN(price_inr)
                    FROM Oil_prices
                    WHERE date >= date('now','-10 years')""",
        "db": "Oil_prices.db"
    },

    "Oil Volatility": {
        "query": """SELECT strftime('%Y',date) AS year,
                           MAX(price_inr)-MIN(price_inr) AS volatility
                    FROM Oil_prices
                    GROUP BY year""",
        "db": "Oil_prices.db"
    },

    # ------------------ STOCKS ------------------
    "NSEI Stock Data": {
        "query": """SELECT date,open,high,low,close,volume
                    FROM stocks
                    WHERE ticker='^NSEI'""",
        "db": "stocks.db"
    },

    "NASDAQ Highest Close": {
        "query": """SELECT date,ticker,close
                    FROM stocks
                    WHERE ticker='^IXIC'
                    ORDER BY close DESC
                    LIMIT 1""",
        "db": "stocks.db"
    },

    "S&P500 Volatility Days": {
        "query": """SELECT date,high,low,(high-low) AS diff
                    FROM stocks
                    WHERE ticker='^GSPC'
                    ORDER BY diff DESC
                    LIMIT 5""",
        "db": "stocks.db"
    },

    "Monthly Avg Stocks": {
        "query": """SELECT ticker,strftime('%Y-%m',date) AS month,
                           AVG(close)
                    FROM stocks
                    GROUP BY ticker,month""",
        "db": "stocks.db"
    },

    "NSEI Volume 2024": {
        "query": """SELECT AVG(volume)
                    FROM stocks
                    WHERE ticker='^NSEI'
                    AND date BETWEEN '2024-01-01' AND '2024-12-31'""",
        "db": "stocks.db"
    },

    # ------------------ MERGED DATA ------------------
    "Bitcoin vs Oil 2026": {
        "query": """SELECT 'Bitcoin' AS asset,AVG(price_inr)
                    FROM merged_data
                    WHERE coin_id='bitcoin'
                    UNION ALL
                    SELECT 'Oil',AVG(price)
                    FROM merged_data""",
        "db": "merged_data.db"
    },

    "Bitcoin vs S&P500": {
        "query": """SELECT date,price_inr,GSPC_Close
                    FROM merged_data
                    WHERE coin_id='bitcoin'""",
        "db": "merged_data.db"
    },

    "Ethereum vs NASDAQ": {
        "query": """SELECT date,price_inr,IXIC_Close
                    FROM merged_data
                    WHERE coin_id='ethereum'""",
        "db": "merged_data.db"
    },

    "Bitcoin Oil Correlation Data": {
        "query": """SELECT date,price_inr AS bitcoin_price,Price AS oil_price
                    FROM merged_data
                    WHERE coin_id='bitcoin'""",
        "db": "merged_data.db"
    },

    "Top 3 Coins vs Market": {
        "query": """SELECT date,coin_id,price_inr,GSPC_Close,IXIC_Close
                    FROM merged_data
                    WHERE coin_id IN ('bitcoin','ethereum','tether')
                    LIMIT 10""",
        "db": "merged_data.db"
    },

    "Stock vs Oil": {
        "query": """SELECT date,GSPC_Close,Price
                    FROM merged_data
                    LIMIT 10""",
        "db": "merged_data.db"
    },

    "Bitcoin Full Market View": {
        "query": """SELECT date,price_inr,GSPC_Close,IXIC_Close,Price
                    FROM merged_data
                    WHERE coin_id='bitcoin'
                    LIMIT 10""",
        "db": "merged_data.db"
    }
}

    #  ALL QUERIES
    selected_query = st.selectbox("Select SQL Query", list(queries.keys()))

    st.code(queries[selected_query]["query"], language="sql")

    if st.button("Run Query"):
      query = queries[selected_query]["query"]
      db = queries[selected_query]["db"]

      conn = sqlite3.connect(db)

      result = pd.read_sql_query(query, conn)
      st.dataframe(result)



elif selected == "Top 5 Crypto Analysis":
    st.title("Top 5 Crypto Analysis")




    conn = sqlite3.connect("Crypto_prices.db")

    # ---- Get Top 3 coins ----
    top_crypto_query = """
        SELECT DISTINCT coin_id
        FROM Crypto_prices
        LIMIT 3
    """
    top_crypto_df = pd.read_sql_query(top_crypto_query, conn)

    crypto_list = top_crypto_df["coin_id"].tolist()

    # ---- Select Crypto ----
    selected_crypto = st.selectbox("Select Cryptocurrency", crypto_list)

    # ---- Load Data for selected crypto ----
    query = f"""
        SELECT date, price_inr
        FROM Crypto_prices
        WHERE coin_id = '{selected_crypto}'
    """
    df = pd.read_sql_query(query, conn)

    # ---- Convert Date ----
    df["date"] = pd.to_datetime(df["date"])

    # ---- Date Filter ----
    start_date = st.date_input("Start Date", df["date"].min())
    end_date = st.date_input("End Date", df["date"].max())

    filtered_df = df[(df["date"] >= pd.to_datetime(start_date)) &
                     (df["date"] <= pd.to_datetime(end_date))]

    # ---- Line Chart (Optional) ----
    st.subheader("Daily Price Trend")
    st.line_chart(filtered_df.set_index("date")["price_inr"])

    # ---- Table ----
    st.subheader("Daily Price Data")
    st.dataframe(filtered_df)

    conn.close()

Overwriting project.py

In [8]:
!ls

cloudflared-linux-amd64  merged_data.db  project.py
Cryptocurrencies.db	 nohup.out	 sample_data
Crypto_prices.db	 Oil_prices.db	 stocks.db

In [19]:
!streamlit run /content/project.py &>/content/logs.txt &

In [10]:
!grep -o 'https://.*\.trycloudflare.com' nohup.out | head -n 1 | xargs -I {} echo "Your tunnel url {}"

Your tunnel url https://shirts-med-rental-abs.trycloudflare.com